import { whyCollectionsDevelopmentPack } from "@/content/development-packs/lesson-4-1";
import { pythonListsDevelopmentPack } from "@/content/development-packs/lesson-4-2";
import { workingWithListsDevelopmentPack } from "@/content/development-packs/lesson-4-3";
import type { LessonDocument } from "@/types/content";

export const moduleFourLessons: LessonDocument[] = [
  {
    id: "module-4-lesson-1",
    moduleId: "module-4",
    number: "4.1",
    title: "Why Collections?",
    summary: "Experience the limits of individual variables and discover why growing applications need related data to be organized together—before learning any collection syntax.",
    durationMinutes: 120,
    level: "Beginner",
    introduction: { title: "The problem before the solution", body: "The Smart Farm has outgrown one-variable-per-reading design. This lesson makes that scaling problem visible before introducing Python Lists in Lesson 4.2." },
    objectives: [
      "Understand the limitations of individual variables",
      "Recognize repeated data patterns",
      "Explain why collections are necessary",
      "Compare individual variables with grouped data",
      "Appreciate the motivation behind Python Lists",
    ],
    whyThisMatters: { title: "Data volume changes program design", body: "A technique that works for five readings may collapse under five thousand. Recognizing that boundary helps programmers select structures that remain understandable as systems grow." },
    industryMotivation: { title: "Every data product groups related records", body: "Agritech platforms, banks, streaming services, and search engines manage many related values as organized datasets rather than inventing a new variable name for every record.", signal: "This lesson intentionally introduces motivation only. Collection syntax, indexing, slicing, methods, and collection iteration begin later." },
    concept: { title: "A collection groups related values", body: "When many variables represent the same kind of data, treating them as one organized group makes the design easier to scale, reason about, and maintain.", items: ["Related data", "Repeated patterns", "Scale", "Organization", "Maintainability"] },
    workflow: { title: "Recognize the need for a collection", description: "Move from a small working example to a scalable data-design question.", steps: [
      { title: "Observe", description: "Notice repeated related variables." },
      { title: "Scale", description: "Imagine hundreds or thousands of values." },
      { title: "Measure", description: "Count declarations and update points." },
      { title: "Group", description: "Describe the values as one related body of data." },
      { title: "Prepare", description: "Choose a collection type in later lessons." },
    ] },
    agritechExample: { title: "Thousands of sensor readings need one data strategy", body: "Moisture, temperature, humidity, and pH readings arrive continuously. Numbered variables cannot provide a maintainable foundation for storing and analyzing them." },
    playground: {
      title: "Experience the maintenance problem",
      description: "Run and edit individual sensor variables. Add more declarations and observe that each new reading creates another name and another future maintenance point.",
      starterCode: "sensor1 = 25\nsensor2 = 30\nsensor3 = 28\nsensor4 = 29\nsensor5 = 31\n\nprint(sensor1)\nprint(sensor2)\nprint(sensor3)\nprint(sensor4)\nprint(sensor5)",
      expectedOutcome: "Python prints the five readings, while the analysis panel counts the repeated declarations and shows why this pattern cannot scale.",
    },
    practice: [
      { level: "Easy", title: "Five temperatures", prompt: "Write five separately named temperature variables and describe the naming pattern.", guidance: "Notice what remains the same and what changes." },
      { level: "Medium", title: "Twenty temperatures", prompt: "Extend the same idea to twenty readings, then count the declarations and update statements required.", guidance: "Record how repetition affects readability and review effort." },
      { level: "Challenge", title: "Design for ten thousand sensors", prompt: "Explain why separately named variables would fail as a long-term design and describe the organizational capability the program needs.", guidance: "Focus on grouping, updating, searching, and analysis without writing collection syntax." },
    ],
    quiz: [
      { title: "Question 1", question: "What commonly signals that related data should be grouped?", options: ["Repeated variable names that differ only by a number", "One clear constant", "A single print statement", "A comment"], correctOptionIndex: 0, note: "Repeated naming patterns reveal related values.", explanation: "A growing numbered family of variables is difficult to maintain individually." },
      { title: "Question 2", question: "Why do individual variables fail at large scale?", options: ["They create repetitive declarations and update points", "Python forbids numbers", "They always become strings", "They cannot be printed"], correctOptionIndex: 0, note: "The problem is design scale, not basic validity.", explanation: "Each value adds another name and another place that future changes can miss." },
      { title: "Question 3", question: "What is the central purpose of a collection?", options: ["Group related values", "Rename Python", "Replace every function", "Avoid all data"], correctOptionIndex: 0, note: "Collections organize related information.", explanation: "Grouping makes many values easier to access, update, and analyze." },
      { title: "Question 4", question: "Does Lesson 4.1 teach collection syntax?", options: ["No, it teaches the motivation first", "Yes, every syntax form", "Only advanced dictionary syntax", "Only indexing"], correctOptionIndex: 0, note: "Problem understanding comes first.", explanation: "Python Lists begin in Lesson 4.2." },
    ],
    assignment: { title: "Explain the sensor-data design problem", brief: "Model a farm with individually named readings, measure how the code grows, and recommend grouping related data without using collection syntax.", deliverables: ["Five temperature variables", "Twenty-variable growth estimate", "Ten-thousand-sensor maintenance analysis", "Repeated-pattern explanation", "Bookshelf analogy in your own words", "A short justification for grouping related values", "No collection syntax"] },
    summarySection: { title: "You now know why collections exist", body: "Individual variables are useful for small, distinct values, but repeated related data needs an organized structure. You measured code growth, found naming patterns, and described the need for grouping without learning syntax prematurely.", items: ["Scaling limits", "Repeated data patterns", "Code growth", "Maintenance risk", "Grouped data", "Collection motivation"] },
    keyTakeaways: ["Individual variables work for small amounts of distinct data", "Repeated numbered variables signal a design problem", "Large applications need related values organized together", "Collections solve different data-management problems", "Understanding the need comes before learning syntax"],
    whatsNext: { title: "Lesson 4.2 · Python Lists", body: "Now that the scaling problem is clear, learn how Python Lists create and organize the first practical group of related Smart Farm readings." },
    developmentPack: whyCollectionsDevelopmentPack,
  },
  {
    id: "module-4-lesson-2",
    moduleId: "module-4",
    number: "4.2",
    title: "Python Lists: Storing Related Data Together",
    summary: "Create ordered, mutable Lists, access elements with positive indexes, replace values, and inspect sensor data with len(), max(), and min().",
    durationMinutes: 150,
    level: "Beginner",
    introduction: { title: "Store related readings together", body: "Lesson 4.1 exposed the cost of separately named variables. This lesson introduces Python Lists as the first practical structure for one ordered body of related Smart Farm data." },
    objectives: [
      "Understand what a List is",
      "Create Lists",
      "Store multiple values in a single variable",
      "Access List elements using positive indexing",
      "Explain why Lists are ordered and mutable",
      "Use len(), max(), and min() with Lists",
      "Recognize when a List is the appropriate collection",
    ],
    whyThisMatters: { title: "Lists turn repeated values into manageable data", body: "One collection name makes related readings easier to access, update, summarize, and pass between the focused functions learners built in Module 3." },
    industryMotivation: { title: "Ordered datasets power monitoring dashboards", body: "A farm dashboard needs a predictable series of readings that can change as sensors report new values. Lists provide that beginner-friendly model.", signal: "This lesson teaches creation, positive indexing, element replacement, len(), max(), and min(). Negative indexing, slicing, list methods, sorting, and loops are intentionally deferred." },
    concept: { title: "A List is ordered, mutable, and permits duplicates", body: "Square brackets hold multiple elements under one variable name. Each element has a zero-based position, and an existing position can receive a new value.", items: ["Single variable", "Multiple elements", "Order", "Positive index", "Mutability", "Duplicates"] },
    workflow: { title: "Create, inspect, access, and replace", description: "Use the smallest complete workflow for learning List fundamentals.", steps: [
      { title: "Create", description: "Place related elements inside square brackets." },
      { title: "Visualize", description: "Map every element to a zero-based position." },
      { title: "Access", description: "Select one existing positive index." },
      { title: "Replace", description: "Assign a new value to an existing position." },
      { title: "Inspect", description: "Use len(), max(), and min()." },
    ] },
    agritechExample: { title: "One temperature List supports three immediate insights", body: "A dashboard can count four readings, identify 31 as the maximum, and identify 28 as the minimum while retaining the original sensor order." },
    playground: {
      title: "Explore a real moisture List",
      description: "Edit the List, access a positive index, replace an element, and run len(), max(), or min(). The synchronized panels visualize the current elements and selected index.",
      starterCode: "moisture = [25, 30, 28, 29, 31]\n\nprint(moisture)\nprint(moisture[0])\nprint(len(moisture))\nprint(max(moisture))\nprint(min(moisture))",
      expectedOutcome: "Python prints the complete List, its first element, the count 5, the maximum 31, and the minimum 25.",
    },
    practice: [
      { level: "Easy", title: "Create a crop List", prompt: "Create a List containing five crop names and print the complete List.", guidance: "Use one descriptive variable name and five quoted elements." },
      { level: "Medium", title: "Inspect temperature readings", prompt: "Create a temperature List and display its first element, last element using its positive index, and number of readings.", guidance: "Count the positions from zero; negative indexing begins in Lesson 4.3." },
      { level: "Challenge", title: "Summarize rainfall", prompt: "Create a List of rainfall values and display the highest and lowest readings.", guidance: "Use only max() and min(); sorting begins later." },
    ],
    quiz: [
      { title: "Question 1", question: "What does a Python List store?", options: ["Multiple values under one variable name", "Only one character", "Only functions", "No data"], correctOptionIndex: 0, note: "Lists group related elements.", explanation: "One List variable can refer to many ordered values." },
      { title: "Question 2", question: "What is the index of the first List element?", options: ["0", "1", "-1 only", "10"], correctOptionIndex: 0, note: "Python uses zero-based indexing.", explanation: "The first position is index 0." },
      { title: "Question 3", question: "What does mutable mean?", options: ["Elements can be replaced after creation", "The List has no order", "Duplicates are forbidden", "The List cannot change"], correctOptionIndex: 0, note: "Mutability permits in-place change.", explanation: "Assigning to an existing index replaces that element." },
      { title: "Question 4", question: "Which function counts List elements?", options: ["len()", "max()", "min()", "print()"], correctOptionIndex: 0, note: "len() reports collection size.", explanation: "It returns the number of elements." },
      { title: "Question 5", question: "Can a List contain duplicate values?", options: ["Yes", "No", "Only empty Lists", "Only strings"], correctOptionIndex: 0, note: "Duplicates preserve real repeated readings.", explanation: "Lists do not require unique elements." },
    ],
    assignment: { title: "Build a Farm Reading Snapshot", brief: "Create separate Lists for crops, temperatures, and rainfall, then demonstrate creation, positive indexing, mutability, and the three essential built-ins.", deliverables: ["A five-crop List", "A temperature List", "A rainfall List", "First and final elements using positive indexes", "One element replacement", "len() result", "max() result", "min() result", "A short explanation of order and mutability", "No negative indexing or slicing", "No list methods or loops"] },
    summarySection: { title: "You can now store and inspect related data with Lists", body: "You created Lists, mapped values to zero-based positions, accessed positive indexes, replaced elements, and used three essential Python built-ins without moving into later List techniques.", items: ["List creation", "Elements", "Order", "Positive indexing", "Mutability", "Duplicates", "len()", "max()", "min()"] },
    keyTakeaways: ["A List stores multiple related values in one variable", "Lists preserve element order", "Positive indexing begins at zero", "Lists are mutable and allow duplicates", "len(), max(), and min() inspect List contents", "Built-in functions and List methods are different categories"],
    whatsNext: { title: "Lesson 4.3 · Working with Lists", body: "Next, manage changing data through negative indexing, slicing, updates, additions, removals, traversal, built-ins, and List methods." },
    developmentPack: pythonListsDevelopmentPack,
  },
  {
    id: "module-4-lesson-3", moduleId: "module-4", number: "4.3", title: "Working with Lists", summary: "Manage changing Smart Farm data with negative indexing, slicing, updates, traversal, common built-ins, and the essential List methods.", durationMinutes: 180, level: "Beginner",
    introduction: { title: "A useful List must support change", body: "Sensor datasets grow, contain errors, and serve different reporting windows. This lesson completes the essential List toolkit before Module 4 moves to Tuples." },
    objectives: ["Access List elements using positive and negative indexing", "Extract portions of a List using slicing", "Update existing elements", "Add and remove elements", "Traverse a List", "Apply commonly used Python built-in functions and List methods", "Distinguish operations that return new results from methods that mutate a List", "Choose the appropriate List operation for a data-management task"],
    whyThisMatters: { title: "Real datasets evolve", body: "Farm monitoring software must correct faulty readings, incorporate new data, extract reporting windows, compute summaries, and preserve an understandable history." },
    industryMotivation: { title: "Operation semantics prevent data mistakes", body: "Professional developers care whether an operation changes live data or returns a separate result. The difference between sorted(readings) and readings.sort() is small in syntax but large in system behavior.", signal: "This lesson completes essential one-dimensional List operations. List comprehensions, nested Lists, matrices, and advanced sorting with key are intentionally deferred." },
    concept: { title: "List work combines access, mutation, traversal, and analysis", body: "Indexes and slices select data; assignments and methods modify it; traversal processes each element; built-ins compute or derive results.", items: ["Negative index", "Slice boundary", "Mutation", "Add", "Remove", "Traversal", "Built-in function", "List method", "Returned copy", "In-place change"] },
    workflow: { title: "Manage a sensor-data batch", description: "Move from selection to safe transformation and analysis.", steps: [{ title: "Select", description: "Use an index or slice." }, { title: "Correct", description: "Replace an incorrect element." }, { title: "Grow", description: "Append, insert, or extend." }, { title: "Clean", description: "Remove, pop, or clear." }, { title: "Traverse", description: "Process elements in order." }, { title: "Analyze", description: "Apply an appropriate built-in." }, { title: "Verify", description: "Inspect mutation versus returned results." }] },
    agritechExample: { title: "From raw readings to a managed snapshot", body: "The farm adds a reading, removes a fault, extracts a reporting window, traverses the clean batch, and computes count, total, minimum, and maximum." },
    playground: { title: "List Operations Laboratory", description: "Edit and run Python while the visualizer maps positive and negative indexes, highlights slices, records mutations, and calculates built-in results.", starterCode: "moisture = [25, 30, 28, 29, 31]\n\n# Explore indexing\nprint(moisture[-1])\nprint(moisture[1:4])\n\n# Modify\nmoisture.append(40)\nmoisture.remove(28)\n\nprint(sorted(moisture))\nprint(sum(moisture))", expectedOutcome: "Python prints 31, the slice [30, 28, 29], the sorted managed List, and the total 155." },
    practice: [{ level: "Easy", title: "Add a crop", prompt: "Append a new crop to an existing crop List and print the updated List.", guidance: "Use append() for one value at the end." }, { level: "Medium", title: "Clean and sort readings", prompt: "Remove one failed reading, preserve the original List, and display a sorted copy.", guidance: "Use remove() for the known fault and sorted() for a separate result." }, { level: "Challenge", title: "Calculate average moisture", prompt: "Clean a numeric List and calculate its average with sum(readings) / len(readings).", guidance: "Make sure the List is not empty before dividing." }],
    quiz: [{ title: "Question 1", question: "Which index selects the final element?", options: ["-1", "0", "1", "len(readings)"], correctOptionIndex: 0, note: "Negative indexes count from the end.", explanation: "-1 is the final element." }, { title: "Question 2", question: "In readings[1:4], is index 4 included?", options: ["No", "Yes", "Only for strings", "Only after sorting"], correctOptionIndex: 0, note: "Slice stop is exclusive.", explanation: "Indexes 1, 2, and 3 are selected." }, { title: "Question 3", question: "Which adds one element at the end?", options: ["append()", "extend()", "remove()", "clear()"], correctOptionIndex: 0, note: "append() receives one new element.", explanation: "extend() adds multiple elements from another iterable." }, { title: "Question 4", question: "What is the key difference between sorted(readings) and readings.sort()?", options: ["sorted() returns a new List; sort() mutates the List", "They are identical", "sort() returns a string", "sorted() clears the List"], correctOptionIndex: 0, note: "Returned copy versus in-place mutation matters.", explanation: "The original remains unchanged when only sorted() is called." }, { title: "Question 5", question: "What does traversal mean?", options: ["Visiting elements one at a time", "Deleting the List", "Creating a Tuple", "Renaming Python"], correctOptionIndex: 0, note: "A for loop can process every element.", explanation: "Traversal follows the collection in order." }],
    assignment: { title: "Create a Sensor Batch Manager", brief: "Build one program demonstrating safe access, slicing, updates, additions, removals, traversal, built-ins, and methods on a one-dimensional numeric List.", deliverables: ["Positive and negative access", "At least three slices", "One correction", "append(), insert(), and extend()", "remove() and pop()", "for-loop traversal", "len(), min(), max(), and sum()", "sorted() compared with sort()", "copy() demonstration", "Average calculation", "No comprehensions, nested Lists, matrices, or key sorting"] },
    summarySection: { title: "The essential List toolkit is complete", body: "You selected values from either end, extracted slices, corrected and reordered data, added and removed elements, traversed readings, compared built-ins with methods, and reasoned about returned results versus mutation.", items: ["Negative indexing", "Slicing", "Updating", "append / insert / extend", "remove / pop / clear", "Traversal", "Built-ins", "List methods", "Copy versus mutation"] },
    keyTakeaways: ["Positive and negative indexes provide flexible access", "A slice includes its start and excludes its stop", "Lists are ordered and mutable", "Built-ins work across many collection types", "List methods belong to List objects", "Some operations mutate while others return new results", "Lists suit ordered collections that change over time"],
    whatsNext: { title: "Lesson 4.4 · Tuples", body: "Next, explore immutable ordered collections, understand why fixed data benefits from protection, and compare Tuples directly with Lists." },
    developmentPack: workingWithListsDevelopmentPack,
  },
];

export const moduleFourLessonSummaries = [
  { id: "module-4-lesson-1", moduleId: "module-4", order: 1, title: "4.1 Why Collections?", estimatedMinutes: 120, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-4-lesson-2", moduleId: "module-4", order: 2, title: "4.2 Python Lists", estimatedMinutes: 150, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-4-lesson-3", moduleId: "module-4", order: 3, title: "4.3 Working with Lists", estimatedMinutes: 180, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-4-lesson-4", moduleId: "module-4", order: 4, title: "4.4 Tuples", estimatedMinutes: 120, status: "not-started" as const, isPlaceholder: true },
  { id: "module-4-lesson-5", moduleId: "module-4", order: 5, title: "4.5 Sets", estimatedMinutes: 120, status: "not-started" as const, isPlaceholder: true },
  { id: "module-4-lesson-6", moduleId: "module-4", order: 6, title: "4.6 Dictionaries", estimatedMinutes: 150, status: "not-started" as const, isPlaceholder: true },
  { id: "module-4-lesson-7", moduleId: "module-4", order: 7, title: "4.7 Collection Operations & Built-ins", estimatedMinutes: 150, status: "not-started" as const, isPlaceholder: true },
  { id: "module-4-lesson-8", moduleId: "module-4", order: 8, title: "4.8 Choosing the Right Collection", estimatedMinutes: 120, status: "not-started" as const, isPlaceholder: true },
  { id: "module-4-lesson-9", moduleId: "module-4", order: 9, title: "4.9 Collections in Real-World Applications", estimatedMinutes: 150, status: "not-started" as const, isPlaceholder: true },
  { id: "module-4-lesson-10", moduleId: "module-4", order: 10, title: "4.10 Smart Farm Data Management Capstone", estimatedMinutes: 240, status: "not-started" as const, isPlaceholder: true },
];
