import { firstProgramDevelopmentPack } from "@/content/development-packs/lesson-1-1";
import { variablesDevelopmentPack } from "@/content/development-packs/lesson-1-2";
import { dataTypesDevelopmentPack } from "@/content/development-packs/lesson-1-3";
import { userInputDevelopmentPack } from "@/content/development-packs/lesson-1-4";
import { typeConversionDevelopmentPack } from "@/content/development-packs/lesson-1-5";
import { operatorsDevelopmentPack } from "@/content/development-packs/lesson-1-6";
import { problemSolvingDevelopmentPack } from "@/content/development-packs/lesson-1-7";
import { smartFarmProjectDevelopmentPack } from "@/content/development-packs/lesson-1-8";
import type { LessonDocument } from "@/types/content";

export const moduleOneLessons: LessonDocument[] = [
  {
    id: "module-1-lesson-1",
    moduleId: "module-1",
    number: "1.1",
    title: "Writing Your First Python Program",
    summary: "Learn how programs give computers instructions, then write, run, read, and debug a first Python program.",
    durationMinutes: 40,
    level: "Beginner",
    introduction: { title: "Your first instructions for a computer", body: "Programming begins with a simple idea: describe a task clearly enough that a computer can carry it out." },
    objectives: [
      "Understand what a computer program is",
      "Understand what Python code is",
      "Write and execute a first Python program",
      "Use the print() function",
      "Understand statements and comments",
      "Understand why indentation matters",
      "Read Python syntax confidently",
      "Modify an existing program",
    ],
    whyThisMatters: { title: "Programs turn repeated work into repeatable instructions", body: "Clear instructions allow computers to display reports, process observations, and support reliable workflows without rewriting the same message manually." },
    industryMotivation: { title: "Programming supports almost every modern industry", body: "Banking, artificial intelligence, websites, agriculture, mobile applications, and space research all depend on programs that express tasks precisely.", signal: "Readable programs make instructions easier for teams to review, improve, and reuse." },
    concept: { title: "A Python program is a sequence of statements", body: "Python normally reads statements from top to bottom. Correct spelling, punctuation, quotation marks, parentheses, and indentation determine whether those statements can run.", items: ["Programs", "Statements", "print()", "Comments", "Indentation"] },
    workflow: firstProgramDevelopmentPack.story.workflow,
    agritechExample: { title: "A smart agriculture status screen", body: "Several print statements can display a readable field report containing the farmer, crop, temperature, and rainfall." },
    playground: { title: "Run your first Python program", description: "Run the two statements, then personalise the messages and add more print statements.", starterCode: "print(\"Welcome to Python\")\nprint(\"Let's Learn Programming\")", expectedOutcome: "The two messages should appear in order. Each additional print statement should add another output line." },
    practice: [
      { level: "Easy", title: "Display personal details", prompt: "Write three print statements about yourself.", guidance: "Place each message inside quotation marks.", activities: ["Print your name", "Print your village", "Print your college"] },
      { level: "Medium", title: "Create a farmer profile", prompt: "Display Farmer, Crop, Village, and District on separate lines.", guidance: "Use one print statement for each line." },
      { level: "Challenge", title: "Build a welcome banner", prompt: "Use print statements to display a border, WELCOME, SMART FARM, and a closing border.", guidance: "A line of asterisks is still a message and needs quotation marks." },
    ],
    quiz: [
      { title: "Question 1", question: "Programming means", options: ["Playing games", "Giving instructions", "Browsing the internet", "Watching videos"], correctOptionIndex: 1, note: "Programming is the process of giving a computer instructions.", explanation: "A program contains instructions that tell a computer what task to perform." },
      { title: "Question 2", question: "Which function displays output?", options: ["input()", "show()", "print()", "display()"], correctOptionIndex: 2, note: "print() displays output.", explanation: "The built-in print function sends a value or message to the output screen." },
      { title: "Question 3", question: "Which symbol starts a Python comment?", options: ["#", "//", "<!--", "**"], correctOptionIndex: 0, note: "Python comments begin with #.", explanation: "Python ignores the text after # on that line." },
      { title: "Question 4", question: "In this lesson, Python normally executes statements", options: ["Bottom to top", "Randomly", "Top to bottom", "All at once"], correctOptionIndex: 2, note: "Python normally proceeds from top to bottom.", explanation: "For this simple program, the interpreter handles each statement in sequence." },
      { title: "Question 5", question: "Which statement correctly displays Rice?", options: ["Print Rice", "print(\"Rice\")", "display Rice", "print Rice"], correctOptionIndex: 1, note: "print(\"Rice\") is correct.", explanation: "The function name is lowercase, the message is quoted, and the parentheses are complete." },
    ],
    assignment: { title: "Create a Smart Agriculture System welcome screen", brief: "Write a Python program that displays a clear welcome screen for a smart agriculture system.", deliverables: ["Farmer name", "Crop", "Village", "Temperature", "Date", "A readable heading"] },
    summarySection: { title: "You can now read and run a simple Python program", body: "Programs contain instructions. Python executes statements, print displays output, comments explain code, and indentation must be intentional.", items: ["Programming", "Python code", "print()", "Statements", "Comments", "Indentation", "Running programs"] },
    keyTakeaways: ["Python is designed to be readable", "Programs are collections of instructions", "print() displays output", "Comments improve readability", "Indentation matters", "Practice makes programming easier"],
    whatsNext: { title: "Lesson 1.2 · Variables", body: "Next, discover how Python remembers information so a program can reuse names and values." },
    developmentPack: firstProgramDevelopmentPack,
  },
  {
    id: "module-1-lesson-2",
    moduleId: "module-1",
    number: "1.2",
    title: "Variables: Storing Information in Python",
    summary: "Learn how meaningful variable names help Python remember, update, inspect, and reuse agricultural information.",
    durationMinutes: 60,
    level: "Beginner",
    introduction: { title: "Give every value a meaningful name", body: "Variables connect readable names such as crop and soil_moisture to values a program needs to remember." },
    objectives: [
      "Understand what variables are and why they are needed",
      "Create and modify variables",
      "Understand assignment with =",
      "Follow Python variable-naming rules",
      "Choose meaningful variable names",
      "Print current variable values",
      "Understand that Python names can be rebound dynamically",
      "Apply variables to Agritech information",
    ],
    whyThisMatters: { title: "Names preserve the meaning of agricultural observations", body: "A value such as 31 becomes useful when a program identifies it as temperature. Meaningful names make information easier to update, inspect, and reuse." },
    industryMotivation: { title: "Operational systems depend on clearly named changing values", body: "Irrigation dashboards, sensor services, weather tools, and farm reports continually update named observations such as soil moisture, humidity, and rainfall.", signal: "Readable variable names reduce ambiguity when researchers and engineers review the same program." },
    concept: { title: "Variables are names bound to values", body: "Assignment binds a name to a value managed by Python. Reassignment can bind that name to a newer value without declaring a fixed type for the name.", items: ["Meaningful name", "Assignment", "Current value", "Reassignment", "Dynamic binding"] },
    workflow: variablesDevelopmentPack.story.workflow,
    agritechExample: { title: "A readable smart-farm record", body: "Variables can preserve the meaning of farmer, crop, village, temperature, rainfall, and soil-moisture observations in one short program." },
    playground: { title: "Build a live farm memory model", description: "Edit the assignments and watch the memory visualizer and variable inspector update before running the code.", starterCode: "farmer = \"Rahul\"\ncrop = \"Rice\"\ntemperature = 31\nsoil_moisture = 42\n\nprint(farmer)\nprint(crop)", expectedOutcome: "The output should display Rahul and Rice. The inspector should show the four current variables." },
    practice: [
      { level: "Easy", title: "Create three personal variables", prompt: "Create variables for your name, age, and city, then print them.", guidance: "Use meaningful lowercase names and one assignment per line.", activities: ["Create name", "Create age", "Create city"] },
      { level: "Medium", title: "Represent a farm profile", prompt: "Store and display crop, rainfall, temperature, farmer, and village.", guidance: "Use snake_case when a name needs more than one word." },
      { level: "Challenge", title: "Model ten farm parameters", prompt: "Create meaningful variables for ten different farm parameters and display every current value.", guidance: "Choose names that another agricultural researcher could understand without extra explanation." },
    ],
    quiz: [
      { title: "Question 1", question: "What is a variable in this lesson?", options: ["A named reference to a value", "A Python error", "A printed heading", "A comment"], correctOptionIndex: 0, note: "A variable is a name bound to a value.", explanation: "Python uses names to refer to values it manages in memory." },
      { title: "Question 2", question: "Which symbol assigns a value?", options: ["==", "=", "#", "-"], correctOptionIndex: 1, note: "The = symbol performs assignment.", explanation: "Assignment binds the name on the left to the value on the right." },
      { title: "Question 3", question: "Which variable name is valid?", options: ["2crop", "crop-name", "crop name", "crop_name"], correctOptionIndex: 3, note: "crop_name is valid.", explanation: "It begins with a letter and contains only letters and an underscore." },
      { title: "Question 4", question: "What happens after assigning a new value to an existing variable?", options: ["Later code reads the new value", "Python keeps only the old value", "The name becomes invalid", "The program turns into a comment"], correctOptionIndex: 0, note: "Later code uses the latest binding.", explanation: "Reassignment updates which value the variable name refers to." },
      { title: "Question 5", question: "Can a variable's value change during a program?", options: ["Yes", "No", "Only in comments", "Only after restarting Python"], correctOptionIndex: 0, note: "Variables can be reassigned.", explanation: "A later assignment can bind the same name to a new value." },
    ],
    assignment: { title: "Create a Smart Farm Information System", brief: "Write a readable Python program that stores and displays a complete smart-farm profile.", deliverables: ["Farmer name", "Village", "Crop", "Temperature", "Rainfall", "Humidity", "Soil moisture", "A print statement for every stored value"] },
    summarySection: { title: "Variables give changing information a readable identity", body: "You created, printed, updated, validated, inspected, and swapped variables while connecting each name to a current value managed by Python.", items: ["Variables", "Assignment", "Memory", "Naming rules", "Updating", "Printing", "Swapping"] },
    keyTakeaways: ["Variables help Python remember information", "Meaningful names preserve context", "Assignment with = stores a value under a name", "Variables can change over time", "Readable names make programs easier to understand"],
    whatsNext: { title: "Lesson 1.3 · Data Types", body: "Next, explore how Python distinguishes numbers, text, logical values, and other kinds of information." },
    developmentPack: variablesDevelopmentPack,
  },
  {
    id: "module-1-lesson-3",
    moduleId: "module-1",
    number: "1.3",
    title: "Data Types in Python",
    summary: "Understand how Python represents text, whole numbers, decimal measurements, logical states, and unavailable information.",
    durationMinutes: 60,
    level: "Beginner",
    introduction: { title: "Different information needs different representations", body: "Farm records contain names, counts, measurements, status values, and sometimes missing observations. Python uses data types to distinguish them." },
    objectives: [
      "Understand why data types exist",
      "Differentiate between int, float, str, bool, and None",
      "Use the type() function",
      "Convert compatible values between data types",
      "Identify common data-type mistakes",
      "Apply appropriate data types to Agritech scenarios",
    ],
    whyThisMatters: { title: "A value's type determines how Python can use it", body: "The characters 10 can represent a number or text. Choosing the appropriate type allows Python to calculate, display, compare, and communicate information correctly." },
    industryMotivation: { title: "Reliable data systems preserve the meaning of every field", body: "Sensor pipelines, farm databases, dashboards, and analytical tools distinguish text labels, numeric measurements, logical states, and missing observations.", signal: "A correct value with the wrong type can still produce an error or a misleading result." },
    concept: { title: "Every Python value has a data type", body: "This lesson focuses on five foundational representations: int, float, str, bool, and NoneType. The type function reveals the current type of a value.", items: ["int", "float", "str", "bool", "NoneType", "type()", "Conversion"] },
    workflow: dataTypesDevelopmentPack.story.workflow,
    agritechExample: { title: "One farm record, several data types", body: "A smart-farm record can combine strings for names, floats for precise measurements, integers for counts, Booleans for status, and None for unavailable sensor data." },
    playground: { title: "Explore live Python data types", description: "Edit the values and watch the shared Variable Explorer update their value, detected type, and memory representation before running Python.", starterCode: "farmer = \"Rahul\"\ntemperature = 31.5\nplants = 2500\nmotor_on = True\nsensor_data = None\n\nprint(type(farmer))\nprint(type(temperature))\nprint(type(plants))\nprint(type(motor_on))\nprint(type(sensor_data))", expectedOutcome: "Python should display str, float, int, bool, and NoneType in that order." },
    practice: [
      { level: "Easy", title: "Choose three appropriate types", prompt: "Create variables for a name, age, and temperature using appropriate values.", guidance: "Use quoted text for the name, a whole number for age, and a decimal measurement for temperature.", activities: ["Create name", "Create age", "Create temperature"] },
      { level: "Medium", title: "Represent a farm observation set", prompt: "Store crop, rainfall, soil pH, motor status, and farmer name using appropriate data types.", guidance: "Decide which values are text, measurements, or two-state information." },
      { level: "Challenge", title: "Build a ten-field smart-farm dataset", prompt: "Create ten meaningful variables using int, float, str, bool, and None where appropriate.", guidance: "Include at least one value of every foundational type introduced in this lesson." },
    ],
    quiz: [
      { title: "Question 1", question: "Which data type stores decimal values?", options: ["float", "int", "str", "bool"], correctOptionIndex: 0, note: "float stores decimal values.", explanation: "A value such as 31.5 is represented as a float." },
      { title: "Question 2", question: "Which data type stores text?", options: ["bool", "str", "int", "NoneType"], correctOptionIndex: 1, note: "str stores text.", explanation: "Text enclosed in quotation marks is a string." },
      { title: "Question 3", question: "What does type() do?", options: ["Reports a value's data type", "Reads keyboard input", "Deletes a variable", "Starts a loop"], correctOptionIndex: 0, note: "type() reports the current type.", explanation: "Passing a value or variable to type() reveals its Python data type." },
      { title: "Question 4", question: "Which value belongs to the bool data type?", options: ["\"True\"", "1.0", "True", "None"], correctOptionIndex: 2, note: "True is a Boolean value.", explanation: "Python Boolean values are exactly True and False without quotation marks." },
      { title: "Question 5", question: "What does None represent?", options: ["No value is currently available", "The number zero", "An empty crop name", "A syntax error"], correctOptionIndex: 0, note: "None represents no current value.", explanation: "None is useful when information is absent or not available yet." },
    ],
    assignment: { title: "Build a typed Farm Information System", brief: "Create and run a farm-information program that stores each field using an appropriate data type and prints every value with its type.", deliverables: ["Farmer name", "Crop", "Rainfall", "Soil pH", "Temperature", "Motor status", "Sensor value set to None", "Printed values and type() results"] },
    summarySection: { title: "You can now choose and inspect foundational Python data types", body: "You represented whole numbers, decimal measurements, text, logical states, and missing information, then inspected and converted compatible values.", items: ["Integer", "Float", "String", "Boolean", "None", "type()", "Type conversion"] },
    keyTakeaways: ["Every value has a data type", "Data types determine how values behave", "Choose the appropriate type for the information", "type() reveals the current type", "Type conversion is common when values arrive in another compatible form"],
    whatsNext: { title: "Lesson 1.4 · User Input", body: "Next, learn how a program can receive information directly from a user instead of relying only on values written in the code." },
    developmentPack: dataTypesDevelopmentPack,
  },
  {
    id: "module-1-lesson-4",
    moduleId: "module-1",
    number: "1.4",
    title: "User Input in Python",
    summary: "Turn fixed scripts into interactive applications that collect, convert, and display information supplied by each user.",
    durationMinutes: 60,
    level: "Beginner",
    introduction: { title: "Let the user become part of the program", body: "Until now, every value was written into the source code. input() allows a running program to ask for information and adapt its output." },
    objectives: [
      "Understand why user input is important",
      "Use the input() function",
      "Store user input in variables",
      "Display user-provided information",
      "Convert compatible input with int() and float()",
      "Build an interactive console application",
      "Avoid common input-handling mistakes",
    ],
    whyThisMatters: { title: "Real applications respond to the people using them", body: "A program becomes more useful when it can collect current names, crops, and measurements instead of repeating one fixed record." },
    industryMotivation: { title: "Interactive systems begin by collecting reliable information", body: "Registration tools, field-survey applications, sensor configuration screens, and farm dashboards all receive information before they can produce a useful result.", signal: "Input validation and error recovery become important in later lessons; this lesson establishes the collection and conversion foundation." },
    concept: { title: "input() always returns a string", body: "The prompt asks a question, the user types a response, and input() returns that response as text. Use int() or float() when compatible text must become a number.", items: ["Prompt", "Response", "String", "Variable", "Conversion", "Output"] },
    workflow: userInputDevelopmentPack.story.workflow,
    agritechExample: { title: "Collect a live smart-farm observation", body: "An interactive program can ask each farmer for a crop, temperature, rainfall, and soil-moisture reading, then display a personalised report." },
    playground: { title: "Run an interactive farm program", description: "Use the synchronized farm fields as responses for input(). Edit the Python code, run it, and compare the console interaction with form mode.", starterCode: "farmer = input(\"Farmer Name : \")\ncrop = input(\"Crop : \")\ntemperature = float(input(\"Temperature : \"))\n\nprint(\"Farmer :\", farmer)\nprint(\"Crop :\", crop)\nprint(\"Temperature :\", temperature)", expectedOutcome: "The console should echo each supplied response and display a personalised farmer, crop, and temperature report." },
    practice: [
      { level: "Easy", title: "Collect a personal profile", prompt: "Ask for name, age, and city, then display all three values.", guidance: "Keep name and city as strings. Convert age with int() if you need it as a whole number.", activities: ["Ask for a name", "Ask for an age", "Ask for a city", "Display each response"] },
      { level: "Medium", title: "Collect a farm profile", prompt: "Ask for crop, village, temperature, and rainfall, then display a readable report.", guidance: "Use float(input(...)) for measurements that may contain decimals." },
      { level: "Challenge", title: "Design a ten-field interactive report", prompt: "Collect ten meaningful values and display them in a formatted report.", guidance: "Choose string, integer, or float conversion based on what each response represents." },
    ],
    quiz: [
      { title: "Question 1", question: "Which Python function accepts keyboard input?", options: ["print()", "input()", "type()", "show()"], correctOptionIndex: 1, note: "input() receives a response.", explanation: "input() optionally displays a prompt and returns the entered text." },
      { title: "Question 2", question: "What type does input() return by default?", options: ["int", "float", "str", "bool"], correctOptionIndex: 2, note: "input() returns str.", explanation: "Even digit characters arrive as text until they are converted." },
      { title: "Question 3", question: "Why wrap input() with int()?", options: ["To create a whole number from compatible digit text", "To display a message", "To start the program", "To create a comment"], correctOptionIndex: 0, note: "int() creates a whole number.", explanation: "Numerical calculations need a numeric value rather than digit text." },
      { title: "Question 4", question: "Which conversion is appropriate for a decimal temperature?", options: ["str()", "bool()", "float()", "list()"], correctOptionIndex: 2, note: "float() preserves decimal measurements.", explanation: "A response such as 31.5 can be converted with float()." },
      { title: "Question 5", question: "Can input() collect a crop name?", options: ["Yes", "No", "Only after int()", "Only inside a loop"], correctOptionIndex: 0, note: "input() can collect text.", explanation: "A crop name is exactly the kind of string input() returns." },
    ],
    assignment: { title: "Build a Student Information System", brief: "Create an interactive program that collects student information and displays a clearly formatted report.", deliverables: ["Name", "Roll number", "Branch", "Semester", "CGPA", "Appropriate numeric conversions", "A readable report heading"] },
    summarySection: { title: "You can now build programs that respond to their users", body: "You collected text and numeric responses, stored them in variables, converted compatible values, and displayed personalised console reports.", items: ["input()", "Text input", "Numeric input", "Type conversion", "Interactive programs", "Console applications"] },
    keyTakeaways: ["input() makes programs interactive", "input() always returns a string", "Use int() for compatible whole-number input", "Use float() for compatible decimal input", "Interactive programs can adapt to each user"],
    whatsNext: { title: "Lesson 1.5 · Type Conversion", body: "Next, explore conversion between Python data types in greater depth and learn how conversion supports calculations and data processing." },
    developmentPack: userInputDevelopmentPack,
  },
  {
    id: "module-1-lesson-5",
    moduleId: "module-1",
    number: "1.5",
    title: "Type Conversion in Python",
    summary: "Learn how and why Python values move between text, whole-number, decimal, and Boolean representations.",
    durationMinutes: 60,
    level: "Beginner",
    introduction: { title: "Choose the representation needed for the next task", body: "Programs often receive information in one form and need it in another. Type conversion makes that transformation explicit, predictable, and useful." },
    objectives: [
      "Explain what type conversion is",
      "Differentiate between implicit and explicit conversion",
      "Use int(), float(), str(), and bool()",
      "Predict compatible conversion results",
      "Recognize and diagnose invalid conversions",
      "Apply type conversion in Agritech programs",
    ],
    whyThisMatters: { title: "Useful data must have a representation that matches the task", body: "Sensor readings and keyboard input often arrive as text. Calculations, reporting, and status handling require deliberate choices about when and how those values should change type." },
    industryMotivation: { title: "Data pipelines convert representations at every boundary", body: "Farm sensors, CSV files, APIs, forms, and databases exchange information in different formats. Reliable systems convert fields intentionally before analysis or automation.", signal: "Conversion does not repair incorrect information; production systems validate source data before trusting the converted result." },
    concept: { title: "Conversion can be implicit or explicit", body: "Python performs some safe numeric promotions automatically. A programmer uses int(), float(), str(), or bool() when the required destination representation must be stated directly.", items: ["Implicit conversion", "Explicit conversion", "int()", "float()", "str()", "bool()", "ValueError"] },
    workflow: typeConversionDevelopmentPack.story.workflow,
    agritechExample: { title: "Prepare farm observations for calculation and reporting", body: "A farm application can preserve names as text, convert measurements to floats, convert counts to integers, and decode a 1/0 status as a Boolean." },
    playground: { title: "Trace live type conversions", description: "Edit the conversions, run real Python, and inspect the original value, conversion result, variable types, console output, and every executed line.", starterCode: "temperature = \"31.5\"\ntemperature = float(temperature)\n\nplants = \"250\"\nplants = int(plants)\n\nprint(temperature)\nprint(plants)", expectedOutcome: "Python should display 31.5 and 250. The trace should show each variable changing from str to its numeric type." },
    practice: [
      { level: "Easy", title: "Convert three foundational values", prompt: "Convert \"25\" to int, 20 to float, and 50 to str, then print each result and type.", guidance: "Store each converted result in a meaningfully named variable.", activities: ["Convert \"25\" with int()", "Convert 20 with float()", "Convert 50 with str()"] },
      { level: "Medium", title: "Convert interactive measurements", prompt: "Accept age and rainfall using input(), convert age to int and rainfall to float, then display both results.", guidance: "Wrap each input() call with the conversion function appropriate for the field." },
      { level: "Challenge", title: "Build a typed farm registration program", prompt: "Collect a farm profile and convert every field to a type that matches its meaning.", guidance: "Keep names as strings, counts as integers, measurements as floats, and document how a 1/0 status becomes Boolean." },
    ],
    quiz: [
      { title: "Question 1", question: "Which function converts compatible values to an integer?", options: ["str()", "float()", "int()", "input()"], correctOptionIndex: 2, note: "int() creates integers.", explanation: "int() converts compatible digit text, floats, and Boolean values into whole numbers." },
      { title: "Question 2", question: "What is implicit conversion?", options: ["A safe conversion Python performs automatically", "A conversion written with int()", "A syntax error", "A comment"], correctOptionIndex: 0, note: "Python performs implicit conversion automatically.", explanation: "For example, Python can promote an integer to float in a mixed numeric expression." },
      { title: "Question 3", question: "What happens when Python runs int(\"Rice\")?", options: ["It returns 0", "It returns Rice", "It raises ValueError", "It returns True"], correctOptionIndex: 2, note: "The conversion raises ValueError.", explanation: "Rice is not a valid whole-number representation." },
      { title: "Question 4", question: "Which function creates a decimal representation?", options: ["bool()", "float()", "str()", "print()"], correctOptionIndex: 1, note: "float() creates decimal values.", explanation: "Compatible integers and numeric strings can be converted to float." },
      { title: "Question 5", question: "What is the output of bool(0)?", options: ["True", "False", "0.0", "ValueError"], correctOptionIndex: 1, note: "bool(0) is False.", explanation: "Numeric zero is a falsy value in Python." },
    ],
    assignment: { title: "Create a Crop Information System", brief: "Build an interactive crop-information program and convert every response to a representation that matches its meaning.", deliverables: ["Crop name as text", "Number of plants as int", "Average height as float", "Irrigation status entered as 1/0 and converted to bool", "A formatted report", "Printed type() checks"] },
    summarySection: { title: "You can now transform compatible values deliberately", body: "You compared implicit and explicit conversion, used Python's foundational conversion functions, predicted results, inspected errors, and traced variables as their types changed.", items: ["Implicit conversion", "Explicit conversion", "int()", "float()", "str()", "bool()", "Conversion errors", "Agritech applications"] },
    keyTakeaways: ["Type conversion changes one representation into another", "Python performs some safe conversions automatically", "Programmers request explicit conversion with conversion functions", "Validate source information before converting it", "Interactive and data-processing programs depend on correct conversions"],
    whatsNext: { title: "Lesson 1.6 · Operators in Python", body: "Next, explore how Python performs calculations, comparisons, and logical operations using operators." },
    developmentPack: typeConversionDevelopmentPack,
  },
  {
    id: "module-1-lesson-6",
    moduleId: "module-1",
    number: "1.6",
    title: "Operators in Python",
    summary: "Calculate, compare, combine conditions, update values, inspect identity and membership, and understand how Python evaluates expressions.",
    durationMinutes: 90,
    level: "Beginner",
    introduction: { title: "Turn values into calculations and decision signals", body: "Operators connect the variables and data types learned so far. They allow a program to calculate quantities, compare measurements, and combine several Boolean conditions." },
    objectives: [
      "Understand operators and operands",
      "Perform arithmetic operations",
      "Use comparison operators",
      "Combine Boolean conditions with logical operators",
      "Update variables with assignment operators",
      "Distinguish identity from equality",
      "Check membership in text and simple containers",
      "Recognize introductory bitwise operators",
      "Apply operator precedence",
      "Build Agritech decision expressions",
    ],
    whyThisMatters: { title: "Every calculation and decision begins with an expression", body: "Yield estimation, irrigation thresholds, resource allocation, validation, and status checks all depend on operators producing accurate numeric or Boolean results." },
    industryMotivation: { title: "Agricultural systems continuously evaluate operational rules", body: "Sensor services calculate averages, compare readings with thresholds, combine safety conditions, and update running totals before an application selects an action.", signal: "This lesson produces Boolean decision signals. Lesson 1.8 will use if statements to map those signals to different program actions." },
    concept: { title: "Operators act on operands and produce results", body: "Python groups operators by purpose: arithmetic, comparison, logical, assignment, identity, membership, and bitwise. Precedence determines which operation happens first inside a larger expression.", items: ["Arithmetic", "Comparison", "Logical", "Assignment", "Identity", "Membership", "Bitwise", "Precedence"] },
    workflow: operatorsDevelopmentPack.story.workflow,
    agritechExample: { title: "Combine farm measurements into one decision signal", body: "Comparison operators evaluate individual thresholds and logical and requires every irrigation condition to be satisfied." },
    playground: { title: "Explore farm operators with execution tracing", description: "Edit the values and expressions, run real Python, then inspect results in the console, Operator Explorer, Expression Visualizer, Variable Explorer, and Code Trace Panel.", starterCode: "temperature = 32\nrainfall = 20\n\nprint(temperature > 30)\nprint(rainfall < 50)\nprint(temperature > 30 and rainfall < 50)", expectedOutcome: "Python should display True three times. Changing either measurement should update the comparison and combined logical result." },
    practice: [
      { level: "Easy", title: "Practice arithmetic operations", prompt: "Create two agricultural values and calculate their sum, difference, and product.", guidance: "Print each expression separately so its result is easy to verify.", activities: ["Addition", "Subtraction", "Multiplication"] },
      { level: "Medium", title: "Compare environmental measurements", prompt: "Compare temperature, rainfall, and humidity with meaningful thresholds and print each Boolean result.", guidance: "Write one precise comparison for each measurement before combining anything." },
      { level: "Challenge", title: "Build an irrigation decision expression", prompt: "Combine temperature, rainfall, humidity, and soil-moisture comparisons into one should_start_irrigation Boolean variable.", guidance: "Use and when every threshold is required. Print the Boolean signal without using an if statement." },
    ],
    quiz: [
      { title: "Question 1", question: "Which operator checks whether two values are equal?", options: ["=", "==", "!=", "is"], correctOptionIndex: 1, note: "== compares values.", explanation: "A single = performs assignment, while == asks whether values are equal." },
      { title: "Question 2", question: "Which operator performs exponentiation?", options: ["^", "**", "//", "%"], correctOptionIndex: 1, note: "** performs exponentiation.", explanation: "For example, 2 ** 3 produces 8." },
      { title: "Question 3", question: "What is the difference between = and ==?", options: ["= assigns and == compares", "They are identical", "= compares and == assigns", "Both are logical operators"], correctOptionIndex: 0, note: "Assignment and comparison have different roles.", explanation: "Use = to bind or update a variable and == to compare values." },
      { title: "Question 4", question: "What does and require?", options: ["Every combined condition must be True", "Only one condition must be True", "Every condition must be False", "Two numbers must be equal"], correctOptionIndex: 0, note: "and requires all conditions to be true.", explanation: "If one Boolean operand is false, the combined and result is false." },
      { title: "Question 5", question: "Which operator checks membership?", options: ["in", "is", "==", "&"], correctOptionIndex: 0, note: "in checks membership.", explanation: "in asks whether a value occurs inside a sequence or collection." },
    ],
    assignment: { title: "Create a Farm Eligibility Checker", brief: "Accept farm measurements, convert them to numeric types, and calculate a Boolean irrigation-eligibility signal using comparisons and logical operators.", deliverables: ["Temperature input", "Rainfall input", "Soil-moisture input", "Appropriate float conversions", "Meaningful threshold comparisons", "One combined eligibility variable", "A formatted report containing the Boolean result"] },
    summarySection: { title: "You can now build complete Python expressions", body: "You calculated values, compared measurements, combined Boolean results, updated variables, inspected identity and membership, explored binary operations, and followed precedence rules.", items: ["Arithmetic operators", "Comparison operators", "Logical operators", "Assignment operators", "Identity operators", "Membership operators", "Bitwise introduction", "Operator precedence"] },
    keyTakeaways: ["Operators allow Python to calculate, compare, and create decision signals", "Each operator category serves a distinct purpose", "Logical operators combine Boolean conditions", "Identity is different from value equality", "Operator precedence changes evaluation order", "Operators prepare learners for conditions, loops, and complete problem-solving programs"],
    whatsNext: { title: "Lesson 1.7 · Expressions & Problem Solving", body: "Next, combine variables, data types, user input, type conversion, and operators in complete Agritech calculations and problem-solving programs." },
    developmentPack: operatorsDevelopmentPack,
  },
  {
    id: "module-1-lesson-7",
    moduleId: "module-1",
    number: "1.7",
    title: "Expressions & Problem Solving",
    summary: "Stop memorizing isolated syntax and learn how to translate real requirements into inputs, formulas, readable Python programs, and verified results.",
    durationMinutes: 120,
    level: "Beginner to Intermediate",
    introduction: { title: "Start thinking like a programmer", body: "Variables, data types, input, conversion, and operators become useful when they work together to solve a complete problem. This lesson establishes a repeatable process for moving from a real request to a tested result." },
    objectives: [
      "Solve real-world numerical problems",
      "Break a large problem into smaller steps",
      "Write complete Python programs",
      "Build and evaluate mathematical expressions",
      "Read a problem statement carefully",
      "Identify required inputs and their units",
      "Define meaningful outputs",
      "Display and verify useful results",
    ],
    whyThisMatters: { title: "Software users ask for outcomes, not syntax", body: "A farmer needs a fertilizer estimate, not an explanation of multiplication. A programmer must understand that requirement, identify the information and formula, then create a reliable program that communicates the answer." },
    industryMotivation: { title: "Agricultural software converts field requirements into measurable decisions", body: "Resource calculators, yield estimators, financial tools, and research workflows all begin with clearly defined inputs, consistent units, formulas, and outputs that domain experts can verify.", signal: "A correct-looking program is not enough. The result must also be reasonable, correctly labelled, and useful to the person making the decision." },
    concept: { title: "Problem solving connects every Module 1 building block", body: "A complete numerical program receives values, converts them to appropriate types, stores them under meaningful names, evaluates expressions, and prints a result with context and units.", items: ["Understand", "Inputs", "Outputs", "Formula", "Expression", "Code", "Test", "Verify"] },
    workflow: problemSolvingDevelopmentPack.story.workflow,
    agritechExample: { title: "One formula can answer an operational farm question", body: "Land area multiplied by a per-acre rate can estimate total yield, water, fertilizer, or seed requirements. The formula is simple; disciplined interpretation and verification make the program trustworthy." },
    playground: { title: "Solve and trace a crop-yield problem", description: "Edit the complete Python program, supply simulated console inputs, run it in the browser, and compare the output with the calculation steps and execution trace.", starterCode: "area = float(input(\"Land Area (acres): \"))\n\nyield_per_acre = float(input(\"Yield per Acre (kg): \"))\n\ntotal_yield = area * yield_per_acre\n\nprint(\"Total Yield:\", total_yield, \"kg\")", expectedOutcome: "With 5 acres and 750 kg per acre, the program should display Total Yield: 3750.0 kg." },
    practice: [
      { level: "Easy", title: "Translate formulas into expressions", prompt: "Create complete programs for rectangle area and the average of four measurements.", guidance: "Write the inputs, formula, and labelled output before running each program.", activities: ["Rectangle area", "Average of four numbers"] },
      { level: "Medium", title: "Build practical calculators", prompt: "Create complete GST, discount, and profit calculators using converted user input.", guidance: "Separate intermediate values such as tax amount or revenue when that makes the solution easier to verify.", activities: ["GST calculator", "Discount calculator", "Profit calculator"] },
      { level: "Challenge", title: "Solve complete Agritech resource problems", prompt: "Build crop-yield, fertilizer, water, and seed estimators with meaningful units and independently verified sample results.", guidance: "Apply the seven-stage framework to every problem before writing code.", activities: ["Crop yield", "Fertilizer requirement", "Water requirement", "Seed requirement"] },
    ],
    quiz: [
      { title: "Question 1", question: "What is a Python expression?", options: ["A combination of values, variables, and operators that produces a result", "Only a variable name", "Only an input prompt", "A comment"], correctOptionIndex: 0, note: "Expressions produce values.", explanation: "For example, area * yield_per_acre combines two variables with an operator and produces total yield." },
      { title: "Question 2", question: "Which operator performs exponentiation?", options: ["^", "**", "//", "%"], correctOptionIndex: 1, note: "** performs exponentiation.", explanation: "Expressions such as radius ** 2 square a numeric value." },
      { title: "Question 3", question: "What should happen before writing a formula in code?", options: ["Identify the required inputs and output", "Choose random values", "Add a loop", "Memorize print()"], correctOptionIndex: 0, note: "Understand the information flow first.", explanation: "Inputs, output, and units define what the formula must accomplish." },
      { title: "Question 4", question: "Why are numeric input values converted with float() in these calculators?", options: ["input() returns text", "float() prints headings", "Python requires every variable to be float", "It makes variable names shorter"], correctOptionIndex: 0, note: "input() returns a string.", explanation: "Arithmetic needs compatible numeric values, so decimal-capable measurements are converted before calculation." },
      { title: "Question 5", question: "What is the first step in the problem-solving framework?", options: ["Understand the problem", "Write code", "Run Python", "Choose an operator"], correctOptionIndex: 0, note: "Begin with the real need.", explanation: "A clear understanding prevents a technically correct program from solving the wrong problem." },
    ],
    assignment: { title: "Build a Farm Resource Calculator", brief: "Create one complete console program that accepts farm area and three per-acre rates, then calculates and displays the total resources required.", deliverables: ["Land-area input", "Water-per-acre input", "Fertilizer-per-acre input", "Seed-rate input", "Appropriate numeric conversion", "Total water calculation with units", "Total fertilizer calculation with units", "Total seed calculation with units", "At least one manually verified test case"] },
    summarySection: { title: "You can now translate a requirement into a complete program", body: "You used a reusable framework to understand problems, identify inputs and outputs, choose formulas, build expressions, run code, and verify results across general and Agritech calculations.", items: ["Problem decomposition", "Inputs and outputs", "Formula building", "Expressions", "Complete programs", "Testing", "Verification", "Agritech calculations"] },
    keyTakeaways: ["Programming is problem solving, not syntax memorization", "Every solution begins with understanding the real problem", "Identify inputs, outputs, units, and formulas before writing code", "Expressions combine variables and operators to produce useful results", "Intermediate values can make calculations easier to read and verify", "Realistic practice builds confidence for conditions and loops"],
    whatsNext: { title: "Lesson 1.8 · Mini Project: Smart Farm Information System", body: "Next, combine every Module 1 skill in one complete console application before beginning programming logic." },
    developmentPack: problemSolvingDevelopmentPack,
  },
  {
    id: "module-1-lesson-8",
    moduleId: "module-1",
    number: "1.8",
    title: "Mini Project: Smart Farm Information System",
    summary: "Integrate every Module 1 concept into a complete, tested Python application that collects farm information, calculates resource requirements, and generates a professional report.",
    durationMinutes: 120,
    level: "Beginner",
    introduction: { title: "Build your first complete Python application", body: "This capstone introduces no new syntax. It combines programs, variables, data types, user input, conversion, operators, expressions, and problem solving in one meaningful Agritech project." },
    objectives: [
      "Build a complete Python application",
      "Accept and organize user input",
      "Store information using meaningful variables",
      "Apply appropriate foundational data types",
      "Convert numeric input safely for calculations",
      "Calculate farm-resource requirements",
      "Display a readable formatted report",
      "Structure a program in logical sections",
      "Test expected results with sample datasets",
      "Debug simple integration errors",
      "Think like a software developer",
    ],
    whyThisMatters: { title: "Confidence comes from integrating concepts into a useful product", body: "A complete project reveals how small Python ideas work together. Learners must interpret requirements, choose representations, write formulas, organize code, and verify that the application serves its user." },
    industryMotivation: { title: "A prototype makes an idea testable", body: "Agritech teams often begin with small tools that prove an information flow: collect farm records, calculate operational values, and communicate them clearly. Testing the prototype exposes requirements before a production system adds databases, authentication, dashboards, or analytics.", signal: "This console application is intentionally small, but its inputs → processing → outputs architecture is shared by much larger software systems." },
    concept: { title: "One application, every Module 1 skill", body: "The Smart Farm Information System gathers text and measurements, converts numeric responses, stores values under readable names, evaluates two resource formulas, and generates one labelled report.", items: ["Requirements", "Inputs", "Variables", "Data types", "Conversion", "Operators", "Expressions", "Outputs", "Testing"] },
    workflow: smartFarmProjectDevelopmentPack.story.workflow,
    agritechExample: { title: "A practical farm-resource report", body: "The farmer supplies identity, farm, weather, and per-acre resource values. The program calculates total water and fertilizer, then presents every value with its correct context and unit." },
    playground: { title: "Build and test the Smart Farm Information System", description: "Edit the complete program, modify the synchronized farmer inputs, load predefined test datasets, run real Python, inspect the console report, and trace each executed line.", starterCode: smartFarmProjectDevelopmentPack.finalProgram, expectedOutcome: "The reference Rice farm should report 15000.0 litres of water and 250.0 kg of fertilizer alongside the complete farm profile." },
    practice: [],
    quiz: [
      { title: "Question 1", question: "Which data type is appropriate for land area when decimal acres are possible?", options: ["float", "bool", "NoneType", "Only str"], correctOptionIndex: 0, note: "float supports decimal measurements.", explanation: "A farm may have an area such as 2.5 acres, so the input is converted to float." },
      { title: "Question 2", question: "Why does the project use float(input(...)) for resource rates?", options: ["input() returns text and calculations need numbers", "float() creates headings", "Every Python value must be decimal", "It prevents output"], correctOptionIndex: 0, note: "Console input starts as text.", explanation: "The rate must be numeric before Python can multiply it by land area." },
      { title: "Question 3", question: "Which expression calculates total water required?", options: ["area * water_per_acre", "area + temperature", "water_per_acre == area", "print(area)"], correctOptionIndex: 0, note: "Multiply area by the per-acre rate.", explanation: "A rate per acre becomes a total when multiplied by the number of acres." },
      { title: "Question 4", question: "Why should test datasets include expected outputs?", options: ["To verify that calculations produce known results", "To rename variables", "To avoid running code", "To introduce loops"], correctOptionIndex: 0, note: "Known outputs make verification objective.", explanation: "A program passes a test when its actual result matches the independently calculated expectation." },
      { title: "Question 5", question: "Which variables store calculated values in this project?", options: ["total_water and total_fertilizer", "farmer and village", "temperature and rainfall", "crop and area"], correctOptionIndex: 0, note: "The total variables store formula results.", explanation: "Their values are derived from area and the two per-acre rates." },
    ],
    assignment: { title: "Enhance the Smart Farm Information System", brief: "Extend the Module 1 capstone using only concepts already learned. Preserve the requirements-first structure and add a manually verified test case.", deliverables: ["Farmer ID stored as text", "Mobile number stored as text", "Seed rate per acre", "Calculated total seed requirement", "Labour cost per acre", "Calculated total labour cost", "A simple total farm cost formula", "An improved report with labels and units", "One documented input dataset", "Expected and actual calculated outputs"] },
    summarySection: { title: "You built and tested your first complete Python application", body: "The project combined every Module 1 foundation into one requirements-driven solution: input, variables, data types, conversion, operators, expressions, calculations, structured output, debugging, and testing.", items: ["Variables", "Data types", "User input", "Type conversion", "Operators", "Expressions", "Problem solving", "Report generation", "Testing"] },
    keyTakeaways: ["Real applications combine multiple concepts", "Planning inputs, processing, and outputs is as important as coding", "Clear variable names make program intent visible", "Measurements and calculated results need explicit units", "Testing with known data verifies correctness", "Complete projects reinforce fundamentals more effectively than isolated syntax exercises"],
    whatsNext: { title: "Module 2 · Decision Making & Control Flow", body: "Next, programs will respond differently and repeat work using if, if-else, nested conditions, elif, match-case, for, while, break, continue, and pass." },
    developmentPack: smartFarmProjectDevelopmentPack,
  },
];

export const moduleOneLessonSummaries = [
  { id: "module-1-lesson-1", moduleId: "module-1", order: 1, title: "1.1 Writing Your First Python Program", estimatedMinutes: 40, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-1-lesson-2", moduleId: "module-1", order: 2, title: "1.2 Variables: Storing Information in Python", estimatedMinutes: 60, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-1-lesson-3", moduleId: "module-1", order: 3, title: "1.3 Data Types in Python", estimatedMinutes: 60, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-1-lesson-4", moduleId: "module-1", order: 4, title: "1.4 User Input in Python", estimatedMinutes: 60, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-1-lesson-5", moduleId: "module-1", order: 5, title: "1.5 Type Conversion in Python", estimatedMinutes: 60, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-1-lesson-6", moduleId: "module-1", order: 6, title: "1.6 Operators in Python", estimatedMinutes: 90, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-1-lesson-7", moduleId: "module-1", order: 7, title: "1.7 Expressions & Problem Solving", estimatedMinutes: 120, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-1-lesson-8", moduleId: "module-1", order: 8, title: "1.8 Mini Project: Smart Farm Information System", estimatedMinutes: 120, status: "in-progress" as const, isPlaceholder: false },
];
