import { whyFunctionsDevelopmentPack } from "@/content/development-packs/lesson-3-1";
import { functionDefinitionDevelopmentPack } from "@/content/development-packs/lesson-3-2";
import { functionParametersDevelopmentPack } from "@/content/development-packs/lesson-3-3";
import type { LessonDocument } from "@/types/content";

export const moduleThreeLessons: LessonDocument[] = [
  {
    id: "module-3-lesson-1",
    moduleId: "module-3",
    number: "3.1",
    title: "Why Functions?",
    summary: "Feel the cost of repeated code, discover reusable responsibilities, and build a conceptual mental model of function calls before learning any function-creation syntax.",
    durationMinutes: 120,
    level: "Beginner+",
    introduction: {
      title: "Start with the maintenance problem, not new syntax",
      body: "The Module 2 Smart Farm Console works, but important logic is copied across several features. This lesson investigates that design problem and introduces functions as reusable, focused tools.",
    },
    objectives: [
      "Understand why functions are needed",
      "Identify repeated code and duplicated responsibilities",
      "Explain code reusability in plain language",
      "Recognize modular programming",
      "Think of functions as reusable tools",
      "Follow a function call and the return of control conceptually",
      "Identify Smart Farm tasks that should become reusable",
      "Prepare for creating functions in the next lesson",
    ],
    whyThisMatters: {
      title: "Repeated logic makes working software expensive to change",
      body: "A copied irrigation rule may work today, but every later improvement must be applied consistently in every location. Functions help one focused responsibility serve many features.",
    },
    industryMotivation: {
      title: "Modular design is how teams keep growing software understandable",
      body: "Production applications separate domain responsibilities so developers can improve, test, and discuss one capability without searching an entire codebase for copied logic.",
      signal: "This lesson is intentionally conceptual. Function-creation syntax, parameters, arguments, and produced values begin in later lessons.",
    },
    concept: {
      title: "A function gives one specific task a reusable name and boundary",
      body: "The main program can request that task whenever it is needed. The focused work completes, control returns, and the program continues.",
      items: ["Focused responsibility", "Reusable behaviour", "Clear name", "Modular design", "Function call concept", "Return of control"],
    },
    workflow: {
      title: "A conceptual function call",
      description: "Responsibility moves from the main program to a focused task and then back.",
      steps: whyFunctionsDevelopmentPack.functionFlow.steps,
    },
    agritechExample: {
      title: "One farm-status check can support several experiences",
      body: "A dashboard, report, and mobile experience can all request the same dependable farm-status capability instead of maintaining separate copies of the soil, temperature, and rainfall checks.",
    },
    playground: {
      title: "Conceptual module simulator",
      description: "Choose a Smart Farm responsibility and watch the function-call mental model without writing function syntax.",
      starterCode: "Main Program → checkIrrigation() → Task → Main Program",
      expectedOutcome: "The selected module performs one focused responsibility and then gives control back to the main program.",
    },
    practice: [
      {
        level: "Easy",
        title: "Spot repeated work",
        prompt: "Review a dashboard, report, and mobile experience that each contain the same irrigation rule. Identify the repeated responsibility.",
        guidance: "Describe the task in one short verb-and-object phrase.",
        activities: ["Find the repeated soil check", "Find the repeated irrigation message", "Propose one clear task name"],
      },
      {
        level: "Medium",
        title: "Divide the Smart Farm into modules",
        prompt: "Group irrigation, temperature, crop recommendation, sensor inspection, and reporting into focused reusable responsibilities.",
        guidance: "Each group should have one reason to change and one clear purpose.",
        activities: ["Name each responsibility", "Describe its purpose", "Identify the features that need it"],
      },
      {
        level: "Challenge",
        title: "Explain the maintenance impact",
        prompt: "Compare changing one shared irrigation responsibility with changing eighteen copied versions. Explain the likely effect on bugs, testing, and teamwork.",
        guidance: "Focus on consistency and source of truth rather than only counting lines.",
      },
    ],
    quiz: [
      { title: "Question 1", question: "Why do programmers use functions?", options: ["To organize and reuse focused tasks", "To make every file longer", "Only to display text", "To avoid planning"], correctOptionIndex: 0, note: "Functions create reusable responsibilities.", explanation: "A focused block can support every feature that needs the same task." },
      { title: "Question 2", question: "What problem do functions help solve?", options: ["Repeated logic and unclear organization", "The need for more copied code", "Screen brightness", "Keyboard layout"], correctOptionIndex: 0, note: "Duplication increases maintenance risk.", explanation: "One authoritative responsibility is easier to change consistently." },
      { title: "Question 3", question: "Can one function be used many times?", options: ["Yes", "No", "Only once per project", "Only in data science"], correctOptionIndex: 0, note: "Reusability is a central benefit.", explanation: "Several parts of a program can request the same focused task." },
      { title: "Question 4", question: "Does modular design improve maintainability?", options: ["Yes", "No", "Only for very short scripts", "Only when no testing exists"], correctOptionIndex: 0, note: "Clear boundaries make change safer.", explanation: "Developers can locate, test, and improve a responsibility in one place." },
      { title: "Question 5", question: "What happens conceptually after a function finishes its task?", options: ["Control returns and the main program continues", "The computer always shuts down", "All variables disappear immediately", "Every task repeats forever"], correctOptionIndex: 0, note: "Follow the call-and-return mental model.", explanation: "The focused task completes, then execution continues in the calling program." },
    ],
    assignment: {
      title: "Refactor the Module 2 Capstone on paper",
      brief: "Review the Smart Farm Automation Console and identify reusable responsibilities. No coding or function syntax is required.",
      deliverables: [
        "Highlight at least five repeated or specialized code blocks",
        "Give each proposed responsibility a clear conceptual name",
        "Explain the single task each responsibility performs",
        "List every application feature that would use it",
        "Explain how centralizing it would reduce maintenance risk",
        "Draw one call-and-return flow from the main program",
      ],
    },
    summarySection: {
      title: "You now understand the problem functions are designed to solve",
      body: "You found duplication, compared copied and reusable designs, separated a Smart Farm into modules, followed the function-call mental model, and selected responsibilities that deserve a reusable boundary.",
      items: ["Repeated code", "Reusability", "Focused responsibilities", "Modular programming", "Maintainability", "Function-call concept", "Return of control"],
    },
    keyTakeaways: [
      "Functions solve the problem of repeated code",
      "A function should perform one specific task",
      "One reusable responsibility reduces inconsistent updates",
      "Modular software is easier to understand, test, and extend",
      "The main program can request a focused task and continue after it finishes",
      "Understanding why functions exist matters more than memorizing syntax",
    ],
    whatsNext: {
      title: "Lesson 3.2 · Creating Functions",
      body: "Next, turn these conceptual responsibilities into real reusable Python functions using the def keyword, then call them from different parts of the Smart Farm application.",
    },
    developmentPack: whyFunctionsDevelopmentPack,
  },
  {
    id: "module-3-lesson-2",
    moduleId: "module-3",
    number: "3.2",
    title: "Creating Functions with def",
    summary: "Turn repeated Smart Farm logic into the first real reusable Python function, then trace the difference between defining, calling, and reusing it.",
    durationMinutes: 120,
    level: "Beginner+",
    introduction: { title: "Solve duplication with a real reusable Python tool", body: "Lesson 3.1 established why functions matter. Now you will create a parameter-free function, call it, reuse it, and watch control move between the main program and function body." },
    objectives: ["Create functions using the def keyword", "Identify every part of a function definition", "Explain why defining a function does not execute its body", "Call functions correctly", "Call one function multiple times", "Differentiate function definitions from function calls", "Build reusable Smart Farm modules", "Trace execution through function calls and back to the main program"],
    whyThisMatters: { title: "A reusable design becomes valuable when it can actually execute", body: "Clear function boundaries let one trusted implementation support dashboards, reports, and mobile experiences. Calling that function activates the behaviour only when the application needs it." },
    industryMotivation: { title: "Named modules give teams practical units for development and testing", body: "Production software separates irrigation, weather, sensor, reporting, and notification responsibilities so they can be owned, tested, reused, and changed independently.", signal: "This lesson uses parameter-free functions that print their results. Parameters, arguments, return values, defaults, lambda functions, and recursion remain outside the scope." },
    concept: { title: "Definition creates the reusable block; a call executes it", body: "The def statement records a name and an indented body. Parentheses after the name create a function call that enters the body and returns control when the task is complete.", items: ["def keyword", "Function name", "Empty parentheses", "Colon", "Indented body", "Function definition", "Function call", "Return of control", "Repeated calls"] },
    workflow: functionDefinitionDevelopmentPack.story.workflow,
    agritechExample: { title: "One farm-status function can serve every product surface", body: "check_farm_status() contains the soil, temperature, and rainfall messages once. The dashboard, report, and mobile experience can each call that same definition." },
    playground: { title: "Create and trace a reusable farm-status function", description: "Edit the Python, run it in the browser, and step through the real execution trace, current frame, call stack, variables, and output.", starterCode: "def check_farm_status():\n    print(\"Checking Soil Moisture...\")\n    print(\"Checking Temperature...\")\n    print(\"Checking Rainfall...\")\n\ncheck_farm_status()", expectedOutcome: "Python creates the function without output, then the call executes all three indented statements in order." },
    practice: [
      { level: "Easy", title: "Create show_name()", prompt: "Define show_name() so it displays your name, then call it once.", guidance: "Use def, a meaningful name, empty parentheses, a colon, an indented print statement, and a separate call." },
      { level: "Medium", title: "Create a three-message welcome()", prompt: "Define welcome() with three agricultural welcome messages, then call it twice.", guidance: "Write the three print statements once inside the body and reuse the function through calls." },
      { level: "Challenge", title: "Create daily_report()", prompt: "Define daily_report() that displays soil moisture, temperature, and rainfall labels, then call it from two simulated report sections.", guidance: "Keep the function parameter-free and use only print statements in this lesson." },
    ],
    quiz: [
      { title: "Question 1", question: "Which keyword creates a Python function?", options: ["def", "function", "make", "call"], correctOptionIndex: 0, note: "def begins the definition.", explanation: "Python uses def followed by the function name and parentheses." },
      { title: "Question 2", question: "Does defining a function execute its body?", options: ["No", "Yes", "Only when it prints", "Only on the first line"], correctOptionIndex: 0, note: "Definition and execution are separate.", explanation: "The body waits until Python reaches a function call." },
      { title: "Question 3", question: "Which code calls greet?", options: ["greet()", "def greet():", "greet", "call greet"], correctOptionIndex: 0, note: "A call uses the name followed by parentheses.", explanation: "greet without parentheses refers to the function but does not execute it." },
      { title: "Question 4", question: "Why do functions reduce repeated code?", options: ["The body is defined once and can be called many times", "They remove all indentation", "They never execute", "They require copied bodies"], correctOptionIndex: 0, note: "Reuse the call, not the body.", explanation: "Every caller relies on the same function definition." },
      { title: "Question 5", question: "Can one function be called multiple times?", options: ["Yes", "No", "Only with parameters", "Only from a loop"], correctOptionIndex: 0, note: "Repeated calls are valid.", explanation: "Each call executes the same body again in that call's position." },
    ],
    assignment: { title: "Refactor the Module 2 Capstone into placeholder functions", brief: "Create separate parameter-free functions for the major Smart Farm responsibilities. Each function should print a placeholder message and be called once from the main program.", deliverables: ["irrigation()", "temperature_analysis()", "crop_recommendation()", "sensor_inspection()", "report_generation()", "One correctly indented placeholder print in each function", "One call to each function", "A short note explaining how the structure reduces duplication", "No parameters or return values"] },
    summarySection: { title: "You created and reused your first functions", body: "You used def, inspected function anatomy, separated definition from invocation, called one function repeatedly, traced the call stack, built a Smart Farm function library, and repaired common syntax and ordering mistakes.", items: ["def keyword", "Function anatomy", "Definition", "Call", "Indented body", "Repeated calls", "Execution flow", "Call stack preview", "Smart Farm modules"] },
    keyTakeaways: ["def defines a reusable block of code", "Defining a function does not execute its body", "A function executes when it is called with parentheses", "One definition can support many calls", "Python must execute a definition before it reaches the call", "Focused functions improve readability, testing, and maintenance"],
    whatsNext: { title: "Lesson 3.3 · Function Parameters", body: "Next, make functions flexible by supplying different inputs for different crops, fields, and sensor readings while preserving one reusable function body." },
    developmentPack: functionDefinitionDevelopmentPack,
  },
  {
    id: "module-3-lesson-3",
    moduleId: "module-3",
    number: "3.3",
    title: "Function Parameters",
    summary: "Transform fixed functions into flexible tools by mapping different positional arguments into parameters and tracing how data flows through each call.",
    durationMinutes: 120,
    level: "Beginner+",
    introduction: { title: "Make one function useful for every farm", body: "A parameter-free function repeats one fixed task. Real Smart Farm software must use different sensor IDs, locations, crops, and readings without creating a new function for each value." },
    objectives: ["Understand why parameters are needed", "Differentiate parameters from hardcoded values", "Create functions that accept inputs", "Distinguish parameters from supplied argument values", "Call one function with different values", "Map multiple positional arguments in order", "Trace data as it enters a function", "Build reusable Smart Farm functions using parameters"],
    whyThisMatters: { title: "Reusable software must adapt to current data", body: "A function that always reports 25% moisture is not useful across many fields. Parameters keep the algorithm stable while allowing every call to supply current information." },
    industryMotivation: { title: "Parameterized functions are the interface between reusable logic and changing data", body: "Production systems reuse the same validation, analysis, and reporting functions for thousands of records by supplying the relevant values at each call.", signal: "This lesson uses positional arguments only. Return values, keyword arguments, default arguments, lambda functions, and recursion remain outside the scope." },
    concept: { title: "A parameter receives one matching positional argument", body: "Parameters are names in a function definition. Arguments are the values supplied in a function call. Python maps them by position and makes those values available inside the function body.", items: ["Function parameter", "Positional argument", "Parameter assignment", "Argument order", "One parameter", "Multiple parameters", "Local function data", "Reusable calls"] },
    workflow: functionParametersDevelopmentPack.story.workflow,
    agritechExample: { title: "One inspection function can process every sensor", body: "inspect_sensor(sensor_id) receives a new ID at each call, so sensors 101, 205, 309, and 415 share one clear implementation." },
    playground: { title: "Create and trace parameterized sensor inspections", description: "Edit the Python, rename parameters, change positional arguments, add calls, and inspect real parameter values, function frames, call stacks, executed lines, and output.", starterCode: "def inspect_sensor(sensor_id):\n    print(\"Checking Sensor\", sensor_id)\n\ninspect_sensor(101)\ninspect_sensor(205)\ninspect_sensor(309)", expectedOutcome: "Each call maps its sensor ID into sensor_id and produces a different inspection message from one function definition." },
    practice: [{ level: "Easy", title: "Create show_name(name)", prompt: "Define show_name with one parameter and call it with three different names.", guidance: "Keep the parameter name in the definition and supply one positional argument in each call." }, { level: "Medium", title: "Create show_crop(crop)", prompt: "Display Rice, Wheat, and Cotton through three calls to the same function.", guidance: "Do not hardcode a crop inside the body; print the crop parameter." }, { level: "Challenge", title: "Create farm_report(field, moisture)", prompt: "Accept a field name and moisture reading, then display both values for three fields.", guidance: "Map the field argument first and moisture argument second in every call." }],
    quiz: [{ title: "Question 1", question: "What is a parameter?", options: ["A variable in a function definition that receives call data", "Only a printed result", "A function name", "A comment"], correctOptionIndex: 0, note: "Parameters belong to the definition.", explanation: "Each parameter receives the matching argument supplied by the caller." }, { title: "Question 2", question: "Why are parameters useful?", options: ["They let one function process different inputs", "They force hardcoded values", "They prevent function calls", "They replace indentation"], correctOptionIndex: 0, note: "Parameters create flexibility.", explanation: "The reusable body stays the same while call data changes." }, { title: "Question 3", question: "Can one function receive different values across calls?", options: ["Yes", "No", "Only strings", "Only one time"], correctOptionIndex: 0, note: "Every call can supply new arguments.", explanation: "The parameter receives the value from the current call." }, { title: "Question 4", question: "Where is a parameter available in this lesson's mental model?", options: ["Inside its function call frame", "In every unrelated function automatically", "Only before the definition", "Nowhere"], correctOptionIndex: 0, note: "The call frame holds the current parameter values.", explanation: "Later lessons explore local and global scope in greater detail." }, { title: "Question 5", question: "How many parameters may a Python function define?", options: ["More than one", "Exactly one", "None ever", "Only two"], correctOptionIndex: 0, note: "Functions can accept several inputs.", explanation: "This lesson explores one, two, and three positional parameters." }],
    assignment: { title: "Parameterize the Module 2 Capstone modules", brief: "Update the placeholder functions from Lesson 3.2 so each accepts and displays its relevant input. Do not produce return values yet.", deliverables: ["irrigation(moisture)", "weather(temperature)", "crop_recommendation(crop_name)", "inspect_sensor(sensor_id)", "Display every received value", "At least two calls per function", "Correct positional argument counts", "No keyword or default arguments", "No return statements"] },
    summarySection: { title: "Your functions can now adapt to changing farm data", body: "You replaced hardcoded values with parameters, distinguished definition names from call values, mapped one to three positional arguments, traced parameter values in real function frames, and reused one inspection function for several sensors.", items: ["Parameters", "Positional arguments", "Hardcoded vs dynamic values", "Parameter mapping", "Argument order", "Multiple calls", "Multiple parameters", "Parameter inspection"] },
    keyTakeaways: ["Parameters make functions flexible", "A parameter is a variable named in the function header", "An argument is a value supplied at a function call", "Positional arguments map to parameters in order", "One definition can process many different inputs", "Parameterized functions reduce duplication and improve scalability"],
    whatsNext: { title: "Lesson 3.4 · Return Values", body: "Next, move beyond functions that only perform actions. Use return to produce a result and send it back to the calling program for storage, comparison, and further calculation." },
    developmentPack: functionParametersDevelopmentPack,
  },
];

export const moduleThreeLessonSummaries = [
  { id: "module-3-lesson-1", moduleId: "module-3", order: 1, title: "3.1 Why Functions?", estimatedMinutes: 120, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-3-lesson-2", moduleId: "module-3", order: 2, title: "3.2 Creating Functions", estimatedMinutes: 120, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-3-lesson-3", moduleId: "module-3", order: 3, title: "3.3 Function Parameters", estimatedMinutes: 120, status: "in-progress" as const, isPlaceholder: false },
  { id: "module-3-lesson-4", moduleId: "module-3", order: 4, title: "3.4 Return Values", estimatedMinutes: 100, status: "not-started" as const, isPlaceholder: true },
  { id: "module-3-lesson-5", moduleId: "module-3", order: 5, title: "3.5 Positional vs Keyword Arguments", estimatedMinutes: 90, status: "not-started" as const, isPlaceholder: true },
  { id: "module-3-lesson-6", moduleId: "module-3", order: 6, title: "3.6 Default Arguments", estimatedMinutes: 90, status: "not-started" as const, isPlaceholder: true },
  { id: "module-3-lesson-7", moduleId: "module-3", order: 7, title: "3.7 Variable Scope (Local vs Global)", estimatedMinutes: 110, status: "not-started" as const, isPlaceholder: true },
  { id: "module-3-lesson-8", moduleId: "module-3", order: 8, title: "3.8 Lambda Functions", estimatedMinutes: 90, status: "not-started" as const, isPlaceholder: true },
  { id: "module-3-lesson-9", moduleId: "module-3", order: 9, title: "3.9 Recursion (Introduction)", estimatedMinutes: 110, status: "not-started" as const, isPlaceholder: true },
  { id: "module-3-lesson-10", moduleId: "module-3", order: 10, title: "3.10 Capstone · Smart Farm Automation v2", estimatedMinutes: 180, status: "not-started" as const, isPlaceholder: true },
];
