import { CourseBreadcrumb } from "@/components/course/CourseBreadcrumb";
import { PreviousNextNavigation } from "@/components/course/PreviousNextNavigation";
import { ProjectProgressChecklist } from "@/components/learning/CapstoneProjectLearningBlocks";
import { ApplicationFlowVisualizer, ApplicationModules, CapstoneChecklist, CapstoneOverviewCard, CapstoneProgramCard, CapstoneStoryCard, ConceptMappingCard, ExtensionChallenges, InteractiveConsoleSimulator, ReflectionCard } from "@/components/learning/ControlFlowCapstoneLearningBlocks";
import { LessonHero } from "@/components/learning/LessonHero";
import { IndustryInsightCard, KeyTakeawaysCard, LearningObjectivesCard, SummaryCard, WhatsNextCard } from "@/components/learning/LearningBlocks";
import { DebugChallengeCollection } from "@/components/learning/ProblemSolvingLearningBlocks";
import type { CourseLesson, CourseModule } from "@/types/course";
import type { LessonDocument } from "@/types/content";

const outline = [["objectives", "Objectives"], ["capstone-story", "Project story"], ["project-overview", "Overview"], ["application-flow", "Architecture"], ["concept-mapping", "Concept mapping"], ["application-modules", "Application modules"], ["project-progress", "Implementation guide"], ["complete-program", "Complete application"], ["playground", "Interactive console"], ["testing-panel", "Testing"], ["debug-challenge", "Debugging"], ["extension-challenges", "Extensions"], ["reflection", "Reflection"], ["capstone-checklist", "Checklist"], ["summary", "Summary"], ["whats-next", "Module 3"]] as const;

export function ControlFlowCapstoneLessonRenderer({ lesson, courseLesson, module, previous, next }: { lesson: LessonDocument; courseLesson: CourseLesson; module: CourseModule; previous: CourseLesson | null; next: CourseLesson | null }) {
  const pack = lesson.developmentPack;
  if (!pack || pack.kind !== "control-flow-capstone") return null;
  return <article className="published-lesson control-flow-capstone-development-pack"><CourseBreadcrumb module={module} lesson={courseLesson} /><LessonHero eyebrow={`Module ${module.index} · Capstone`} title={lesson.title} summary={lesson.summary} icon={module.icon} level={lesson.level} durationMinutes={lesson.durationMinutes} prerequisite={pack.prerequisite} /><div className="published-lesson-layout control-flow-capstone-layout"><div className="published-lesson-flow"><LearningObjectivesCard id="objectives" objectives={lesson.objectives} /><CapstoneStoryCard content={pack.story} /><CapstoneOverviewCard content={pack.overview} /><ApplicationFlowVisualizer steps={pack.architecture.steps} title={pack.architecture.title} body={pack.architecture.body} /><ConceptMappingCard content={pack.conceptMapping} /><ApplicationModules modules={pack.modules} futureFeature={pack.futureFeature} /><ProjectProgressChecklist steps={pack.buildSteps} /><CapstoneProgramCard code={pack.finalProgram} /><IndustryInsightCard id="industry-insight" section={lesson.industryMotivation} /><InteractiveConsoleSimulator content={lesson.playground} modules={pack.modules} tests={pack.tests} /><DebugChallengeCollection challenges={pack.debugChallenges} /><ExtensionChallenges extensions={pack.extensions} /><ReflectionCard content={pack.reflection} /><CapstoneChecklist content={pack.checklist} /><SummaryCard id="summary" section={lesson.summarySection} /><KeyTakeawaysCard id="key-takeaways" items={lesson.keyTakeaways} /><WhatsNextCard id="whats-next" section={lesson.whatsNext} /></div><aside className="lesson-outline published-lesson-outline" aria-label="On this page"><p>On this page</p>{outline.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside></div><PreviousNextNavigation previous={previous} next={next} /></article>;
}
