import { CourseBreadcrumb } from "@/components/course/CourseBreadcrumb";
import { PreviousNextNavigation } from "@/components/course/PreviousNextNavigation";
import { CommonMistakesCard } from "@/components/learning/FirstProgramLessonBlocks";
import { AgritechLoopExamples, ForLoopDefinitionCard, ForLoopPlayground, ForLoopStoryCard, ForSyntaxBreakdown, LoopComparisonCard, NestedLoopPreview, RangeExplorer, SequenceExplorer, WhyLoopsCard } from "@/components/learning/ForLoopLearningBlocks";
import { LessonHero } from "@/components/learning/LessonHero";
import { AssignmentCard, IndustryInsightCard, KeyTakeawaysCard, LearningObjectivesCard, PracticeCard, QuizCard, SummaryCard, WhatsNextCard } from "@/components/learning/LearningBlocks";
import { DebugChallengeCollection } from "@/components/learning/ProblemSolvingLearningBlocks";
import { MiniProjectCard } from "@/components/learning/UserInputLearningBlocks";
import { EngineerScenario } from "@/components/learning/WhyPythonLessonBlocks";
import type { CourseLesson, CourseModule } from "@/types/course";
import type { LessonDocument } from "@/types/content";

const forOutline = [["objectives", "Objectives"], ["for-story", "Story continuation"], ["why-loops", "Why loops?"], ["for-definition", "What is a for loop?"], ["for-syntax", "Syntax"], ["range-explorer", "Range explorer"], ["agritech-loop-examples", "Agritech examples"], ["sequence-explorer", "Sequence explorer"], ["nested-loop-preview", "Nested preview"], ["playground", "Execution lab"], ["common-mistakes", "Common mistakes"], ["debug-challenge", "Debug challenge"], ["engineer-scenario", "Engineer thinking"], ["practice", "Practice"], ["mini-project", "Mini project"], ["quiz", "Quiz"], ["assignment", "Assignment"], ["compare-choose", "Compare & choose"], ["summary", "Summary"], ["whats-next", "What's next"]] as const;

export function ForLoopLessonRenderer({ lesson, courseLesson, module, previous, next }: { lesson: LessonDocument; courseLesson: CourseLesson; module: CourseModule; previous: CourseLesson | null; next: CourseLesson | null }) {
  const pack = lesson.developmentPack;
  if (!pack || pack.kind !== "for-loop") return null;
  return <article className="published-lesson for-loop-development-pack"><CourseBreadcrumb module={module} lesson={courseLesson} /><LessonHero eyebrow={`Module ${module.index} · Lesson ${lesson.number}`} title={lesson.title} summary={lesson.summary} icon={module.icon} level={lesson.level} durationMinutes={lesson.durationMinutes} prerequisite={pack.prerequisite} /><div className="published-lesson-layout for-loop-lesson-layout"><div className="published-lesson-flow"><LearningObjectivesCard id="objectives" objectives={lesson.objectives} /><ForLoopStoryCard content={pack.story} /><WhyLoopsCard content={pack.whyLoops} /><ForLoopDefinitionCard content={pack.definition} /><ForSyntaxBreakdown content={pack.syntax} /><RangeExplorer examples={pack.rangeExamples} /><AgritechLoopExamples examples={pack.agritechExamples} /><IndustryInsightCard id="industry-insight" section={lesson.industryMotivation} /><SequenceExplorer stringExample={pack.stringExample} listExample={pack.listExample} /><NestedLoopPreview content={pack.nestedPreview} /><ForLoopPlayground content={lesson.playground} fields={pack.simulatorFields} /><CommonMistakesCard title={pack.mistakesTitle} mistakes={pack.mistakes} /><DebugChallengeCollection challenges={pack.debugChallenges} /><EngineerScenario content={pack.engineerScenario} /><PracticeCard id="practice" tasks={lesson.practice} /><MiniProjectCard project={pack.miniProject} /><QuizCard id="quiz" quiz={lesson.quiz} /><AssignmentCard id="assignment" assignment={lesson.assignment} /><LoopComparisonCard content={pack.comparison} /><SummaryCard id="summary" section={lesson.summarySection} /><KeyTakeawaysCard id="key-takeaways" items={lesson.keyTakeaways} /><WhatsNextCard id="whats-next" section={lesson.whatsNext} /></div><aside className="lesson-outline published-lesson-outline" aria-label="On this page"><p>On this page</p>{forOutline.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside></div><PreviousNextNavigation previous={previous} next={next} /></article>;
}
