import { useMemo, useState } from "react";
import { Button, CodeSnippet, ProgressBar, Tag, Tile, Toggle } from "@carbon/react";
import { ArrowRight, CheckmarkOutline, Clean, FunctionMath, Task, WarningAlt } from "@carbon/icons-react";
import { FunctionDebugChallenges } from "@/components/learning/FunctionDefinitionLearningBlocks";
import { FunctionEvolutionPanel } from "@/components/learning/FunctionParameterLearningBlocks";
import { FunctionLifecyclePanel } from "@/components/learning/ReturnValueLearningBlocks";
import { CodeTracePanel } from "@/components/learning/CodeTracePanel";
import type { PlaygroundExecution } from "@/components/learning/usePythonRunner";
import type { FunctionDesignLessonDevelopmentPack } from "@/types/content";

export { FunctionDebugChallenges, FunctionEvolutionPanel, FunctionLifecyclePanel };
type QualityMetric={label:string;score:number;suggestion:string};
const genericNames=new Set(["fun","test","abc","data","x","f","function"]);
function analyzeFunction(code:string):QualityMetric[]{const name=code.match(/def\s+([A-Za-z_]\w*)\s*\(/)?.[1]??"";const params=code.match(/def\s+\w+\s*\(([^)]*)\)/)?.[1].split(",").map((item)=>item.trim()).filter(Boolean)??[];const lines=code.split("\n").filter((line)=>line.trim()).length;const globals=/^\w+\s*=.*\n[\s\S]*def\s+/m.test(code);const returns=/\breturn\b/.test(code);const docstring=/def[^\n]*:\s*\n\s*(?:"""|''')/.test(code);const responsibilities=[/sensor|soil/i,/water|irrigat/i,/alert|sms|notify/i,/report|pdf/i,/database|save/i].filter((pattern)=>pattern.test(code)).length;const nameScore=!name?0:genericNames.has(name)?20:name.includes("_")&&name.length>10?100:name.length>6?70:40;return [{label:"Name clarity",score:nameScore,suggestion:nameScore>=80?"The name communicates a specific responsibility.":"Use a descriptive verb-and-object name."},{label:"Parameter quality",score:params.length>0&&!globals?100:params.length>0?65:globals?20:60,suggestion:globals?"Replace hidden global inputs with explicit parameters.":params.length?"Dependencies are visible at the function boundary.":"Add parameters when the function depends on changing data."},{label:"Return contract",score:returns?100:35,suggestion:returns?"The function produces reusable data.":"Return calculated data unless display is the responsibility."},{label:"Focused size",score:lines<=12?100:lines<=20?70:35,suggestion:lines<=12?"The body is small enough to scan quickly.":"Look for cohesive responsibilities that can be extracted."},{label:"Single responsibility",score:responsibilities<=1?100:responsibilities===2?65:25,suggestion:responsibilities<=1?"One clear domain responsibility is visible.":`Detected ${responsibilities} domain concerns; consider splitting them.`},{label:"Documentation",score:docstring?100:45,suggestion:docstring?"A docstring communicates the contract.":"Add a concise docstring when purpose or units are not obvious."}];}
function stars(score:number){const filled=Math.max(1,Math.min(5,Math.round(score>5?score/20:score)));return "★".repeat(filled)+"☆".repeat(5-filled);}

export function FunctionDesignStory({ content }: { content:FunctionDesignLessonDevelopmentPack["story"] }) { return <section id="story" className="lesson-card function-design-story" aria-labelledby="design-story-title"><p className="lesson-section-label"><FunctionMath size={16}/> Story continuation</p><h2 id="design-story-title">{content.title}</h2><p>{content.body}</p><div className="design-story-grid"><CodeSnippet type="multi" feedback="Copied">{content.badCode}</CodeSnippet><div>{content.questions.map((question)=><Tile key={question}><WarningAlt size={16}/><span>{question}</span></Tile>)}</div></div><ol className="professional-code-flow">{content.workflow.map((step,index)=><li key={step.title}><span>{index+1}</span><strong>{step.title}</strong><small>{step.description}</small>{index<content.workflow.length-1&&<ArrowRight/>}</li>)}</ol></section>; }

export function CodeQualityCard({ content }: { content:FunctionDesignLessonDevelopmentPack["quality"] }) { return <section id="code-quality" className="lesson-card code-quality-card" aria-labelledby="code-quality-title"><p className="lesson-section-label"><Clean size={16}/> Why code quality matters</p><h2 id="code-quality-title">{content.title}</h2><p>{content.body}</p><div className="quality-stage-grid">{content.stages.map((step)=><Tile key={step.title}><CheckmarkOutline size={18}/><strong>{step.title}</strong><span>{step.description}</span></Tile>)}</div><div className="quality-benefits">{content.benefits.map((item)=><Tag key={item} type="green">{item}</Tag>)}</div></section>; }

export function NamingQualityMeter({ content }: { content:FunctionDesignLessonDevelopmentPack["naming"] }) { const [active,setActive]=useState(0);const example=content.examples[active];return <section id="naming" className="lesson-card naming-quality-meter" aria-labelledby="naming-meter-title"><p className="lesson-section-label"><FunctionMath size={16}/> Naming Quality Meter</p><h2 id="naming-meter-title">{content.title}</h2><p>{content.body}</p><div className="naming-choice-list">{content.examples.map((item,index)=><Button key={item.name} size="sm" kind={active===index?"primary":"ghost"} onClick={()=>setActive(index)}><code>{item.name}()</code></Button>)}</div><Tile className="naming-score" aria-live="polite"><div><code>{example.name}()</code><strong aria-label={`${example.score} out of 5 stars`}>{stars(example.score)}</strong></div><ProgressBar label="Naming quality" helperText={example.explanation} value={example.score*20} max={100}/></Tile></section>; }

export function SRPVisualizer({ content }: { content:FunctionDesignLessonDevelopmentPack["srp"] }) { const [split,setSplit]=useState(false);return <section id="single-responsibility" className="lesson-card srp-visualizer" aria-labelledby="srp-title"><div className="lesson-card-heading"><div><p className="lesson-section-label"><Clean size={16}/> Single Responsibility Principle</p><h2 id="srp-title">{content.title}</h2><p>{content.body}</p></div><Toggle id="srp-view" labelText="Design view" labelA="One huge box" labelB="Focused boxes" toggled={split} onToggle={setSplit}/></div>{split?<><div className="srp-responsibilities">{content.responsibilities.map((item)=><Tile key={item.name}><code>{item.name}</code><span>{item.purpose}</span></Tile>)}</div><CodeSnippet type="multi" feedback="Copied">{content.afterCode}</CodeSnippet></>:<div className="srp-monolith"><CodeSnippet type="multi" feedback="Copied">{content.beforeCode}</CodeSnippet><Tag type="red">{content.responsibilities.length} reasons to change</Tag></div>}</section>; }

export function FunctionSizeCard({ content }: { content:FunctionDesignLessonDevelopmentPack["size"] }) { return <section id="small-functions" className="lesson-card function-size-card" aria-labelledby="function-size-title"><p className="lesson-section-label"><Clean size={16}/> Small vs large functions</p><h2 id="function-size-title">{content.title}</h2><p>{content.body}</p><div className="function-size-visual"><Tile><strong>{content.largeLines}</strong><span>lines in one mixed function</span></Tile><ArrowRight/><Tile><strong>{content.targetFunctions}</strong><span>focused functions</span></Tile><ArrowRight/><Tile><strong>≈ {content.targetLines}</strong><span>lines per coherent idea</span></Tile></div><div className="quality-benefits">{content.benefits.map((item)=><Tag key={item} type="blue">{item}</Tag>)}</div></section>; }

export function ExplicitDataFlowCard({ parameters, returns }: { parameters:FunctionDesignLessonDevelopmentPack["parameters"];returns:FunctionDesignLessonDevelopmentPack["returns"] }) { const [mode,setMode]=useState<"parameters"|"returns">("parameters");const current=mode==="parameters"?parameters:returns;return <section id="data-flow" className="lesson-card explicit-data-flow" aria-labelledby="data-flow-title"><p className="lesson-section-label"><FunctionMath size={16}/> Parameters and return design</p><h2 id="data-flow-title">Make dependencies and results explicit</h2><div className="design-tabs"><Button size="sm" kind={mode==="parameters"?"primary":"ghost"} onClick={()=>setMode("parameters")}>Parameters vs globals</Button><Button size="sm" kind={mode==="returns"?"primary":"ghost"} onClick={()=>setMode("returns")}>Return vs print</Button></div><h3>{current.title}</h3><p>{current.body}</p><div className="before-after-design"><article><Tag type="red">Hidden or limited</Tag><CodeSnippet type="multi" feedback="Copied">{current.badCode}</CodeSnippet></article><ArrowRight/><article><Tag type="green">Explicit and reusable</Tag><CodeSnippet type="multi" feedback="Copied">{current.goodCode}</CodeSnippet></article></div>{mode==="returns"&&<div className="return-consumer-tags">{returns.consumers.map((item)=><Tag key={item} type="teal">{item}</Tag>)}</div>}</section>; }

export function DocumentationCard({ content }: { content:FunctionDesignLessonDevelopmentPack["documentation"] }) { return <section id="documentation" className="lesson-card documentation-card" aria-labelledby="documentation-title"><p className="lesson-section-label"><Clean size={16}/> Documentation & docstrings</p><h2 id="documentation-title">{content.title}</h2><p>{content.body}</p><div className="before-after-design"><article><Tag type="red">Ambiguous</Tag><CodeSnippet type="multi" feedback="Copied">{content.badCode}</CodeSnippet></article><ArrowRight/><article><Tag type="green">Documented contract</Tag><CodeSnippet type="multi" feedback="Copied">{content.goodCode}</CodeSnippet></article></div><ul>{content.rules.map((rule)=><li key={rule}><CheckmarkOutline size={16}/><span>{rule}</span></li>)}</ul></section>; }

export function FunctionQualityAnalyzer({ code }: { code:string }) { const metrics=useMemo(()=>analyzeFunction(code),[code]);const overall=Math.round(metrics.reduce((sum,item)=>sum+item.score,0)/metrics.length);return <section className="function-quality-analyzer" aria-labelledby="quality-analyzer-title"><div><Clean size={18}/><h3 id="quality-analyzer-title">Function Quality Analyzer</h3><Tag type={overall>=80?"green":overall>=55?"blue":"red"}>{overall}%</Tag></div><div>{metrics.map((metric)=><Tile key={metric.label}><div><strong>{metric.label}</strong><span>{stars(metric.score)}</span></div><ProgressBar label={metric.label} hideLabel value={metric.score} max={100}/><p>{metric.suggestion}</p></Tile>)}</div></section>; }

export function FunctionHealthReport({ content, code }: { content:FunctionDesignLessonDevelopmentPack["checklist"];code:string }) { const metrics=analyzeFunction(code);return <section id="health-report" className="lesson-card function-health-report" aria-labelledby="health-report-title"><p className="lesson-section-label"><Clean size={16}/> Function Health Report</p><h2 id="health-report-title">{content.title}</h2><p>{content.body}</p><div className="health-score-grid">{metrics.map((metric)=><Tile key={metric.label}><span>{metric.label}</span><strong>{stars(metric.score)}</strong><small>{metric.suggestion}</small></Tile>)}</div><div className="design-checklist">{content.items.map((item)=><Tile key={item}><CheckmarkOutline size={16}/><span>{item}</span></Tile>)}</div></section>; }

export function RefactoringWorkspace({ content }: { content:FunctionDesignLessonDevelopmentPack["refactoring"] }) { const [active,setActive]=useState(0);const stage=content.stages[active];return <section id="refactoring" className="lesson-card refactoring-workspace" aria-labelledby="refactoring-title"><p className="lesson-section-label"><Clean size={16}/> Refactoring Workspace</p><h2 id="refactoring-title">{content.title}</h2><p>{content.body}</p><div className="refactoring-stage-tabs">{content.stages.map((item,index)=><Button key={item.label} size="sm" kind={active===index?"primary":"ghost"} onClick={()=>setActive(index)}>{index+1}. {item.label}</Button>)}</div><div className="refactoring-workspace-grid"><CodeSnippet type="multi" feedback="Copied">{content.stages[0].code}</CodeSnippet><ArrowRight/><div><CodeSnippet type="multi" feedback="Copied">{stage.code}</CodeSnippet><ul>{stage.improvements.length?stage.improvements.map((item)=><li key={item}><CheckmarkOutline size={16}/><span>{item}</span></li>):<li><WarningAlt size={16}/><span>Start by identifying unclear names, mixed responsibilities, and hidden data.</span></li>}</ul></div></div></section>; }

export function AgritechRefactoring({ content }: { content:FunctionDesignLessonDevelopmentPack["agritechExamples"] }) { return <section id="agritech-examples" className="lesson-card agritech-refactoring" aria-labelledby="agritech-refactor-title"><p className="lesson-section-label"><Clean size={16}/> Agritech refactoring</p><h2 id="agritech-refactor-title">Separate the sensor pipeline by responsibility</h2>{content.map((item)=><div key={item.title}><h3>{item.title}</h3><p>{item.explanation}</p><div className="before-after-design"><article><Tag type="red">Before</Tag><CodeSnippet type="multi" feedback="Copied">{item.before}</CodeSnippet></article><ArrowRight/><article><Tag type="green">After</Tag><CodeSnippet type="multi" feedback="Copied">{item.after}</CodeSnippet></article></div></div>)}</section>; }

export function DesignComparison({ content }: { content:FunctionDesignLessonDevelopmentPack["comparison"] }) { return <section id="compare-choose" className="lesson-card design-comparison" aria-labelledby="design-comparison-title"><p className="lesson-section-label"><Clean size={16}/> Compare & choose</p><h2 id="design-comparison-title">{content.title}</h2><p>{content.body}</p><div tabIndex={0} role="region" aria-label="Poor and professional function design comparison"><table><thead><tr><th>Poor design</th><th>Professional design</th><th>Benefit</th></tr></thead><tbody>{content.rows.map((row)=><tr key={row.poor}><td><code>{row.poor}</code></td><td><code>{row.professional}</code></td><td>{row.reason}</td></tr>)}</tbody></table></div></section>; }

export function DesignPlaygroundSupplement({ code, execution }: { code:string;execution:PlaygroundExecution }) { return <div className="design-playground-supplement"><FunctionQualityAnalyzer code={code}/><CodeTracePanel execution={execution}/></div>; }

export function FunctionDesignMiniProject({ content }: { content:FunctionDesignLessonDevelopmentPack["miniProject"] }) { return <section id="mini-project" className="lesson-card function-design-mini-project" aria-labelledby="design-project-title"><p className="lesson-section-label"><Task size={16}/> Mini project</p><h2 id="design-project-title">{content.title}</h2><p>{content.brief}</p><CodeSnippet type="multi" feedback="Copied">{content.starterCode}</CodeSnippet><div className="design-project-checklist">{content.deliverables.map((item)=><Tile key={item}><CheckmarkOutline size={16}/><span>{item}</span></Tile>)}</div><Tile className="design-project-challenge"><strong>Challenge</strong><p>{content.challenge}</p></Tile></section>; }
