import { useState } from "react";
import { Button, CodeSnippet, NumberInput, Tag, TextInput, Tile, Toggle } from "@carbon/react";
import { ArrowRight, CheckmarkOutline, DataConnected, FunctionMath, Settings, Task, UserData } from "@carbon/icons-react";
import { CallStackPreview, FunctionDebugChallenges } from "@/components/learning/FunctionDefinitionLearningBlocks";
import { FunctionEvolutionPanel, ParameterInspector } from "@/components/learning/FunctionParameterLearningBlocks";
import { FunctionLifecyclePanel } from "@/components/learning/ReturnValueLearningBlocks";
import { CodeTracePanel } from "@/components/learning/CodeTracePanel";
import type { PlaygroundExecution } from "@/components/learning/usePythonRunner";
import type { ArgumentBindingExample, ArgumentBindingSource, FunctionArgumentsLessonDevelopmentPack } from "@/types/content";

export { FunctionDebugChallenges, FunctionEvolutionPanel, FunctionLifecyclePanel };
const tagType:Record<ArgumentBindingSource,"blue"|"purple"|"teal">={positional:"blue",keyword:"purple",default:"teal"};

function BindingRows({ example }: { example: ArgumentBindingExample }) { return <div className="argument-binding-rows">{example.bindings.map((binding,index)=><div key={`${binding.parameter}-${index}`}><code>{binding.value}</code><ArrowRight/><code>{binding.parameter}</code><Tag type={tagType[binding.source]}>{binding.source}</Tag></div>)}</div>; }

export function ArgumentStory({ content }: { content: FunctionArgumentsLessonDevelopmentPack["story"] }) { return <section id="story" className="lesson-card argument-story" aria-labelledby="argument-story-title"><p className="lesson-section-label"><FunctionMath size={16}/> Story continuation</p><h2 id="argument-story-title">{content.title}</h2><p>{content.body}</p><CodeSnippet type="multi" feedback="Copied">{content.code}</CodeSnippet><div>{content.needs.map((need)=><Tile key={need}><CheckmarkOutline size={18}/><span>{need}</span></Tile>)}</div></section>; }

export function ParameterReview({ content }: { content: FunctionArgumentsLessonDevelopmentPack["review"] }) { return <section id="parameter-review" className="lesson-card parameter-review" aria-labelledby="parameter-review-title"><p className="lesson-section-label"><UserData size={16}/> Parameter review</p><h2 id="parameter-review-title">{content.title}</h2><p>{content.body}</p><div className="parameter-review-code"><Tile><span>Definition</span><code>{content.definition}</code></Tile><ArrowRight/><Tile><span>Call</span><code>{content.call}</code></Tile></div><BindingRows example={{label:"Review",call:content.call,bindings:content.parameters.map((parameter,index)=>({parameter,value:content.arguments[index],source:"positional"})),output:""}}/></section>; }

export function ArgumentOrderComparator({ content }: { content: FunctionArgumentsLessonDevelopmentPack["positional"] }) { const [wrong,setWrong]=useState(false);const example=wrong?content.wrong:content.correct;return <section id="positional" className="lesson-card argument-order-comparator" aria-labelledby="positional-title"><div className="lesson-card-heading"><div><p className="lesson-section-label"><DataConnected size={16}/> Positional arguments</p><h2 id="positional-title">{content.title}</h2><p>{content.explanation}</p></div><Toggle id="positional-order" labelText="Argument order" labelA="Correct" labelB="Swapped" toggled={wrong} onToggle={setWrong}/></div><CodeSnippet type="multi" feedback="Copied">{content.code}</CodeSnippet><Tile className={wrong?"binding-call is-warning":"binding-call is-valid"}><Tag type={wrong?"red":"green"}>{example.label}</Tag><code>{example.call}</code><strong>{example.output}</strong></Tile><BindingRows example={example}/></section>; }

export function KeywordArgumentExplorer({ content }: { content: FunctionArgumentsLessonDevelopmentPack["keyword"] }) { const [selected,setSelected]=useState(0);const example=content.examples[selected];return <section id="keyword" className="lesson-card keyword-argument-explorer" aria-labelledby="keyword-title"><p className="lesson-section-label"><DataConnected size={16}/> Keyword arguments</p><h2 id="keyword-title">{content.title}</h2><p>{content.explanation}</p><div className="argument-example-tabs" role="tablist" aria-label="Keyword call order">{content.examples.map((item,index)=><Button role="tab" aria-selected={selected===index} key={item.label} size="sm" kind={selected===index?"primary":"tertiary"} onClick={()=>setSelected(index)}>{item.label}</Button>)}</div><Tile className="binding-call is-valid"><Tag type="purple">Matched by name</Tag><code>{example.call}</code><strong>{example.output}</strong></Tile><BindingRows example={example}/><p aria-live="polite">Keyword names preserve the same mapping even when call order changes.</p></section>; }

export function DefaultValueSimulator({ content }: { content: FunctionArgumentsLessonDevelopmentPack["defaults"] }) { const [supplied,setSupplied]=useState(false);const example=supplied?content.overridden:content.omitted;return <section id="defaults" className="lesson-card default-value-simulator" aria-labelledby="defaults-title"><div className="lesson-card-heading"><div><p className="lesson-section-label"><Settings size={16}/> Default arguments</p><h2 id="defaults-title">{content.title}</h2><p>{content.explanation}</p></div><Toggle id="default-supplied" labelText="Optional unit" labelA="Omitted" labelB="Supplied" toggled={supplied} onToggle={setSupplied}/></div><CodeSnippet type="multi" feedback="Copied">{content.code}</CodeSnippet><ol className="default-decision-flow">{content.decisionSteps.map((step,index)=><li key={step.title} className={index===3?"is-active":""}><span>{index+1}</span><strong>{step.title}</strong><small>{step.description}</small></li>)}</ol><Tile className="binding-call is-valid"><Tag type={supplied?"blue":"teal"}>{supplied?"Override":"Default used"}</Tag><code>{example.call}</code><strong>{example.output}</strong></Tile><BindingRows example={example}/></section>; }

export function CombinedArgumentsCard({ content }: { content: FunctionArgumentsLessonDevelopmentPack["combined"] }) { return <section id="combined" className="lesson-card combined-arguments-card" aria-labelledby="combined-title"><p className="lesson-section-label"><DataConnected size={16}/> Combining argument styles</p><h2 id="combined-title">{content.title}</h2><p>{content.explanation}</p><CodeSnippet type="multi" feedback="Copied">{content.code}</CodeSnippet><BindingRows example={content.binding}/><div className="combined-rules">{content.rules.map((rule)=><Tile key={rule}><CheckmarkOutline size={16}/><span>{rule}</span></Tile>)}</div></section>; }

export function ArgumentMappingVisualizer({ content }: { content: FunctionArgumentsLessonDevelopmentPack["mapping"] }) { const [selected,setSelected]=useState(0);const example=content.examples[selected];return <section id="mapping-visualizer" className="lesson-card argument-mapping-visualizer" aria-labelledby="mapping-title"><p className="lesson-section-label"><DataConnected size={16}/> Argument mapping visualizer</p><h2 id="mapping-title">{content.title}</h2><p>{content.body}</p><div className="argument-example-tabs" role="tablist" aria-label="Binding style">{content.examples.map((item,index)=><Button role="tab" aria-selected={selected===index} key={item.label} size="sm" kind={selected===index?"primary":"tertiary"} onClick={()=>setSelected(index)}>{item.label}</Button>)}</div><div className="mapping-stage"><Tile><span>Function call</span><code>{example.call}</code></Tile><ArrowRight/><Tile><span>Matching rules</span><strong>{[...new Set(example.bindings.map((item)=>item.source))].join(" + ")}</strong></Tile><ArrowRight/><Tile><span>Execution values</span><code>{example.output}</code></Tile></div><BindingRows example={example}/><p aria-live="polite">{example.label}: {example.bindings.map((binding)=>`${binding.parameter} receives ${binding.value} by ${binding.source}`).join("; ")}.</p></section>; }

export function FunctionCallBuilder({ content }: { content: FunctionArgumentsLessonDevelopmentPack["builder"] }) { const [keyword,setKeyword]=useState(false);const [optional,setOptional]=useState(false);const initial=Object.fromEntries(content.parameters.map((item)=>[item.name,item.initialValue]));const [values,setValues]=useState<Record<string,string>>(initial);const supplied=content.parameters.filter((item)=>!item.defaultValue||optional);const args=supplied.map((item)=>{const raw=item.type==="text"?`"${values[item.name]}"`:values[item.name];return keyword?`${item.name}=${raw}`:raw;});const call=`${content.functionName}(${args.join(", ")})`;const example:ArgumentBindingExample={label:"Generated call",call,output:supplied.map((item)=>values[item.name]).join(" · "),bindings:content.parameters.map((item)=>({parameter:item.name,value:!item.defaultValue||optional?(item.type==="text"?`"${values[item.name]}"`:values[item.name]):`"${item.defaultValue}"`,source:!item.defaultValue||optional?(keyword?"keyword":"positional"):"default"}))};return <section id="call-builder" className="lesson-card function-call-builder" aria-labelledby="call-builder-title"><p className="lesson-section-label"><Settings size={16}/> Function call builder</p><h2 id="call-builder-title">{content.title}</h2><p>{content.body}</p><div className="call-builder-layout"><form onSubmit={(event)=>event.preventDefault()}><Toggle id="builder-style" labelText="Call style" labelA="Positional" labelB="Keyword" toggled={keyword} onToggle={setKeyword}/><Toggle id="builder-optional" labelText="Optional unit" labelA="Use default" labelB="Supply value" toggled={optional} onToggle={setOptional}/>{content.parameters.filter((item)=>!item.defaultValue||optional).map((item)=>item.type==="number"?<NumberInput key={item.name} id={`builder-${item.name}`} label={item.name} value={Number(values[item.name])} min={0} onChange={(_,state)=>setValues((current)=>({...current,[item.name]:String(state.value)}))}/>:<TextInput key={item.name} id={`builder-${item.name}`} labelText={item.name} value={values[item.name]} onChange={(event)=>setValues((current)=>({...current,[item.name]:event.currentTarget.value}))}/>)}</form><div><Tile><span>Generated Python call</span><code>{call}</code></Tile><BindingRows example={example}/></div></div></section>; }

export function ArgumentComparison({ content }: { content: FunctionArgumentsLessonDevelopmentPack["comparison"] }) { return <section id="compare-choose" className="lesson-card argument-comparison" aria-labelledby="argument-comparison-title"><p className="lesson-section-label"><DataConnected size={16}/> Compare & choose</p><h2 id="argument-comparison-title">{content.title}</h2><p>{content.body}</p><div tabIndex={0} role="region" aria-label="Argument style comparison"><table><thead><tr><th>Feature</th><th>Positional</th><th>Keyword</th><th>Default</th></tr></thead><tbody>{content.rows.map((row)=><tr key={row.feature}><th>{row.feature}</th><td>{row.positional}</td><td>{row.keyword}</td><td>{row.defaults}</td></tr>)}</tbody></table></div></section>; }

export function ArgumentPlaygroundSupplement({ execution }: { execution: PlaygroundExecution }) { const active=execution.trace.at(-1);return <div className="argument-playground-supplement"><div><CallStackPreview stack={active?.callStack??["Main Program"]} activeFrame={active?.frameName}/><ParameterInspector execution={execution}/></div><CodeTracePanel execution={execution}/></div>; }

export function ArgumentMiniProject({ content }: { content: FunctionArgumentsLessonDevelopmentPack["miniProject"] }) { return <section id="mini-project" className="lesson-card argument-mini-project" aria-labelledby="argument-project-title"><p className="lesson-section-label"><Task size={16}/> Mini project</p><h2 id="argument-project-title">{content.title}</h2><p>{content.brief}</p><CodeSnippet type="multi" feedback="Copied">{`${content.starterCode}\n\n${content.calls.join("\n")}`}</CodeSnippet><div className="argument-project-checklist">{content.deliverables.map((item)=><Tile key={item}><CheckmarkOutline size={16}/><span>{item}</span></Tile>)}</div><Tile className="argument-project-challenge"><strong>Challenge</strong><p>{content.challenge}</p></Tile></section>; }
