import { useMemo, useState } from "react";
import { Button, CodeSnippet, ProgressBar, Tag, TextArea, Tile } from "@carbon/react";
import { ArrowRight, Checkmark, Clean, FunctionMath, Network_3, Task, WarningAlt } from "@carbon/icons-react";
import { FunctionEvolutionPanel } from "@/components/learning/FunctionParameterLearningBlocks";
import { FunctionQualityAnalyzer } from "@/components/learning/FunctionDesignLearningBlocks";
import { CodeTracePanel } from "@/components/learning/CodeTracePanel";
import type { PlaygroundExecution } from "@/components/learning/usePythonRunner";
import type { FunctionCapstoneDevelopmentPack } from "@/types/content";

export { FunctionEvolutionPanel };

export function CapstoneStory({content}:{content:FunctionCapstoneDevelopmentPack["story"]}){return <section id="story" className="lesson-card function-capstone-story"><p className="lesson-section-label"><Task size={16}/> Capstone story</p><h2>{content.title}</h2><p>{content.body}</p><div className="capstone-responsibility-grid">{content.responsibilities.map((item,index)=><Tile key={item}><span>{String(index+1).padStart(2,"0")}</span><strong>{item}</strong></Tile>)}</div></section>}

export function ProjectArchitectureViewer({content}:{content:FunctionCapstoneDevelopmentPack["architecture"]}){const [active,setActive]=useState("main");const node=content.nodes.find((item)=>item.id===active)??content.nodes[0];return <section id="architecture" className="lesson-card project-architecture-viewer"><p className="lesson-section-label"><Network_3 size={16}/> Project Architecture Viewer</p><h2>{content.title}</h2><p>{content.body}</p><div className="architecture-workspace"><div className="architecture-node-grid">{content.nodes.map((item)=><button key={item.id} type="button" className={active===item.id?"is-active":""} onClick={()=>setActive(item.id)}><span>Phase {item.phase}</span><strong>{item.label}</strong></button>)}</div><Tile className="architecture-inspector" aria-live="polite"><Tag type="purple">{node.id}</Tag><h3>{node.label}</h3><p>{node.purpose}</p><a href={`#phase-${node.phase}`}>Jump to phase {node.phase} <ArrowRight size={16}/></a></Tile></div><div className="architecture-edge-list" aria-label="Architecture connections">{content.edges.map((edge)=><Tag key={`${edge.from}-${edge.to}`} type="cool-gray">{edge.from} → {edge.to}</Tag>)}</div></section>}

export function PlanningBoard({content}:{content:FunctionCapstoneDevelopmentPack["planning"]}){return <section id="planning" className="lesson-card capstone-planning-board"><p className="lesson-section-label"><Clean size={16}/> Project planning</p><h2>{content.title}</h2><p>{content.body}</p><div className="planning-contracts">{content.functions.map((item)=><Tile key={item.name}><code>{item.name}</code><p>{item.responsibility}</p><dl><div><dt>Inputs</dt><dd>{item.inputs}</dd></div><div><dt>Output</dt><dd>{item.output}</dd></div></dl></Tile>)}</div></section>}

export function PhaseImplementation({phases}:{phases:FunctionCapstoneDevelopmentPack["phases"]}){const [active,setActive]=useState(0);const phase=phases[active];return <section id="implementation" className="lesson-card capstone-phases"><p className="lesson-section-label"><FunctionMath size={16}/> Phase-by-phase implementation</p><h2>Build one dependable layer at a time</h2><div className="phase-selector" role="tablist" aria-label="Capstone phases">{phases.map((item,index)=><Button key={item.id} size="sm" kind={index===active?"primary":"ghost"} role="tab" aria-selected={index===active} onClick={()=>setActive(index)}>{index+1}</Button>)}</div><article id={`phase-${active+1}`} aria-live="polite"><div><Tag type="blue">{phase.lesson}</Tag><Tag type="teal">{phase.concept}</Tag></div><h3>{phase.title}</h3><p>{phase.body}</p><CodeSnippet type="multi" feedback="Copied">{phase.code}</CodeSnippet><Tile className="phase-milestone"><Checkmark size={18}/><span>{phase.milestone}</span></Tile></article></section>}

export function FunctionDependencyGraph({content}:{content:FunctionCapstoneDevelopmentPack["dependencies"]}){const [active,setActive]=useState(content.root);const selected=content.functions.find((item)=>item.name===active)??content.functions[0];return <section id="dependency-graph" className="lesson-card function-dependency-graph"><p className="lesson-section-label"><Network_3 size={16}/> Function Dependency Graph</p><h2>{content.title}</h2><p>{content.body}</p><div className="dependency-graph-layout"><div className="dependency-root"><button type="button" className={active===content.root?"is-active":""} onClick={()=>setActive(content.root)}><code>{content.root}</code></button><div>{content.functions.slice(1).map((item)=><button key={item.name} type="button" className={active===item.name?"is-active":""} onClick={()=>setActive(item.name)}><code>{item.name}</code><small>{item.role}</small></button>)}</div></div><Tile aria-live="polite"><Tag type="purple">{selected.role}</Tag><h3><code>{selected.name}</code></h3><p>{selected.calls.length?"Calls these focused contracts:":"Leaf function · no unrelated function dependencies"}</p>{selected.calls.map((call)=><Tag key={call} type="blue">{call}</Tag>)}</Tile></div></section>}

export function ProjectFileExplorer({files}:{files:FunctionCapstoneDevelopmentPack["projectFiles"]}){const [active,setActive]=useState(0);const file=files[active];return <section id="project-files" className="lesson-card project-file-explorer"><p className="lesson-section-label"><Task size={16}/> Editable project blueprint</p><h2>Start with TODOs, inspect the integrated version, and record design choices</h2><div className="project-file-tabs" role="tablist">{files.map((item,index)=><Button key={item.name} role="tab" aria-selected={active===index} size="sm" kind={active===index?"primary":"ghost"} onClick={()=>setActive(index)}>{item.name}</Button>)}</div><p>{file.purpose}</p><CodeSnippet type="multi" feedback="Copied">{file.code}</CodeSnippet><p className="project-file-note">Use the editable playground below for execution. These tabs preserve the conceptual multi-file project view without introducing file handling.</p></section>}

export function ProfessionalRefactoringReview({content}:{content:FunctionCapstoneDevelopmentPack["refactoring"]}){const [after,setAfter]=useState(false);return <section id="refactoring" className="lesson-card capstone-refactoring"><div className="lesson-card-heading"><div><p className="lesson-section-label"><Clean size={16}/> Refactoring Assistant</p><h2>{content.title}</h2><p>{content.body}</p></div><Button size="sm" kind={after?"secondary":"primary"} onClick={()=>setAfter((value)=>!value)}>{after?"Show poor design":"Apply refactoring"}</Button></div><CodeSnippet type="multi" feedback="Copied">{after?content.afterCode:content.beforeCode}</CodeSnippet><div className="refactoring-suggestions">{content.suggestions.map((item,index)=><Tile key={item} className={after?"is-resolved":""}>{after?<Checkmark size={16}/>:<WarningAlt size={16}/>}<span>{item}</span><small>{after?"Applied":"Suggestion"} {index+1}</small></Tile>)}</div></section>}

export function CapstoneProgressTracker({content}:{content:FunctionCapstoneDevelopmentPack["progress"]}){const key="di-notes:m3-capstone-progress";const [complete,setComplete]=useState<string[]>(()=>{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem(key)??"[]")}catch{return[]}});const toggle=(id:string,index:number)=>{const priorReady=index===0||complete.includes(content.milestones[index-1].id);if(!priorReady&&!complete.includes(id))return;const next=complete.includes(id)?complete.filter((item)=>item!==id):[...complete,id];setComplete(next);localStorage.setItem(key,JSON.stringify(next));};const percent=Math.round(complete.length/content.milestones.length*100);return <section id="progress" className="lesson-card capstone-progress-tracker"><p className="lesson-section-label"><Task size={16}/> Capstone Progress Tracker</p><h2>{content.title}</h2><p>{content.body}</p><ProgressBar label={`${complete.length} of ${content.milestones.length} milestones`} helperText={`${percent}% complete`} value={percent} max={100}/><div className="capstone-milestones">{content.milestones.map((item,index)=>{const done=complete.includes(item.id);const unlocked=index===0||complete.includes(content.milestones[index-1].id)||done;return <button type="button" key={item.id} disabled={!unlocked} className={done?"is-complete":""} onClick={()=>toggle(item.id,index)}><span>{done?<Checkmark size={18}/>:index+1}</span><strong>{item.label}</strong><small>{unlocked?item.requirement:"Complete the previous milestone first"}</small></button>})}</div></section>}

export function IntegrationConsole({code,execution}:{code:string;execution:PlaygroundExecution}){const latest=execution.trace.at(-1);const frames=latest?.callStack??[];const returns=useMemo(()=>execution.trace.flatMap((step)=>step.variables.filter((variable)=>["water","fertilizer","status","report"].includes(variable.name))).slice(-6),[execution.trace]);return <div className="integration-console"><div className="integration-dashboard"><Tile><span>Current function</span><strong>{latest?.frameName??"Run the project"}</strong></Tile><Tile><span>Parameters / locals</span><strong>{latest?.variables.length??0}</strong></Tile><Tile><span>Call stack depth</span><strong>{frames.length}</strong></Tile><Tile><span>Execution</span><Tag type={execution.status==="success"?"green":execution.status==="error"?"red":"gray"}>{execution.status}</Tag></Tile></div><div className="integration-data-flow"><article><h4>Active scope</h4>{latest?.variables.length?latest.variables.slice(0,8).map((item)=><Tag key={item.name} type="teal">{item.name} = {item.value}</Tag>):<p>Variables appear here during execution.</p>}</article><article><h4>Returned integration values</h4>{returns.length?returns.map((item,index)=><Tag key={`${item.name}-${index}`} type="purple">{item.name}: {item.value}</Tag>):<p>Run the project to inspect returned results.</p>}</article></div><FunctionQualityAnalyzer code={code}/><CodeTracePanel execution={execution}/></div>}

export function AssessmentRubric({content}:{content:FunctionCapstoneDevelopmentPack["rubric"]}){const total=content.rows.reduce((sum,row)=>sum+row.marks,0);return <section id="rubric" className="lesson-card capstone-rubric"><p className="lesson-section-label"><Task size={16}/> Assessment rubric</p><h2>{content.title}</h2><p>{content.body}</p><div tabIndex={0} role="region" aria-label="Capstone assessment rubric"><table><thead><tr><th>Criterion</th><th>Evidence</th><th>Marks</th></tr></thead><tbody>{content.rows.map((row)=><tr key={row.criterion}><td>{row.criterion}</td><td>{row.evidence}</td><td>{row.marks}</td></tr>)}</tbody><tfoot><tr><th colSpan={2}>Total</th><th>{total}</th></tr></tfoot></table></div></section>}

export function EngineeringReflectionPanel({content}:{content:FunctionCapstoneDevelopmentPack["reflection"]}){const key="di-notes:m3-capstone-reflection";const [answers,setAnswers]=useState<string[]>(()=>{if(typeof window==="undefined")return content.prompts.map(()=>"");try{const saved=JSON.parse(localStorage.getItem(key)??"[]");return content.prompts.map((_,index)=>saved[index]??"")}catch{return content.prompts.map(()=>"")}});const update=(index:number,value:string)=>{const next=answers.map((answer,itemIndex)=>itemIndex===index?value:answer);setAnswers(next);localStorage.setItem(key,JSON.stringify(next));};return <section id="reflection" className="lesson-card engineering-reflection"><p className="lesson-section-label"><Clean size={16}/> Engineering Reflection</p><h2>{content.title}</h2><p>{content.body}</p><div>{content.prompts.map((prompt,index)=><TextArea key={prompt} id={`capstone-reflection-${index}`} labelText={`${index+1}. ${prompt}`} rows={3} value={answers[index]} onChange={(event)=>update(index,event.currentTarget.value)}/>)}</div><Tag type="green">Saved on this device</Tag></section>}

export function FinalChallenge({content}:{content:FunctionCapstoneDevelopmentPack["finalChallenge"]}){return <section id="final-challenge" className="lesson-card capstone-final-challenge"><p className="lesson-section-label"><Task size={16}/> Final challenge</p><h2>{content.title}</h2><p>{content.brief}</p><div className="final-challenge-examples">{content.examples.map((item)=><Tag key={item} type="magenta">{item}</Tag>)}</div><div className="design-project-checklist">{content.deliverables.map((item)=><Tile key={item}><Checkmark size={16}/><span>{item}</span></Tile>)}</div><Tile><strong>Constraint</strong><p>{content.constraint}</p></Tile></section>}
