import { useEffect, useState } from "react";
import { Button, CodeSnippet, NumberInput, Tag, TextInput, Tile } from "@carbon/react";
import { ArrowRight, CheckmarkOutline, DataConnected, FunctionMath, Play, Restart, Task, UserData } from "@carbon/icons-react";
import { CallStackPreview } from "@/components/learning/FunctionDefinitionLearningBlocks";
import { CodeTracePanel } from "@/components/learning/CodeTracePanel";
import type { PlaygroundExecution, PythonTraceVariable } from "@/components/learning/usePythonRunner";
import type { FunctionParametersLessonDevelopmentPack, ParameterExampleContent } from "@/types/content";

export function FunctionEvolutionPanel({ content }: { content: FunctionParametersLessonDevelopmentPack["evolution"] }) {
  return <section id="function-evolution" className="lesson-card function-evolution-panel" aria-labelledby="function-evolution-title"><p className="lesson-section-label"><DataConnected size={16} /> Function evolution</p><h2 id="function-evolution-title">{content.title}</h2><p>{content.body}</p><ol>{content.stages.map((stage) => <li key={stage.lesson} className={stage.active ? "is-active" : ""} aria-current={stage.active ? "step" : undefined}><Tag type={stage.active ? "purple" : "gray"}>Lesson {stage.lesson}</Tag><code>{stage.code}</code><span>{stage.capability}</span></li>)}</ol></section>;
}

export function ParameterStory({ content }: { content: FunctionParametersLessonDevelopmentPack["story"] }) {
  return <section id="story" className="lesson-card parameter-story" aria-labelledby="parameter-story-title"><p className="lesson-section-label"><FunctionMath size={16} /> Story continuation</p><h2 id="parameter-story-title">{content.title}</h2><p>{content.body}</p><CodeSnippet type="multi" feedback="Copied">{content.fixedFunction}</CodeSnippet><div className="parameter-farm-grid">{content.farms.map((farm) => <Tile key={farm.name}><strong>{farm.name}</strong><span>{farm.moisture}% moisture</span><ArrowRight /><code>irrigation(...)</code></Tile>)}</div><Tile className="parameter-rejected-design"><span>Do not create</span>{content.rejectedNames.map((name) => <code key={name}>{name}</code>)}<strong>Use one function with different inputs.</strong></Tile></section>;
}

export function HardcodedFunctionProblem({ content }: { content: FunctionParametersLessonDevelopmentPack["hardcoded"] }) {
  return <section id="hardcoded-problem" className="lesson-card hardcoded-function-problem" aria-labelledby="hardcoded-title"><p className="lesson-section-label"><DataConnected size={16} /> Problem with fixed functions</p><h2 id="hardcoded-title">{content.title}</h2><p>{content.explanation}</p><div className="hardcoded-grid"><CodeSnippet type="multi" feedback="Copied">{content.code}</CodeSnippet><Tile><Tag type="red">Fixed value: {content.fixedValue}</Tag><strong>{content.problem}</strong><ul>{content.risks.map((risk) => <li key={risk}>{risk}</li>)}</ul></Tile></div></section>;
}

export function ParameterConceptCard({ content }: { content: FunctionParametersLessonDevelopmentPack["definition"] }) {
  return <section id="parameter-concept" className="lesson-card parameter-concept-card" aria-labelledby="parameter-concept-title"><p className="lesson-section-label"><UserData size={16} /> What is a parameter?</p><h2 id="parameter-concept-title">{content.title}</h2><p>{content.body}</p><div className="parameter-container-visual"><div><span>{content.containerLabel}</span><strong>Waiting...</strong></div><ArrowRight /><div className="is-filled"><span>{content.containerLabel}</span><strong>18</strong></div></div><div className="delivery-analogy"><h3>{content.analogy.title}</h3><div>{content.analogy.inputs.map((input) => <Tile key={input}>{input}</Tile>)}</div><strong>{content.analogy.outcome}</strong></div></section>;
}

export function ParameterizedFunctionCard({ content }: { content: ParameterExampleContent }) {
  return <section id="first-parameter" className="lesson-card parameterized-function-card" aria-labelledby="first-parameter-title"><p className="lesson-section-label"><FunctionMath size={16} /> First parameterized function</p><h2 id="first-parameter-title">{content.title}</h2><p>{content.explanation}</p><div className="parameterized-example-grid"><CodeSnippet type="multi" feedback="Copied">{content.code}</CodeSnippet><pre><code>{content.output}</code></pre></div><div className="parameter-call-gallery">{content.calls.map((call, index) => <Tile key={`${call.arguments.join("-")}-${index}`}><code>{content.functionName}({call.arguments.join(", ")})</code><ArrowRight /><span>{call.output}</span></Tile>)}</div></section>;
}

function MappingRows({ parameters, arguments: values, activeIndex = -1 }: { parameters: string[]; arguments: string[]; activeIndex?: number }) {
  return <div className="argument-parameter-rows">{parameters.map((parameter, index) => <div key={`${parameter}-${index}`} className={index === activeIndex ? "is-active" : ""}><code>{values[index] ?? "Missing"}</code><ArrowRight /><code>{parameter}</code><span>Position {index + 1}</span></div>)}</div>;
}

export function ParameterFlowVisualizer({ content }: { content: FunctionParametersLessonDevelopmentPack["parameterFlow"] }) {
  const [activeStep, setActiveStep] = useState(0); const [playing, setPlaying] = useState(false);
  useEffect(() => { if (!playing || activeStep >= content.steps.length - 1) return; const timer = window.setTimeout(() => { const next = activeStep + 1; setActiveStep(next); if (next >= content.steps.length - 1) setPlaying(false); }, 650); return () => window.clearTimeout(timer); }, [activeStep, content.steps.length, playing]);
  const mappingActive = activeStep === 2 ? 0 : -1;
  return <section id="parameter-flow" className="lesson-card parameter-flow-visualizer" aria-labelledby="parameter-flow-title"><p className="lesson-section-label"><Play size={16} /> Parameter flow visualizer</p><h2 id="parameter-flow-title">{content.title}</h2><p>{content.body}</p><ol className="parameter-flow-steps">{content.steps.map((step, index) => <li key={step.title} className={index === activeStep ? "is-active" : index < activeStep ? "is-complete" : ""}><span>{index + 1}</span><div><strong>{step.title}</strong><p>{step.description}</p></div></li>)}</ol><MappingRows parameters={content.parameters} arguments={content.arguments} activeIndex={mappingActive} /><div className="parameter-flow-controls"><Button size="sm" kind="secondary" disabled={activeStep === 0 || playing} onClick={() => setActiveStep((step) => step - 1)}>Previous</Button><Button size="sm" renderIcon={playing ? Restart : Play} disabled={playing} onClick={() => activeStep === content.steps.length - 1 ? setActiveStep(0) : setPlaying(true)}>{activeStep === content.steps.length - 1 ? "Replay" : "Play flow"}</Button><Button size="sm" kind="tertiary" disabled={activeStep === content.steps.length - 1 || playing} onClick={() => setActiveStep((step) => step + 1)}>Next</Button></div><p aria-live="polite">Step {activeStep + 1} of {content.steps.length}: {content.steps[activeStep].title}</p></section>;
}

export function ArgumentParameterMapper({ content }: { content: FunctionParametersLessonDevelopmentPack["mapper"] }) {
  const [selected, setSelected] = useState(0); const active = content.argumentSets[selected];
  return <section id="argument-mapper" className="lesson-card argument-parameter-mapper" aria-labelledby="argument-mapper-title"><p className="lesson-section-label"><DataConnected size={16} /> Argument-to-parameter mapper</p><h2 id="argument-mapper-title">{content.title}</h2><p>{content.body}</p><div className="mapper-presets" role="tablist" aria-label="Argument examples">{content.argumentSets.map((set, index) => <Button role="tab" aria-selected={index === selected} key={set.label} size="sm" kind={index === selected ? "primary" : "tertiary"} onClick={() => setSelected(index)}>{set.label}</Button>)}</div><div className="mapper-call-definition"><Tile><span>Function call</span><code>{content.functionName}({active.arguments.join(", ")})</code></Tile><ArrowRight /><Tile><span>Function definition</span><code>{content.functionName}({content.parameters.join(", ")})</code></Tile></div><MappingRows parameters={content.parameters} arguments={active.arguments} /><p className={selected === content.argumentSets.length - 1 ? "mapper-warning" : "mapper-success"} aria-live="polite">{selected === content.argumentSets.length - 1 ? "Order changed: the location text now maps to sensor_id and 101 maps to location." : "Each argument maps to the parameter in the same position."}</p></section>;
}

export function FunctionInputSimulator({ content }: { content: FunctionParametersLessonDevelopmentPack["simulator"] }) {
  const initial = Object.fromEntries(content.fields.map((field) => [field.id, field.defaultValue])); const [values, setValues] = useState<Record<string,string>>(initial); const [ran, setRan] = useState(false);
  const args = content.fields.map((field) => field.type === "text" ? `"${values[field.id]}"` : values[field.id]); const output = content.outputTemplate.replaceAll(/\{([^}]+)\}/g, (_, id) => values[id] ?? "");
  return <section id="input-simulator" className="lesson-card function-input-simulator" aria-labelledby="input-simulator-title"><p className="lesson-section-label"><UserData size={16} /> Function input simulator</p><h2 id="input-simulator-title">{content.title}</h2><p>{content.body}</p><div className="function-input-layout"><form onSubmit={(event) => { event.preventDefault(); setRan(true); }}>{content.fields.map((field) => field.type === "number" ? <NumberInput key={field.id} id={`parameter-${field.id}`} label={field.label} value={Number(values[field.id])} min={0} onChange={(_, state) => { setValues((current) => ({ ...current, [field.id]: String(state.value) })); setRan(false); }} /> : <TextInput key={field.id} id={`parameter-${field.id}`} labelText={field.label} value={values[field.id]} onChange={(event) => { setValues((current) => ({ ...current, [field.id]: event.currentTarget.value })); setRan(false); }} />)}<Button type="submit" size="sm" renderIcon={Play}>Run function</Button></form><div><Tile><span>Generated call</span><code>{content.functionName}({args.join(", ")})</code></Tile><MappingRows parameters={content.parameters} arguments={args} /><pre aria-live="polite"><code>{ran ? output : "Run the function to generate output."}</code></pre></div></div></section>;
}

export function MultiParameterExplorer({ content }: { content: FunctionParametersLessonDevelopmentPack["explorer"] }) {
  const [selected, setSelected] = useState(0); const [swapped, setSwapped] = useState(false); const active = content.examples[selected]; const args = swapped && active.arguments.length > 1 ? [active.arguments[1], active.arguments[0], ...active.arguments.slice(2)] : active.arguments;
  return <section id="multi-parameter" className="lesson-card multi-parameter-explorer" aria-labelledby="multi-parameter-title"><p className="lesson-section-label"><DataConnected size={16} /> Multi-parameter explorer</p><h2 id="multi-parameter-title">{content.title}</h2><p>{content.body}</p><div className="multi-parameter-controls" role="tablist" aria-label="Parameter count examples">{content.examples.map((example,index) => <Button role="tab" aria-selected={selected===index} key={example.label} size="sm" kind={selected===index?"primary":"tertiary"} onClick={() => {setSelected(index);setSwapped(false);}}>{example.label}</Button>)}</div><div className="multi-parameter-code"><code>def {active.functionName}({active.parameters.join(", ")}):</code><code>{active.functionName}({args.join(", ")})</code></div><MappingRows parameters={active.parameters} arguments={args} />{active.arguments.length > 1 && <Button size="sm" kind="ghost" onClick={() => setSwapped((value)=>!value)}>{swapped?"Restore argument order":"Swap first two arguments"}</Button>}<p aria-live="polite">{swapped ? "The first two values now map to different parameters. Positional order changes meaning." : `${active.parameters.length} parameter${active.parameters.length===1?"":"s"} mapped correctly.`}</p></section>;
}

export function ParameterInspector({ execution }: { execution: PlaygroundExecution }) {
  const functionStep = [...execution.trace].reverse().find((step) => step.frameName && step.frameName !== "Main Program"); const variables: PythonTraceVariable[] = functionStep?.variables ?? [];
  return <div className="parameter-inspector" aria-labelledby="parameter-inspector-title"><div><UserData size={18}/><h3 id="parameter-inspector-title">Parameter Inspector</h3><Tag size="sm" type={functionStep?"green":"gray"}>{functionStep?.frameName ?? "Waiting"}</Tag></div>{variables.length?<div>{variables.map((variable)=><Tile key={variable.name}><strong>{variable.name}</strong><code>{variable.value}</code><Tag size="sm" type="blue">{variable.type}</Tag></Tile>)}</div>:<p>Run a parameterized function to inspect values inside its function frame.</p>}</div>;
}

export function ParameterPlaygroundSupplement({ execution }: { execution: PlaygroundExecution }) {
  const active = execution.trace.at(-1); return <div className="parameter-playground-supplement"><div><CallStackPreview stack={active?.callStack ?? ["Main Program"]} activeFrame={active?.frameName}/><ParameterInspector execution={execution}/></div><CodeTracePanel execution={execution}/></div>;
}

export function ParameterComparison({ content }: { content: FunctionParametersLessonDevelopmentPack["comparison"] }) {
  return <section id="compare-choose" className="lesson-card parameter-comparison" aria-labelledby="parameter-comparison-title"><p className="lesson-section-label"><DataConnected size={16}/> Compare & choose</p><h2 id="parameter-comparison-title">{content.title}</h2><p>{content.body}</p><div tabIndex={0} role="region" aria-label="Fixed and parameterized functions comparison"><table><thead><tr><th>Feature</th><th>Fixed function</th><th>Function with parameters</th></tr></thead><tbody>{content.rows.map((row)=><tr key={row.feature}><th>{row.feature}</th><td>{row.fixed}</td><td>{row.parameterized}</td></tr>)}</tbody></table></div></section>;
}

export function ParameterMiniProject({ content }: { content: FunctionParametersLessonDevelopmentPack["miniProject"] }) {
  return <section id="mini-project" className="lesson-card parameter-mini-project" aria-labelledby="parameter-project-title"><p className="lesson-section-label"><Task size={16}/> Mini project</p><h2 id="parameter-project-title">{content.title}</h2><p>{content.brief}</p><CodeSnippet type="multi" feedback="Copied">{content.starterCode}</CodeSnippet><div className="parameter-project-checklist">{content.deliverables.map((item)=><Tile key={item}><CheckmarkOutline size={16}/><span>{item}</span></Tile>)}</div><Tile className="parameter-project-challenge"><strong>Challenge</strong><p>{content.challenge}</p></Tile></section>;
}
