import { CourseBreadcrumb } from "@/components/course/CourseBreadcrumb";
import { PreviousNextNavigation } from "@/components/course/PreviousNextNavigation";
import { CommonMistakesCard } from "@/components/learning/FirstProgramLessonBlocks";
import { AgritechElifExamples, ConditionCoverageTester, ConditionOrderAnalyzer, DecisionTreeBuilder, ElifDefinitionCard, ElifPlayground, ElifSyntaxBreakdown, IfElifElseVisualizer, IfElifStoryCard, MultiBranchExecutionComparator, WhyTwoPathsCard } from "@/components/learning/IfElifElseLearningBlocks";
import { LessonHero } from "@/components/learning/LessonHero";
import { AssignmentCard, IndustryInsightCard, KeyTakeawaysCard, LearningObjectivesCard, PracticeCard, QuizCard, SummaryCard, WhatsNextCard } from "@/components/learning/LearningBlocks";
import { DebugChallengeCollection } from "@/components/learning/ProblemSolvingLearningBlocks";
import { MiniProjectCard } from "@/components/learning/UserInputLearningBlocks";
import { EngineerScenario } from "@/components/learning/WhyPythonLessonBlocks";
import type { CourseLesson, CourseModule } from "@/types/course";
import type { LessonDocument } from "@/types/content";

const elifOutline = [["objectives", "Objectives"], ["elif-story", "Story continuation"], ["why-two-paths", "Why multiple paths?"], ["elif-definition", "What is elif?"], ["elif-syntax", "Syntax"], ["elif-first-example", "First example"], ["elif-agritech-examples", "Agritech examples"], ["decision-tree-builder", "Decision tree builder"], ["condition-order-analyzer", "Order analyzer"], ["elif-execution-comparator", "Compare executions"], ["condition-coverage", "Coverage tester"], ["playground", "Execution lab"], ["common-mistakes", "Common mistakes"], ["debug-challenge", "Debug challenge"], ["engineer-scenario", "Engineer thinking"], ["practice", "Practice"], ["mini-project", "Mini project"], ["quiz", "Quiz"], ["assignment", "Assignment"], ["summary", "Summary"], ["whats-next", "What's next"]] as const;

export function IfElifElseLessonRenderer({ lesson, courseLesson, module, previous, next }: { lesson: LessonDocument; courseLesson: CourseLesson; module: CourseModule; previous: CourseLesson | null; next: CourseLesson | null }) {
  const pack = lesson.developmentPack;
  if (!pack || pack.kind !== "if-elif-else") return null;
  return <article className="published-lesson if-elif-else-development-pack"><CourseBreadcrumb module={module} lesson={courseLesson} /><LessonHero eyebrow={`Module ${module.index} · Lesson ${lesson.number}`} title={lesson.title} summary={lesson.summary} icon={module.icon} level={lesson.level} durationMinutes={lesson.durationMinutes} prerequisite={pack.prerequisite} /><div className="published-lesson-layout elif-lesson-layout"><div className="published-lesson-flow"><LearningObjectivesCard id="objectives" objectives={lesson.objectives} /><IfElifStoryCard content={pack.story} /><WhyTwoPathsCard content={pack.whyTwoPaths} /><ElifDefinitionCard content={pack.definition} /><ElifSyntaxBreakdown content={pack.syntax} /><IfElifElseVisualizer content={pack.firstExample} /><AgritechElifExamples examples={pack.agritechExamples} /><IndustryInsightCard id="industry-insight" section={lesson.industryMotivation} /><DecisionTreeBuilder content={pack.treeBuilder} /><ConditionOrderAnalyzer content={pack.orderAnalyzer} branches={pack.treeBuilder.branches} /><MultiBranchExecutionComparator branches={pack.treeBuilder.branches} /><ConditionCoverageTester content={pack.coverage} /><ElifPlayground content={lesson.playground} fields={pack.simulatorFields} branches={pack.treeBuilder.branches} /><CommonMistakesCard title={pack.mistakesTitle} mistakes={pack.mistakes} /><DebugChallengeCollection challenges={pack.debugChallenges} /><EngineerScenario content={pack.engineerScenario} /><PracticeCard id="practice" tasks={lesson.practice} /><MiniProjectCard project={pack.miniProject} /><QuizCard id="quiz" quiz={lesson.quiz} /><AssignmentCard id="assignment" assignment={lesson.assignment} /><SummaryCard id="summary" section={lesson.summarySection} /><KeyTakeawaysCard id="key-takeaways" items={lesson.keyTakeaways} /><WhatsNextCard id="whats-next" section={lesson.whatsNext} /></div><aside className="lesson-outline published-lesson-outline" aria-label="On this page"><p>On this page</p>{elifOutline.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside></div><PreviousNextNavigation previous={previous} next={next} /></article>;
}
