import { useState } from "react";
import { Button, CodeSnippet, Tag, TextInput, Tile } from "@carbon/react";
import { ArrowRight, CheckmarkOutline, FunctionMath, Task, TransformInstructions } from "@carbon/icons-react";
import { CallStackPreview, FunctionDebugChallenges } from "@/components/learning/FunctionDefinitionLearningBlocks";
import { FunctionEvolutionPanel } from "@/components/learning/FunctionParameterLearningBlocks";
import { FunctionLifecyclePanel } from "@/components/learning/ReturnValueLearningBlocks";
import { CodeTracePanel } from "@/components/learning/CodeTracePanel";
import type { PlaygroundExecution } from "@/components/learning/usePythonRunner";
import type { LambdaExampleContent, LambdaFunctionsLessonDevelopmentPack } from "@/types/content";

export { FunctionDebugChallenges, FunctionEvolutionPanel, FunctionLifecyclePanel };

function calculate(expression: string, values: number[]) {
  if (expression === "x * x") return values[0] * values[0];
  if (expression === "a * b") return values[0] * values[1];
  if (expression === "moisture * 5") return values[0] * 5;
  if (expression === "income - expense") return values[0] - values[1];
  return Number.NaN;
}

export function LambdaStory({ content }: { content: LambdaFunctionsLessonDevelopmentPack["story"] }) { return <section id="story" className="lesson-card lambda-story" aria-labelledby="lambda-story-title"><p className="lesson-section-label"><FunctionMath size={16}/> Story continuation</p><h2 id="lambda-story-title">{content.title}</h2><p>{content.body}</p><div className="lambda-story-functions">{content.namedFunctions.map((name)=><Tile key={name}><Tag type="blue">Reusable</Tag><code>{name}</code></Tile>)}</div><div className="lambda-story-once"><span>One-time need</span><strong>{content.oneTimeTask}</strong><ArrowRight/><code>lambda moisture: moisture * 10</code></div></section>; }

export function WhyLambdaCard({ content }: { content: LambdaFunctionsLessonDevelopmentPack["motivation"] }) { return <section id="why-lambda" className="lesson-card why-lambda-card" aria-labelledby="why-lambda-title"><p className="lesson-section-label"><TransformInstructions size={16}/> Why lambda?</p><h2 id="why-lambda-title">{content.title}</h2><p>{content.body}</p><div className="lambda-motivation-grid"><div><span>Reusable named task</span><CodeSnippet type="multi" feedback="Copied">{content.regularCode}</CodeSnippet></div><ArrowRight/><div><span>Small temporary expression</span><CodeSnippet type="single" feedback="Copied">{content.lambdaCode}</CodeSnippet></div></div><div className="lambda-traits">{content.traits.map((trait)=><Tag key={trait} type="purple">{trait}</Tag>)}</div></section>; }

export function LambdaSyntaxExplorer({ content }: { content: LambdaFunctionsLessonDevelopmentPack["syntax"] }) { const [selected,setSelected]=useState(0);return <section id="lambda-syntax" className="lesson-card lambda-syntax-explorer" aria-labelledby="lambda-syntax-title"><p className="lesson-section-label"><FunctionMath size={16}/> Lambda syntax</p><h2 id="lambda-syntax-title">{content.title}</h2><p>{content.body}</p><CodeSnippet type="single" feedback="Copied">{content.template}</CodeSnippet><div className="lambda-syntax-parts" role="list">{content.parts.map((part,index)=><button type="button" role="listitem" className={selected===index?"is-active":""} key={part.token} onClick={()=>setSelected(index)}><code>{part.token}</code><strong>{part.label}</strong><span>{part.description}</span></button>)}</div><Tile aria-live="polite"><Tag type="purple">{content.parts[selected].label}</Tag><p>{content.parts[selected].description}</p></Tile></section>; }

export function FunctionStyleComparator({ content, comparison }: { content: LambdaFunctionsLessonDevelopmentPack["comparisonExample"]; comparison: LambdaFunctionsLessonDevelopmentPack["comparison"] }) { return <section id="style-comparator" className="lesson-card function-style-comparator" aria-labelledby="style-comparator-title"><p className="lesson-section-label"><TransformInstructions size={16}/> Function style comparator</p><h2 id="style-comparator-title">{content.title}</h2><p>{content.body}</p><div className="function-style-code"><article><Tag type="blue">def</Tag><CodeSnippet type="multi" feedback="Copied">{content.regularCode}</CodeSnippet></article><article><Tag type="purple">lambda</Tag><CodeSnippet type="multi" feedback="Copied">{content.lambdaCode}</CodeSnippet></article></div><Tile className="lambda-shared-result"><code>{content.call}</code><ArrowRight/><strong>{content.result}</strong></Tile><div className="lambda-comparison-table" tabIndex={0} role="region" aria-label="Regular function and lambda comparison"><table><thead><tr><th>Feature</th><th>Regular function</th><th>Lambda function</th></tr></thead><tbody>{comparison.rows.map((row)=><tr key={row.feature}><th>{row.feature}</th><td>{row.regular}</td><td>{row.lambda}</td></tr>)}</tbody></table></div></section>; }

export function LambdaExecutionVisualizer({ example }: { example: LambdaExampleContent }) { return <div className="lambda-execution-visualizer"><div><h3>{example.title}</h3><Tag type="green">{example.result}</Tag></div><ol>{[{label:"Arguments",value:example.arguments.join(", ")},{label:"Parameter binding",value:example.parameters.map((name,index)=>`${name} = ${example.arguments[index]}`).join(" · ")},{label:"Expression",value:example.expression},{label:"Returned value",value:example.result}].map((step,index)=><li key={step.label}><span>{index+1}</span><strong>{step.label}</strong><code>{step.value}</code>{index<3&&<ArrowRight/>}</li>)}</ol></div>; }

export function LambdaExecutionSection({ content }: { content: LambdaFunctionsLessonDevelopmentPack["execution"] }) { const [active,setActive]=useState(0);return <section id="lambda-execution" className="lesson-card lambda-execution-section" aria-labelledby="lambda-execution-title"><p className="lesson-section-label"><FunctionMath size={16}/> Execution visualizer</p><h2 id="lambda-execution-title">{content.title}</h2><p>{content.body}</p><div className="lambda-example-tabs">{content.examples.map((item,index)=><Button key={item.title} size="sm" kind={active===index?"primary":"ghost"} onClick={()=>setActive(index)}>{item.title}</Button>)}</div><CodeSnippet type="multi" feedback="Copied">{content.examples[active].code}</CodeSnippet><LambdaExecutionVisualizer example={content.examples[active]}/></section>; }

export function LambdaBuilder({ content }: { content: LambdaFunctionsLessonDevelopmentPack["builder"] }) { const [presetIndex,setPresetIndex]=useState(0);const preset=content.presets[presetIndex];const [argumentSets,setArgumentSets]=useState(()=>content.presets.map((item)=>item.arguments));const args=argumentSets[presetIndex];const values=args.map(Number);const result=calculate(preset.expression,values);const lambda=`lambda ${preset.parameters.join(", ")}: ${preset.expression}`;const call=`(${lambda})(${args.join(", ")})`;const update=(index:number,value:string)=>setArgumentSets((current)=>current.map((set,setIndex)=>setIndex===presetIndex?set.map((item,itemIndex)=>itemIndex===index?value:item):set));return <section id="lambda-builder" className="lesson-card lambda-builder" aria-labelledby="lambda-builder-title"><p className="lesson-section-label"><FunctionMath size={16}/> Lambda builder</p><h2 id="lambda-builder-title">{content.title}</h2><p>{content.body}</p><div className="lambda-example-tabs">{content.presets.map((item,index)=><Button key={item.label} size="sm" kind={presetIndex===index?"primary":"ghost"} onClick={()=>setPresetIndex(index)}>{item.label}</Button>)}</div><div className="lambda-builder-layout"><form onSubmit={(event)=>event.preventDefault()}>{preset.parameters.map((parameter,index)=><TextInput key={parameter} id={`lambda-argument-${parameter}`} labelText={`Argument for ${parameter}`} inputMode="decimal" value={args[index]} onChange={(event)=>update(index,event.currentTarget.value)}/>)}</form><div><Tile><span>Generated lambda</span><code>{lambda}</code></Tile><Tile><span>Immediate call</span><code>{call}</code></Tile><LambdaExecutionVisualizer example={{title:"Live execution",code:call,explanation:"",parameters:preset.parameters,expression:preset.expression,arguments:args,result:Number.isFinite(result)?String(result):"Enter valid numbers"}}/></div></div></section>; }

export function DefToLambdaConverter({ content }: { content: LambdaFunctionsLessonDevelopmentPack["converter"] }) { const [active,setActive]=useState(0);const example=content.examples[active];return <section id="def-lambda-converter" className="lesson-card def-lambda-converter" aria-labelledby="def-lambda-title"><p className="lesson-section-label"><TransformInstructions size={16}/> Def-to-lambda converter</p><h2 id="def-lambda-title">{content.title}</h2><p>{content.body}</p><div className="lambda-example-tabs">{content.examples.map((item,index)=><Button key={item.label} size="sm" kind={active===index?"primary":"ghost"} onClick={()=>setActive(index)}>{item.label}</Button>)}</div><div className="converter-code-grid"><CodeSnippet type="multi" feedback="Copied">{example.regularCode}</CodeSnippet><ArrowRight/><CodeSnippet type="multi" feedback="Copied">{example.lambdaCode}</CodeSnippet></div><Tile aria-live="polite"><Tag type="green">Same result</Tag><strong>{example.result}</strong></Tile></section>; }

export function LambdaPlaygroundSupplement({ execution }: { execution: PlaygroundExecution }) { const active=execution.trace.at(-1);return <div className="lambda-playground-supplement"><CallStackPreview stack={active?.callStack??["Main Program"]} activeFrame={active?.frameName}/><CodeTracePanel execution={execution}/></div>; }

export function LambdaMiniProject({ content }: { content: LambdaFunctionsLessonDevelopmentPack["miniProject"] }) { return <section id="mini-project" className="lesson-card lambda-mini-project" aria-labelledby="lambda-project-title"><p className="lesson-section-label"><Task size={16}/> Mini project</p><h2 id="lambda-project-title">{content.title}</h2><p>{content.brief}</p><CodeSnippet type="multi" feedback="Copied">{content.starterCode}</CodeSnippet><div className="lambda-project-checklist">{content.deliverables.map((item)=><Tile key={item}><CheckmarkOutline size={16}/><span>{item}</span></Tile>)}</div><Tile className="lambda-project-challenge"><strong>Challenge</strong><p>{content.challenge}</p></Tile></section>; }
