import { CourseBreadcrumb } from "@/components/course/CourseBreadcrumb";
import { PreviousNextNavigation } from "@/components/course/PreviousNextNavigation";
import { CommonMistakesCard } from "@/components/learning/FirstProgramLessonBlocks";
import { LessonHero } from "@/components/learning/LessonHero";
import { AssignmentCard, IndustryInsightCard, KeyTakeawaysCard, LearningObjectivesCard, PracticeCard, QuizCard, SummaryCard, WhatsNextCard } from "@/components/learning/LearningBlocks";
import { AgritechMatchExamples, MatchCasePlayground, MatchCaseStoryCard, MatchCaseVisualizer, MatchComparisonCard, MatchDefinitionCard, MatchSyntaxBreakdown, MenuSimulator, StructureAdvisor, WhyMatchCard } from "@/components/learning/MatchCaseLearningBlocks";
import { DebugChallengeCollection } from "@/components/learning/ProblemSolvingLearningBlocks";
import { MiniProjectCard } from "@/components/learning/UserInputLearningBlocks";
import { EngineerScenario } from "@/components/learning/WhyPythonLessonBlocks";
import type { CourseLesson, CourseModule } from "@/types/course";
import type { LessonDocument } from "@/types/content";

const matchOutline = [["objectives", "Objectives"], ["match-story", "Story continuation"], ["why-match", "Why match-case?"], ["match-definition", "What is match-case?"], ["match-syntax", "Syntax"], ["match-first-example", "Execution visualizer"], ["match-agritech-examples", "Agritech examples"], ["menu-simulator", "Menu simulator"], ["playground", "Execution lab"], ["common-mistakes", "Common mistakes"], ["debug-challenge", "Debug challenge"], ["engineer-scenario", "Engineer thinking"], ["practice", "Practice"], ["compare-choose", "Compare & choose"], ["structure-advisor", "Structure Advisor"], ["mini-project", "Mini project"], ["quiz", "Quiz"], ["assignment", "Assignment"], ["summary", "Summary"], ["whats-next", "What's next"]] as const;

export function MatchCaseLessonRenderer({ lesson, courseLesson, module, previous, next }: { lesson: LessonDocument; courseLesson: CourseLesson; module: CourseModule; previous: CourseLesson | null; next: CourseLesson | null }) {
  const pack = lesson.developmentPack;
  if (!pack || pack.kind !== "match-case") return null;
  return <article className="published-lesson match-case-development-pack"><CourseBreadcrumb module={module} lesson={courseLesson} /><LessonHero eyebrow={`Module ${module.index} · Lesson ${lesson.number}`} title={lesson.title} summary={lesson.summary} icon={module.icon} level={lesson.level} durationMinutes={lesson.durationMinutes} prerequisite={pack.prerequisite} /><div className="published-lesson-layout match-lesson-layout"><div className="published-lesson-flow"><LearningObjectivesCard id="objectives" objectives={lesson.objectives} /><MatchCaseStoryCard content={pack.story} /><WhyMatchCard content={pack.whyMatch} /><MatchDefinitionCard content={pack.definition} /><MatchSyntaxBreakdown content={pack.syntax} /><MatchCaseVisualizer content={pack.firstExample} /><AgritechMatchExamples examples={pack.agritechExamples} /><IndustryInsightCard id="industry-insight" section={lesson.industryMotivation} /><MenuSimulator content={pack.menuSimulator} /><MatchCasePlayground content={lesson.playground} fields={pack.simulatorFields} /><CommonMistakesCard title={pack.mistakesTitle} mistakes={pack.mistakes} /><DebugChallengeCollection challenges={pack.debugChallenges} /><EngineerScenario content={pack.engineerScenario} /><PracticeCard id="practice" tasks={lesson.practice} /><MatchComparisonCard content={pack.comparison} /><StructureAdvisor content={pack.structureAdvisor} /><MiniProjectCard project={pack.miniProject} /><QuizCard id="quiz" quiz={lesson.quiz} /><AssignmentCard id="assignment" assignment={lesson.assignment} /><SummaryCard id="summary" section={lesson.summarySection} /><KeyTakeawaysCard id="key-takeaways" items={lesson.keyTakeaways} /><WhatsNextCard id="whats-next" section={lesson.whatsNext} /></div><aside className="lesson-outline published-lesson-outline" aria-label="On this page"><p>On this page</p>{matchOutline.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside></div><PreviousNextNavigation previous={previous} next={next} /></article>;
}
