import { CourseBreadcrumb } from "@/components/course/CourseBreadcrumb";
import { PreviousNextNavigation } from "@/components/course/PreviousNextNavigation";
import { CodePlayground } from "@/components/learning/CodePlayground";
import { CustomizationConcept, CustomizationMistakes, CustomizationReference, FarmChartDesigner, FigureAxesSubplots, FixBadChart, LabelsLimitsTicks, StyleVocabulary, SubplotBuilder } from "@/components/learning/MatplotlibCustomizationLearningBlocks";
import { LessonHero } from "@/components/learning/LessonHero";
import { IndustryInsightCard, KeyTakeawaysCard, LearningObjectivesCard, PracticeCard, QuizCard, SummaryCard, WhatsNextCard } from "@/components/learning/LearningBlocks";
import { DebugChallengeCollection } from "@/components/learning/ProblemSolvingLearningBlocks";
import type { LessonDocument } from "@/types/content";
import type { CourseLesson, CourseModule } from "@/types/course";

const outline = [["objectives", "Objectives"], ["customization-concept", "Why customize"], ["style-vocabulary", "Style controls"], ["labels-limits", "Labels and scale"], ["figure-axes", "Figure and Axes"], ["chart-designer", "Chart designer"], ["subplot-builder", "Subplot builder"], ["fix-chart", "Fix a chart"], ["customization-mistakes", "Mistakes"], ["playground", "Code runner"], ["practice", "Practice"], ["debug-challenge", "Debug"], ["quiz", "Quiz"], ["customization-reference", "Quick reference"], ["summary", "Summary"], ["whats-next", "What's next"]] as const;

export function MatplotlibCustomizationLessonRenderer({ lesson, courseLesson, module, previous, next }: { lesson: LessonDocument; courseLesson: CourseLesson; module: CourseModule; previous: CourseLesson | null; next: CourseLesson | null }) {
  const pack = lesson.developmentPack; if (!pack || pack.kind !== "matplotlib-customization-subplots") return null;
  return <article className="published-lesson matplotlib-customization-pack"><CourseBreadcrumb module={module} lesson={courseLesson} /><LessonHero eyebrow={`Module ${module.index} · Lesson ${lesson.number}`} title={lesson.title} summary={lesson.summary} icon={module.icon} level={lesson.level} durationMinutes={lesson.durationMinutes} prerequisite={pack.prerequisite} /><div className="published-lesson-layout"><div className="published-lesson-flow"><LearningObjectivesCard id="objectives" objectives={lesson.objectives} /><section className="lesson-card"><p className="lesson-section-label">Final Matplotlib lesson</p><h2>Move from a valid chart to a clear analytical figure</h2><p>{pack.storyHook}</p></section><CustomizationConcept /><StyleVocabulary /><LabelsLimitsTicks /><FigureAxesSubplots /><FarmChartDesigner pack={pack} /><SubplotBuilder pack={pack} /><FixBadChart pack={pack} /><CustomizationMistakes pack={pack} /><IndustryInsightCard id="industry-insight" section={lesson.industryMotivation} /><CodePlayground id="playground" content={lesson.playground} className="matplotlib-customization-playground" /><PracticeCard id="practice" tasks={lesson.practice} /><DebugChallengeCollection challenges={pack.debugChallenges} /><QuizCard id="quiz" quiz={lesson.quiz} /><CustomizationReference pack={pack} /><SummaryCard id="summary" section={lesson.summarySection} /><KeyTakeawaysCard id="key-takeaways" items={lesson.keyTakeaways} /><WhatsNextCard id="whats-next" section={lesson.whatsNext} /></div><aside className="lesson-outline published-lesson-outline" aria-label="On this page"><p>On this page</p>{outline.map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</aside></div><PreviousNextNavigation previous={previous} next={next} /></article>;
}
