import { CourseBreadcrumb } from "@/components/course/CourseBreadcrumb";
import { PreviousNextNavigation } from "@/components/course/PreviousNextNavigation";
import { BinExplorer, BoxPlotAnatomy, DistributionConcept, DistributionExplorer, DistributionMistakes, DistributionQuickReference, FieldDistributionComparison, HistogramBoxComparison, OutlierDetective } from "@/components/learning/MatplotlibDistributionLearningBlocks";
import { CodePlayground } from "@/components/learning/CodePlayground";
import { LessonHero } from "@/components/learning/LessonHero";
import { IndustryInsightCard, KeyTakeawaysCard, LearningObjectivesCard, PracticeCard, QuizCard, SummaryCard, WhatsNextCard } from "@/components/learning/LearningBlocks";
import { DebugChallengeCollection } from "@/components/learning/ProblemSolvingLearningBlocks";
import type { LessonDocument } from "@/types/content";
import type { CourseLesson, CourseModule } from "@/types/course";

const outline = [["objectives", "Objectives"], ["distribution-concept", "Distribution"], ["histogram-box-comparison", "Histogram vs box"], ["boxplot-anatomy", "Box anatomy"], ["field-comparison", "Compare fields"], ["distribution-explorer", "Distribution explorer"], ["outlier-detective", "Outlier detective"], ["bin-explorer", "Bin explorer"], ["distribution-mistakes", "Mistakes"], ["playground", "Code runner"], ["practice", "Practice"], ["debug-challenge", "Debug"], ["quiz", "Quiz"], ["distribution-reference", "Quick reference"], ["summary", "Summary"], ["whats-next", "What's next"]] as const;

export function MatplotlibDistributionLessonRenderer({ lesson, courseLesson, module, previous, next }: { lesson: LessonDocument; courseLesson: CourseLesson; module: CourseModule; previous: CourseLesson | null; next: CourseLesson | null }) {
  const pack = lesson.developmentPack; if (!pack || pack.kind !== "matplotlib-distribution-analysis") return null;
  return <article className="published-lesson matplotlib-distribution-pack"><CourseBreadcrumb module={module} lesson={courseLesson} /><LessonHero eyebrow={`Module ${module.index} · Lesson ${lesson.number}`} title={lesson.title} summary={lesson.summary} icon={module.icon} level={lesson.level} durationMinutes={lesson.durationMinutes} prerequisite={pack.prerequisite} /><div className="published-lesson-layout"><div className="published-lesson-flow"><LearningObjectivesCard id="objectives" objectives={lesson.objectives} /><section className="lesson-card"><p className="lesson-section-label">From readings to distribution</p><h2>Ask how all observations behave together</h2><p>{pack.storyHook}</p></section><DistributionConcept /><HistogramBoxComparison pack={pack} /><BoxPlotAnatomy /><FieldDistributionComparison pack={pack} /><DistributionExplorer pack={pack} /><OutlierDetective pack={pack} /><BinExplorer pack={pack} /><DistributionMistakes mistakes={pack.commonMistakes} /><IndustryInsightCard id="industry-insight" section={lesson.industryMotivation} /><CodePlayground id="playground" content={lesson.playground} className="matplotlib-distribution-playground" /><PracticeCard id="practice" tasks={lesson.practice} /><DebugChallengeCollection challenges={pack.debugChallenges} /><QuizCard id="quiz" quiz={lesson.quiz} /><DistributionQuickReference rows={pack.quickReference} /><SummaryCard id="summary" section={lesson.summarySection} /><KeyTakeawaysCard id="key-takeaways" items={lesson.keyTakeaways} /><WhatsNextCard id="whats-next" section={lesson.whatsNext} /></div><aside className="lesson-outline published-lesson-outline" aria-label="On this page"><p>On this page</p>{outline.map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</aside></div><PreviousNextNavigation previous={previous} next={next} /></article>;
}
