import { useState } from "react";
import { CodeSnippet, Tile } from "@carbon/react";
import { MatplotlibChartRenderer, type MatplotlibChartKind } from "@/components/learning/MatplotlibChartRenderer";
import type { MatplotlibChartTypesDevelopmentPack } from "@/types/content";

type Pack = MatplotlibChartTypesDevelopmentPack;
type VariableId = Pack["timeSeries"]["variables"][number]["id"];

const chartFunction: Record<MatplotlibChartKind, string> = { line: "plot", bar: "bar", barh: "barh", scatter: "scatter", area: "fill_between" };

export function ChartQuestionMap() {
  const items = [["Trend over time", "Line", "plt.plot()"], ["Compare categories", "Bar", "plt.bar()"], ["Numerical relationship", "Scatter", "plt.scatter()"], ["Magnitude over time", "Area", "plt.fill_between()"]];
  return <section id="chart-question-map" className="lesson-card"><p className="lesson-section-label">Question before chart</p><h2>Four chart forms answer four different questions</h2><div className="chart-type-map">{items.map(([question, chart, code]) => <Tile key={chart}><span>{question}</span><strong>{chart}</strong><code>{code}</code></Tile>)}</div><p className="matplotlib-focus-note"><strong>Choose for communication.</strong> A chart is appropriate when its visual encoding matches the structure of the question—not because it looks attractive.</p></section>;
}

export function CoreChartExamples({ pack }: { pack: Pack }) {
  const temperature = pack.timeSeries.variables[0]; const moisture = pack.timeSeries.variables[1];
  return <section id="core-chart-examples" className="lesson-card"><p className="lesson-section-label">Core chart types</p><h2>See how the same visual grammar changes with the question</h2><div className="core-chart-grid"><Tile><MatplotlibChartRenderer kind="line" x={pack.timeSeries.days} y={temperature.values} title="Weekly Farm Temperature" xLabel="Day" yLabel="Temperature (°C)" /><strong>Line → ordered trend</strong><code>plt.plot(days, temperature)</code></Tile><Tile><MatplotlibChartRenderer kind="bar" x={pack.cropYield.crops} y={pack.cropYield.values} title="Crop Yield Comparison" xLabel="Crop" yLabel="Yield (kg/acre)" /><strong>Bar → category comparison</strong><code>plt.bar(crops, yield_data)</code></Tile><Tile><MatplotlibChartRenderer kind="scatter" x={[24, 26, 28, 30, 32, 34, 36]} y={pack.timeSeries.yieldValues} title="Temperature vs Crop Yield" xLabel="Temperature (°C)" yLabel="Yield (kg/acre)" /><strong>Scatter → numerical relationship</strong><code>plt.scatter(temperature, yield_data)</code></Tile><Tile><MatplotlibChartRenderer kind="area" x={pack.timeSeries.days} y={moisture.values} title="Soil Moisture Over Time" xLabel="Day" yLabel="Soil Moisture (%)" /><strong>Area → magnitude over time</strong><code>plt.fill_between(days, moisture, 0)</code></Tile></div></section>;
}

export function LineBarDistinction({ pack }: { pack: Pack }) {
  const fieldA = pack.timeSeries.variables[0].values; const fieldB = [24, 26, 27, 29, 30, 30, 28];
  return <section id="line-bar-distinction" className="lesson-card"><p className="lesson-section-label">Line, bar, and barh</p><h2>Continuity and category structure decide the chart</h2><div className="line-bar-comparison"><Tile><MatplotlibChartRenderer kind="line" x={pack.timeSeries.days} y={fieldA} secondSeries={{ y: fieldB, label: "Field B" }} seriesLabel="Field A" title="Field Temperature Comparison" xLabel="Day" yLabel="Temperature (°C)" /><strong>Multiple lines compare trends</strong><code>plt.plot(..., label="Field A")</code></Tile><Tile><MatplotlibChartRenderer kind="barh" x={pack.cropYield.crops} y={pack.cropYield.values} title="Crop Yield Comparison" xLabel="Crop" yLabel="Yield (kg/acre)" /><strong>Horizontal bars fit longer labels</strong><code>plt.barh(crops, yield_data)</code></Tile></div><div className="chart-rule-strip"><span><b>Bar</b> compares discrete categories</span><span><b>Line</b> shows ordered progression</span></div></section>;
}

export function AgritechChartExplorer({ pack }: { pack: Pack }) {
  const [variableId, setVariableId] = useState<VariableId>("temperature"); const [kind, setKind] = useState<"line" | "bar" | "scatter" | "area">("line");
  const variable = pack.timeSeries.variables.find((item) => item.id === variableId) ?? pack.timeSeries.variables[0]; const scatter = kind === "scatter"; const x = scatter ? variable.values : pack.timeSeries.days; const y = scatter ? pack.timeSeries.yieldValues : variable.values;
  const xName = scatter ? variable.id : "days"; const yName = scatter ? "yield_data" : variable.id; const title = scatter ? `${variable.label} vs Crop Yield` : `${variable.label} by Day`; const xLabel = scatter ? `${variable.label} (${variable.unit})` : "Day"; const yLabel = scatter ? "Yield (kg/acre)" : `${variable.label} (${variable.unit})`;
  const call = kind === "area" ? `plt.fill_between(${xName}, ${yName}, 0)` : `plt.${chartFunction[kind]}(${xName}, ${yName}${kind === "line" ? ', marker="o"' : ""})`;
  const code = [`${xName} = [${x.join(", ")}]`, `${yName} = [${y.join(", ")}]`, "", call, `plt.title("${title}")`, `plt.xlabel("${xLabel}")`, `plt.ylabel("${yLabel}")`, ...(kind === "line" || kind === "scatter" ? ["plt.grid()"] : []), "plt.show()"].join("\n");
  return <section id="chart-explorer" className="lesson-card"><p className="lesson-section-label">Interactive AgriTech Chart Explorer</p><h2>Change the chart and inspect the code it requires</h2><div className="chart-explorer-controls"><label>Variable<select aria-label="Explorer variable" value={variableId} onChange={(event) => setVariableId(event.target.value as VariableId)}>{pack.timeSeries.variables.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Chart type<select aria-label="Explorer chart type" value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="line">Line</option><option value="bar">Bar</option><option value="scatter">Scatter</option><option value="area">Area</option></select></label></div><MatplotlibChartRenderer kind={kind} x={x} y={y} title={title} xLabel={xLabel} yLabel={yLabel} /><Tile className="chart-generated-code"><CodeSnippet type="multi" feedback="Copied">{code}</CodeSnippet><p>{scatter ? "Each point pairs one selected sensor value with one yield observation. Association does not prove causation." : `${variable.label} is encoded against the ordered day values.`}</p></Tile></section>;
}

export function ChartDecisionActivity({ pack }: { pack: Pack }) {
  const [index, setIndex] = useState(0); const [choice, setChoice] = useState<Pack["decisions"][number]["answer"] | null>(null); const scenario = pack.decisions[index]; const correct = choice === scenario.answer;
  const choose = (answer: Pack["decisions"][number]["answer"]) => setChoice(answer); const next = () => { setIndex((index + 1) % pack.decisions.length); setChoice(null); };
  return <section id="chart-decision" className="lesson-card"><p className="lesson-section-label">Interactive chart decision</p><h2>Which chart should I use?</h2><div className="chart-decision-card"><span>Scenario {index + 1} of {pack.decisions.length}</span><strong>{scenario.question}</strong><div>{(["line", "bar", "scatter", "area"] as const).map((answer) => <button type="button" aria-pressed={choice === answer} onClick={() => choose(answer)} key={answer}>{answer[0].toUpperCase() + answer.slice(1)}</button>)}</div>{choice && <p className={correct ? "is-correct" : "is-incorrect"} aria-live="polite"><b>{correct ? "Correct." : "Try again."}</b> {correct ? scenario.explanation : "Decide whether the question is about a trend, categories, a relationship, or magnitude."}</p>}{choice && <button type="button" className="chart-next-question" onClick={next}>Next scenario</button>}</div></section>;
}

export function VisualizationLab({ pack }: { pack: Pack }) {
  const [xId, setXId] = useState<"days" | VariableId>("days"); const [yId, setYId] = useState<VariableId>("temperature"); const [kind, setKind] = useState<MatplotlibChartKind>("line");
  const variable = (id: VariableId) => pack.timeSeries.variables.find((item) => item.id === id) ?? pack.timeSeries.variables[0]; const xValues = xId === "days" ? pack.timeSeries.days : variable(xId).values; const yVariable = variable(yId); const xLabel = xId === "days" ? "Day" : `${variable(xId).label} (${variable(xId).unit})`; const title = `${yVariable.label} by ${xId === "days" ? "Day" : variable(xId).label}`;
  const codeName = chartFunction[kind]; const call = kind === "area" ? `plt.fill_between(${xId}, ${yId}, 0)` : `plt.${codeName}(${xId}, ${yId})`; const code = `${call}\nplt.xlabel("${xLabel}")\nplt.ylabel("${yVariable.label} (${yVariable.unit})")\nplt.show()`;
  return <section id="visualization-lab" className="lesson-card"><p className="lesson-section-label">Interactive Agritech Visualization Lab</p><h2>Build an x/y/chart combination</h2><div className="chart-lab-controls"><label>X variable<select aria-label="Lab X variable" value={xId} onChange={(event) => setXId(event.target.value as typeof xId)}><option value="days">Day</option>{pack.timeSeries.variables.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>Y variable<select aria-label="Lab Y variable" value={yId} onChange={(event) => setYId(event.target.value as VariableId)}>{pack.timeSeries.variables.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>Chart type<select aria-label="Lab chart type" value={kind} onChange={(event) => setKind(event.target.value as MatplotlibChartKind)}><option value="line">Line</option><option value="bar">Bar</option><option value="barh">Horizontal bar</option><option value="scatter">Scatter</option><option value="area">Area</option></select></label></div><MatplotlibChartRenderer kind={kind} x={xValues} y={yVariable.values} title={title} xLabel={xLabel} yLabel={`${yVariable.label} (${yVariable.unit})`} /><Tile className="chart-generated-code"><CodeSnippet type="multi" feedback="Copied">{code}</CodeSnippet><p>Check whether the selected chart matches the analytical question before interpreting it.</p></Tile></section>;
}

export function ChartMistakes({ mistakes }: { mistakes: Pack["commonMistakes"] }) { return <section id="chart-mistakes" className="lesson-card"><p className="lesson-section-label">Common mistakes</p><h2>A valid chart can still communicate the wrong idea</h2><div className="chart-mistake-grid">{mistakes.map((item) => <Tile key={item.title}><strong>{item.title}</strong><code>{item.code}</code><p>{item.explanation}</p></Tile>)}</div></section>; }

export function ChartQuickReference({ rows }: { rows: Pack["quickReference"] }) { return <section id="chart-reference" className="lesson-card"><p className="lesson-section-label">Quick reference and decision map</p><h2>Choose from the relationship in the data</h2><div className="chart-reference-grid">{rows.map((row) => <Tile key={row.task}><span>{row.task}</span><code>{row.code}</code><strong>{row.use}</strong></Tile>)}</div></section>; }
