import { CourseBreadcrumb } from "@/components/course/CourseBreadcrumb";
import { PreviousNextNavigation } from "@/components/course/PreviousNextNavigation";
import { AgritechChartExplorer, ChartDecisionActivity, ChartMistakes, ChartQuestionMap, ChartQuickReference, CoreChartExamples, LineBarDistinction, VisualizationLab } from "@/components/learning/MatplotlibChartTypesLearningBlocks";
import { CodePlayground } from "@/components/learning/CodePlayground";
import { LessonHero } from "@/components/learning/LessonHero";
import { IndustryInsightCard, KeyTakeawaysCard, LearningObjectivesCard, PracticeCard, QuizCard, SummaryCard, WhatsNextCard } from "@/components/learning/LearningBlocks";
import { DebugChallengeCollection } from "@/components/learning/ProblemSolvingLearningBlocks";
import type { LessonDocument } from "@/types/content";
import type { CourseLesson, CourseModule } from "@/types/course";

const outline = [["objectives", "Objectives"], ["chart-question-map", "Chart choice"], ["core-chart-examples", "Four chart types"], ["line-bar-distinction", "Line vs bar"], ["chart-explorer", "Chart explorer"], ["chart-decision", "Choose a chart"], ["visualization-lab", "Visualization lab"], ["chart-mistakes", "Mistakes"], ["playground", "Code runner"], ["practice", "Practice"], ["debug-challenge", "Debug"], ["quiz", "Quiz"], ["chart-reference", "Quick reference"], ["summary", "Summary"], ["whats-next", "What's next"]] as const;

export function MatplotlibChartTypesLessonRenderer({ lesson, courseLesson, module, previous, next }: { lesson: LessonDocument; courseLesson: CourseLesson; module: CourseModule; previous: CourseLesson | null; next: CourseLesson | null }) {
  const pack = lesson.developmentPack; if (!pack || pack.kind !== "matplotlib-core-chart-types") return null;
  return <article className="published-lesson matplotlib-chart-types-pack"><CourseBreadcrumb module={module} lesson={courseLesson} /><LessonHero eyebrow={`Module ${module.index} · Lesson ${lesson.number}`} title={lesson.title} summary={lesson.summary} icon={module.icon} level={lesson.level} durationMinutes={lesson.durationMinutes} prerequisite={pack.prerequisite} /><div className="published-lesson-layout"><div className="published-lesson-flow"><LearningObjectivesCard id="objectives" objectives={lesson.objectives} /><section className="lesson-card"><p className="lesson-section-label">From question to visual encoding</p><h2>Start with what the farmer needs to understand</h2><p>{pack.storyHook}</p><div className="chart-question-flow"><span>Question</span><span>Data relationship</span><span>Chart type</span><strong>Interpretation</strong></div></section><ChartQuestionMap /><CoreChartExamples pack={pack} /><LineBarDistinction pack={pack} /><AgritechChartExplorer pack={pack} /><ChartDecisionActivity pack={pack} /><VisualizationLab pack={pack} /><ChartMistakes mistakes={pack.commonMistakes} /><IndustryInsightCard id="industry-insight" section={lesson.industryMotivation} /><CodePlayground id="playground" content={lesson.playground} className="matplotlib-chart-playground" /><PracticeCard id="practice" tasks={lesson.practice} /><DebugChallengeCollection challenges={pack.debugChallenges} /><QuizCard id="quiz" quiz={lesson.quiz} /><ChartQuickReference rows={pack.quickReference} /><SummaryCard id="summary" section={lesson.summarySection} /><KeyTakeawaysCard id="key-takeaways" items={lesson.keyTakeaways} /><WhatsNextCard id="whats-next" section={lesson.whatsNext} /></div><aside className="lesson-outline published-lesson-outline" aria-label="On this page"><p>On this page</p>{outline.map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</aside></div><PreviousNextNavigation previous={previous} next={next} /></article>;
}
