import { useState } from "react";
import { CodeSnippet, Tile } from "@carbon/react";
import { BoxPlotChart, HistogramChart } from "@/components/learning/MatplotlibDistributionRenderer";
import { summarizeBox } from "@/lib/distribution-statistics";
import type { MatplotlibDistributionDevelopmentPack } from "@/types/content";

type Pack = MatplotlibDistributionDevelopmentPack;
type DatasetId = Pack["datasets"][number]["id"];

export function DistributionConcept() {
  return <section id="distribution-concept" className="lesson-card"><p className="lesson-section-label">What is a distribution?</p><h2>Move from individual readings to the pattern formed by all readings</h2><div className="distribution-question-flow"><span>Low values</span><span>Concentration</span><span>High values</span><strong>Unusual observations</strong></div><div className="distribution-lenses"><Tile><strong>Center</strong><span>Where readings concentrate</span></Tile><Tile><strong>Spread</strong><span>How widely readings vary</span></Tile><Tile><strong>Shape</strong><span>Symmetric or skewed pattern</span></Tile><Tile><strong>Outliers</strong><span>Values separated from most readings</span></Tile></div></section>;
}

export function HistogramBoxComparison({ pack }: { pack: Pack }) {
  const data = pack.datasets[0];
  return <section id="histogram-box-comparison" className="lesson-card"><p className="lesson-section-label">Histogram versus box plot</p><h2>Related data, different questions</h2><div className="distribution-comparison"><Tile><HistogramChart values={data.values} bins={5} title="Temperature Distribution" label={data.label} unit={data.unit} /><strong>Histogram → shape and frequency</strong><span>Intervals reveal concentration and gaps.</span><code>plt.hist(temperature, bins=5)</code></Tile><Tile><BoxPlotChart groups={[{ label: "Temperature", values: data.values }]} title="Temperature Summary" label={data.label} unit={data.unit} /><strong>Box plot → compact summary</strong><span>Median, quartiles, whiskers, and potential outliers.</span><code>plt.boxplot(temperature)</code></Tile></div></section>;
}

export function BoxPlotAnatomy() {
  const sample = [10, 12, 14, 15, 17, 18, 20, 22, 25, 30]; const stat = summarizeBox(sample);
  return <section id="boxplot-anatomy" className="lesson-card"><p className="lesson-section-label">Box plot anatomy</p><h2>The middle 50% is the box; the median divides it</h2><div className="box-anatomy-layout"><BoxPlotChart groups={[{ label: "Sample", values: sample }]} title="Quartile Anatomy" label="Value" unit="units" /><div className="box-stat-list"><span><b>Q1</b>{stat.q1.toFixed(1)} · 25th percentile</span><span><b>Median</b>{stat.median.toFixed(1)} · 50th percentile</span><span><b>Q3</b>{stat.q3.toFixed(1)} · 75th percentile</span><span><b>IQR</b>{stat.iqr.toFixed(1)} = Q3 − Q1</span><span><b>Fences</b>{stat.lower.toFixed(1)} to {stat.upper.toFixed(1)}</span></div></div><p className="distribution-warning"><strong>Potential outlier does not mean bad data.</strong> It may be an extreme event, field condition, irrigation response, sensor fault, or entry error.</p></section>;
}

export function FieldDistributionComparison({ pack }: { pack: Pack }) {
  return <section id="field-comparison" className="lesson-card"><p className="lesson-section-label">Multiple distributions</p><h2>Compare typical value, spread, and unusual observations across fields</h2><BoxPlotChart groups={pack.fieldGroups} title="Temperature Distribution by Field" label="Temperature" unit="°C" /><div className="field-observations"><span>Field B has the highest median.</span><span>Field C contains a potential high outlier.</span><span>Compare spread before comparing single readings.</span></div></section>;
}

export function DistributionExplorer({ pack }: { pack: Pack }) {
  const [datasetId, setDatasetId] = useState<DatasetId>("temperature"); const [view, setView] = useState<"histogram" | "boxplot">("histogram"); const [bins, setBins] = useState(5); const dataset = pack.datasets.find((item) => item.id === datasetId) ?? pack.datasets[0]; const variable = dataset.id === "moisture" ? "moisture" : dataset.id;
  const code = view === "histogram" ? `plt.hist(${variable}, bins=${bins})\nplt.xlabel("${dataset.label} (${dataset.unit})")\nplt.ylabel("Frequency")\nplt.show()` : `plt.boxplot(${variable})\nplt.ylabel("${dataset.label} (${dataset.unit})")\nplt.show()`;
  return <section id="distribution-explorer" className="lesson-card"><p className="lesson-section-label">Interactive Farm Sensor Distribution Explorer</p><h2>Switch dataset and summary view</h2><div className="distribution-controls"><label>Dataset<select aria-label="Distribution dataset" value={datasetId} onChange={(event) => setDatasetId(event.target.value as DatasetId)}>{pack.datasets.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>Visualization<select aria-label="Distribution visualization" value={view} onChange={(event) => setView(event.target.value as typeof view)}><option value="histogram">Histogram</option><option value="boxplot">Box Plot</option></select></label>{view === "histogram" && <div className="distribution-bin-buttons"><span>Bins: {bins}</span>{[5, 10, 15].map((value) => <button type="button" aria-pressed={bins === value} onClick={() => setBins(value)} key={value}>{value}</button>)}</div>}</div>{view === "histogram" ? <HistogramChart values={dataset.values} bins={bins} title={`${dataset.label} Distribution`} label={dataset.label} unit={dataset.unit} /> : <BoxPlotChart groups={[{ label: dataset.label, values: dataset.values }]} title={`${dataset.label} Summary`} label={dataset.label} unit={dataset.unit} />}<Tile className="distribution-generated-code"><CodeSnippet type="multi" feedback="Copied">{code}</CodeSnippet><p>{dataset.interpretation}</p></Tile></section>;
}

export function OutlierDetective({ pack }: { pack: Pack }) {
  const [choice, setChoice] = useState<number | null>(null); const options = [45, 50, 90, 53]; const correct = choice === 90; const stat = summarizeBox(pack.outlierData);
  return <section id="outlier-detective" className="lesson-card"><p className="lesson-section-label">Interactive Outlier Detective</p><h2>Which observation falls beyond the IQR fence?</h2><BoxPlotChart groups={[{ label: "Moisture", values: pack.outlierData }]} title="Soil Moisture Outlier Investigation" label="Soil Moisture" unit="%" /><div className="outlier-options">{options.map((value) => <button type="button" aria-pressed={choice === value} onClick={() => setChoice(value)} key={value}>{value}</button>)}</div>{choice !== null && <div className={correct ? "outlier-feedback is-correct" : "outlier-feedback is-incorrect"} aria-live="polite"><strong>{correct ? "90 is the potential outlier." : `${choice} remains inside the whisker range.`}</strong>{correct ? <p>Upper fence: {stat.upper.toFixed(1)}. Investigate sensor error, heavy rainfall, irrigation, or an extreme field condition before deciding what to do.</p> : <p>Compare the point with the upper fence, not only with the median.</p>}</div>}<p className="distribution-warning"><strong>Investigate, do not automatically delete.</strong> Statistical rarity and data invalidity are different claims.</p></section>;
}

export function BinExplorer({ pack }: { pack: Pack }) {
  const [bins, setBins] = useState(5); const data = pack.datasets[0]; const message = bins <= 4 ? "Few bins give a broad summary and may hide detail." : bins >= 11 ? "Many bins reveal detail but can make a small dataset look noisy." : "A moderate bin count balances concentration and detail.";
  return <section id="bin-explorer" className="lesson-card"><p className="lesson-section-label">Interactive Bin Explorer</p><h2>Bin choice changes the appearance—not the underlying readings</h2><div className="bin-slider"><span>Bins: <b>{bins}</b></span><button type="button" aria-label="Decrease bins" disabled={bins === 3} onClick={() => setBins((value) => Math.max(3, value - 1))}>−</button><input aria-label="Histogram bin count" type="range" min="3" max="15" value={bins} onChange={(event) => setBins(Number(event.target.value))} /><button type="button" aria-label="Increase bins" disabled={bins === 15} onClick={() => setBins((value) => Math.min(15, value + 1))}>+</button></div><HistogramChart values={data.values} bins={bins} title={`${bins}-Bin Temperature Histogram`} label={data.label} unit={data.unit} /><p className="bin-interpretation" aria-live="polite">{message}</p></section>;
}

export function DistributionMistakes({ mistakes }: { mistakes: Pack["commonMistakes"] }) { return <section id="distribution-mistakes" className="lesson-card"><p className="lesson-section-label">Common mistakes</p><h2>A statistical flag still needs context</h2><div className="distribution-mistake-grid">{mistakes.map((item) => <Tile key={item.title}><strong>{item.title}</strong><code>{item.code}</code><p>{item.explanation}</p></Tile>)}</div></section>; }
export function DistributionQuickReference({ rows }: { rows: Pack["quickReference"] }) { return <section id="distribution-reference" className="lesson-card"><p className="lesson-section-label">Quick reference and decision map</p><h2>Shape and frequency, or compact summary?</h2><div className="distribution-reference-grid">{rows.map((row) => <Tile key={row.task}><span>{row.task}</span><code>{row.code}</code><strong>{row.meaning}</strong></Tile>)}</div></section>; }
