import { summarizeBox } from "@/lib/distribution-statistics";

export function HistogramChart({ values, bins, title, label, unit }: { values: number[]; bins: number; title: string; label: string; unit: string }) {
  const width = 680; const height = 320; const left = 64; const right = 24; const top = 38; const bottom = 54; const min = Math.min(...values); const max = Math.max(...values); const binWidth = (max - min || 1) / bins; const counts = Array.from({ length: bins }, () => 0); values.forEach((value) => { const index = Math.min(Math.floor((value - min) / binWidth), bins - 1); counts[index] += 1; }); const maxCount = Math.max(...counts, 1); const slot = (width - left - right) / bins; const py = (value: number) => top + (maxCount - value) * ((height - top - bottom) / maxCount);
  return <div className="distribution-chart-shell"><svg className="distribution-chart histogram-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${title}. ${bins} bins; maximum frequency ${maxCount}.`}><title>{title}</title><desc>{values.length} {label.toLowerCase()} readings grouped into {bins} numerical intervals.</desc><line className="dist-axis" x1={left} x2={left} y1={top} y2={height - bottom} /><line className="dist-axis" x1={left} x2={width - right} y1={height - bottom} y2={height - bottom} />{Array.from({ length: maxCount + 1 }, (_, tick) => <g key={tick}><line className="dist-grid" x1={left} x2={width - right} y1={py(tick)} y2={py(tick)} /><text className="dist-tick" x={left - 9} y={py(tick) + 4} textAnchor="end">{tick}</text></g>)}{counts.map((count, index) => <g key={index}><rect className="hist-bar" x={left + index * slot + 1} y={py(count)} width={Math.max(slot - 2, 1)} height={height - bottom - py(count)} /><text className="dist-tick" x={left + (index + .5) * slot} y={height - bottom + 18} textAnchor="middle">{(min + index * binWidth).toFixed(max - min < 20 ? 1 : 0)}</text></g>)}<text className="dist-title" x={left} y="22">{title}</text><text className="dist-label" data-axis="x" x={(left + width - right) / 2} y={height - 10} textAnchor="middle">{label} ({unit}) ranges</text><text className="dist-label" data-axis="y" transform={`translate(16 ${(top + height - bottom) / 2}) rotate(-90)`} textAnchor="middle">Frequency</text></svg></div>;
}

export function BoxPlotChart({ groups, title, label, unit }: { groups: Array<{ label: string; values: number[] }>; title: string; label: string; unit: string }) {
  const width = 680; const height = 330; const left = 64; const right = 24; const top = 38; const bottom = 58; const all = groups.flatMap((group) => group.values); const stats = groups.map((group) => summarizeBox(group.values)); const min = Math.min(...all); const max = Math.max(...all); const pad = Math.max((max - min) * .1, 1); const low = min - pad; const high = max + pad; const py = (value: number) => top + (high - value) * ((height - top - bottom) / (high - low)); const slot = (width - left - right) / groups.length; const ticks = Array.from({ length: 5 }, (_, index) => low + index * ((high - low) / 4));
  return <div className="distribution-chart-shell"><svg className="distribution-chart boxplot-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${title}. ${groups.length} box plot${groups.length > 1 ? "s" : ""}; ${stats.reduce((sum, item) => sum + item.outliers.length, 0)} potential outliers.`}><title>{title}</title><desc>Box plots show Q1, median, Q3, whiskers, and potential outliers.</desc>{ticks.map((tick) => <g key={tick}><line className="dist-grid" x1={left} x2={width - right} y1={py(tick)} y2={py(tick)} /><text className="dist-tick" x={left - 9} y={py(tick) + 4} textAnchor="end">{tick.toFixed(1)}</text></g>)}<line className="dist-axis" x1={left} x2={left} y1={top} y2={height - bottom} /><line className="dist-axis" x1={left} x2={width - right} y1={height - bottom} y2={height - bottom} />{groups.map((group, index) => { const stat = stats[index]; const cx = left + (index + .5) * slot; const boxWidth = Math.min(slot * .46, 90); return <g className="box-group" key={group.label}><line className="box-whisker" x1={cx} x2={cx} y1={py(stat.max)} y2={py(stat.min)} /><line className="box-whisker" x1={cx - boxWidth * .3} x2={cx + boxWidth * .3} y1={py(stat.max)} y2={py(stat.max)} /><line className="box-whisker" x1={cx - boxWidth * .3} x2={cx + boxWidth * .3} y1={py(stat.min)} y2={py(stat.min)} /><rect className="box-body" x={cx - boxWidth / 2} y={py(stat.q3)} width={boxWidth} height={py(stat.q1) - py(stat.q3)} /><line className="box-median" x1={cx - boxWidth / 2} x2={cx + boxWidth / 2} y1={py(stat.median)} y2={py(stat.median)} />{stat.outliers.map((value, outlierIndex) => <circle className="box-outlier" cx={cx} cy={py(value)} r="6" key={`${value}-${outlierIndex}`} />)}<text className="dist-tick" x={cx} y={height - bottom + 20} textAnchor="middle">{group.label}</text></g>; })}<text className="dist-title" x={left} y="22">{title}</text><text className="dist-label" data-axis="x" x={(left + width - right) / 2} y={height - 10} textAnchor="middle">Field / dataset</text><text className="dist-label" data-axis="y" transform={`translate(16 ${(top + height - bottom) / 2}) rotate(-90)`} textAnchor="middle">{label} ({unit})</text></svg></div>;
}
