import { CourseBreadcrumb } from "@/components/course/CourseBreadcrumb";
import { PreviousNextNavigation } from "@/components/course/PreviousNextNavigation";
import { AgritechTrendExplorer, CodeToChartExplorer, FigureAxesConcept, MatplotlibMistakes, MatplotlibQuickReference, MatplotlibWorkflow, MultipleSeriesCaution, VisualizationPurpose } from "@/components/learning/MatplotlibBasicsLearningBlocks";
import { CodePlayground } from "@/components/learning/CodePlayground";
import { LessonHero } from "@/components/learning/LessonHero";
import { IndustryInsightCard, KeyTakeawaysCard, LearningObjectivesCard, PracticeCard, QuizCard, SummaryCard, WhatsNextCard } from "@/components/learning/LearningBlocks";
import { DebugChallengeCollection } from "@/components/learning/ProblemSolvingLearningBlocks";
import type { LessonDocument } from "@/types/content";
import type { CourseLesson, CourseModule } from "@/types/course";

const outline = [["objectives", "Objectives"], ["visualization-purpose", "Why visualize"], ["figure-axes", "Figure and Axes"], ["trend-explorer", "Trend explorer"], ["code-chart-explorer", "Code to chart"], ["multiple-series", "Multiple series"], ["matplotlib-workflow", "Workflow"], ["common-mistakes", "Mistakes"], ["playground", "Code runner"], ["practice", "Practice"], ["debug-challenge", "Debug"], ["quiz", "Quiz"], ["quick-reference", "Quick reference"], ["summary", "Summary"], ["whats-next", "What's next"]] as const;

export function MatplotlibBasicsLessonRenderer({ lesson, courseLesson, module, previous, next }: { lesson: LessonDocument; courseLesson: CourseLesson; module: CourseModule; previous: CourseLesson | null; next: CourseLesson | null }) {
  const pack = lesson.developmentPack;
  if (!pack || pack.kind !== "matplotlib-introduction-basics") return null;
  return <article className="published-lesson matplotlib-basics-pack"><CourseBreadcrumb module={module} lesson={courseLesson} /><LessonHero eyebrow={`Module ${module.index} · Lesson ${lesson.number}`} title={lesson.title} summary={lesson.summary} icon={module.icon} level={lesson.level} durationMinutes={lesson.durationMinutes} prerequisite={pack.prerequisite} /><div className="published-lesson-layout"><div className="published-lesson-flow"><LearningObjectivesCard id="objectives" objectives={lesson.objectives} /><section className="lesson-card"><p className="lesson-section-label">From measurements to meaning</p><h2>Patterns become visible before they become conclusions</h2><p>{pack.storyHook}</p><div className="matplotlib-story-values"><span>Temperature rises</span><span>Yield rises</span><span>Yield later falls</span><strong>Ask why</strong></div></section><VisualizationPurpose /><FigureAxesConcept /><AgritechTrendExplorer pack={pack} /><CodeToChartExplorer /><MultipleSeriesCaution /><MatplotlibWorkflow steps={pack.workflow} /><MatplotlibMistakes mistakes={pack.commonMistakes} /><IndustryInsightCard id="industry-insight" section={lesson.industryMotivation} /><CodePlayground id="playground" content={lesson.playground} className="matplotlib-playground" /><PracticeCard id="practice" tasks={lesson.practice} /><DebugChallengeCollection challenges={pack.debugChallenges} /><QuizCard id="quiz" quiz={lesson.quiz} /><MatplotlibQuickReference rows={pack.quickReference} /><SummaryCard id="summary" section={lesson.summarySection} /><KeyTakeawaysCard id="key-takeaways" items={lesson.keyTakeaways} /><WhatsNextCard id="whats-next" section={lesson.whatsNext} /></div><aside className="lesson-outline published-lesson-outline" aria-label="On this page"><p>On this page</p>{outline.map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</aside></div><PreviousNextNavigation previous={previous} next={next} /></article>;
}
