import { CodeSnippet, Tile } from "@carbon/react";
import { useMemo, useState } from "react";
import { StyledLineChart, SubplotFigure } from "@/components/learning/MatplotlibCustomizationRenderer";
import type { MatplotlibCustomizationDevelopmentPack } from "@/types/content";

const baseConfig = { title: "Weekly Farm Temperature", xLabel: "Day", yLabel: "Temperature (°C)", marker: "o", lineStyle: "-", lineWidth: 2, alpha: .8, showGrid: true, showLegend: true, legendPosition: "upper right" };

export function CustomizationConcept() { return <section className="lesson-card" id="customization-concept"><p className="lesson-section-label">Purpose before decoration</p><h2>Customization should answer a readability problem</h2><div className="customization-flow"><Tile><strong>Basic chart</strong><span>Data exists</span></Tile><Tile><strong>Meaningful context</strong><span>Titles + units + labels</span></Tile><Tile><strong>Purposeful emphasis</strong><span>Markers + grid + legend</span></Tile><Tile><strong>Clear visual</strong><span>Question becomes inspectable</span></Tile></div><p className="style-rule">A chart should make sense even when viewed without its surrounding paragraph.</p></section>; }

export function StyleVocabulary() { return <section className="lesson-card" id="style-vocabulary"><p className="lesson-section-label">Line vocabulary</p><h2>Combine a small set of keyword arguments</h2><div className="style-property-grid">{[["color=", "series identity"], ["marker=", "observations"], ["linestyle=", "line pattern"], ["linewidth=", "emphasis"], ["alpha=", "transparency"], ["label=", "legend entry"]].map(([a,b]) => <Tile key={a}><code>{a}</code><span>{b}</span></Tile>)}</div><CodeSnippet type="multi">{`plt.figure(figsize=(8, 5))\nplt.plot(days, temperature, color="green", marker="o",\n         linestyle="--", linewidth=2, alpha=0.8,\n         label="Temperature")`}</CodeSnippet></section>; }

export function LabelsLimitsTicks() { return <section className="lesson-card" id="labels-limits"><p className="lesson-section-label">Context and scale</p><h2>Labels identify; limits and ticks frame the evidence</h2><div className="labels-comparison"><Tile><strong>Weak</strong><code>xlabel("X")</code><code>ylabel("Y")</code><span>Variables and units are unknown.</span></Tile><Tile><strong>Useful</strong><code>xlabel("Day")</code><code>ylabel("Temperature (°C)")</code><span>The chart can stand alone.</span></Tile></div><CodeSnippet type="multi">{`plt.xlim(1, 7)\nplt.ylim(20, 40)\nplt.xticks(\n    [1, 2, 3, 4, 5, 6, 7],\n    ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]\n)`}</CodeSnippet><p className="axis-caution"><strong>Scale caution:</strong> limits can clarify a relevant range, but a narrow range can also exaggerate small differences.</p></section>; }

export function FigureAxesSubplots() { return <section className="lesson-card" id="figure-axes"><p className="lesson-section-label">Object-oriented Matplotlib</p><h2>Figure is the canvas; Axes are the plotting areas</h2><div className="figure-axes-model"><div><strong>Figure</strong><span>Entire canvas</span><div className="axes-mini-grid"><span>Axes [0, 0]</span><span>Axes [0, 1]</span><span>Axes [1, 0]</span><span>Axes [1, 1]</span></div></div><CodeSnippet type="multi">{`fig, axes = plt.subplots(2, 2, figsize=(10, 7))\naxes[0, 0].plot(days, temperature)\naxes[0, 1].plot(days, moisture)\naxes[1, 0].bar(days, rainfall)\naxes[1, 1].plot(days, yield_data)\nplt.tight_layout()`}</CodeSnippet></div><p className="style-rule"><code>tight_layout()</code> reduces overlap; <code>sharex=True</code> aligns time-based panels on one x scale.</p></section>; }

export function FarmChartDesigner({ pack }: { pack: MatplotlibCustomizationDevelopmentPack }) {
  const [config, setConfig] = useState(baseConfig); const temperature = pack.data.variables[0];
  const set = <K extends keyof typeof config>(key: K, value: (typeof config)[K]) => setConfig(current => ({ ...current, [key]: value }));
  const code = `plt.figure(figsize=(8, 5))\nplt.plot(days, temperature, marker="${config.marker}", linestyle="${config.lineStyle}",\n         linewidth=${config.lineWidth}, alpha=${config.alpha}, label="Temperature")\nplt.title("${config.title}")\nplt.xlabel("${config.xLabel}")\nplt.ylabel("${config.yLabel}")${config.showGrid ? `\nplt.grid(linestyle="--", alpha=0.5)` : ""}${config.showLegend ? `\nplt.legend(loc="${config.legendPosition}")` : ""}\nplt.show()`;
  return <section className="lesson-card" id="chart-designer"><p className="lesson-section-label">Interactive · Farm Chart Designer</p><h2>Change the communication layer</h2><div className="designer-controls"><label>Title<input value={config.title} onChange={e => set("title", e.target.value)} /></label><label>X label<input value={config.xLabel} onChange={e => set("xLabel", e.target.value)} /></label><label>Y label<input value={config.yLabel} onChange={e => set("yLabel", e.target.value)} /></label><label>Marker<select value={config.marker} onChange={e => set("marker", e.target.value)}>{pack.markers.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label>Line style<select value={config.lineStyle} onChange={e => set("lineStyle", e.target.value)}>{pack.lineStyles.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label>Legend position<select value={config.legendPosition} onChange={e => set("legendPosition", e.target.value)}>{pack.legendPositions.map(item => <option key={item}>{item}</option>)}</select></label><label>Line width <output>{config.lineWidth}</output><input type="range" min="1" max="6" step="1" value={config.lineWidth} onChange={e => set("lineWidth", Number(e.target.value))} /></label><label>Alpha <output>{config.alpha.toFixed(1)}</output><input type="range" min="0.2" max="1" step="0.1" value={config.alpha} onChange={e => set("alpha", Number(e.target.value))} /></label><div className="designer-checks"><label><input type="checkbox" checked={config.showGrid} onChange={e => set("showGrid", e.target.checked)} /> Show grid</label><label><input type="checkbox" checked={config.showLegend} onChange={e => set("showLegend", e.target.checked)} /> Show legend</label></div></div><StyledLineChart days={pack.data.days} values={temperature.values} config={config} /><div className="style-generated-code"><CodeSnippet type="multi">{code}</CodeSnippet><p>Styling changes the presentation, not the underlying seven readings.</p></div></section>;
}

export function SubplotBuilder({ pack }: { pack: MatplotlibCustomizationDevelopmentPack }) {
  const [rows, setRows] = useState(2), [columns, setColumns] = useState(2), [shareX, setShareX] = useState(true), [selected, setSelected] = useState<string[]>(pack.data.variables.map(item => item.id));
  const visible = selected.slice(0, rows * columns); const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  const code = useMemo(() => { const lines = [`fig, axes = plt.subplots(${rows}, ${columns}, figsize=(10, 7)${shareX ? ", sharex=True" : ""})`]; visible.forEach((id, index) => { const item = pack.data.variables.find(variable => variable.id === id)!; const ref = rows === 1 && columns === 1 ? "axes" : rows === 1 || columns === 1 ? `axes[${index}]` : `axes[${Math.floor(index / columns)}, ${index % columns}]`; lines.push(`${ref}.${item.chart === "bar" ? "bar" : "plot"}(days, ${id})`, `${ref}.set_title("${item.label}")`); }); lines.push("plt.tight_layout()", "plt.show()"); return lines.join("\n"); }, [columns, pack.data.variables, rows, shareX, visible]);
  return <section className="lesson-card" id="subplot-builder"><p className="lesson-section-label">Interactive · Subplot Builder</p><h2>Organize related farm variables in one Figure</h2><div className="subplot-controls"><label>Rows<select value={rows} onChange={e => setRows(Number(e.target.value))}><option>1</option><option>2</option></select></label><label>Columns<select value={columns} onChange={e => setColumns(Number(e.target.value))}><option>1</option><option>2</option></select></label><label className="share-check"><input type="checkbox" checked={shareX} onChange={e => setShareX(e.target.checked)} /> Share x-axis</label></div><div className="variable-toggles">{pack.data.variables.map(item => <button type="button" aria-pressed={selected.includes(item.id)} key={item.id} onClick={() => toggle(item.id)}>{item.label}</button>)}</div><SubplotFigure pack={pack} selected={visible} rows={rows} columns={columns} shareX={shareX} /><div className="style-generated-code"><CodeSnippet type="multi">{code}</CodeSnippet><p>{visible.length} selected variable{visible.length === 1 ? "" : "s"} fit into {rows * columns} available Axes.</p></div></section>;
}

const repairOptions = ["Meaningful title", "Axis labels with units", "Series legend", "Readable figure size", "Useful grid"];
export function FixBadChart({ pack }: { pack: MatplotlibCustomizationDevelopmentPack }) {
  const [selected, setSelected] = useState<string[]>([]); const fixed = selected.length === repairOptions.length; const config = fixed ? baseConfig : { ...baseConfig, title: "", xLabel: "X", yLabel: "Y", lineWidth: 1, showGrid: false, showLegend: false };
  const toggle = (item: string) => setSelected(current => current.includes(item) ? current.filter(value => value !== item) : [...current, item]);
  return <section className="lesson-card" id="fix-chart"><p className="lesson-section-label">Interactive · Fix the Bad Chart</p><h2>Repair meaning before decoration</h2><div className="repair-options">{repairOptions.map(item => <label key={item}><input type="checkbox" checked={selected.includes(item)} onChange={() => toggle(item)} /> {item}</label>)}</div><StyledLineChart compact days={pack.data.days} values={pack.data.variables[0].values} config={config} /><div className={`repair-feedback ${fixed ? "is-complete" : ""}`}><strong>{fixed ? "Clear chart restored" : `${selected.length} of ${repairOptions.length} communication fixes selected`}</strong><span>{fixed ? "The title, units, legend, size, and restrained grid now help the reader." : "Select every change that makes the chart independently understandable."}</span></div></section>;
}

export function CustomizationMistakes({ pack }: { pack: MatplotlibCustomizationDevelopmentPack }) { return <section className="lesson-card" id="customization-mistakes"><p className="lesson-section-label">Common mistakes</p><h2>More styling is not automatically better</h2><div className="style-mistake-grid">{pack.commonMistakes.map(item => <Tile key={item.title}><strong>{item.title}</strong><code>{item.code}</code><p>{item.explanation}</p></Tile>)}</div></section>; }
export function CustomizationReference({ pack }: { pack: MatplotlibCustomizationDevelopmentPack }) { return <section className="lesson-card" id="customization-reference"><p className="lesson-section-label">Quick reference</p><h2>Communication and layout tools</h2><div className="style-reference-grid">{pack.quickReference.map(item => <Tile key={item.task}><strong>{item.task}</strong><code>{item.code}</code><span>{item.meaning}</span></Tile>)}</div></section>; }
