import { CourseBreadcrumb } from "@/components/course/CourseBreadcrumb";
import { PreviousNextNavigation } from "@/components/course/PreviousNextNavigation";
import { CodePlayground } from "@/components/learning/CodePlayground";
import { DataAnalysisQuickReference, FarmRanking, SmartFarmAnalyzer, SmartFarmDataFilter, SmartFarmDataset, TransformationPanel } from "@/components/learning/NumpyDataAnalysisLearningBlocks";
import { LessonHero } from "@/components/learning/LessonHero";
import { IndustryInsightCard, KeyTakeawaysCard, LearningObjectivesCard, PracticeCard, QuizCard, SummaryCard, WhatsNextCard } from "@/components/learning/LearningBlocks";
import { DebugChallengeCollection } from "@/components/learning/ProblemSolvingLearningBlocks";
import type { LessonDocument } from "@/types/content";
import type { CourseLesson, CourseModule } from "@/types/course";

const outline = [["objectives", "Objectives"], ["dataset", "Dataset"], ["analyzer", "Analyzer"], ["filter", "Filter"], ["ranking", "Ranking"], ["transform", "Transform"], ["playground", "Code runner"], ["practice", "Practice"], ["debug-challenge", "Debug"], ["quiz", "Quiz"], ["quick-reference", "Cheat sheet"], ["summary", "Summary"], ["whats-next", "What's next"]] as const;

export function NumpyDataAnalysisLessonRenderer({ lesson, courseLesson, module, previous, next }: { lesson: LessonDocument; courseLesson: CourseLesson; module: CourseModule; previous: CourseLesson | null; next: CourseLesson | null }) {
  const pack = lesson.developmentPack;
  if (!pack || pack.kind !== "numpy-data-analysis-capstone") return null;
  return <article className="published-lesson numpy-introduction-pack numpy-data-analysis-pack"><CourseBreadcrumb module={module} lesson={courseLesson} /><LessonHero eyebrow={`Module ${module.index} · Lesson ${lesson.number}`} title={lesson.title} summary={lesson.summary} icon={module.icon} level={lesson.level} durationMinutes={lesson.durationMinutes} prerequisite={pack.prerequisite} /><div className="published-lesson-layout"><div className="published-lesson-flow"><LearningObjectivesCard id="objectives" objectives={lesson.objectives} /><section className="lesson-card"><p className="lesson-section-label">Capstone problem</p><h2>Turn one farm table into operational decisions</h2><p>{pack.storyHook}</p><div className="numpy-analysis-flow"><span>Select</span><span>Analyze</span><span>Filter</span><span>Rank</span><span>Decide</span></div></section><SmartFarmDataset content={pack.dataset} /><SmartFarmAnalyzer dataset={pack.dataset} analyses={pack.analyses} /><SmartFarmDataFilter dataset={pack.dataset} columns={pack.filterColumns} /><FarmRanking dataset={pack.dataset} /><TransformationPanel normalization={pack.normalization} metric={pack.derivedMetric} dataset={pack.dataset} /><IndustryInsightCard id="industry-insight" section={lesson.industryMotivation} /><CodePlayground id="playground" content={lesson.playground} className="numpy-playground" /><PracticeCard id="practice" tasks={lesson.practice} /><DebugChallengeCollection challenges={pack.debugChallenges} /><QuizCard id="quiz" quiz={lesson.quiz} /><DataAnalysisQuickReference rows={pack.quickReference} /><SummaryCard id="summary" section={lesson.summarySection} /><KeyTakeawaysCard id="key-takeaways" items={lesson.keyTakeaways} /><WhatsNextCard id="whats-next" section={lesson.whatsNext} /></div><aside className="lesson-outline published-lesson-outline" aria-label="On this page"><p>On this page</p>{outline.map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</aside></div><PreviousNextNavigation previous={previous} next={next} /></article>;
}
