import { useMemo, useState } from "react";
import { CodeSnippet, NumberInput, Tile } from "@carbon/react";
import { Checkmark, Close, Filter, Search, SortAscending, SortDescending } from "@carbon/icons-react";
import { ArrayGrid } from "@/components/learning/NumpyIntroductionLearningBlocks";
import type { NumpyFilteringDevelopmentPack } from "@/types/content";

type Pack = NumpyFilteringDevelopmentPack;

export function SortingVisualizer({ content }: { content: Pack["sorting"] }) {
  const [mode, setMode] = useState<"original" | "ascending" | "descending" | "indices">("ascending");
  const output = mode === "original" ? content.values : mode === "ascending" ? content.ascending : mode === "descending" ? content.descending : content.indices;
  const code = mode === "original" ? "moisture" : mode === "ascending" ? "np.sort(moisture)" : mode === "descending" ? "np.sort(moisture)[::-1]" : "np.argsort(moisture)";
  return <section id="sorting" className="lesson-card"><p className="lesson-section-label">Interactive Sorting Visualizer</p><h2>Sort values—or ask for the positions that sort them</h2><ArrayGrid values={[content.values]} name="original moisture" /><div className="numpy-sort-controls" role="tablist" aria-label="Sorting mode"><button type="button" role="tab" aria-selected={mode === "original"} className={mode === "original" ? "is-active" : ""} onClick={() => setMode("original")}>Original</button><button type="button" role="tab" aria-selected={mode === "ascending"} className={mode === "ascending" ? "is-active" : ""} onClick={() => setMode("ascending")}><SortAscending size={18} />Ascending</button><button type="button" role="tab" aria-selected={mode === "descending"} className={mode === "descending" ? "is-active" : ""} onClick={() => setMode("descending")}><SortDescending size={18} />Descending</button><button type="button" role="tab" aria-selected={mode === "indices"} className={mode === "indices" ? "is-active" : ""} onClick={() => setMode("indices")}><Search size={18} />Show indices</button></div><div className={`numpy-sort-output is-${mode}`}><ArrayGrid values={[output]} name={mode === "indices" ? "argsort indices" : `${mode} result`} /><CodeSnippet type="single" feedback="Copied">{code}</CodeSnippet><p>{mode === "indices" ? "These original positions produce ascending order: 38→[2], 42→[0], 47→[4], 55→[1], 61→[3]." : mode === "descending" ? "NumPy sorts ascending, then [::-1] reverses the sorted copy." : mode === "ascending" ? "np.sort() returns a new sorted array; the original stays unchanged." : "The original order is preserved until an in-place sort is requested."}</p></div><div className="numpy-sort-distinction"><Tile><code>{content.copyCode}</code><strong>Sorted copy</strong><span>Original remains unchanged</span></Tile><Tile><code>{content.inPlaceCode}</code><strong>In-place sort</strong><span>Original array changes</span></Tile></div></section>;
}

export function BooleanMaskVisualizer({ content }: { content: Pack["where"] }) {
  const [threshold, setThreshold] = useState(30);
  const mask = content.values.map((value) => value > threshold);
  const filtered = content.values.filter((_value, index) => mask[index]);
  const indices = mask.flatMap((keep, index) => keep ? [index] : []);
  const code = `temperature[temperature > ${threshold}]`;
  return <section id="boolean-mask" className="lesson-card"><p className="lesson-section-label">Interactive Boolean Mask Visualizer</p><h2>True keeps a reading; False removes it</h2><div className="numpy-mask-threshold"><NumberInput id="mask-threshold" label="Keep values greater than" value={threshold} onChange={(_event, state) => setThreshold(Number(state.value))} /></div><div className="numpy-mask-pipeline"><div><span>Values</span><div className="numpy-mask-row">{content.values.map((value, index) => <strong key={index}>{value}</strong>)}</div></div><div><span>Condition &gt; {threshold}</span><div className="numpy-mask-row">{mask.map((keep, index) => <b className={keep ? "is-true" : "is-false"} key={index}>{keep ? "T" : "F"}</b>)}</div></div><div><span>Filtered</span><div className="numpy-mask-row is-filtered">{filtered.length ? filtered.map((value, index) => <strong key={index}>{value}</strong>) : <em>No matches</em>}</div></div></div><Tile className="numpy-where-result"><div><code>{code}</code><strong>[{filtered.join("  ")}]</strong></div><div><code>{`np.where(temperature > ${threshold})[0]`}</code><strong>[{indices.join("  ")}]</strong></div></Tile></section>;
}

export function MultipleConditionsPanel({ conditions, anyAll, where }: { conditions: Pack["conditions"]; anyAll: Pack["anyAll"]; where: Pack["where"] }) {
  const [mode, setMode] = useState<"and" | "or">("and");
  const active = conditions.find((item) => item.id === mode) ?? conditions[0];
  return <section id="conditions" className="lesson-card"><p className="lesson-section-label">Multiple conditions, any, and all</p><h2>Combine element-wise questions with &amp; and |</h2><div className="numpy-condition-tabs" role="tablist" aria-label="Condition operator"><button type="button" role="tab" aria-selected={mode === "and"} className={mode === "and" ? "is-active" : ""} onClick={() => setMode("and")}>&amp; · both conditions</button><button type="button" role="tab" aria-selected={mode === "or"} className={mode === "or" ? "is-active" : ""} onClick={() => setMode("or")}>| · either condition</button></div><div className="numpy-condition-flow"><ArrayGrid values={[active.values]} name="temperature" /><div><code>{active.code}</code><div className="numpy-mask-row">{active.mask.map((keep, index) => <b className={keep ? "is-true" : "is-false"} key={index}>{keep ? "T" : "F"}</b>)}</div></div><ArrayGrid values={[active.result]} name="filtered" /></div><p>{active.meaning} Use parentheses around each comparison; Python's <code>and</code> and <code>or</code> are not element-wise NumPy operators.</p><div className="numpy-any-all-grid">{anyAll.map((item) => <Tile key={item.code}>{item.function === "np.any" ? <Checkmark size={20} /> : item.result ? <Checkmark size={20} /> : <Close size={20} />}<code>{item.code}</code><strong>{String(item.result)}</strong><span>{item.meaning}</span></Tile>)}</div><Tile className="numpy-replacement-note"><code>{where.replacementCode}</code><strong>[{where.replacement.join("  ")}]</strong><span><code>np.where(condition, true_value, false_value)</code> can create simple numerical labels.</span></Tile></section>;
}

export function IrrigationDecisionPanel({ content }: { content: Pack["irrigation"] }) {
  return <section id="irrigation" className="lesson-card"><p className="lesson-section-label">Agritech irrigation decision</p><h2>Find both the urgent values and their field positions</h2><div className="numpy-irrigation-flow"><ArrayGrid values={[content.values]} name="moisture" /><div><Filter size={24} /><code>{content.condition}</code><div className="numpy-mask-row">{content.mask.map((keep, index) => <b className={keep ? "is-true" : "is-false"} key={index}>{keep ? "T" : "F"}</b>)}</div></div><Tile><span>Readings needing irrigation</span><strong>[{content.filtered.join("  ")}]</strong><span>Field indices</span><strong>[{content.indices.join("  ")}]</strong></Tile></div></section>;
}

type FilterMode = "temperature" | "moisture" | "and" | "or";

export function SmartFarmSensorFilter({ content }: { content: Pack["sensorFilter"] }) {
  const [mode, setMode] = useState<FilterMode>("and");
  const [temperature, setTemperature] = useState(32);
  const [moisture, setMoisture] = useState(30);
  const mask = useMemo(() => content.matrix.map((row) => { const hot = row[0] > temperature; const dry = row[2] < moisture; return mode === "temperature" ? hot : mode === "moisture" ? dry : mode === "and" ? hot && dry : hot || dry; }), [content.matrix, mode, moisture, temperature]);
  const rows = content.matrix.filter((_row, index) => mask[index]);
  const left = `sensor_data[:, 0] > ${temperature}`;
  const right = `sensor_data[:, 2] < ${moisture}`;
  const condition = mode === "temperature" ? left : mode === "moisture" ? right : `(${left}) ${mode === "and" ? "&" : "|"} (${right})`;
  return <section id="farm-filter" className="lesson-card"><p className="lesson-section-label">Interactive Smart Farm Sensor Filter</p><h2>Build a row filter from sensor-column conditions</h2><div className="numpy-filter-controls"><div role="tablist" aria-label="Farm filter mode">{(["temperature", "moisture", "and", "or"] as FilterMode[]).map((item) => <button type="button" role="tab" aria-selected={mode === item} className={mode === item ? "is-active" : ""} onClick={() => setMode(item)} key={item}>{item === "and" ? "AND" : item === "or" ? "OR" : item}</button>)}</div><div><NumberInput id="temperature-filter" label="Temperature greater than" value={temperature} onChange={(_event, state) => setTemperature(Number(state.value))} /><NumberInput id="moisture-filter" label="Moisture less than" value={moisture} onChange={(_event, state) => setMoisture(Number(state.value))} /></div></div><div className="numpy-filter-layout"><div className="numpy-sensor-table"><div className="is-heading"><span>Field</span>{content.columns.map((column) => <strong key={column}>{column}</strong>)}<span>Keep?</span></div>{content.matrix.map((row, rowIndex) => <div className={mask[rowIndex] ? "is-selected" : ""} key={rowIndex}><span>F{rowIndex + 1}</span>{row.map((value, index) => <strong key={index}>{value}</strong>)}<span>{mask[rowIndex] ? "True" : "False"}</span></div>)}</div><Tile className="numpy-filter-summary"><span>Boolean mask</span><strong>[{mask.map((keep) => keep ? "T" : "F").join("  ")}]</strong><span>Rows selected</span><strong>{rows.length}</strong><code>{`sensor_data[${condition}]`}</code></Tile></div><div className="numpy-selected-rows"><span>Selected rows</span>{rows.length ? <ArrayGrid values={rows} name="filtered sensor_data" /> : <em>No rows match this filter.</em>}</div></section>;
}

export function FilteringQuickReference({ rows }: { rows: Pack["quickReference"] }) {
  return <section id="quick-reference" className="lesson-card"><p className="lesson-section-label">Quick reference</p><h2>Sorting, searching, and filtering at a glance</h2><div className="numpy-filter-reference">{rows.map((row) => <Tile key={row.name}><code>{row.name}</code><strong>{row.purpose}</strong><span>{row.example}</span></Tile>)}</div></section>;
}
