import { CourseBreadcrumb } from "@/components/course/CourseBreadcrumb";
import { PreviousNextNavigation } from "@/components/course/PreviousNextNavigation";
import { CodePlayground } from "@/components/learning/CodePlayground";
import { FarmDataFilterLab, LocIlocExplorer, MultiConditionBuilder, PandasSelectionQuickReference, QueryPatternExplorer, SelectionProblemStory } from "@/components/learning/PandasSelectionLearningBlocks";
import { LessonHero } from "@/components/learning/LessonHero";
import { IndustryInsightCard, KeyTakeawaysCard, LearningObjectivesCard, PracticeCard, QuizCard, SummaryCard, WhatsNextCard } from "@/components/learning/LearningBlocks";
import { DebugChallengeCollection } from "@/components/learning/ProblemSolvingLearningBlocks";
import type { LessonDocument } from "@/types/content";
import type { CourseLesson, CourseModule } from "@/types/course";

const outline = [["objectives", "Objectives"], ["dataset", "Farm questions"], ["loc-iloc", "loc vs iloc"], ["filter-lab", "Filter lab"], ["condition-builder", "Conditions"], ["query-patterns", "Query patterns"], ["playground", "Code runner"], ["practice", "Practice"], ["debug-challenge", "Debug"], ["quiz", "Quiz"], ["quick-reference", "Quick reference"], ["summary", "Summary"], ["whats-next", "What's next"]] as const;

export function PandasSelectionLessonRenderer({ lesson, courseLesson, module, previous, next }: { lesson: LessonDocument; courseLesson: CourseLesson; module: CourseModule; previous: CourseLesson | null; next: CourseLesson | null }) {
  const pack = lesson.developmentPack;
  if (!pack || pack.kind !== "pandas-selection-filtering") return null;
  return <article className="published-lesson pandas-series-pack pandas-selection-pack"><CourseBreadcrumb module={module} lesson={courseLesson} /><LessonHero eyebrow={`Module ${module.index} · Lesson ${lesson.number}`} title={lesson.title} summary={lesson.summary} icon={module.icon} level={lesson.level} durationMinutes={lesson.durationMinutes} prerequisite={pack.prerequisite} /><div className="published-lesson-layout"><div className="published-lesson-flow"><LearningObjectivesCard id="objectives" objectives={lesson.objectives} /><section className="lesson-card"><p className="lesson-section-label">From inspection to questions</p><h2>Which records satisfy the farm decision?</h2><p>{pack.storyHook}</p><div className="pandas-story-flow"><span>DataFrame</span><span>Select</span><span>Filter</span><span>Relevant answer</span></div></section><SelectionProblemStory dataset={pack.dataset} /><LocIlocExplorer dataset={pack.dataset} examples={pack.selectionExamples} /><FarmDataFilterLab dataset={pack.dataset} columns={pack.filterColumns} operators={pack.operators} /><MultiConditionBuilder dataset={pack.dataset} columns={pack.filterColumns} operators={pack.operators} /><QueryPatternExplorer examples={pack.queryExamples} /><IndustryInsightCard id="industry-insight" section={lesson.industryMotivation} /><CodePlayground id="playground" content={lesson.playground} className="pandas-playground" /><PracticeCard id="practice" tasks={lesson.practice} /><DebugChallengeCollection challenges={pack.debugChallenges} /><QuizCard id="quiz" quiz={lesson.quiz} /><PandasSelectionQuickReference rows={pack.quickReference} /><SummaryCard id="summary" section={lesson.summarySection} /><KeyTakeawaysCard id="key-takeaways" items={lesson.keyTakeaways} /><WhatsNextCard id="whats-next" section={lesson.whatsNext} /></div><aside className="lesson-outline published-lesson-outline" aria-label="On this page"><p>On this page</p>{outline.map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</aside></div><PreviousNextNavigation previous={previous} next={next} /></article>;
}
