import { useState } from "react";
import { Button, CodeSnippet, Tag, TextInput, Tile, Toggle } from "@carbon/react";
import { ArrowDown, ArrowRight, CheckmarkOutline, FunctionMath, Task, TreeView, WarningAlt } from "@carbon/icons-react";
import { FunctionDebugChallenges } from "@/components/learning/FunctionDefinitionLearningBlocks";
import { FunctionEvolutionPanel } from "@/components/learning/FunctionParameterLearningBlocks";
import { FunctionLifecyclePanel } from "@/components/learning/ReturnValueLearningBlocks";
import { CodeTracePanel } from "@/components/learning/CodeTracePanel";
import type { PlaygroundExecution } from "@/components/learning/usePythonRunner";
import type { RecursionLessonDevelopmentPack } from "@/types/content";

export { FunctionDebugChallenges, FunctionEvolutionPanel, FunctionLifecyclePanel };

export function RecursionStory({ content }: { content: RecursionLessonDevelopmentPack["story"] }) { const children=(parentId?:string)=>content.hierarchy.filter((item)=>item.parentId===parentId);const render=(parentId?:string):React.ReactNode=><ul>{children(parentId).map((item)=><li key={item.id}><Tile><TreeView size={18}/><strong>{item.label}</strong></Tile>{children(item.id).length>0&&render(item.id)}</li>)}</ul>;return <section id="story" className="lesson-card recursion-story" aria-labelledby="recursion-story-title"><p className="lesson-section-label"><TreeView size={16}/> Story continuation</p><h2 id="recursion-story-title">{content.title}</h2><p>{content.body}</p><div className="farm-recursion-tree">{render()}</div><Tile className="recursion-insight"><strong>{content.insight}</strong></Tile></section>; }

export function RecursionConcept({ content }: { content: RecursionLessonDevelopmentPack["definition"] }) { return <section id="recursion-concept" className="lesson-card recursion-concept" aria-labelledby="recursion-concept-title"><p className="lesson-section-label"><FunctionMath size={16}/> What is recursion?</p><h2 id="recursion-concept-title">{content.title}</h2><p>{content.body}</p><blockquote>{content.rule}</blockquote><div className="nesting-doll-flow">{content.analogy.map((item,index)=><div key={item}><Tile><span>{index+1}</span><strong>{item}</strong></Tile>{index<content.analogy.length-1&&<ArrowDown/>}</div>)}</div></section>; }

export function ProblemDecomposition({ content }: { content: RecursionLessonDevelopmentPack["decomposition"] }) { const [active,setActive]=useState(0);return <section id="smaller-problems" className="lesson-card problem-decomposition" aria-labelledby="decomposition-title"><p className="lesson-section-label"><TreeView size={16}/> Smaller versions of the same problem</p><h2 id="decomposition-title">{content.title}</h2><p>{content.body}</p><div className="decomposition-controls"><Button size="sm" kind="secondary" disabled={active===0} onClick={()=>setActive((value)=>value-1)}>Previous</Button><Tag type="blue">{content.problem}</Tag><Button size="sm" disabled={active===content.levels.length-1} onClick={()=>setActive((value)=>value+1)}>Smaller problem</Button></div><ol className="decomposition-levels">{content.levels.map((level,index)=><li key={level.call} className={index===active?"is-active":index<active?"is-complete":""}><span>{index+1}</span><code>{level.call}</code><p>{level.remaining}</p></li>)}</ol></section>; }

export function BaseCaseCard({ content }: { content: RecursionLessonDevelopmentPack["baseCase"] }) { const [enabled,setEnabled]=useState(true);return <section id="base-case" className="lesson-card base-case-card" aria-labelledby="base-case-title"><div className="lesson-card-heading"><div><p className="lesson-section-label"><WarningAlt size={16}/> Base case</p><h2 id="base-case-title">{content.title}</h2><p>{content.body}</p></div><Toggle id="base-case-toggle" labelText="Stopping condition" labelA="Missing" labelB="Enabled" toggled={enabled} onToggle={setEnabled}/></div><CodeSnippet type="multi" feedback="Copied">{enabled?content.safeCode:content.unsafeCode}</CodeSnippet><Tile className={enabled?"is-safe":"is-warning"} aria-live="polite">{enabled?<CheckmarkOutline size={20}/>:<WarningAlt size={20}/>}<div><strong>{enabled?"Reachable stopping condition":"Infinite recursion risk"}</strong><p>{enabled?"The smallest problem returns without creating another call.":content.warning}</p></div></Tile></section>; }

export function RecursiveCaseCard({ content }: { content: RecursionLessonDevelopmentPack["recursiveCase"] }) { return <section id="recursive-case" className="lesson-card recursive-case-card" aria-labelledby="recursive-case-title"><p className="lesson-section-label"><FunctionMath size={16}/> Recursive case</p><h2 id="recursive-case-title">{content.title}</h2><p>{content.body}</p><div className="recursive-progress"><Tile><span>Current problem</span><code>{content.currentProblem}</code></Tile><ArrowRight/><Tile><span>Smaller problem</span><code>{content.smallerProblem}</code></Tile></div><Tile className="movement-rule"><strong>Progress guarantee</strong><p>{content.movementRule}</p></Tile></section>; }

function callValues(start:number,base:number){return Array.from({length:Math.max(0,start-base)+1},(_,index)=>start-index);}

export function RecursionTreeExplorer({ functionName, initialValue, baseValue }: { functionName:string;initialValue:number;baseValue:number }) { const [startText,setStartText]=useState(String(initialValue));const start=Math.min(8,Math.max(baseValue,Number(startText)||baseValue));const values=callValues(start,baseValue);const [phase,setPhase]=useState(0);const total=values.length*2-1;const step=Math.min(phase,total);const descending=step<values.length;const activeIndex=descending?step:Math.max(0,total-step-1);const visible=descending?values.slice(0,activeIndex+1):values.slice(0,activeIndex+1);const active=values[activeIndex];const next=()=>setPhase((value)=>Math.min(total,value+1));const reset=()=>setPhase(0);return <section id="recursion-tree" className="lesson-card recursion-tree-explorer" aria-labelledby="recursion-tree-title"><p className="lesson-section-label"><TreeView size={16}/> Recursion tree explorer</p><h2 id="recursion-tree-title">Watch the problem shrink, then watch the calls return</h2><div className="recursion-tree-controls"><TextInput id="recursion-tree-start" labelText="Starting value (0–8)" type="number" min={baseValue} max={8} value={startText} onChange={(event)=>{setStartText(event.currentTarget.value);setPhase(0);}}/><Button size="sm" kind="secondary" onClick={reset}>Reset</Button><Button size="sm" onClick={next} disabled={phase>=total}>{phase>=total?"Complete":descending?"Next call":"Return one frame"}</Button></div><div className="recursive-tree-nodes" aria-live="polite">{values.map((value,index)=><div key={value} className={index===activeIndex?"is-active":index<visible.length?"is-visible":""} style={{marginInlineStart:`${Math.min(index,6)*1.25}rem`}}><span>{index+1}</span><code>{functionName}({value})</code><Tag type={value===baseValue?"green":index===activeIndex?"purple":"gray"}>{value===baseValue?"Base case":index===activeIndex?(descending?"Current call":"Returning"):"Waiting"}</Tag></div>)}</div><p className="recursion-tree-status">{phase>=total?"Every frame has returned to the main program.":descending?`${functionName}(${active}) is active; the next call receives a smaller value.`:`${functionName}(${active}) resumes and returns during stack unwinding.`}</p></section>; }

export function CallStackAnimator({ content }: { content: RecursionLessonDevelopmentPack["stack"] }) { const values=callValues(content.initialValue,content.baseValue);const [depth,setDepth]=useState(1);const growing=depth<=values.length;const frames=growing?values.slice(0,depth):values.slice(0,Math.max(0,values.length-(depth-values.length)));const max=values.length*2;return <section id="call-stack" className="lesson-card call-stack-animator" aria-labelledby="call-stack-title"><p className="lesson-section-label"><FunctionMath size={16}/> Call stack animator</p><h2 id="call-stack-title">{content.title}</h2><p>{content.body}</p><div className="stack-animator-layout"><div className="stack-frame-column" aria-live="polite">{[...frames].reverse().map((value,index)=><Tile key={value} className={index===0?"is-active":""}><code>{content.functionName}({value})</code><span>{value===content.baseValue?"Base case":"Waiting for smaller call"}</span></Tile>)}{frames.length===0&&<Tile><strong>Main Program</strong><span>Recursive call complete</span></Tile>}</div><div className="stack-controls"><Tag type={growing?"purple":"green"}>{growing?"Stack growing":"Stack unwinding"}</Tag><strong>{frames.length} active frame{frames.length===1?"":"s"}</strong><Button size="sm" onClick={()=>setDepth((value)=>Math.min(max,value+1))} disabled={depth>=max}>{depth>=max?"Complete":growing?"Push next call":"Pop frame"}</Button><Button size="sm" kind="ghost" onClick={()=>setDepth(1)}>Restart</Button></div></div></section>; }

export function BaseCaseDetector({ content }: { content: RecursionLessonDevelopmentPack["detector"] }) { const [active,setActive]=useState(0);const example=content.examples[active];const safe=example.hasBaseCase&&example.movesTowardBase;return <section id="base-case-detector" className="lesson-card base-case-detector" aria-labelledby="detector-title"><p className="lesson-section-label"><WarningAlt size={16}/> Base Case Detector</p><h2 id="detector-title">{content.title}</h2><p>{content.body}</p><div className="detector-tabs">{content.examples.map((item,index)=><Button key={item.label} size="sm" kind={active===index?"primary":"ghost"} onClick={()=>setActive(index)}>{item.label}</Button>)}</div><CodeSnippet type="multi" feedback="Copied">{example.code}</CodeSnippet><div className="detector-checks"><Tile><span>Base case</span><Tag type={example.hasBaseCase?"green":"red"}>{example.hasBaseCase?"Found":"Missing"}</Tag></Tile><Tile><span>Progress toward stop</span><Tag type={example.movesTowardBase?"green":"red"}>{example.movesTowardBase?"Yes":"No"}</Tag></Tile><Tile className={safe?"is-safe":"is-warning"}><strong>{safe?"Safe recursive shape":"Infinite recursion risk"}</strong><p>{example.explanation}</p></Tile></div></section>; }

export function FactorialExplorer({ content }: { content: RecursionLessonDevelopmentPack["factorial"] }) { const [step,setStep]=useState(0);return <section id="factorial" className="lesson-card factorial-explorer" aria-labelledby="factorial-title"><p className="lesson-section-label"><FunctionMath size={16}/> Factorial—only after the mental model</p><h2 id="factorial-title">{content.title}</h2><p>{content.explanation}</p><CodeSnippet type="multi" feedback="Copied">{content.code}</CodeSnippet><div className="factorial-expansion"><div aria-live="polite"><span>Expansion step {step+1}</span><strong>{content.expansion[step]}</strong></div><Button size="sm" kind="secondary" disabled={step===0} onClick={()=>setStep((value)=>value-1)}>Previous</Button><Button size="sm" disabled={step===content.expansion.length-1} onClick={()=>setStep((value)=>value+1)}>Resolve next</Button></div></section>; }

export function LoopRecursionComparator({ content }: { content: RecursionLessonDevelopmentPack["comparison"] }) { return <section id="compare-choose" className="lesson-card loop-recursion-comparator" aria-labelledby="recursion-comparison-title"><p className="lesson-section-label"><TreeView size={16}/> Compare & choose</p><h2 id="recursion-comparison-title">{content.title}</h2><p>{content.body}</p><div tabIndex={0} role="region" aria-label="Loop and recursion comparison"><table><thead><tr><th>Feature</th><th>Loop</th><th>Recursion</th></tr></thead><tbody>{content.rows.map((row)=><tr key={row.feature}><th>{row.feature}</th><td>{row.loop}</td><td>{row.recursion}</td></tr>)}</tbody></table></div></section>; }

export function RecursivePlaygroundSupplement({ execution }: { execution: PlaygroundExecution }) { const active=execution.trace.at(-1);const frames=active?.callStack??["Main Program"];const recursiveFrames=frames.filter((frame)=>frame!=="Main Program");return <div className="recursive-playground-supplement"><section className="live-recursion-stack" aria-labelledby="live-stack-title"><div><h3 id="live-stack-title">Live recursive stack</h3><Tag type="purple">{recursiveFrames.length} calls</Tag></div>{frames.map((frame,index)=><Tile key={`${frame}-${index}`} className={index===frames.length-1?"is-active":""}><span>{index+1}</span><code>{frame}</code></Tile>)}</section><CodeTracePanel execution={execution}/></div>; }

export function RecursionMiniProject({ content }: { content: RecursionLessonDevelopmentPack["miniProject"] }) { return <section id="mini-project" className="lesson-card recursion-mini-project" aria-labelledby="recursion-project-title"><p className="lesson-section-label"><Task size={16}/> Mini project</p><h2 id="recursion-project-title">{content.title}</h2><p>{content.brief}</p><CodeSnippet type="multi" feedback="Copied">{content.starterCode}</CodeSnippet><div className="recursion-project-checklist">{content.deliverables.map((item)=><Tile key={item}><CheckmarkOutline size={16}/><span>{item}</span></Tile>)}</div><Tile className="recursion-project-challenge"><strong>Challenge</strong><p>{content.challenge}</p></Tile></section>; }
