import { useState } from "react";
import { Button, CodeSnippet, Tag, Tile, Toggle } from "@carbon/react";
import { ArrowRight, CheckmarkOutline, DataConnected, FunctionMath, Task, UserData } from "@carbon/icons-react";
import { CallStackPreview, FunctionDebugChallenges } from "@/components/learning/FunctionDefinitionLearningBlocks";
import { FunctionEvolutionPanel } from "@/components/learning/FunctionParameterLearningBlocks";
import { FunctionLifecyclePanel } from "@/components/learning/ReturnValueLearningBlocks";
import { CodeTracePanel } from "@/components/learning/CodeTracePanel";
import type { PlaygroundExecution, PythonTraceVariable } from "@/components/learning/usePythonRunner";
import type { ScopeVariableContent, VariableScopeLessonDevelopmentPack } from "@/types/content";

export { FunctionDebugChallenges, FunctionEvolutionPanel, FunctionLifecyclePanel };
function VariableToken({ variable, selected, onClick }: { variable: ScopeVariableContent; selected?: boolean; onClick?:()=>void }) { return <button type="button" className={`scope-variable-token ${selected?"is-selected":""}`} onClick={onClick}><Tag type={variable.scope==="global"?"blue":"purple"}>{variable.scope}</Tag><code>{variable.name} = {JSON.stringify(variable.value)}</code><span>{variable.owner}</span></button>; }

export function ScopeStory({ content }: { content: VariableScopeLessonDevelopmentPack["story"] }) { return <section id="story" className="lesson-card scope-story" aria-labelledby="scope-story-title"><p className="lesson-section-label"><FunctionMath size={16}/> Story continuation</p><h2 id="scope-story-title">{content.title}</h2><p>{content.body}</p><div className="scope-story-boundaries"><div><span>Entire application</span><VariableToken variable={content.globalVariable}/></div><ArrowRight/><div><span>One irrigation call</span><VariableToken variable={content.localVariable}/></div></div></section>; }
export function ScopeConcept({ content }: { content: VariableScopeLessonDevelopmentPack["definition"] }) { return <section id="scope-concept" className="lesson-card scope-concept" aria-labelledby="scope-concept-title"><p className="lesson-section-label"><DataConnected size={16}/> What is scope?</p><h2 id="scope-concept-title">{content.title}</h2><p>{content.body}</p><div className="scope-analogy">{content.analogy.map((item,index)=><div key={item.title}><Tile><Tag type={index===0?"blue":"purple"}>{item.scope}</Tag><strong>{item.title}</strong><span>{item.access}</span></Tile>{index<content.analogy.length-1&&<ArrowRight/>}</div>)}</div></section>; }
export function LocalScopeCard({ content }: { content: VariableScopeLessonDevelopmentPack["local"] }) { return <section id="local-scope" className="lesson-card local-scope-card" aria-labelledby="local-scope-title"><p className="lesson-section-label"><UserData size={16}/> Local variables</p><h2 id="local-scope-title">{content.title}</h2><p>{content.explanation}</p><div className="scope-code-grid"><CodeSnippet type="multi" feedback="Copied">{content.code}</CodeSnippet><div className="scope-function-box"><span>irrigation() boundary</span><VariableToken variable={content.variable}/></div></div><Tile className="scope-error-example"><span>Outside the box</span><code>{content.outsideCode}</code><Tag type="red">{content.outsideResult}</Tag></Tile></section>; }
export function GlobalScopeCard({ content }: { content: VariableScopeLessonDevelopmentPack["global"] }) { return <section id="global-scope" className="lesson-card global-scope-card" aria-labelledby="global-scope-title"><p className="lesson-section-label"><UserData size={16}/> Global variables</p><h2 id="global-scope-title">{content.title}</h2><p>{content.explanation}</p><div className="global-scope-box"><VariableToken variable={content.variable}/><div><span>Readable from</span><code>{content.reader}</code><ArrowRight/><strong>{content.output}</strong></div></div><CodeSnippet type="multi" feedback="Copied">{content.code}</CodeSnippet></section>; }
export function ShadowingSimulator({ content }: { content: VariableScopeLessonDevelopmentPack["shadowing"] }) { const [inside,setInside]=useState(true);return <section id="shadowing" className="lesson-card shadowing-simulator" aria-labelledby="shadowing-title"><div className="lesson-card-heading"><div><p className="lesson-section-label"><DataConnected size={16}/> Shadowing simulator</p><h2 id="shadowing-title">{content.title}</h2><p>{content.explanation}</p></div><Toggle id="shadow-location" labelText="Current location" labelA="Main program" labelB="Inside display()" toggled={inside} onToggle={setInside}/></div><CodeSnippet type="multi" feedback="Copied">{content.code}</CodeSnippet><div className="shadowing-boxes"><Tile className={!inside?"is-active":""}><Tag type="blue">Global</Tag><code>farm = {JSON.stringify(content.globalValue)}</code></Tile><ArrowRight/><Tile className={inside?"is-active":""}><Tag type="purple">Local</Tag><code>farm = {JSON.stringify(content.localValue)}</code></Tile></div><Tile className="shadowing-result" aria-live="polite"><span>Python chooses</span><strong>{inside?content.localValue:content.globalValue}</strong><Tag type={inside?"purple":"blue"}>{inside?"Nearest local name":"Global name"}</Tag></Tile></section>; }
export function VariableLifetimeTimeline({ content }: { content: VariableScopeLessonDevelopmentPack["lifetime"] }) { const [local,setLocal]=useState(true);const steps=local?content.localSteps:content.globalSteps;return <section id="lifetime" className="lesson-card variable-lifetime" aria-labelledby="lifetime-title"><div className="lesson-card-heading"><div><p className="lesson-section-label"><DataConnected size={16}/> Variable lifetime timeline</p><h2 id="lifetime-title">{content.title}</h2><p>{content.body}</p></div><Toggle id="lifetime-type" labelText="Variable type" labelA="Global" labelB="Local" toggled={local} onToggle={setLocal}/></div><ol>{steps.map((step,index)=><li key={step.title} className={index===steps.length-1?"is-exit":""}><span>{index+1}</span><strong>{step.title}</strong><small>{step.description}</small></li>)}</ol></section>; }
export function ScopeBoundaryVisualizer({ content }: { content: VariableScopeLessonDevelopmentPack["boundaries"] }) { const all=[...content.globalVariables,...content.functions.flatMap((item)=>item.variables)];const [selected,setSelected]=useState(all[0]);return <section id="scope-boundaries" className="lesson-card scope-boundary-visualizer" aria-labelledby="scope-boundary-title"><p className="lesson-section-label"><DataConnected size={16}/> Scope boundary visualizer</p><h2 id="scope-boundary-title">{content.title}</h2><p>{content.body}</p><div className="global-program-boundary"><span>Main Program · Global Scope</span><div>{content.globalVariables.map((variable)=><VariableToken key={variable.name} variable={variable} selected={selected.name===variable.name} onClick={()=>setSelected(variable)}/>)}</div><div className="function-boundary-grid">{content.functions.map((fn)=><div key={fn.name}><strong>{fn.name}</strong>{fn.variables.map((variable)=><VariableToken key={variable.name} variable={variable} selected={selected.name===variable.name} onClick={()=>setSelected(variable)}/>)}</div>)}</div></div><VisibilityDetails variable={selected} location={selected.owner}/></section>; }
function VisibilityDetails({ variable, location }: { variable: ScopeVariableContent; location:string }) { return <Tile className="visibility-details" aria-live="polite"><Tag type={variable.scope==="global"?"blue":"purple"}>{variable.scope}</Tag><div><span>Variable</span><code>{variable.name}</code></div><div><span>Current value</span><code>{variable.value}</code></div><div><span>Owner</span><strong>{variable.owner}</strong></div><div><span>Lifetime</span><strong>{variable.lifetime}</strong></div><div><span>Accessible from {location}?</span><strong>Yes</strong></div></Tile>; }
export function ScopeExplorer({ content }: { content: VariableScopeLessonDevelopmentPack["explorer"] }) { const [phase,setPhase]=useState(0);const active=content.phases[phase];return <section id="scope-explorer" className="lesson-card scope-explorer" aria-labelledby="scope-explorer-title"><p className="lesson-section-label"><DataConnected size={16}/> Scope explorer</p><h2 id="scope-explorer-title">{content.title}</h2><p>{content.body}</p><div className="scope-phase-tabs" role="tablist" aria-label="Execution phases">{content.phases.map((item,index)=><Button role="tab" aria-selected={index===phase} key={item.label} size="sm" kind={index===phase?"primary":"tertiary"} onClick={()=>setPhase(index)}>{item.label}</Button>)}</div><div className="scope-explorer-stage"><Tile><span>Active frame</span><strong>{active.activeFrame}</strong></Tile><Tile><span>Visible now</span><div>{active.visible.map((name)=><Tag key={name} type={name==="farm_name"?"blue":"purple"}>{name}</Tag>)}</div></Tile><Tile><span>Destroyed</span><div>{active.destroyed.length?active.destroyed.map((name)=><Tag key={name} type="red">{name}</Tag>):<small>Nothing yet</small>}</div></Tile></div><p aria-live="polite">{active.label}: {active.visible.join(" and ")} visible{active.destroyed.length?`; ${active.destroyed.join(" and ")} no longer exists`:""}.</p></section>; }
export function ScopeVisibilityInspector({ execution }: { execution: PlaygroundExecution }) { const active=execution.trace.at(-1);const main=[...execution.trace].reverse().find((step)=>step.frameName==="Main Program");const fn=[...execution.trace].reverse().find((step)=>step.frameName&&step.frameName!=="Main Program");const merge=(items:PythonTraceVariable[])=>items.filter((item)=>!item.name.startsWith("__"));return <div className="scope-visibility-inspector"><div><UserData size={18}/><h3>Visibility Inspector</h3><Tag type={active?.frameName&&active.frameName!=="Main Program"?"purple":"blue"}>{active?.frameName??"Waiting"}</Tag></div><div><ScopeTraceGroup title="Global / main frame" variables={merge(main?.variables??[])}/><ScopeTraceGroup title="Latest function frame" variables={merge(fn?.variables??[])}/></div></div>; }
function ScopeTraceGroup({title,variables}:{title:string;variables:PythonTraceVariable[]}){return <div><strong>{title}</strong>{variables.length?variables.map((item)=><Tile key={item.name}><code>{item.name}</code><span>{item.value}</span><Tag type="gray">{item.type}</Tag></Tile>):<p>No visible learner variables.</p>}</div>;}
export function ScopePlaygroundSupplement({ execution }: { execution: PlaygroundExecution }) { const active=execution.trace.at(-1);return <div className="scope-playground-supplement"><div><CallStackPreview stack={active?.callStack??["Main Program"]} activeFrame={active?.frameName}/><ScopeVisibilityInspector execution={execution}/></div><CodeTracePanel execution={execution}/></div>; }
export function ScopeComparison({ content }: { content: VariableScopeLessonDevelopmentPack["comparison"] }) { return <section id="compare-choose" className="lesson-card scope-comparison" aria-labelledby="scope-comparison-title"><p className="lesson-section-label"><DataConnected size={16}/> Compare & choose</p><h2 id="scope-comparison-title">{content.title}</h2><p>{content.body}</p><div tabIndex={0} role="region" aria-label="Local and global comparison"><table><thead><tr><th>Feature</th><th>Local variable</th><th>Global variable</th></tr></thead><tbody>{content.rows.map((row)=><tr key={row.feature}><th>{row.feature}</th><td>{row.local}</td><td>{row.global}</td></tr>)}</tbody></table></div></section>; }
export function ScopeMiniProject({ content }: { content: VariableScopeLessonDevelopmentPack["miniProject"] }) { return <section id="mini-project" className="lesson-card scope-mini-project" aria-labelledby="scope-project-title"><p className="lesson-section-label"><Task size={16}/> Mini project</p><h2 id="scope-project-title">{content.title}</h2><p>{content.brief}</p><CodeSnippet type="multi" feedback="Copied">{content.starterCode}</CodeSnippet><div className="scope-project-checklist">{content.deliverables.map((item)=><Tile key={item}><CheckmarkOutline size={16}/><span>{item}</span></Tile>)}</div><Tile className="scope-project-challenge"><strong>Challenge</strong><p>{content.challenge}</p></Tile></section>; }
