import { CourseBreadcrumb } from "@/components/course/CourseBreadcrumb";
import { PreviousNextNavigation } from "@/components/course/PreviousNextNavigation";
import { CommonMistakesCard } from "@/components/learning/FirstProgramLessonBlocks";
import { LessonHero } from "@/components/learning/LessonHero";
import { AssignmentCard, IndustryInsightCard, KeyTakeawaysCard, LearningObjectivesCard, PracticeCard, QuizCard, SummaryCard, WhatsNextCard } from "@/components/learning/LearningBlocks";
import { DebugChallengeCollection } from "@/components/learning/ProblemSolvingLearningBlocks";
import { MiniProjectCard } from "@/components/learning/UserInputLearningBlocks";
import { AgritechWhileExamples, CompareChooseCard, InfiniteLoopDetector, LoopComparisonCard, UpdateCycleCard, WhileDefinitionCard, WhileLoopPlayground, WhileLoopStoryCard, WhileLoopVisualizer, WhileSyntaxBreakdown, WhyWhileCard } from "@/components/learning/WhileLoopLearningBlocks";
import { EngineerScenario } from "@/components/learning/WhyPythonLessonBlocks";
import type { CourseLesson, CourseModule } from "@/types/course";
import type { LessonDocument } from "@/types/content";

const whileOutline = [["objectives", "Objectives"], ["while-story", "Story continuation"], ["why-while", "for vs while"], ["while-definition", "What is while?"], ["while-syntax", "Syntax"], ["while-visualizer", "Loop visualizer"], ["update-cycle", "Variable updates"], ["agritech-while-examples", "Agritech examples"], ["infinite-loop-detector", "Infinite loops"], ["for-while-comparison", "Loop comparison"], ["playground", "Execution lab"], ["common-mistakes", "Common mistakes"], ["debug-challenge", "Debug challenge"], ["engineer-scenario", "Engineer thinking"], ["practice", "Practice"], ["mini-project", "Mini project"], ["quiz", "Quiz"], ["assignment", "Assignment"], ["compare-choose", "Compare & choose"], ["summary", "Summary"], ["whats-next", "What's next"]] as const;

export function WhileLoopLessonRenderer({ lesson, courseLesson, module, previous, next }: { lesson: LessonDocument; courseLesson: CourseLesson; module: CourseModule; previous: CourseLesson | null; next: CourseLesson | null }) {
  const pack = lesson.developmentPack;
  if (!pack || pack.kind !== "while-loop") return null;
  return <article className="published-lesson while-loop-development-pack"><CourseBreadcrumb module={module} lesson={courseLesson} /><LessonHero eyebrow={`Module ${module.index} · Lesson ${lesson.number}`} title={lesson.title} summary={lesson.summary} icon={module.icon} level={lesson.level} durationMinutes={lesson.durationMinutes} prerequisite={pack.prerequisite} /><div className="published-lesson-layout while-loop-lesson-layout"><div className="published-lesson-flow"><LearningObjectivesCard id="objectives" objectives={lesson.objectives} /><WhileLoopStoryCard content={pack.story} /><WhyWhileCard content={pack.whyWhile} /><WhileDefinitionCard content={pack.definition} /><WhileSyntaxBreakdown content={pack.syntax} /><WhileLoopVisualizer example={pack.firstExample} /><UpdateCycleCard content={pack.updateCycle} /><AgritechWhileExamples examples={pack.agritechExamples} /><IndustryInsightCard id="industry-insight" section={lesson.industryMotivation} /><InfiniteLoopDetector content={pack.infiniteLoop} /><LoopComparisonCard content={pack.forWhileComparison} /><WhileLoopPlayground content={lesson.playground} fields={pack.simulatorFields} /><CommonMistakesCard title={pack.mistakesTitle} mistakes={pack.mistakes} /><DebugChallengeCollection challenges={pack.debugChallenges} /><EngineerScenario content={pack.engineerScenario} /><PracticeCard id="practice" tasks={lesson.practice} /><MiniProjectCard project={pack.miniProject} /><QuizCard id="quiz" quiz={lesson.quiz} /><AssignmentCard id="assignment" assignment={lesson.assignment} /><CompareChooseCard content={pack.comparison} /><SummaryCard id="summary" section={lesson.summarySection} /><KeyTakeawaysCard id="key-takeaways" items={lesson.keyTakeaways} /><WhatsNextCard id="whats-next" section={lesson.whatsNext} /></div><aside className="lesson-outline published-lesson-outline" aria-label="On this page"><p>On this page</p>{whileOutline.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside></div><PreviousNextNavigation previous={previous} next={next} /></article>;
}
