import type { LoopControlLessonDevelopmentPack } from "@/types/content";

export const loopControlDevelopmentPack: LoopControlLessonDevelopmentPack = {
  kind: "loop-control",
  prerequisite: "Decision Making, for Loop, and while Loop",
  story: { title: "Real monitoring loops need operational control", body: "The Smart Farm can inspect hundreds of sensors, but real devices are imperfect. A critical emergency must stop processing, an isolated bad reading should be skipped, and an unfinished feature still needs syntactically valid space.", items: ["Stop immediately", "Skip bad data", "Reserve future logic"], incidents: ["Faulty sensor", "Missing reading", "Critical emergency"], workflow: { title: "Control the loop when field conditions demand it", description: "Each control statement changes execution in a different, deliberate way.", steps: [{ title: "Loop running", description: "Process the current sensor." }, { title: "Emergency?", description: "Use break to stop." }, { title: "Bad reading?", description: "Use continue to skip." }, { title: "Future feature?", description: "Use pass as a placeholder." }] } },
  whyControl: { title: "A loop does not always run cleanly from beginning to end", body: "Loop control lets software react to what happens during an iteration without duplicating or abandoning the complete monitoring workflow.", items: ["Normal processing", "Isolated fault", "Critical fault"], normalFlow: ["Sensor 1", "Sensor 2", "Sensor 3", "Sensor 4", "Sensor 5"], faultFlow: ["Sensor 1", "Sensor 2", "Fault · skip", "Sensor 4"], emergencyFlow: ["Sensor 1", "Sensor 2", "Emergency · stop"] },
  controls: [
    { statement: "break", triggerValue: 6, title: "break exits the nearest loop immediately", explanation: "When the condition is met, Python skips every remaining statement and iteration in that nearest loop.", code: "for i in range(1, 11):\n    if i == 6:\n        break\n    print(i)", output: "1\n2\n3\n4\n5", action: "Exit the loop", agritechCode: "for sensor in range(1, 11):\n    print(\"Checking Sensor\", sensor)\n    if sensor == 5:\n        print(\"Critical Fault Detected\")\n        break", agritechExplanation: "A critical failure ends inspection immediately so downstream automation can respond." },
    { statement: "continue", triggerValue: 3, title: "continue skips the rest of the current iteration", explanation: "Python jumps to the next item. The loop remains active and later iterations still run.", code: "for i in range(1, 6):\n    if i == 3:\n        continue\n    print(i)", output: "1\n2\n4\n5", action: "Skip this iteration", agritechCode: "faulty_sensor = 4\nfor sensor in range(1, 8):\n    if sensor == faulty_sensor:\n        continue\n    print(\"Reading Sensor\", sensor)", agritechExplanation: "One faulty device is omitted without losing valid readings from every other sensor." },
    { statement: "pass", triggerValue: 3, title: "pass deliberately performs no action", explanation: "The placeholder keeps an empty block valid. Execution continues normally with the next statement in the same iteration.", code: "for sensor in range(5):\n    if sensor == 3:\n        pass\n    print(sensor)", output: "0\n1\n2\n3\n4", action: "Do nothing", agritechCode: "sensor_status = \"Maintenance\"\nif sensor_status == \"Maintenance\":\n    pass", agritechExplanation: "A future maintenance feature can be represented without inventing unfinished behavior." },
  ],
  comparator: { title: "Compare break, continue, and pass", body: "The three statements are related control tools, but their effects on the loop and current iteration are distinct.", rows: [{ statement: "break", effect: "Exit loop immediately", loopContinues: "No", currentIteration: "Ends" }, { statement: "continue", effect: "Skip remaining code", loopContinues: "Yes", currentIteration: "Skipped" }, { statement: "pass", effect: "Do nothing", loopContinues: "Yes", currentIteration: "Continues normally" }] },
  simulator: { title: "Sensor Fault Simulator", body: "Move the maintenance and critical-fault sensors to see continue skip one reading and break end the complete inspection.", sensorCount: 20, maintenanceSensor: 7, criticalSensor: 15 },
  mistakesTitle: "Common loop-control mistakes",
  mistakes: [{ title: "break outside a loop", incorrect: "break", reason: "break is valid only inside a for or while loop.", correct: "for sensor in range(5):\n    if sensor == 3:\n        break" }, { title: "continue outside a loop", incorrect: "continue", reason: "There is no current iteration to skip outside a loop.", correct: "for sensor in range(5):\n    if sensor == 3:\n        continue" }, { title: "Expecting pass to skip", incorrect: "if sensor == 3:\n    pass\nprint(\"Hello\")", reason: "pass does nothing, so execution proceeds to print.", correct: "if sensor == 3:\n    pass  # placeholder\nprint(\"Hello\")" }],
  debugChallenges: [{ title: "Predict combined control flow", prompt: "Predict the output before revealing the solution.", code: "for i in range(10):\n    if i == 5:\n        continue\n    if i == 8:\n        break\n    print(i)", mistakesToFind: 0, solution: "0\n1\n2\n3\n4\n6\n7", hiddenGuidance: "Five skips its print; eight ends the loop before its print." }, { title: "Place break in a valid context", prompt: "Explain and repair the syntax error.", code: "if True:\n    break", mistakesToFind: 1, solution: "for sensor in range(5):\n    if sensor == 3:\n        break", hiddenGuidance: "An if block alone is not a loop." }],
  engineerScenario: { title: "Respond proportionally to sensor failures", scenario: "A farm monitors 500 sensors. Sensor 28 can report either a missing reading or a Motor Fire event.", question: "How should the monitoring loop respond?", options: [{ label: "continue for missing data; break for Motor Fire", explanation: "An isolated invalid reading should not discard valid later data, while a critical safety event demands immediate termination.", recommended: true }, { label: "break for every missing reading", explanation: "One recoverable sensor fault would prevent all later devices from being inspected.", recommended: false }, { label: "continue after Motor Fire", explanation: "Continuing normal inspection delays critical incident handling.", recommended: false }] },
  miniProject: { title: "Mini Project · Smart Sensor Monitoring System", brief: "Inspect sensors 1–20, skip sensor 7 under maintenance, and stop when sensor 15 reports a critical fault.", deliverables: ["Iterate through sensors 1–20", "Use continue for sensor 7", "Use break for sensor 15", "Print Critical Fault before stopping", "Display every processed sensor", "Accept a different critical sensor as an extension", "Test maintenance before and after the critical fault"], outputTemplate: "Checking Sensor 1\n...\nChecking Sensor 6\nChecking Sensor 8\n...\nChecking Sensor 14\nCritical Fault" },
  comparison: { title: "Compare & Choose", body: "Choose the smallest control action that correctly represents the operational event.", rows: [{ situation: "Stop after a critical fault", bestChoice: "break", reason: "No later iteration should run" }, { situation: "Ignore one faulty sensor", bestChoice: "continue", reason: "Later valid readings still matter" }, { situation: "Reserve future implementation", bestChoice: "pass", reason: "Keep an empty block valid" }, { situation: "Process every item", bestChoice: "Normal loop", reason: "No interruption is needed" }] },
};
