import type { UserInputLessonDevelopmentPack } from "@/types/content";

export const userInputDevelopmentPack: UserInputLessonDevelopmentPack = {
  kind: "user-input",
  prerequisite: "Lessons 1.1–1.3",
  story: {
    title: "A smart irrigation app needs information from its farmer",
    body: "When a farmer opens the app, it asks for the details required to prepare a useful field report. The answers cannot be written into the program in advance because every farmer and field is different.",
    prompts: ["Enter farmer name", "Enter crop", "Enter soil moisture", "Enter temperature"],
    question: "How does the application receive information while it is running?",
    answer: "It pauses for user input, stores each response, and continues with the new information.",
    workflow: {
      title: "From a farmer to a program result",
      description: "Follow one response as it moves through an interactive Python program.",
      steps: [
        { title: "User", description: "The farmer decides what information to provide." },
        { title: "Keyboard", description: "The response is entered as text." },
        { title: "Python input()", description: "The program waits for and receives the response." },
        { title: "Variable", description: "A meaningful name stores the returned string." },
        { title: "Program", description: "Later statements use the stored response." },
        { title: "Output", description: "The application displays a personalised result." },
      ],
    },
  },
  whyInput: {
    title: "Input turns a fixed script into an interactive application",
    body: "A hardcoded program repeats the same information for everyone. An interactive program asks each user for the information it needs.",
    staticCode: "print(\"Rahul\")\nprint(\"Rice\")",
    interactiveCode: "name = input(\"Enter your name : \")\nprint(name)",
    stages: [
      { title: "Static program", description: "The values are fixed inside the source code." },
      { title: "Interactive program", description: "input() accepts a different response from each user." },
      { title: "Real application", description: "The response can personalise reports and workflows." },
    ],
  },
  inputFunction: {
    title: "Understanding input()",
    body: "input() displays an optional prompt, pauses the program, and returns the text entered by the user. Assignment stores that returned text in a variable.",
    syntax: "variable = input(\"Message\")",
    example: {
      title: "Ask for a name",
      code: "name = input(\"Enter your name : \" )\nprint(name)",
      explanation: "Python shows the prompt, waits for a response, stores the response in name, and then prints it.",
      output: "Enter your name : Rahul\nRahul",
    },
    workflow: {
      title: "What happens when Python reaches input()",
      description: "The program pauses only long enough to receive the next response.",
      steps: [
        { title: "Question", description: "The prompt explains what information is required." },
        { title: "User types", description: "The learner enters a response." },
        { title: "Python receives", description: "input() returns the entered characters as a string." },
        { title: "Variable stores", description: "Assignment binds the response to a readable name." },
        { title: "Output", description: "The program can now display or process the response." },
      ],
    },
  },
  textInput: {
    title: "Receive and display text input",
    code: "farmer = input(\"Farmer Name : \")\ncrop = input(\"Crop Name : \")\n\nprint(farmer)\nprint(crop)",
    explanation: "Both responses are strings. Meaningful variables preserve what each response represents.",
    output: "Farmer Name : Rahul\nCrop Name : Rice\nRahul\nRice",
    sampleInputs: ["Rahul", "Rice"],
  },
  multipleInputs: {
    title: "Collect a simple profile with multiple inputs",
    code: "name = input(\"Name : \")\nvillage = input(\"Village : \")\ndistrict = input(\"District : \")\nstate = input(\"State : \")\n\nprint(name)\nprint(village)\nprint(district)\nprint(state)",
    explanation: "Python handles the input calls in order. Each call consumes the next response provided by the user.",
    output: "Name : Asha\nVillage : Panvel\nDistrict : Raigad\nState : Maharashtra\nAsha\nPanvel\nRaigad\nMaharashtra",
    activity: "Adapt this pattern to build a four-field student profile.",
  },
  numericInput: {
    title: "Numeric-looking input still arrives as text",
    code: "age = input(\"Age : \")\nprint(type(age))",
    explanation: "Typing digits does not change the return type of input(). The returned value is still a string until it is converted.",
    output: "Age : 24\n<class 'str'>",
    question: "What type does input() return when the user types 24?",
    answer: "str",
  },
  conversion: {
    title: "Convert input when the program needs a number",
    body: "Wrap input() with int() for whole numbers or float() for decimal measurements. Conversion happens after the keyboard response arrives as text.",
    integer: {
      title: "Whole-number input",
      code: "age = int(input(\"Enter age : \"))\nprint(age)",
      explanation: "int() converts compatible digit text into an integer.",
      output: "Enter age : 24\n24",
    },
    decimal: {
      title: "Decimal measurement input",
      code: "temperature = float(input(\"Temperature : \"))\nprint(temperature)",
      explanation: "float() converts compatible numeric text into a decimal value.",
      output: "Temperature : 31.5\n31.5",
    },
    workflow: {
      title: "Convert a keyboard response into an integer",
      description: "The keyboard always supplies text; the conversion function creates the numeric value.",
      steps: [
        { title: "Keyboard", description: "The learner types 20." },
        { title: "String", description: "input() returns the text \"20\"." },
        { title: "int()", description: "Python validates and converts the digit text." },
        { title: "Integer", description: "The program can now calculate with 20." },
      ],
    },
  },
  whyConversion: {
    title: "Predict why input conversion matters",
    body: "Assume the learner enters 20. Decide whether Python will join text or add numbers.",
    predictions: [
      { title: "Unconverted input", code: "age = input(\"Age : \")\nprint(age + age)", options: ["40", "2020", "Error"], answer: "2020", explanation: "input() returned the string \"20\", so + joins the two strings." },
      { title: "Converted input", code: "age = int(input(\"Age : \"))\nprint(age + age)", options: ["40", "2020", "Error"], answer: "40", explanation: "int() created the integer 20, so + performs numerical addition." },
    ],
  },
  agritechProgram: {
    title: "Collect a smart-farm observation",
    code: "farmer = input(\"Farmer Name : \")\ncrop = input(\"Crop : \")\ntemperature = float(input(\"Temperature : \"))\nsoil = int(input(\"Soil Moisture : \"))\n\nprint(\"Farmer :\", farmer)\nprint(\"Crop :\", crop)\nprint(\"Temperature :\", temperature)\nprint(\"Soil Moisture :\", soil)",
    explanation: "Text fields remain strings, the temperature becomes a float, and the whole-number soil-moisture reading becomes an integer.",
    output: "Farmer Name : Rahul\nCrop : Rice\nTemperature : 31.5\nSoil Moisture : 42\nFarmer : Rahul\nCrop : Rice\nTemperature : 31.5\nSoil Moisture : 42",
  },
  simulator: {
    title: "Smart farm input simulator",
    description: "Complete the form, run the Python program, and compare the approachable form experience with the equivalent console interaction.",
    fields: [
      { id: "farmer", label: "Farmer name", prompt: "Farmer Name : ", defaultValue: "Rahul", type: "str" },
      { id: "crop", label: "Crop", prompt: "Crop : ", defaultValue: "Rice", type: "str" },
      { id: "temperature", label: "Temperature", prompt: "Temperature : ", defaultValue: "31.5", type: "float" },
      { id: "rainfall", label: "Rainfall", prompt: "Rainfall : ", defaultValue: "120.5", type: "float" },
      { id: "soil_moisture", label: "Soil moisture", prompt: "Soil Moisture : ", defaultValue: "42", type: "int" },
    ],
    code: "farmer = input(\"Farmer Name : \")\ncrop = input(\"Crop : \")\ntemperature = float(input(\"Temperature : \"))\nrainfall = float(input(\"Rainfall : \"))\nsoil_moisture = int(input(\"Soil Moisture : \"))\n\nprint(\"SMART FARM REPORT\")\nprint(\"Farmer :\", farmer)\nprint(\"Crop :\", crop)\nprint(\"Temperature :\", temperature)\nprint(\"Rainfall :\", rainfall)\nprint(\"Soil Moisture :\", soil_moisture)",
    reportTitle: "SMART FARM REPORT",
  },
  playgroundActivities: ["Change the farmer and crop", "Enter a decimal temperature", "Add the rainfall input() call", "Add the soil-moisture input() call", "Display all five values as a report"],
  mistakesTitle: "Repair common input mistakes",
  mistakes: [
    { title: "Calculating with unconverted input", incorrect: "age = input(\"Age : \" )\nprint(age + 10)", reason: "input() returns a string, which cannot be added directly to an integer.", correct: "age = int(input(\"Age : \"))\nprint(age + 10)" },
    { title: "Combining a float and text with +", incorrect: "temperature = float(input(\"Temperature : \"))\nprint(temperature + \" Degree\")", reason: "A float and string cannot be joined directly with +.", correct: "temperature = float(input(\"Temperature : \"))\nprint(\"Temperature :\", temperature, \"Degree\")" },
    { title: "Using int() for a decimal reading", incorrect: "rainfall = int(input(\"Rainfall : \"))", reason: "A response such as 12.5 is not valid whole-number text.", correct: "rainfall = float(input(\"Rainfall : \"))" },
  ],
  debugChallenge: {
    title: "Repair an interactive farm calculation",
    prompt: "The program receives numeric text but tries to calculate before converting it. Find and repair the input-handling mistakes.",
    code: "temperature = input(\"Temperature : \" )\nsoil = input(\"Soil : \" )\nprint(temperature + soil)\nage = input(\"Age : \" )\nprint(age + 5)",
    mistakesToFind: 3,
    solution: "temperature = float(input(\"Temperature : \"))\nsoil = float(input(\"Soil : \"))\nprint(temperature + soil)\nage = int(input(\"Age : \"))\nprint(age + 5)",
    hiddenGuidance: "Decide whether each response represents text, a whole number, or a decimal measurement before using it.",
  },
  engineerScenario: {
    title: "Choose input conversions for a smart-farm dashboard",
    scenario: "The dashboard asks for farmer name, crop, temperature, rainfall, humidity, and motor status.",
    question: "Which input strategy preserves the meaning of these values at this stage of the course?",
    options: [
      { label: "input, input, float(input), float(input), float(input), input", explanation: "Names and crop remain text; measurements become floats. Motor status remains text because converting typed words into a Boolean requires logic taught later.", recommended: true },
      { label: "int(input) for every field", explanation: "Names and crops are not integers, and decimal measurements may lose or reject important precision.", recommended: false },
      { label: "input for every field", explanation: "This collects the data but leaves measurements as strings, limiting calculations until conversion occurs.", recommended: false },
      { label: "float(input) for every field", explanation: "Farmer names, crop names, and status words cannot be represented as floats.", recommended: false },
    ],
  },
  miniProject: {
    title: "Mini project · Farm Registration System",
    brief: "Build an interactive program that collects a farm profile and displays a clearly formatted smart-farm report.",
    deliverables: ["Farmer name", "Village", "Crop", "Temperature", "Rainfall", "Soil moisture", "A report heading and readable separators"],
    outputTemplate: "SMART FARM REPORT\n------------------------\nFarmer :\nVillage :\nCrop :\nTemperature :\nRainfall :\nSoil Moisture :\n------------------------",
  },
};
