import type { WhileLoopLessonDevelopmentPack } from "@/types/content";

export const whileLoopDevelopmentPack: WhileLoopLessonDevelopmentPack = {
  kind: "while-loop",
  prerequisite: "Lessons 2.1–2.7",
  story: {
    title: "Keep monitoring until the field state changes",
    body: "A for loop can inspect a known collection of sensors. Irrigation is different: nobody knows in advance whether the soil needs two, ten, or thirty-five minutes. The controller must keep checking until moisture reaches a safe target.",
    knownSequence: ["Sensor 1", "Sensor 2", "Sensor 3", "…", "Sensor 100"],
    unknownDurations: ["2 minutes?", "10 minutes?", "35 minutes?"],
    workflow: { title: "Continuous irrigation monitoring", description: "The motor runs only while the measured soil moisture remains below its target.", steps: [{ title: "Motor ON", description: "Begin irrigation for dry soil." }, { title: "Read moisture", description: "Measure the current field state." }, { title: "Enough water?", description: "Evaluate the stopping condition." }, { title: "Continue or stop", description: "Repeat when False; stop when True." }] },
  },
  whyWhile: { title: "Choose repetition from what is known", body: "A for loop answers ‘how many items?’ A while loop answers ‘has the stopping condition been reached yet?’", items: ["Known repetitions → for", "Unknown repetitions → while", "Condition checked before every iteration"], forCode: "for i in range(10):\n    print(\"Checking Moisture\")", knownLabel: "Known repetitions", unknownLabel: "Unknown repetitions" },
  definition: { title: "A while loop repeats while its condition remains True", body: "Python checks the condition before each iteration. A True result executes the indented block; a False result leaves the loop.", items: ["Condition", "Boolean result", "Repeated block", "Update", "Exit"], flow: [{ title: "Check", description: "Evaluate the condition." }, { title: "True", description: "Execute the block." }, { title: "Update", description: "Change the controlling state." }, { title: "Repeat", description: "Check the condition again." }, { title: "False", description: "End the loop." }] },
  syntax: { title: "The condition controls every iteration", body: "The indented statements repeat only while the condition is True.", template: "while condition:\n    statements", parts: [{ token: "while", label: "Loop keyword", description: "Begins condition-controlled repetition." }, { token: "condition", label: "Continuation rule", description: "Evaluates to True or False before each iteration." }, { token: ":", label: "Block marker", description: "Starts the repeated block." }, { token: "    statements", label: "Repeated block", description: "Runs while the condition remains True." }] },
  firstExample: { title: "Count from one to five", code: "count = 1\n\nwhile count <= 5:\n    print(count)\n    count = count + 1", explanation: "Each iteration prints the current count and moves it one step toward the stopping boundary.", output: "1\n2\n3\n4\n5", initialValue: 1, targetValue: 5, increment: 1, variable: "count" },
  updateCycle: { title: "Condition → Execute → Update → Repeat", body: "The update is essential because it changes the state used by the condition. Without it, the same True result can repeat forever.", code: "count = count + 1", steps: [{ title: "Condition", description: "Is count still at most 5?" }, { title: "Execute", description: "Print the current value." }, { title: "Update", description: "Increase count by one." }, { title: "Repeat", description: "Evaluate the condition again." }] },
  agritechExamples: [
    { title: "Smart Irrigation Controller", code: "soil_moisture = 20\n\nwhile soil_moisture < 30:\n    print(\"Motor Running\")\n    soil_moisture = soil_moisture + 2\n\nprint(\"Stop Irrigation\")", explanation: "Moisture rises in measured steps until it reaches the safe 30% target.", output: "Motor Running\nMotor Running\nMotor Running\nMotor Running\nMotor Running\nStop Irrigation", initialValue: 20, targetValue: 30, increment: 2, variable: "soil_moisture" },
    { title: "Water Tank Filling", code: "water_level = 40\n\nwhile water_level < 100:\n    print(\"Filling Tank\")\n    water_level += 10\n\nprint(\"Tank Full\")", explanation: "The tank level is unknown at each future check, so filling continues until 100%. ", output: "Filling Tank\nFilling Tank\nFilling Tank\nFilling Tank\nFilling Tank\nFilling Tank\nTank Full", initialValue: 40, targetValue: 100, increment: 10, variable: "water_level" },
  ],
  infiniteLoop: { title: "An unchanged condition can repeat forever", body: "This loop never updates count. Since 1 <= 5 remains True, Python keeps executing the same block.", dangerousCode: "count = 1\n\nwhile count <= 5:\n    print(count)", reason: "count is never updated, so the condition cannot become False.", cycle: [{ title: "Condition", description: "True" }, { title: "Execute", description: "Print 1" }, { title: "No update", description: "count remains 1" }, { title: "Forever", description: "The condition is still True" }] },
  simulatorFields: [{ id: "soil", label: "Initial Soil Moisture (%)", prompt: "Enter Soil Moisture (%): ", defaultValue: "26", type: "int" }],
  mistakesTitle: "Common while-loop mistakes",
  mistakes: [{ title: "Missing update", incorrect: "while count < 5:\n    print(count)", reason: "count never changes, so a True condition remains True.", correct: "while count < 5:\n    print(count)\n    count += 1" }, { title: "Wrong indentation", incorrect: "while count < 5:\nprint(count)", reason: "Python cannot identify the repeated block.", correct: "while count < 5:\n    print(count)\n    count += 1" }, { title: "Condition starts False", incorrect: "count = 10\nwhile count < 5:\n    print(count)", reason: "while checks before running, so the body executes zero times.", correct: "count = 1\nwhile count < 5:\n    print(count)\n    count += 1" }],
  debugChallenges: [{ title: "Make the counter terminate", prompt: "Find the missing operation that prevents completion.", code: "count = 1\n\nwhile count <= 5:\n    print(count)", mistakesToFind: 1, solution: "count = 1\n\nwhile count <= 5:\n    print(count)\n    count += 1", hiddenGuidance: "Which value controls the condition, and where does it change?" }, { title: "Repair the irrigation update", prompt: "Explain why assigning soil to itself creates an infinite loop.", code: "soil = 20\n\nwhile soil < 30:\n    print(\"Motor Running\")\n    soil = soil", mistakesToFind: 1, solution: "soil = 20\n\nwhile soil < 30:\n    print(\"Motor Running\")\n    soil += 2", hiddenGuidance: "An assignment is not necessarily a meaningful update." }],
  engineerScenario: { title: "Choose condition-controlled monitoring", scenario: "A controller monitors soil moisture, tank level, and battery percentage. Their final state—not a predetermined count—decides when monitoring ends.", question: "Which repetition model fits these tasks?", options: [{ label: "Use while loops with explicit stopping conditions", explanation: "Each process continues until its measured state reaches a safe boundary.", recommended: true }, { label: "Always repeat exactly ten times", explanation: "A fixed count may stop too early or continue after the target is reached.", recommended: false }, { label: "Copy the check many times", explanation: "Duplicated checks do not adapt to changing sensor values.", recommended: false }] },
  miniProject: { title: "Mini Project · Smart Irrigation Controller v5", brief: "Read the initial soil moisture, keep irrigating in 2% steps, and stop safely at the 30% target.", deliverables: ["Read and convert initial moisture", "Use soil < 30 as the condition", "Display Motor Running during each iteration", "Increase soil by 2", "Display the current moisture after every update", "Display Target Moisture Reached", "Display Motor OFF", "Test values below, equal to, and above 30"], outputTemplate: "Motor Running...\nCurrent Moisture: 28\nMotor Running...\nCurrent Moisture: 30\nTarget Moisture Reached\nMotor OFF" },
  forWhileComparison: { title: "for vs while", body: "Select the loop from the repetition model, not from habit.", rows: [{ feature: "Number of repetitions known?", forLoop: "Yes", whileLoop: "No" }, { feature: "Condition", forLoop: "Implicit sequence completion", whileLoop: "Explicit before each iteration" }, { feature: "Infinite-loop risk", forLoop: "Low", whileLoop: "Higher if state does not change" }, { feature: "Typical use", forLoop: "Collections and ranges", whileLoop: "Continuous monitoring" }, { feature: "Agritech example", forLoop: "Check every sensor", whileLoop: "Irrigate until soil is moist" }] },
  comparison: { title: "Compare & Choose", body: "Control-flow structures solve different shapes of problems.", rows: [{ situation: "One decision", bestConstruct: "if", reason: "One guarded action" }, { situation: "Two outcomes", bestConstruct: "if-else", reason: "Two alternatives" }, { situation: "Multiple outcomes", bestConstruct: "if-elif-else", reason: "Ordered alternatives" }, { situation: "Dependent decisions", bestConstruct: "Nested if", reason: "Hierarchical checks" }, { situation: "Menu selection", bestConstruct: "match-case", reason: "Fixed-value mapping" }, { situation: "Known repetitions", bestConstruct: "for", reason: "Process a known sequence" }, { situation: "Unknown repetitions", bestConstruct: "while", reason: "Repeat until state changes" }] },
};
