import type { ConditionalBranchContent, IfElifElseLessonDevelopmentPack } from "@/types/content";

const soilBranches: ConditionalBranchContent[] = [
  { id: "soil-critical", kind: "if", condition: "soil < 15", action: "Emergency Irrigation", label: "Critical" },
  { id: "soil-low", kind: "elif", condition: "soil < 30", action: "Start Irrigation", label: "Low" },
  { id: "soil-normal", kind: "elif", condition: "soil < 50", action: "Monitor Soil", label: "Normal" },
  { id: "soil-high", kind: "else", action: "Stop Irrigation", label: "High" },
];

export const ifElifElseDevelopmentPack: IfElifElseLessonDevelopmentPack = {
  kind: "if-elif-else",
  prerequisite: "Lessons 2.1 Decision Making · 2.2 if · 2.3 if-else",
  story: { title: "The farm now needs more than two outcomes", body: "The current controller distinguishes dry soil from sufficient moisture. The farm manager now needs different actions for extremely dry, moderately dry, healthy, and overwatered fields.", priorCode: "if soil_moisture < 30:\n    print(\"Start Irrigation\")\nelse:\n    print(\"No Irrigation Required\")", situations: ["Extremely dry", "Moderately dry", "Healthy", "Overwatered"], workflow: { title: "From one measurement to four possible actions", description: "Python evaluates ordered conditions until it finds the first True result.", steps: [{ title: "Soil Moisture", description: "Read one sensor value." }, { title: "Very Low?", description: "Check the narrowest critical range first." }, { title: "Low?", description: "Continue only when the first condition is False." }, { title: "Normal?", description: "Test the next threshold." }, { title: "High", description: "Use else as the default remaining range." }, { title: "Action", description: "Execute exactly one recommendation." }] } },
  whyTwoPaths: { title: "Why if-else is not enough", body: "Two branches cannot communicate four distinct field states without losing important operational detail.", items: ["One measurement", "Four meaningful ranges", "Four different actions"], cases: [{ value: 12, action: "Emergency Irrigation" }, { value: 25, action: "Start Irrigation" }, { value: 40, action: "Monitor Field" }, { value: 70, action: "Stop Irrigation" }] },
  definition: { title: "elif means else if", body: "An elif condition is checked only when every earlier condition in the same chain was False.", items: ["Evaluate from top to bottom", "Stop at the first True condition", "Skip every remaining branch", "Use else as the optional default"], rules: ["if starts the chain", "elif adds alternative conditions", "else handles all remaining values", "Only one branch executes"] },
  syntax: { title: "One ordered chain, several alternatives", body: "Every header ends with a colon and every action belongs to an indented block.", template: "if condition1:\n    statement1\nelif condition2:\n    statement2\nelif condition3:\n    statement3\nelse:\n    statement4", parts: [{ token: "if condition1:", label: "First condition", description: "Always evaluated first." }, { token: "elif condition2:", label: "Second condition", description: "Checked only if the first was False." }, { token: "elif condition3:", label: "Third condition", description: "Checked only if both earlier conditions were False." }, { token: "else:", label: "Default branch", description: "Runs when no condition matched." }] },
  firstExample: { title: "Grades demonstrate first-match execution", code: "marks = 82\n\nif marks >= 90:\n    print(\"Grade A\")\nelif marks >= 75:\n    print(\"Grade B\")\nelif marks >= 50:\n    print(\"Grade C\")\nelse:\n    print(\"Fail\")", explanation: "82 fails the first condition, matches the second, prints Grade B, and skips the remaining branches.", output: "Grade B", variable: "marks", defaultValue: 82, min: 0, max: 100, branches: [{ id: "grade-a", kind: "if", condition: "marks >= 90", action: "Grade A", label: "A" }, { id: "grade-b", kind: "elif", condition: "marks >= 75", action: "Grade B", label: "B" }, { id: "grade-c", kind: "elif", condition: "marks >= 50", action: "Grade C", label: "C" }, { id: "grade-f", kind: "else", action: "Fail", label: "Fail" }] },
  agritechExamples: [
    { title: "Irrigation levels", code: "soil = 18\n\nif soil < 15:\n    print(\"Emergency Irrigation\")\nelif soil < 30:\n    print(\"Start Irrigation\")\nelif soil < 50:\n    print(\"Monitor Soil\")\nelse:\n    print(\"Stop Irrigation\")", explanation: "Ordered thresholds classify the complete soil-moisture range.", output: "Start Irrigation", variable: "soil", branches: soilBranches, defaultValue: 18, min: 0, max: 100, unit: "%" },
    { title: "Greenhouse temperature", code: "temperature = 37\n\nif temperature < 15:\n    print(\"Heating Required\")\nelif temperature < 30:\n    print(\"Temperature Normal\")\nelif temperature < 40:\n    print(\"Open Ventilation\")\nelse:\n    print(\"Heat Emergency\")", explanation: "Temperature ranges select heating, normal, ventilation, or emergency actions.", output: "Open Ventilation", variable: "temperature", defaultValue: 37, min: 0, max: 55, unit: "°C", branches: [{ id: "temp-cold", kind: "if", condition: "temperature < 15", action: "Heating Required", label: "Cold" }, { id: "temp-normal", kind: "elif", condition: "temperature < 30", action: "Temperature Normal", label: "Normal" }, { id: "temp-hot", kind: "elif", condition: "temperature < 40", action: "Open Ventilation", label: "Hot" }, { id: "temp-danger", kind: "else", action: "Heat Emergency", label: "Dangerous" }] },
    { title: "Rainfall monitoring", code: "rainfall = 120\n\nif rainfall < 20:\n    print(\"Drought Alert\")\nelif rainfall < 100:\n    print(\"Normal Rainfall\")\nelif rainfall < 200:\n    print(\"Heavy Rainfall\")\nelse:\n    print(\"Flood Warning\")", explanation: "Rainfall ranges select drought, normal, heavy, or flood guidance.", output: "Heavy Rainfall", variable: "rainfall", defaultValue: 120, min: 0, max: 300, unit: "mm", branches: [{ id: "rain-low", kind: "if", condition: "rainfall < 20", action: "Drought Alert", label: "Low" }, { id: "rain-normal", kind: "elif", condition: "rainfall < 100", action: "Normal Rainfall", label: "Moderate" }, { id: "rain-heavy", kind: "elif", condition: "rainfall < 200", action: "Heavy Rainfall", label: "Heavy" }, { id: "rain-flood", kind: "else", action: "Flood Warning", label: "Flood" }] },
  ],
  treeBuilder: { title: "Build and validate the irrigation decision tree", body: "Reorder thresholds, inspect the path, and restore a logically reachable sequence.", variable: "soil", branches: soilBranches },
  orderAnalyzer: { title: "Condition Order Analyzer", body: "Broader ranges placed first can make narrower branches unreachable because Python stops at the first match.", incorrectCode: "if soil < 50:\n    print(\"Monitor\")\nelif soil < 30:\n    print(\"Start Irrigation\")", correctCode: "if soil < 30:\n    print(\"Start Irrigation\")\nelif soil < 50:\n    print(\"Monitor\")" },
  coverage: { title: "Condition Coverage Tester", body: "Test a collection of sensor values and verify that every decision branch has been exercised at least once.", variable: "soil", branches: soilBranches, defaultInputs: "10, 22, 40, 70" },
  simulatorFields: [{ id: "soil", label: "Soil Moisture (%)", prompt: "Enter Soil Moisture (%): ", defaultValue: "18", type: "float" }],
  mistakesTitle: "Multi-way decisions depend on order and structure",
  mistakes: [{ title: "Broader condition first", incorrect: "if soil < 50:\n    print(\"Monitor\")\nelif soil < 30:\n    print(\"Start Irrigation\")", reason: "A value of 20 matches soil < 50 first, so the narrower branch is unreachable.", correct: "if soil < 30:\n    print(\"Start Irrigation\")\nelif soil < 50:\n    print(\"Monitor\")" }, { title: "Multiple else blocks", incorrect: "if soil < 30:\n    print(\"Low\")\nelse:\n    print(\"Normal\")\nelse:\n    print(\"High\")", reason: "One conditional chain can have only one final else branch.", correct: "if soil < 30:\n    print(\"Low\")\nelif soil < 50:\n    print(\"Normal\")\nelse:\n    print(\"High\")" }, { title: "Missing elif colon", incorrect: "elif soil < 30\n    print(\"Start\")", reason: "Every conditional header must end with a colon.", correct: "elif soil < 30:\n    print(\"Start\")" }],
  debugChallenges: [{ title: "Find the unreachable irrigation branch", prompt: "Explain why Start Irrigation never appears for soil = 22, then repair the order.", code: "soil = 22\n\nif soil < 50:\n    print(\"Monitor\")\nelif soil < 30:\n    print(\"Start Irrigation\")\nelse:\n    print(\"Stop\")", mistakesToFind: 1, solution: "soil = 22\n\nif soil < 30:\n    print(\"Start Irrigation\")\nelif soil < 50:\n    print(\"Monitor\")\nelse:\n    print(\"Stop\")", hiddenGuidance: "Compare which of the two < thresholds describes the broader range." }, { title: "Repair the heat chain", prompt: "Fix the missing colon and keep the most severe threshold first.", code: "temperature = 42\n\nif temperature > 40\n    print(\"Heat Emergency\")\nelif temperature > 30:\n    print(\"Open Ventilation\")", mistakesToFind: 1, solution: "temperature = 42\n\nif temperature > 40:\n    print(\"Heat Emergency\")\nelif temperature > 30:\n    print(\"Open Ventilation\")", hiddenGuidance: "The ordering is correct; inspect the first block header." }],
  engineerScenario: { title: "Design four useful sensor levels", scenario: "A Smart Farm receives temperature, soil moisture, and rainfall readings.", question: "How should four ordered levels for each sensor map to actions?", options: [{ label: "Narrow severe ranges first", explanation: "Define Cold/Normal/Hot/Dangerous, Critical/Low/Normal/High, and Low/Moderate/Heavy/Flood with the most specific threshold first.", recommended: true }, { label: "Broad ranges first", explanation: "Broad conditions capture values before later specific branches can be reached.", recommended: false }, { label: "Use unrelated variables per branch", explanation: "One ordered classification chain should normally classify one measurement consistently.", recommended: false }] },
  miniProject: { title: "Mini Project · Smart Irrigation Controller v3", brief: "Classify soil moisture into four irrigation actions, then add a separate four-level temperature chain.", deliverables: ["Numeric soil input", "Emergency Irrigation below 15%", "Start Irrigation below 30%", "Monitor Soil below 50%", "Stop Irrigation otherwise", "Temperature chain for heating, normal, ventilation, and emergency", "Coverage inputs for every branch"], outputTemplate: "SMART FARM RECOMMENDATIONS\n--------------------------\nStart Irrigation\nOpen Ventilation" },
};
