import type { FunctionParametersLessonDevelopmentPack } from "@/types/content";

export const functionParametersDevelopmentPack: FunctionParametersLessonDevelopmentPack = {
  kind: "function-parameters",
  prerequisite: "Lesson 3.1 · Why Functions and Lesson 3.2 · Creating Functions",
  evolution: {
    title: "Function Evolution",
    body: "Follow the same soil-checking function as each lesson adds one capability. Lesson 3.3 makes the function flexible by accepting data.",
    stages: [{lesson:"3.2",code:"Create Function",capability:"Define reusable work"},{lesson:"3.3",code:"Accept Inputs",capability:"Receive changing values",active:true},{lesson:"3.4",code:"Return Outputs",capability:"Produce reusable results"},{lesson:"3.5",code:"Flexible Function Calls",capability:"Choose how values bind"},{lesson:"3.6",code:"Variable Scope",capability:"Understand where names live"},{lesson:"3.7",code:"Anonymous Functions",capability:"Create compact functions"},{lesson:"3.8",code:"Recursion",capability:"Functions call themselves"},{lesson:"3.9",code:"Best Practices",capability:"Design maintainable functions"},{lesson:"3.10",code:"Capstone",capability:"Integrate the module"}],
  },
  story: {
    title: "One irrigation function must work for every farm",
    body: "A fixed irrigation function performs the same action every time. Real farms report different moisture readings, so the same reusable function needs a way to receive each farm's current data.",
    fixedFunction: "def irrigation():\n    print(\"Starting Irrigation\")",
    farms: [{ name: "Farm A", moisture: 18 }, { name: "Farm B", moisture: 42 }, { name: "Farm C", moisture: 12 }],
    rejectedNames: ["irrigation1()", "irrigation2()", "irrigation3()"],
    workflow: { title: "Same function, different farm data", description: "Parameters let one definition adapt to each call.", steps: [{ title: "Farm A · 18%", description: "Supply the first reading." }, { title: "Farm B · 42%", description: "Supply a different reading." }, { title: "Farm C · 12%", description: "Supply the third reading." }, { title: "Same function", description: "Process each value through one definition." }] },
  },
  hardcoded: {
    title: "Hardcoded values make a function inflexible",
    explanation: "The value 25 is embedded in the body, so every farm sees the same reading even when its sensor reports something else.",
    code: "def check_soil():\n    print(\"Soil Moisture = 25\")\n\ncheck_soil()",
    output: "Soil Moisture = 25",
    problem: "Every farm displays 25",
    fixedValue: "25",
    risks: ["Incorrect field report", "Separate function per farm", "Duplicated maintenance", "No sensor flexibility"],
  },
  definition: {
    title: "A parameter is an empty container waiting for call data",
    body: "A parameter is a variable listed in the function definition. When the function is called, the matching supplied value becomes available through that parameter inside the function body.",
    containerLabel: "Parameter",
    analogy: { title: "One food-delivery app serves different orders", inputs: ["Customer Name", "Address", "Order"], outcome: "Same app · Different delivery" },
  },
  firstParameter: {
    title: "Create the first parameterized function",
    explanation: "moisture appears in the function header and receives the value supplied by each call.",
    code: "def check_soil(moisture):\n    print(\"Soil Moisture:\", moisture)\n\ncheck_soil(18)\ncheck_soil(32)",
    output: "Soil Moisture: 18\nSoil Moisture: 32",
    functionName: "check_soil",
    parameters: ["moisture"],
    calls: [{ arguments: ["18"], output: "Soil Moisture: 18" }, { arguments: ["32"], output: "Soil Moisture: 32" }],
    anatomy: [{ token: "def", label: "Keyword", description: "Begins the definition." }, { token: "check_soil", label: "Function name", description: "Names the reusable task." }, { token: "moisture", label: "Parameter", description: "Receives one value from each call." }],
  },
  parameterFlow: {
    title: "Trace one value into a function",
    body: "Follow the value 18 from the main program into the moisture parameter, through the function body, and back to the caller.",
    functionName: "check_soil",
    parameters: ["moisture"],
    arguments: ["18"],
    steps: [{ title: "Main Program", description: "Execution reaches check_soil(18)." }, { title: "Function Call", description: "The value 18 is supplied as an argument." }, { title: "Parameter Assignment", description: "moisture receives 18." }, { title: "Function Execution", description: "The body prints the current moisture." }, { title: "Return to Main", description: "The call finishes and the program continues." }],
  },
  agritechExamples: [
    { title: "Inspect many sensor IDs", explanation: "One parameter lets the same inspection function identify every sensor.", code: "def inspect_sensor(sensor_id):\n    print(\"Inspecting Sensor\", sensor_id)\n\ninspect_sensor(101)\ninspect_sensor(205)\ninspect_sensor(312)", output: "Inspecting Sensor 101\nInspecting Sensor 205\nInspecting Sensor 312", functionName: "inspect_sensor", parameters: ["sensor_id"], calls: [{ arguments: ["101"], output: "Inspecting Sensor 101" }, { arguments: ["205"], output: "Inspecting Sensor 205" }, { arguments: ["312"], output: "Inspecting Sensor 312" }] },
    { title: "Map two arguments to two parameters", explanation: "Argument position matters: 101 maps to sensor_id and 34 maps to temperature.", code: "def sensor_status(sensor_id, temperature):\n    print(sensor_id)\n    print(temperature)\n\nsensor_status(101, 34)", output: "101\n34", functionName: "sensor_status", parameters: ["sensor_id", "temperature"], calls: [{ arguments: ["101", "34"], output: "101\n34" }] },
  ],
  mapper: {
    title: "Argument-to-Parameter Mapper",
    body: "Compare the function call with its definition. Each positional argument maps to the parameter in the same position.",
    functionName: "inspect_sensor",
    parameters: ["sensor_id", "location"],
    argumentSets: [{ label: "North Field sensor", arguments: ["101", "\"North Field\""] }, { label: "East Field sensor", arguments: ["205", "\"East Field\""] }, { label: "Swapped values", arguments: ["\"North Field\"", "101"] }],
  },
  simulator: {
    title: "Function Input Simulator",
    body: "Enter a sensor ID and location. DI Notes generates the positional function call and shows how the function would use both values.",
    functionName: "inspect_sensor",
    fields: [{ id: "sensor_id", label: "Sensor ID", type: "number", defaultValue: "205" }, { id: "location", label: "Location", type: "text", defaultValue: "East Field" }],
    parameters: ["sensor_id", "location"],
    outputTemplate: "Checking Sensor {sensor_id} at {location}",
  },
  explorer: {
    title: "Multi-Parameter Explorer",
    body: "Move from one to three parameters and inspect how each positional argument maps to one parameter.",
    examples: [{ label: "One parameter", functionName: "show_crop", parameters: ["crop"], arguments: ["\"Rice\""] }, { label: "Two parameters", functionName: "farm_report", parameters: ["field", "moisture"], arguments: ["\"North\"", "24"] }, { label: "Three parameters", functionName: "sensor_report", parameters: ["sensor_id", "temperature", "location"], arguments: ["101", "34", "\"East Field\""] }],
  },
  comparison: {
    title: "Fixed functions versus parameterized functions",
    body: "Parameters preserve one definition while allowing the behavior to use current input values.",
    rows: [{ feature: "Output", fixed: "Same every time", parameterized: "Depends on supplied input" }, { feature: "Values", fixed: "Hardcoded in body", parameterized: "Passed at the call" }, { feature: "Reusability", fixed: "Limited", parameterized: "High" }, { feature: "Growth", fixed: "More copied functions", parameterized: "One scalable definition" }],
  },
  mistakesTitle: "Common parameter mistakes",
  mistakes: [{ title: "Missing argument", incorrect: "check_soil()", reason: "The definition requires one value for moisture.", correct: "check_soil(20)" }, { title: "Too many arguments", incorrect: "check_soil(20, 30)", reason: "One parameter cannot receive two positional arguments.", correct: "check_soil(20)" }, { title: "Wrong argument order", incorrect: "sensor_status(35, 101)", reason: "35 maps to sensor_id and 101 maps to temperature because position controls mapping.", correct: "sensor_status(101, 35)" }, { title: "Undefined name in body", incorrect: "def check():\n    print(moisture)", reason: "moisture is neither a parameter nor another defined variable in the function.", correct: "def check(moisture):\n    print(moisture)" }],
  debugChallenges: [{ title: "Repair the parameterized header", prompt: "Fix the function header before passing a name.", code: "def greet(name)\n    print(name)", mistakesToFind: 1, solution: "def greet(name):\n    print(name)", hiddenGuidance: "The header needs its closing colon." }, { title: "Repair parameter-body indentation", prompt: "Make the body belong to soil().", code: "def soil(level):\n\nprint(level)", mistakesToFind: 1, solution: "def soil(level):\n    print(level)", hiddenGuidance: "Indent the body statement." }, { title: "Supply the required value", prompt: "The definition expects moisture. Fix the call.", code: "def check_soil(moisture):\n    print(moisture)\n\ncheck_soil()", mistakesToFind: 1, solution: "def check_soil(moisture):\n    print(moisture)\n\ncheck_soil(20)", hiddenGuidance: "Add one positional argument." }, { title: "Match the parameter count", prompt: "The definition accepts one value. Repair the call.", code: "def check_soil(moisture):\n    print(moisture)\n\ncheck_soil(20, 40)", mistakesToFind: 1, solution: "def check_soil(moisture):\n    print(moisture)\n\ncheck_soil(20)", hiddenGuidance: "Remove the extra argument." }],
  engineerScenario: {
    title: "Design for 500 farms",
    scenario: "The Smart Farm platform must inspect hundreds of farms with different IDs, moisture readings, crops, and locations.",
    question: "Which design scales without duplicating a function for every farm?",
    options: [{ label: "Create inspect_farm(farm_id)", explanation: "One definition can receive each farm's current identity through a parameter.", recommended: true }, { label: "Create farm1() through farm500()", explanation: "Hundreds of nearly identical definitions create unnecessary duplication.", recommended: false }, { label: "Hardcode the first farm ID", explanation: "Every call would incorrectly inspect the same farm.", recommended: false }],
  },
  miniProject: {
    title: "Smart Farm Sensor Inspector",
    brief: "Create one sensor inspection function and call it with four different IDs.",
    deliverables: ["Define inspect_sensor(sensor_id)", "Display the received sensor ID", "Call with 101", "Call with 205", "Call with 309", "Call with 415", "Verify four distinct outputs", "Explain why one definition is sufficient"],
    starterCode: "def inspect_sensor(sensor_id):\n    print(\"Checking Sensor\", sensor_id)\n\ninspect_sensor(101)\ninspect_sensor(205)\ninspect_sensor(309)\ninspect_sensor(415)",
    challenge: "Extend the function to accept location as a second positional parameter and display both values.",
  },
};
