import type { MatchCaseLessonDevelopmentPack, MatchCaseOptionContent } from "@/types/content";

const cropOptions: MatchCaseOptionContent[] = [
  { id: "rice", pattern: '"Rice"', label: "Rice", output: "Maintain standing water." },
  { id: "wheat", pattern: '"Wheat"', label: "Wheat", output: "Moderate irrigation." },
  { id: "cotton", pattern: '"Cotton"', label: "Cotton", output: "Avoid overwatering." },
  { id: "crop-default", pattern: "_", label: "Other crop", output: "Unknown Crop" },
];

export const matchCaseDevelopmentPack: MatchCaseLessonDevelopmentPack = {
  kind: "match-case",
  prerequisite: "Lessons 2.1–2.5 · Decision Making through Nested if",
  story: {
    title: "The Smart Farm needs a clear operation menu",
    body: "The controller already evaluates changing sensor conditions. Now the farmer selects a crop from a fixed menu and expects one crop-specific recommendation. This is value selection, not a range comparison.",
    operations: ["Irrigation decisions", "Ventilation decisions", "Weather alerts"],
    menu: ["1 · Rice", "2 · Wheat", "3 · Cotton", "4 · Sugarcane"],
    workflow: { title: "From a selected crop to one recommendation", description: "Python compares the selected value with each case and stops after the first match.", steps: [{ title: "Crop Selected", description: "Read one fixed menu value." }, { title: "Match", description: "Begin pattern matching on that value." }, { title: "Cases", description: "Compare fixed patterns in source order." }, { title: "Matched Case", description: "Execute one corresponding block." }, { title: "Recommendation", description: "Display the crop-specific output." }] },
  },
  whyMatch: {
    title: "Repeated equality checks become difficult to scan",
    body: "An if-elif chain works correctly for a few fixed choices. As a menu grows, match-case makes the one-subject, many-pattern structure more explicit.",
    ifElifCode: "crop = \"Rice\"\n\nif crop == \"Rice\":\n    print(\"Use standing water.\")\nelif crop == \"Wheat\":\n    print(\"Moderate irrigation.\")\nelif crop == \"Cotton\":\n    print(\"Avoid overwatering.\")\nelif crop == \"Sugarcane\":\n    print(\"High water requirement.\")",
    scalingCases: ["20 crops", "50 equipment types", "100 menu options"],
  },
  definition: { title: "match-case selects from fixed patterns", body: "match evaluates one subject. Python compares it with cases in order, executes the first matching block, and uses case _ as an optional default.", items: ["One subject", "Several fixed patterns", "First match executes", "Default case"], rules: ["match starts pattern matching", "case defines an available pattern", "The first matching case executes", "case _ handles unmatched values"] },
  syntax: { title: "One subject, clearly aligned cases", body: "Cases align inside match, while each action is indented inside its case block.", template: "match variable:\n    case value1:\n        statement\n    case value2:\n        statement\n    case _:\n        statement", parts: [{ token: "match variable:", label: "Subject", description: "Evaluate one value to be matched." }, { token: "case value:", label: "Pattern", description: "Define one fixed value or supported pattern." }, { token: "case _:", label: "Default", description: "Handle any value not matched earlier." }, { token: "        statement", label: "Case block", description: "Execute only for the selected case." }] },
  firstExample: { title: "Crop recommendation selector", code: "crop = \"Rice\"\n\nmatch crop:\n    case \"Rice\":\n        print(\"Maintain standing water.\")\n    case \"Wheat\":\n        print(\"Moderate irrigation.\")\n    case \"Cotton\":\n        print(\"Avoid overwatering.\")\n    case _:\n        print(\"Unknown Crop\")", explanation: "Rice matches the first case, executes that block, and stops without checking later cases.", output: "Maintain standing water.", variable: "crop", defaultValue: "Rice", options: cropOptions },
  agritechExamples: [
    { title: "Farm Equipment Menu", code: "equipment = \"Drone\"\n\nmatch equipment:\n    case \"Drone\":\n        print(\"Aerial Crop Monitoring\")\n    case \"Tractor\":\n        print(\"Land Preparation\")\n    case \"Sensor\":\n        print(\"Monitor Soil Moisture\")\n    case _:\n        print(\"Equipment Not Found\")", explanation: "A fixed equipment name maps directly to its operational purpose.", output: "Aerial Crop Monitoring", variable: "equipment", defaultValue: "Drone", options: [{ id: "drone", pattern: '"Drone"', label: "Drone", output: "Aerial Crop Monitoring" }, { id: "tractor", pattern: '"Tractor"', label: "Tractor", output: "Land Preparation" }, { id: "sensor", pattern: '"Sensor"', label: "Sensor", output: "Monitor Soil Moisture" }, { id: "equipment-default", pattern: "_", label: "Other equipment", output: "Equipment Not Found" }] },
    { title: "Irrigation Mode", code: "mode = \"Drip\"\n\nmatch mode:\n    case \"Drip\":\n        print(\"Save Water\")\n    case \"Sprinkler\":\n        print(\"Suitable for Large Fields\")\n    case \"Flood\":\n        print(\"High Water Usage\")\n    case _:\n        print(\"Unknown Mode\")", explanation: "One named irrigation mode selects one usage note.", output: "Save Water", variable: "mode", defaultValue: "Drip", options: [{ id: "drip", pattern: '"Drip"', label: "Drip", output: "Save Water" }, { id: "sprinkler", pattern: '"Sprinkler"', label: "Sprinkler", output: "Suitable for Large Fields" }, { id: "flood", pattern: '"Flood"', label: "Flood", output: "High Water Usage" }, { id: "mode-default", pattern: "_", label: "Other mode", output: "Unknown Mode" }] },
  ],
  menuSimulator: { title: "Smart Farm Menu Simulator", body: "Switch between crop, equipment, and irrigation menus. Select a value and inspect the exact case and output.", menus: [{ id: "crop", label: "Crop", prompt: "Choose a crop", options: cropOptions }, { id: "equipment", label: "Equipment", prompt: "Choose equipment", options: [{ id: "menu-drone", pattern: '"Drone"', label: "Drone", output: "Aerial Crop Monitoring" }, { id: "menu-tractor", pattern: '"Tractor"', label: "Tractor", output: "Land Preparation" }, { id: "menu-sensor", pattern: '"Sensor"', label: "Sensor", output: "Monitor Soil Moisture" }, { id: "menu-equipment-default", pattern: "_", label: "Other", output: "Equipment Not Found" }] }, { id: "mode", label: "Irrigation Mode", prompt: "Choose a mode", options: [{ id: "menu-drip", pattern: '"Drip"', label: "Drip", output: "Save Water" }, { id: "menu-sprinkler", pattern: '"Sprinkler"', label: "Sprinkler", output: "Suitable for Large Fields" }, { id: "menu-flood", pattern: '"Flood"', label: "Flood", output: "High Water Usage" }, { id: "menu-mode-default", pattern: "_", label: "Other", output: "Unknown Mode" }] }] },
  simulatorFields: [{ id: "crop", label: "Crop", prompt: "Enter Crop: ", defaultValue: "Rice", type: "str" }],
  mistakesTitle: "Common pattern-matching mistakes",
  mistakes: [{ title: "Using an unsupported comparison pattern", incorrect: "match temperature:\n    case > 30:\n        print(\"Hot\")", reason: "Basic match-case is for matching patterns, not writing an arbitrary > comparison after case.", correct: "if temperature > 30:\n    print(\"Hot\")" }, { title: "No default for unexpected input", incorrect: "match crop:\n    case \"Rice\":\n        print(\"Water\")", reason: "An unmatched crop produces no output, leaving the learner or operator without feedback.", correct: "match crop:\n    case \"Rice\":\n        print(\"Water\")\n    case _:\n        print(\"Unknown Crop\")" }, { title: "Misaligned case", incorrect: "match crop:\ncase \"Rice\":\n    print(\"Water\")", reason: "Every case belongs inside the match block.", correct: "match crop:\n    case \"Rice\":\n        print(\"Water\")" }],
  debugChallenges: [{ title: "Repair the crop matcher", prompt: "Fix the missing match colon and restore the case hierarchy.", code: "match crop\n\ncase \"Rice\":\n    print(\"Water\")", mistakesToFind: 2, solution: "match crop:\n    case \"Rice\":\n        print(\"Water\")", hiddenGuidance: "The match header needs a colon, and case must be indented inside it." }],
  engineerScenario: { title: "Should irrigation decisions use if or match-case?", scenario: "A Smart Irrigation System must react to moisture ranges, while a separate menu lets an operator select a named irrigation mode.", question: "Which structure belongs to each problem?", options: [{ label: "if for ranges; match-case for the mode menu", explanation: "Conditions model thresholds, while fixed named choices map cleanly to cases.", recommended: true }, { label: "match-case for every threshold", explanation: "A pattern such as case > 30 is not a basic replacement for a comparison condition.", recommended: false }, { label: "if-elif for every menu forever", explanation: "It works, but a large fixed-value menu is often clearer as match-case.", recommended: false }] },
  miniProject: { title: "Mini Project · Smart Farm Menu System", brief: "Create a numbered crop menu and use match-case to display water requirement, fertilizer advice, and harvest season for the selected crop.", deliverables: ["Show Rice, Wheat, Cotton, and Sugarcane options", "Read the menu choice", "Use one match statement", "Add one case per crop", "Display three recommendations per crop", "Add case _ for invalid selections", "Test every crop and one invalid choice"], outputTemplate: "SMART FARM MENU\n----------------\nCrop: Rice\nWater: Standing water\nFertilizer: Balanced nitrogen\nHarvest: 100–150 days" },
  comparison: { title: "Compare & Choose", body: "Use conditions for ranges and dependent logic; use match-case when one value selects from fixed choices.", rows: [{ situation: "Temperature > 35", bestChoice: "if", reason: "A range comparison" }, { situation: "Marks ≥ 40", bestChoice: "if", reason: "A threshold" }, { situation: "Grade calculation", bestChoice: "if-elif-else", reason: "Ordered ranges" }, { situation: "Soil + temperature", bestChoice: "Nested if", reason: "Dependent decisions" }, { situation: "Crop type selection", bestChoice: "match-case", reason: "Fixed values" }, { situation: "Menu selection", bestChoice: "match-case", reason: "Fixed options" }, { situation: "ATM menu", bestChoice: "match-case", reason: "Fixed commands" }] },
  structureAdvisor: { title: "Structure Advisor", body: "Choose the control-flow structure that best expresses each requirement, then reveal the engineering rationale.", scenarios: [{ prompt: "Send a heat alert only when temperature exceeds 40°C.", answer: "if", explanation: "One condition guards one action." }, { prompt: "Display Pump ON or Pump OFF.", answer: "if-else", explanation: "One condition has two outcomes." }, { prompt: "Classify soil moisture into four ranges.", answer: "if-elif-else", explanation: "Several ordered alternatives classify a numeric range." }, { prompt: "Check dry soil, then temperature only when dry.", answer: "nested-if", explanation: "The second decision depends on the first." }, { prompt: "Choose an action from a crop menu.", answer: "match-case", explanation: "One selected value maps to a fixed option." }] },
};
