import type { DataTypeLessonDevelopmentPack } from "@/types/content";

export const dataTypesDevelopmentPack: DataTypeLessonDevelopmentPack = {
  kind: "data-types",
  prerequisite: "Lesson 1.2",
  story: {
    title: "A farm record contains different kinds of information",
    body: "A farmer name and crop are text, temperature can include a decimal, livestock count is a whole number, and irrigation status has only two states. Python uses data types to preserve these differences.",
    facts: [
      { label: "Farmer name", value: "Rahul", type: "str" },
      { label: "Crop", value: "Rice", type: "str" },
      { label: "Temperature", value: "32.5", type: "float" },
      { label: "Number of cows", value: "12", type: "int" },
      { label: "Irrigation on", value: "True", type: "bool" },
    ],
    workflow: {
      title: "From farm data to Python data types",
      description: "Different observations need different representations before a program can use them correctly.",
      steps: [
        { title: "Farm data", description: "The farm produces names, measurements, counts, and status values." },
        { title: "Text", description: "Names and labels are represented as strings." },
        { title: "Numbers", description: "Counts are represented as integers." },
        { title: "Decimal numbers", description: "Measurements with decimal precision are represented as floats." },
        { title: "True or False", description: "Two-state information is represented as a Boolean." },
        { title: "Python data types", description: "The type determines how each value can behave." },
      ],
    },
  },
  definition: {
    title: "What is a data type?",
    body: "A data type tells Python what kind of value is being stored and helps determine how that value behaves in a program.",
    code: "crop = \"Rice\"\ntemperature = 31\nrainfall = 120.5\nis_raining = True",
    workflow: {
      title: "From variable to memory representation",
      description: "Follow a named value through the information Python manages.",
      steps: [
        { title: "Variable", description: "A readable name identifies the information." },
        { title: "Value", description: "The current information is bound to the name." },
        { title: "Data type", description: "Python identifies the value as int, float, str, bool, or NoneType." },
        { title: "Memory", description: "Python manages an appropriate value object in memory." },
      ],
    },
  },
  whyTypesMatter: {
    title: "Why do data types matter?",
    body: "The same characters can behave differently when they represent numbers or text. Predict each result before revealing the output.",
    predictions: [
      { title: "Add two integers", code: "print(10 + 20)", options: ["30", "1020", "Error"], answer: "30", explanation: "Integer values are added numerically." },
      { title: "Join two strings", code: "print(\"10\" + \"20\")", options: ["30", "1020", "Error"], answer: "1020", explanation: "The + symbol joins these two strings in this example." },
    ],
  },
  types: { title: "Compare Python's foundational value types", body: "Select a type to inspect its definition, examples, agricultural use, and visual value sequence.", items: [
    {
      type: "int",
      title: "Integer (int)",
      definition: "Whole numbers without a decimal point.",
      examples: "age = 24\nstudents = 120\ntrees = 500\ncows = 12",
      agritechExample: "total_plants = 2500",
      visualValues: ["0", "10", "50", "100", "500"],
    },
    {
      type: "float",
      title: "Float (float)",
      definition: "Numbers containing a decimal point.",
      examples: "temperature = 32.7\nrainfall = 120.45\nsoil_ph = 6.8",
      agritechExample: "soil_moisture = 42.75",
      visualValues: ["31", "31.5", "31.75", "32.10"],
    },
    {
      type: "str",
      title: "String (str)",
      definition: "Text enclosed in matching quotation marks.",
      examples: "farmer_name = \"Rahul\"\ncrop = \"Rice\"\nvillage = \"Panvel\"",
      agritechExample: "crop_variety = \"Basmati\"",
      visualValues: ["Rahul", "Rice", "Panvel"],
    },
    {
      type: "bool",
      title: "Boolean (bool)",
      definition: "A logical value that is exactly True or False.",
      examples: "is_raining = True\npump_on = False",
      agritechExample: "is_motor_running = True",
      visualValues: ["True", "False"],
    },
    {
      type: "NoneType",
      title: "None (NoneType)",
      definition: "The absence of a value, often used while information is not available yet.",
      examples: "sensor_data = None\nlatest_rainfall = None",
      agritechExample: "new_sensor_reading = None",
      visualValues: ["No reading yet", "Not available"],
    },
  ] },
  stringQuotes: {
    title: "Strings need quotation marks",
    body: "Without quotes, Python treats Rice as a variable name and looks for a value bound to that name.",
    quotedCode: "crop = \"Rice\"\nprint(crop)",
    unquotedCode: "crop = Rice\nprint(crop)",
    success: "Rice",
    error: "NameError: name 'Rice' is not defined",
  },
  booleanSwitch: {
    title: "A Boolean models a two-state switch",
    body: "Use True and False with capital first letters. They are Python values, not quoted text.",
    onName: "is_motor_running = True",
    offName: "is_motor_running = False",
  },
  typeFunction: {
    title: "Inspect a value with type()",
    body: "The built-in type function reports the data type of the current value.",
    examples: [
      { title: "Inspect an integer", code: "age = 24\nprint(type(age))", explanation: "The value 24 is an integer.", output: "<class 'int'>" },
      { title: "Inspect a string", code: "crop = \"Rice\"\nprint(type(crop))", explanation: "The quoted value is a string.", output: "<class 'str'>" },
      { title: "Inspect a float", code: "temperature = 31.5\nprint(type(temperature))", explanation: "A number with a decimal point is a float.", output: "<class 'float'>" },
      { title: "Inspect a Boolean", code: "pump_on = True\nprint(type(pump_on))", explanation: "True is a Boolean value.", output: "<class 'bool'>" },
      { title: "Inspect None", code: "sensor_data = None\nprint(type(sensor_data))", explanation: "The type of None is NoneType.", output: "<class 'NoneType'>" },
    ],
  },
  conversions: {
    title: "Convert values between compatible data types",
    body: "Conversion creates a value of another type. It succeeds only when the source value has a compatible form.",
    items: [
      { from: "str", to: "int", code: "age = \"24\"\nprint(int(age))", input: "\"24\"", output: "24", explanation: "A string containing whole-number digits can be converted to int." },
      { from: "int", to: "float", code: "marks = 98\nprint(float(marks))", input: "98", output: "98.0", explanation: "Converting an integer to float adds decimal representation." },
      { from: "float", to: "int", code: "price = 99.9\nprint(int(price))", input: "99.9", output: "99", explanation: "int() truncates the decimal portion; it does not round the value." },
      { from: "int", to: "str", code: "temperature = 31\nprint(str(temperature))", input: "31", output: "\"31\"", explanation: "str() creates a text representation of the number." },
    ],
  },
  agritechProgram: {
    title: "A typed farm information record",
    code: "farmer = \"Rahul\"\ncrop = \"Rice\"\ntemperature = 31.5\nsoil_moisture = 42\nmotor_on = True\nsensor_data = None",
    explanation: "Each value uses a type that matches the information it represents: text, a decimal measurement, a whole-number reading, a two-state status, or missing information.",
    output: "farmer → Rahul → str\ncrop → Rice → str\ntemperature → 31.5 → float\nsoil_moisture → 42 → int\nmotor_on → True → bool\nsensor_data → None → NoneType",
  },
  playgroundActivities: ["Change the temperature to a whole number", "Change plants to a decimal value", "Switch motor_on to False", "Replace sensor_data with a reading", "Add and inspect a crop variable"],
  mistakesTitle: "Repair common data-type mistakes",
  mistakes: [
    { title: "Missing string quotes", incorrect: "crop = Rice", reason: "Python treats Rice as another variable name.", correct: "crop = \"Rice\"" },
    { title: "Number stored as text", incorrect: "temperature = \"31\"", reason: "Quoted digits are text and do not behave like a measurement in numerical work.", correct: "temperature = 31" },
    { title: "Lowercase Boolean", incorrect: "motor_on = true", reason: "Python Boolean values are spelled True and False with capital first letters.", correct: "motor_on = True" },
    { title: "Text used in a numerical expression", incorrect: "plants = \"200\"\nprint(plants + 50)", reason: "A string and integer cannot be combined by this expression.", correct: "plants = 200\nprint(plants + 50)" },
  ],
  debugChallenge: {
    title: "Find the data-type mistakes",
    prompt: "Inspect quotation marks, Boolean spelling, and which values must participate in numerical work.",
    code: "crop = Rice\ntemperature = \"31\"\npump = true\nplants = \"200\"\nprint(plants + 50)",
    mistakesToFind: 4,
    solution: "crop = \"Rice\"\ntemperature = 31\npump = True\nplants = 200\nprint(plants + 50)",
    hiddenGuidance: "Check the text value, measurement, Boolean capitalization, and plant count before revealing the solution.",
  },
  engineerScenario: {
    title: "Choose types for a weather station",
    scenario: "A weather station provides temperature, humidity, rainfall, motor status, farmer name, and whether GPS information is currently available.",
    question: "Which representation best preserves the meaning of the current information?",
    options: [
      { label: "float, float, float, bool, str, bool", explanation: "Measurements can use floats, the motor and GPS availability are two-state Booleans, and the farmer name is text.", recommended: true },
      { label: "str for every value", explanation: "Text would display the readings but would make later numerical analysis harder without conversion.", recommended: false },
      { label: "int for every value", explanation: "Integers cannot represent the farmer name or all decimal measurements and statuses appropriately.", recommended: false },
      { label: "None for every value", explanation: "None represents missing information, not readings that are currently available.", recommended: false },
    ],
  },
};
