import type { VariableScopeLessonDevelopmentPack } from "@/types/content";

export const variableScopeDevelopmentPack: VariableScopeLessonDevelopmentPack = {
  kind:"variable-scope",prerequisite:"Lessons 3.1–3.5 · Functions, Parameters, Return Values, and Argument Styles",
  evolution:{title:"Function Evolution Timeline",body:"Lesson 3.6 reveals where each name lives while a function runs.",stages:[{lesson:"3.2",code:"Create Function",capability:"Define reusable work"},{lesson:"3.3",code:"Accept Inputs",capability:"Receive changing values"},{lesson:"3.4",code:"Return Outputs",capability:"Produce reusable results"},{lesson:"3.5",code:"Flexible Function Calls",capability:"Choose how values bind"},{lesson:"3.6",code:"Variable Scope",capability:"Understand where names live",active:true},{lesson:"3.7",code:"Anonymous Functions",capability:"Create compact functions"},{lesson:"3.8",code:"Recursion",capability:"Functions call themselves"},{lesson:"3.9",code:"Best Practices",capability:"Design maintainable functions"},{lesson:"3.10",code:"Capstone",capability:"Integrate the module"}]},
  lifecycle:{title:"Function Lifecycle",body:"Scope boundaries become visible when Python enters a function, creates local names, returns, and destroys that local frame.",activeStep:"Execute Code",steps:[{title:"Define Function",description:"Create a local boundary."},{title:"Call Function",description:"Enter a new call frame."},{title:"Receive Arguments",description:"Create parameter names locally."},{title:"Execute Code",description:"Create and use local variables."},{title:"Return Value",description:"Send data beyond the boundary."},{title:"Continue Program",description:"Destroy the finished local frame."}]},
  story:{title:"Some farm information belongs everywhere; some belongs to one task",body:"The application-wide dashboard needs farm_name. The temporary water calculation belongs only to irrigation. Scope gives each name a clear visibility boundary.",globalVariable:{name:"farm_name",value:"Green Valley Farm",scope:"global",owner:"Main Program",lifetime:"Program start → program end"},localVariable:{name:"water_required",value:"100",scope:"local",owner:"irrigation()",lifetime:"Function entry → function exit"}},
  definition:{title:"Scope is a variable's visibility area",body:"A name can be used only from locations where it is visible. Crossing a scope boundary can make a name unavailable even though the same text appeared elsewhere in the program.",analogy:[{title:"Entire Farm",access:"Shared operational information",scope:"Global area"},{title:"Manager's Office",access:"Information for one responsibility",scope:"Function area"},{title:"Private Locker",access:"Only the current owner can access it",scope:"Local variable"}]},
  local:{title:"A local variable belongs to one function call",explanation:"water is created inside irrigation(), used there, and removed when that call finishes. The main program has no water name.",code:"def irrigation():\n    water = 100\n    print(water)\n\nirrigation()",output:"100",variable:{name:"water",value:"100",scope:"local",owner:"irrigation()",lifetime:"Function entry → function exit"},outsideCode:"print(water)",outsideResult:"NameError: name 'water' is not defined"},
  global:{title:"A global variable is visible across the program",explanation:"farm_name is created in the main program. show() can read it because no local farm_name hides it.",code:"farm_name = \"Green Valley\"\n\ndef show():\n    print(farm_name)\n\nshow()",output:"Green Valley",variable:{name:"farm_name",value:"Green Valley",scope:"global",owner:"Main Program",lifetime:"Program start → program end"},reader:"show()"},
  shadowing:{title:"A local name can shadow a global name",explanation:"Inside display(), Python chooses the local farm. After the call finishes, the main program still sees the unchanged global farm.",code:"farm = \"Global Farm\"\n\ndef display():\n    farm = \"Local Farm\"\n    print(farm)\n\ndisplay()\nprint(farm)",output:"Local Farm\nGlobal Farm",globalValue:"Global Farm",localValue:"Local Farm"},
  lifetime:{title:"Variable Lifetime Timeline",body:"Visibility and lifetime are connected: a global name lasts through the program, while a local name lives only inside its active function call.",globalSteps:[{title:"Program Starts",description:"Create the global frame."},{title:"farm_name created",description:"Name becomes globally visible."},{title:"Functions run",description:"They may read the global value."},{title:"Program Ends",description:"Global frame is released."}],localSteps:[{title:"Function Entry",description:"Create a local call frame."},{title:"water created",description:"Name becomes locally visible."},{title:"Function Executes",description:"Use local data safely."},{title:"Function Exit",description:"Destroy the local frame."}]},
  boundaries:{title:"Scope Boundary Visualizer",body:"The main program owns global names. Every function call gets its own local box, isolated from sibling functions.",globalVariables:[{name:"farm_name",value:"Green Valley",scope:"global",owner:"Main Program",lifetime:"Whole program"}],functions:[{name:"irrigation()",variables:[{name:"water",value:"100",scope:"local",owner:"irrigation()",lifetime:"One irrigation call"}]},{name:"weather()",variables:[{name:"temperature",value:"32",scope:"local",owner:"weather()",lifetime:"One weather call"}]}]},
  explorer:{title:"Scope Explorer",body:"Move through execution phases and watch local variables appear inside their function boundary, then disappear at function exit.",phases:[{label:"Program starts",activeFrame:"Main Program",visible:["farm_name"],destroyed:[]},{label:"Enter irrigation",activeFrame:"irrigation()",visible:["farm_name"],destroyed:[]},{label:"Create water",activeFrame:"irrigation()",visible:["farm_name","water"],destroyed:[]},{label:"Exit irrigation",activeFrame:"Main Program",visible:["farm_name"],destroyed:["water"]}]},
  comparison:{title:"Choose the smallest useful scope",body:"Local variables are normally safer for reusable functions. Use parameters and returned values to communicate instead of shared mutable global state.",rows:[{feature:"Created inside a function",local:"Yes",global:"No"},{feature:"Accessible outside its function",local:"No",global:"Yes"},{feature:"Lifetime",local:"Active function call",global:"Whole program"},{feature:"Preferred for reusable functions",local:"Yes",global:"Usually no"},{feature:"Unintended-change risk",local:"Lower",global:"Higher"}]},
  agritechExamples:[{title:"Read global farm identity and local water",explanation:"irrigation() can read farm_name and use its own private water value.",code:"farm_name = \"Green Valley\"\n\ndef irrigation():\n    water = 100\n    print(farm_name)\n    print(water)\n\nirrigation()",output:"Green Valley\n100"},{title:"Sibling functions have separate local scopes",explanation:"water belongs to irrigation and temperature belongs to weather; neither local name leaks into the other function.",code:"def irrigation():\n    water = 100\n    print(water)\n\ndef weather():\n    temperature = 32\n    print(temperature)\n\nirrigation()\nweather()",output:"100\n32"}],
  mistakesTitle:"Common scope mistakes",mistakes:[{title:"Using a local variable outside",incorrect:"def test():\n    value = 10\n\nprint(value)",reason:"value exists only while test() is running.",correct:"def test():\n    value = 10\n    print(value)"},{title:"Mistaking shadowing for global modification",incorrect:"count = 5\ndef demo():\n    count = 20\n    print(count)",reason:"The assignment creates a separate local count; the global remains 5.",correct:"count = 5\ndef demo():\n    local_count = 20\n    print(local_count)"},{title:"Assuming a local persists",incorrect:"def calculate():\n    total = 100\ncalculate()\nprint(total)",reason:"The local frame and total disappear after calculate() returns.",correct:"def calculate():\n    return 100\ntotal = calculate()\nprint(total)"}],
  debugChallenges:[{title:"Keep water inside its boundary",prompt:"Explain the NameError and move the display to a visible location.",code:"def irrigation():\n    water = 100\n\nprint(water)",mistakesToFind:1,solution:"def irrigation():\n    water = 100\n    print(water)\n\nirrigation()",hiddenGuidance:"water is local to irrigation()."},{title:"Predict the visible farm",prompt:"Predict the output without adding global mutation.",code:"farm = \"A\"\n\ndef test():\n    farm = \"B\"\n\nprint(farm)",mistakesToFind:0,solution:"A",hiddenGuidance:"test() is not called, and its local farm would not replace the global anyway."},{title:"Return local data safely",prompt:"Make season available to the main program using return.",code:"def crop():\n    season = \"Summer\"\n\ncrop()\nprint(season)",mistakesToFind:1,solution:"def crop():\n    season = \"Summer\"\n    return season\n\nseason = crop()\nprint(season)",hiddenGuidance:"Communicate across the boundary with a returned value."}],
  engineerScenario:{title:"Limit shared state across Smart Farm modules",scenario:"Dashboard, irrigation, weather, reports, and AI recommendation all need to collaborate without accidentally overwriting each other's temporary calculations.",question:"Which design creates clearer ownership and fewer side effects?",options:[{label:"Local variables plus parameters and return values",explanation:"Each module owns temporary state and exchanges intentional data through explicit interfaces.",recommended:true},{label:"Let every module modify shared globals",explanation:"Any module can unexpectedly change state used elsewhere.",recommended:false},{label:"Copy every variable into every module",explanation:"Duplicated state becomes inconsistent and difficult to maintain.",recommended:false}]},
  miniProject:{title:"Smart Farm Dashboard",brief:"Keep farm identity global while giving irrigation and weather separate local working data.",deliverables:["Create global farm_name","Create irrigation()","Create local water","Read farm_name inside irrigation()","Create weather()","Create local temperature","Run both functions","Explain why sibling locals are isolated"],starterCode:"farm_name = \"Green Valley\"\n\ndef irrigation():\n    water = 100\n    print(\"Farm:\", farm_name)\n    print(\"Water:\", water)\n\nirrigation()",challenge:"Add weather() with its own local temperature. Confirm temperature is not visible inside irrigation() and communicate any needed result with return."},
};
