import type { RecursionLessonDevelopmentPack } from "@/types/content";

export const recursionDevelopmentPack: RecursionLessonDevelopmentPack = {
  kind: "recursion",
  prerequisite: "Lessons 3.1–3.7 · Complete the core function journey through Lambda Functions",
  evolution: { title: "Function Evolution Timeline", body: "Lesson 3.8 shows how a named function can temporarily call another instance of itself.", stages: [
    { lesson:"3.2",code:"Create Function",capability:"Define reusable work" },{ lesson:"3.3",code:"Accept Inputs",capability:"Receive changing values" },{ lesson:"3.4",code:"Return Outputs",capability:"Produce reusable results" },{ lesson:"3.5",code:"Flexible Function Calls",capability:"Choose how values bind" },{ lesson:"3.6",code:"Variable Scope",capability:"Understand where names live" },{ lesson:"3.7",code:"Anonymous Functions",capability:"Express one small operation" },{ lesson:"3.8",code:"Recursion",capability:"Solve a smaller same problem",active:true },{ lesson:"3.9",code:"Best Practices",capability:"Design maintainable functions" },{ lesson:"3.10",code:"Capstone",capability:"Integrate the module" },
  ] },
  lifecycle: { title:"Function Lifecycle",body:"Every recursive call receives its own arguments and local frame. A base-case return ends the deepest call, then waiting frames resume in reverse order.",activeStep:"Call Function",steps:[{title:"Call Function",description:"Start with the current problem."},{title:"Check Base Case",description:"Stop if the smallest case is reached."},{title:"Smaller Call",description:"Call the same function with less work."},{title:"Stack Grows",description:"Each caller waits in its own frame."},{title:"Return Value",description:"The base case starts the return path."},{title:"Unwind Stack",description:"Waiting callers finish in reverse order."}] },
  story: { title:"A farm contains smaller structures that look like the whole",body:"Fields contain zones, zones contain sensor groups, and groups contain sensors. Instead of designing a different traversal for every depth, recognize the same inspect-children responsibility at each smaller level.",hierarchy:[{id:"farm",label:"Farm"},{id:"zone-a",label:"Zone A",parentId:"farm"},{id:"zone-b",label:"Zone B",parentId:"farm"},{id:"group-1",label:"Group 1",parentId:"zone-a"},{id:"group-2",label:"Group 2",parentId:"zone-a"},{id:"group-3",label:"Group 3",parentId:"zone-b"},{id:"sensor",label:"Sensors",parentId:"group-3"}],insight:"Every branch is a smaller version of the same hierarchical inspection problem." },
  definition: { title:"Recursion solves a problem through a smaller version of itself",body:"A recursive function calls itself with reduced work until a stopping condition is reached. The technique fits self-similar problems, not every repetition.",items:["Same problem shape","Smaller input","Self-call","Base case","Waiting frames","Return path"],analogy:["Big nesting doll","Medium nesting doll","Small nesting doll","Tiny nesting doll","No more dolls"],rule:"Smaller problem → same solution → repeat until the base case" },
  decomposition: { title:"Make the remaining problem visibly smaller",body:"Countdown is familiar from loops, so it isolates the new idea: the current function delegates the remaining countdown to a smaller call.",problem:"Count down from 4",levels:[{call:"countdown(4)",remaining:"Print 4; solve countdown from 3"},{call:"countdown(3)",remaining:"Print 3; solve countdown from 2"},{call:"countdown(2)",remaining:"Print 2; solve countdown from 1"},{call:"countdown(1)",remaining:"Print 1; solve countdown from 0"},{call:"countdown(0)",remaining:"Base case: print Done and stop"}] },
  baseCase: { title:"The base case is the stopping contract",body:"Before making another self-call, the function must recognize a smallest problem it can answer directly. Without that contract, frames continue growing until Python raises RecursionError.",safeCode:"if n == 0:\n    print(\"Done\")\n    return",unsafeCode:"def countdown(n):\n    print(n)\n    countdown(n - 1)",warning:"No reachable base case: this function keeps creating calls." },
  recursiveCase: { title:"The recursive case must move toward the base case",body:"After handling the current value, countdown delegates a strictly smaller value. Changing n to n - 1 is the progress guarantee.",currentProblem:"countdown(n)",smallerProblem:"countdown(n - 1)",movementRule:"For a base case of n == 0, positive n must decrease on every call." },
  countdown: { title:"First recursive function: countdown",explanation:"Countdown checks its base case before printing and calling itself with one less remaining step.",code:"def countdown(n):\n    if n == 0:\n        print(\"Done\")\n        return\n\n    print(n)\n    countdown(n - 1)\n\ncountdown(5)",output:"5\n4\n3\n2\n1\nDone",functionName:"countdown",initialValue:5,baseValue:0,direction:"decrease" },
  stack: { title:"Call Stack Animator",body:"Grow the stack one call at a time, reach countdown(0), then unwind in reverse order as every waiting call returns.",functionName:"countdown",initialValue:3,baseValue:0 },
  agritechExamples: [{ title:"Inspect farm levels recursively",explanation:"Each call inspects one hierarchy level and delegates the remaining lower levels.",code:"def inspect_zone(level):\n    if level == 0:\n        print(\"Inspection Complete\")\n        return\n\n    print(\"Inspecting Level\", level)\n    inspect_zone(level - 1)\n\ninspect_zone(4)",output:"Inspecting Level 4\nInspecting Level 3\nInspecting Level 2\nInspecting Level 1\nInspection Complete",functionName:"inspect_zone",initialValue:4,baseValue:0,direction:"decrease" }],
  factorial: { title:"Only now: recursive factorial",explanation:"Each frame waits for the smaller factorial result before multiplying. The return path performs the deferred work.",code:"def factorial(n):\n    if n == 1:\n        return 1\n\n    return n * factorial(n - 1)\n\nprint(factorial(4))",output:"24",input:4,expansion:["4 × factorial(3)","4 × 3 × factorial(2)","4 × 3 × 2 × factorial(1)","4 × 3 × 2 × 1","24"],result:24 },
  comparison: { title:"Choose by problem shape, not novelty",body:"Loops and recursion can sometimes solve the same task. Prefer the version whose control flow makes the problem easiest to understand and operate safely.",rows:[{feature:"How repetition happens",loop:"Iteration statement",recursion:"Function calls itself"},{feature:"State",loop:"Loop variables",recursion:"Separate call frames"},{feature:"Memory",loop:"Usually lower",recursion:"Uses call stack"},{feature:"Simple counting",loop:"Usually clearer",recursion:"Possible, often unnecessary"},{feature:"Hierarchical traversal",loop:"Possible with explicit stack",recursion:"Often maps naturally"},{feature:"Stopping rule",loop:"Loop condition",recursion:"Reachable base case"}] },
  detector: { title:"Base Case Detector",body:"Compare safe and unsafe recursive shapes. A base case is not enough by itself—the recursive input must also move toward it.",examples:[{label:"Safe countdown",code:"def count(n):\n    if n == 0:\n        return\n    count(n - 1)",hasBaseCase:true,movesTowardBase:true,explanation:"The call stops at zero and positive n decreases toward zero."},{label:"No base case",code:"def demo():\n    demo()",hasBaseCase:false,movesTowardBase:false,explanation:"Nothing stops the self-call."},{label:"Moves away",code:"def count(n):\n    if n == 0:\n        return\n    count(n + 1)",hasBaseCase:true,movesTowardBase:false,explanation:"Positive n grows, so it never reaches zero."},{label:"No progress",code:"def count(n):\n    if n == 0:\n        return\n    count(n)",hasBaseCase:true,movesTowardBase:false,explanation:"The next problem is identical rather than smaller."}] },
  mistakesTitle:"Common recursion mistakes",mistakes:[{title:"Missing base case",incorrect:"def test():\n    test()",reason:"Every call creates another identical frame until RecursionError.",correct:"def test(remaining):\n    if remaining == 0:\n        return\n    test(remaining - 1)"},{title:"Moving away from zero",incorrect:"def countdown(n):\n    if n == 0:\n        return\n    countdown(n + 1)",reason:"A positive starting value grows instead of approaching the base case.",correct:"def countdown(n):\n    if n == 0:\n        return\n    countdown(n - 1)"},{title:"Making no progress",incorrect:"def count(n):\n    if n == 0:\n        return\n    count(n)",reason:"Every frame receives the same n, so the base case is never closer.",correct:"def count(n):\n    if n == 0:\n        return\n    count(n - 1)"}],
  debugChallenges:[{title:"Stop the infinite self-call",prompt:"Explain why demo never stops and add a decreasing input with a base case.",code:"def demo():\n    demo()",mistakesToFind:1,solution:"def demo(n):\n    if n == 0:\n        return\n    demo(n - 1)\n\ndemo(3)",hiddenGuidance:"Every recursive design needs a smallest direct answer."},{title:"Trace the reachable base case",prompt:"Predict what happens when test(1) runs.",code:"def test(n):\n    if n == 5:\n        return\n    test(n + 1)\n\ntest(1)",mistakesToFind:0,solution:"test receives 1, 2, 3, 4, then 5. The base case returns and all five frames unwind.",hiddenGuidance:"The increasing call is safe here because the base case is above the starting value."},{title:"Make the problem smaller",prompt:"Repair the recursive call so count reaches zero.",code:"def count(n):\n    if n == 0:\n        return\n    count(n)",mistakesToFind:1,solution:"def count(n):\n    if n == 0:\n        return\n    count(n - 1)",hiddenGuidance:"Pass n - 1 rather than the unchanged n."}],
  engineerScenario: { title:"Match control flow to hierarchical data",scenario:"The platform must inspect nested folders, a family tree, an organization chart, and Farm → Zone → Group → Sensor structures of unknown depth.",question:"Which approach most directly mirrors the self-similar structure?",options:[{label:"A bounded recursive traversal with a clear base case",explanation:"Each node applies the same child-inspection rule, and an empty child list stops that branch.",recommended:true},{label:"Hardcode one loop for every possible level",explanation:"Unknown or changing depth makes the implementation brittle and difficult to maintain.",recommended:false},{label:"Use recursion for every repetition",explanation:"Simple fixed counting is usually clearer and more memory-efficient with a loop.",recommended:false}] },
  miniProject: { title:"Smart Farm Inspection System",brief:"Inspect one level, delegate the remaining levels, and make the return path visible.",deliverables:["Define inspect_zone(level)","Stop when level equals zero","Print Inspection Complete at the base case","Print the current zone before the self-call","Call inspect_zone(level - 1)","Test at levels 0, 1, and 4","Explain the growing stack","Explain the unwind order"],starterCode:"def inspect_zone(level):\n    if level == 0:\n        print(\"Inspection Complete\")\n        return\n\n    print(\"Inspecting Zone\", level)\n    inspect_zone(level - 1)\n\ninspect_zone(4)",challenge:"After the recursive call, print Leaving Zone and the current level. Predict why those messages appear in reverse order." },
};
