import type { VariableLessonDevelopmentPack } from "@/types/content";

export const variablesDevelopmentPack: VariableLessonDevelopmentPack = {
  kind: "variables",
  prerequisite: "Lesson 1.1",
  story: {
    title: "A farmer needs a reliable place for changing information",
    body: "A farmer manages many facts: livestock count, farm area, crop, soil moisture, and temperature. A notebook gives each fact a label so it can be found and updated. Python variables serve the same purpose inside a program.",
    facts: ["10 cows", "25 acres", "Rice crop", "Soil moisture: 40%", "Temperature: 31°C"],
    workflow: {
      title: "From farm information to Python memory",
      description: "Follow a value from the farmer's observation to a named variable managed by Python.",
      steps: [
        { title: "Farmer", description: "Observes a useful fact about the farm." },
        { title: "Notebook", description: "Associates the fact with a meaningful label." },
        { title: "Information stored", description: "Keeps the fact available for later use." },
        { title: "Python variable", description: "Gives the value a name inside the program." },
        { title: "Memory", description: "Python manages the value in computer memory." },
      ],
    },
  },
  definition: {
    title: "What is a variable?",
    body: "A variable is a name bound to a value that Python manages in memory. Think of the name as a label on a storage box: the label tells the program which value to use.",
    examples: [
      { name: "crop", value: "Rice" },
      { name: "temperature", value: "31" },
      { name: "farmer", value: "Rahul" },
    ],
  },
  whyVariables: {
    title: "Why do we need variables?",
    body: "Unlabelled values lose their meaning. Variables make each value understandable, reusable, and easier to update.",
    question: "What does 31 represent—temperature, age, or rainfall?",
    answer: "The name temperature preserves the meaning of 31 wherever the program uses it.",
    withoutVariables: "print(\"Rahul\")\nprint(\"Rice\")\nprint(31)\nprint(40)",
    withVariables: "farmer = \"Rahul\"\ncrop = \"Rice\"\ntemperature = 31\nsoil_moisture = 40\n\nprint(farmer)\nprint(crop)\nprint(temperature)\nprint(soil_moisture)",
  },
  memory: {
    title: "Names connect a program to values in memory",
    body: "Python creates and manages value objects in memory. A variable name refers to one of those values. Reassignment can bind the same name to a new value, and Python manages the underlying memory automatically.",
    items: ["Variable name", "Managed memory", "Current value"],
  },
  creating: {
    title: "Creating variables",
    body: "Write a meaningful name, the assignment symbol, and a value. Python creates the name when it executes the statement.",
    syntax: "variable_name = value",
    examples: "farmer_name = \"Suraj\"\nfarm_area = 24\ntemperature = 31.5\nis_raining = True",
    workflow: {
      title: "How assignment stores a value",
      description: "Read the assignment from the value being stored to the name that will refer to it.",
      steps: [
        { title: "Value", description: "The information a program needs to remember." },
        { title: "Assignment operator", description: "The = symbol binds the name to the value." },
        { title: "Variable", description: "A meaningful name becomes available to the program." },
        { title: "Memory", description: "Python manages the value in memory." },
      ],
    },
  },
  assignment: {
    title: "The = symbol means assign",
    body: "In a Python assignment statement, = instructs Python to bind the name on the left to the value on the right.",
    symbol: "=",
    example: "crop = \"Rice\"",
    reading: "Store the value \"Rice\" and let the name crop refer to it.",
    misconception: "Do not read this as a mathematical equality test. Comparing values is a later topic.",
  },
  namingRules: { title: "Test a Python variable name", body: "Enter a name or select an example to classify it as valid or invalid.", rules: [
    { example: "crop_name", valid: true, explanation: "Letters and an underscore form a readable name." },
    { example: "soilMoisture", valid: true, explanation: "Names can contain uppercase letters after the first character." },
    { example: "temperature2", valid: true, explanation: "Digits are allowed after the first character." },
    { example: "_farmer", valid: true, explanation: "An underscore is allowed as the first character." },
    { example: "2crop", valid: false, explanation: "A variable name cannot begin with a digit." },
    { example: "crop-name", valid: false, explanation: "A hyphen is not allowed inside a variable name." },
    { example: "crop name", valid: false, explanation: "Spaces are not allowed inside a variable name." },
    { example: "class", valid: false, explanation: "Reserved Python keywords cannot be used as variable names." },
  ] },
  namingConventions: { title: "Choose names that preserve meaning", body: "Readable code saves time because each name explains the value's purpose.", tiers: [
    { label: "Poor", examples: ["a", "b", "x"], explanation: "These names do not explain what the values represent." },
    { label: "Better", examples: ["crop", "temperature", "rainfall"], explanation: "These names communicate the subject of each value." },
    { label: "Best", examples: ["average_soil_moisture", "annual_crop_yield", "recommended_water_level"], explanation: "Specific snake_case names preserve meaning for future readers." },
  ] },
  printing: [
    { title: "Print a farmer name", code: "farmer = \"Rahul\"\nprint(farmer)", explanation: "Pass the variable name to print; quotation marks would print the word farmer instead.", output: "Rahul" },
    { title: "Print a temperature", code: "temperature = 30\nprint(temperature)", explanation: "Python reads the current value referred to by temperature.", output: "30" },
    { title: "Print two variables", code: "crop = \"Rice\"\ntemperature = 31\nprint(crop)\nprint(temperature)", explanation: "Each print statement reads the current value of its variable.", output: "Rice\n31" },
  ],
  dynamicTyping: {
    title: "A name can be rebound to a different kind of value",
    code: "sensor_reading = 42\nprint(sensor_reading)\n\nsensor_reading = \"offline\"\nprint(sensor_reading)",
    explanation: "Python does not require a fixed type declaration for a variable name. The name can later refer to another value, and the inspector reports the type of the current value.",
    output: "42\noffline",
  },
  updating: {
    title: "Updating a variable",
    code: "water_level = 50\nprint(water_level)\n\nwater_level = 75\nprint(water_level)",
    explanation: "The latest assignment changes which value the name refers to. Later statements use the updated value.",
    output: "50\n75",
    workflow: [
      { title: "50", description: "The first value assigned to water_level." },
      { title: "75", description: "A later assignment updates water_level." },
      { title: "100", description: "Another assignment could update it again." },
    ],
  },
  multipleAssignment: {
    title: "Multiple assignment",
    code: "temperature, humidity, rainfall = 31, 68, 120\nprint(temperature)\nprint(humidity)\nprint(rainfall)",
    explanation: "Python can assign several values to several names in one statement. The order on each side must correspond.",
    output: "31\n68\n120",
  },
  swapping: {
    title: "Swapping variable values",
    body: "Python can exchange two values in one statement. The values on the right are evaluated before the new assignments are made.",
    traditional: "temporary_plot = north_plot\nnorth_plot = south_plot\nsouth_plot = temporary_plot",
    python: "north_plot, south_plot = south_plot, north_plot",
    before: [{ name: "north_plot", value: "Rice" }, { name: "south_plot", value: "Wheat" }],
    after: [{ name: "north_plot", value: "Wheat" }, { name: "south_plot", value: "Rice" }],
  },
  agritechProgram: {
    title: "Smart farm information",
    code: "farmer = \"Rahul\"\ncrop = \"Rice\"\nvillage = \"Panvel\"\ntemperature = 31\nrainfall = 120\nsoil_moisture = 42\n\nprint(farmer)\nprint(crop)\nprint(temperature)",
    explanation: "Meaningful variables keep every farm observation understandable and easy to update.",
    output: "Rahul\nRice\n31",
  },
  playgroundActivities: ["Change the crop", "Change the village", "Update rainfall", "Update temperature", "Add and print a humidity variable"],
  mistakesTitle: "Repair invalid variable assignments",
  mistakes: [
    { title: "Space inside the name", incorrect: "crop name = \"Rice\"", reason: "Variable names cannot contain spaces.", correct: "crop_name = \"Rice\"" },
    { title: "Digit at the beginning", incorrect: "2crop = \"Rice\"", reason: "A name cannot begin with a digit.", correct: "crop2 = \"Rice\"" },
    { title: "Reserved keyword", incorrect: "class = \"Rice\"", reason: "class is a reserved Python keyword.", correct: "crop_class = \"Rice\"" },
    { title: "Hyphen inside the name", incorrect: "crop-name = \"Rice\"", reason: "Python reads a hyphen as a separate symbol, not part of a name.", correct: "crop_name = \"Rice\"" },
  ],
  debugChallenge: {
    title: "Find four variable mistakes",
    prompt: "Inspect the names, assignment symbols, and the final print statement.",
    code: "2crop = \"Rice\"\nCrop Name = \"Wheat\"\ntemperature == 30\nprint(Crop)",
    mistakesToFind: 4,
    solution: "crop2 = \"Rice\"\ncrop_name = \"Wheat\"\ntemperature = 30\nprint(crop2)",
    hiddenGuidance: "Check how names begin, whether they contain spaces, which symbol assigns a value, and whether capitalization matches.",
  },
  engineerScenario: {
    title: "Store smart-irrigation observations",
    scenario: "A smart irrigation system receives temperature, humidity, soil moisture, rainfall, and wind speed readings throughout the day.",
    question: "How should the current readings be represented in a Python program?",
    options: [
      { label: "Use one meaningful variable name for each reading", explanation: "Names such as soil_moisture and wind_speed preserve meaning and allow each current value to be updated.", recommended: true },
      { label: "Store every reading under the name x", explanation: "Reusing one vague name would replace earlier readings and hide what the current value represents.", recommended: false },
      { label: "Print numbers without storing them", explanation: "The values would be visible once but difficult to reuse or update reliably.", recommended: false },
      { label: "Use names containing spaces", explanation: "Spaces make a Python variable name invalid.", recommended: false },
    ],
  },
};
