import type { NumpyArrayCreationDevelopmentPack } from "@/types/content";

export const numpyArrayCreationDevelopmentPack: NumpyArrayCreationDevelopmentPack = {
  kind: "numpy-array-creation",
  prerequisite: "Lesson 6.1 · Introduction to NumPy",
  storyHook: "The Smart Farm now understands ndarray. The next engineering decision is how to create the right starting structure: an empty sensor table, a constant calibration grid, a timed sequence, an identity matrix, or reproducible simulated readings.",
  fromData: {
    title: "Convert existing Python data with np.array()",
    body: "Use np.array() when readings, labels, or field rows already exist in Python. One flat sequence creates a 1D array; nested rows create a 2D array.",
    oneDimensionalCode: "temperature = np.array([28, 30, 31, 29, 32])",
    twoDimensionalCode: `soil = np.array([
    [35, 40, 42],
    [45, 38, 41],
    [30, 36, 39]
])`,
    matrix: [[35, 40, 42], [45, 38, 41], [30, 36, 39]],
  },
  initializedArrays: [
    { id: "zeros", name: "np.zeros()", purpose: "Fill every position with 0", oneDimensional: "np.zeros(5)", twoDimensional: "np.zeros((3, 4))", output: "[[0. 0. 0. 0.] × 3 rows]", useCase: "Reserve a 3-field × 4-reading table before readings arrive." },
    { id: "ones", name: "np.ones()", purpose: "Fill every position with 1", oneDimensional: "np.ones(5)", twoDimensional: "np.ones((2, 3))", output: "[[1. 1. 1.] × 2 rows]", useCase: "Create masks, initial weights, or enabled-state grids." },
    { id: "full", name: "np.full()", purpose: "Fill with one chosen value", oneDimensional: "np.full(5, 25)", twoDimensional: "np.full((3, 4), 25)", output: "[[25 25 25 25] × 3 rows]", useCase: "Initialize every field with a default 25°C calibration value." },
    { id: "empty", name: "np.empty()", purpose: "Allocate without predictable initial values", oneDimensional: "np.empty(5)", twoDimensional: "np.empty((3, 4))", output: "Uninitialized values", warning: "Never assume np.empty() contains zeros. Use it only when every position will be overwritten immediately.", useCase: "Avoid unnecessary initialization before a complete data import overwrites every cell." },
  ],
  sequenceFunctions: [
    { id: "arange", name: "np.arange()", syntax: "np.arange(start, stop, step)", code: "np.arange(6, 19, 2)", output: "[ 6  8 10 12 14 16 18]", control: "You choose the step", endpoint: "Stop is generally excluded", agritechUse: "Generate measurement hours from 06:00 to 18:00 every two hours." },
    { id: "linspace", name: "np.linspace()", syntax: "np.linspace(start, stop, num)", code: "np.linspace(20, 35, 7)", output: "[20.  22.5 25.  27.5 30.  32.5 35. ]", control: "You choose the number of values", endpoint: "Both endpoints are included by default", agritechUse: "Create seven evenly spaced temperature calibration points." },
  ],
  identityMatrix: {
    title: "np.eye() creates an identity matrix",
    body: "An identity matrix contains ones on the main diagonal and zeros everywhere else. Recognize the structure now; its matrix and transformation uses come later.",
    code: "np.eye(3)",
    values: [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    futureUses: ["Linear algebra", "Machine learning", "Matrix transformations"],
  },
  randomFunctions: [
    { id: "rand", name: "np.random.rand()", purpose: "Random floats from 0 up to 1", code: "np.random.rand(5)", output: "Example: [0.37 0.95 0.73 0.60 0.16]", agritechUse: "Prototype normalized model inputs or probability-like values." },
    { id: "randint", name: "np.random.randint()", purpose: "Random integers inside a range", code: "np.random.randint(20, 40, 5)", output: "Seed 42: [26 39 34 30 27]", agritechUse: "Simulate whole-number temperature readings." },
    { id: "uniform", name: "np.random.uniform()", purpose: "Random floats inside a range", code: "np.random.uniform(30, 60, 5)", output: "Seed 42: [41.24 58.52 51.96 47.96 34.68]", agritechUse: "Simulate realistic soil-moisture measurements." },
    { id: "choice", name: "np.random.choice()", purpose: "Choose from supplied categories", code: `np.random.choice(["Healthy", "Warning", "Critical"], 5)`, output: "Example: ['Critical' 'Healthy' 'Critical' 'Critical' 'Healthy']", agritechUse: "Generate categorical sensor-health states." },
  ],
  seed: {
    title: "A seed makes a random sequence reproducible",
    body: "The values are still generated by a pseudo-random algorithm, but the same seed restarts the same sequence. That makes experiments, debugging, lessons, and model comparisons repeatable.",
    code: `np.random.seed(42)
temperature = np.random.randint(20, 40, 5)`,
    benefits: ["Repeatable classroom output", "Reproducible experiments", "Easier debugging", "Fair model comparisons"],
  },
  dtype: {
    title: "Choose storage type with dtype=",
    body: "NumPy normally infers a compatible dtype, but array creation can request one explicitly. Converting decimal readings to integers removes the fractional portion, so choose deliberately.",
    examples: [
      { code: "np.array([28, 30, 31], dtype=float)", output: "[28. 30. 31.]", note: "Whole numbers are stored as floating-point values." },
      { code: "np.array([28.5, 30.2], dtype=int)", output: "[28 30]", note: "The decimal portion is discarded; information is lost." },
    ],
  },
  cheatSheet: [
    { name: "np.array()", purpose: "Create from existing data", example: "np.array([1, 2, 3])" },
    { name: "np.zeros()", purpose: "Fill with zero", example: "np.zeros(5)" },
    { name: "np.ones()", purpose: "Fill with one", example: "np.ones(5)" },
    { name: "np.full()", purpose: "Fill with chosen value", example: "np.full(5, 25)" },
    { name: "np.empty()", purpose: "Allocate uninitialized storage", example: "np.empty(5)" },
    { name: "np.arange()", purpose: "Sequence controlled by step", example: "np.arange(0, 10, 2)" },
    { name: "np.linspace()", purpose: "Requested count of even values", example: "np.linspace(0, 10, 5)" },
    { name: "np.eye()", purpose: "Identity matrix", example: "np.eye(3)" },
    { name: "np.random.rand()", purpose: "Random floats from 0 to 1", example: "np.random.rand(5)" },
    { name: "np.random.randint()", purpose: "Random integers", example: "np.random.randint(20, 40, 5)" },
    { name: "np.random.uniform()", purpose: "Random floats in a range", example: "np.random.uniform(30, 60, 5)" },
    { name: "np.random.choice()", purpose: "Random supplied categories", example: "np.random.choice(statuses, 5)" },
  ],
};
