import type { LambdaFunctionsLessonDevelopmentPack } from "@/types/content";

export const lambdaFunctionsDevelopmentPack: LambdaFunctionsLessonDevelopmentPack = {
  kind: "lambda-functions",
  prerequisite: "Lessons 3.1–3.6 · Functions, Parameters, Return Values, Argument Styles, and Scope",
  evolution: { title: "Function Evolution Timeline", body: "Lesson 3.7 adds a compact function expression for small, one-time operations.", stages: [
    { lesson: "3.2", code: "Create Function", capability: "Define reusable work" }, { lesson: "3.3", code: "Accept Inputs", capability: "Receive changing values" }, { lesson: "3.4", code: "Return Outputs", capability: "Produce reusable results" }, { lesson: "3.5", code: "Flexible Function Calls", capability: "Choose how values bind" }, { lesson: "3.6", code: "Variable Scope", capability: "Understand where names live" }, { lesson: "3.7", code: "Anonymous Functions", capability: "Express one small operation", active: true }, { lesson: "3.8", code: "Recursion", capability: "Functions call themselves" }, { lesson: "3.9", code: "Best Practices", capability: "Design maintainable functions" }, { lesson: "3.10", code: "Capstone", capability: "Integrate the module" },
  ] },
  lifecycle: { title: "Function Lifecycle", body: "A lambda receives arguments, evaluates one expression, returns that expression automatically, and gives control back to the caller.", activeStep: "Return Value", steps: [
    { title: "Create Expression", description: "Describe one anonymous operation." }, { title: "Call Function", description: "Supply values when it is needed." }, { title: "Receive Arguments", description: "Bind values to lambda parameters." }, { title: "Evaluate Expression", description: "Run the single expression." }, { title: "Return Value", description: "Return its result automatically." }, { title: "Continue Program", description: "Use the produced value." },
  ] },
  story: { title: "Not every tiny task needs a permanent name", body: "The Smart Farm already has durable named functions for water, crop reports, and weather analysis. A new moisture transformation is needed once, so a concise anonymous function can perform it without pretending it is a reusable domain module.", namedFunctions: ["calculate_water()", "crop_report()", "weather_analysis()"], oneTimeTask: "Multiply one moisture reading by 10", workflow: { title: "A small temporary task", description: "Match the function style to the responsibility.", steps: [{ title: "Small task", description: "One focused calculation is needed." }, { title: "One-time use", description: "No durable domain name is necessary." }, { title: "Lambda", description: "Evaluate one expression." }, { title: "Done", description: "Use the returned result." }] } },
  motivation: { title: "Why another way to create a function?", body: "A regular function is excellent when a named task will be reused, tested, documented, or expanded. A lambda is useful when one simple expression is needed briefly.", regularCode: "def square(x):\n    return x * x", lambdaCode: "lambda x: x * x", traits: ["Small", "Anonymous", "One expression", "Returns automatically", "Usually used briefly"] },
  syntax: { title: "Read a lambda from left to right", body: "The lambda keyword starts the expression, parameters receive inputs, the colon separates inputs from work, and the expression produces the returned value.", template: "lambda parameters: expression", parts: [{ token: "lambda", label: "Keyword", description: "Create an anonymous function expression." }, { token: "parameters", label: "Inputs", description: "Receive zero or more call values." }, { token: ":", label: "Separator", description: "Separate inputs from the expression." }, { token: "expression", label: "Automatic result", description: "Evaluate and return this value without return." }] },
  comparisonExample: { title: "The same square calculation in two styles", body: "Both versions produce 25. The design choice depends on whether the operation deserves a durable name and body.", regularCode: "def square(x):\n    return x * x", lambdaCode: "square = lambda x: x * x", call: "square(5)", result: "25" },
  execution: { title: "Bind, evaluate, and return", body: "Lambda execution follows the same input-to-output mental model as a regular function, but its body is exactly one expression.", examples: [{ title: "Multiply two values", explanation: "a and b bind by position; their product is returned automatically.", code: "multiply = lambda a, b: a * b\nprint(multiply(4, 5))", output: "20", parameters: ["a", "b"], expression: "a * b", arguments: ["4", "5"], result: "20" }, { title: "Combine farm readings", explanation: "The lambda accepts two parameters and produces one numeric score.", code: "farm_score = lambda moisture, temperature: moisture + temperature\nprint(farm_score(25, 30))", output: "55", parameters: ["moisture", "temperature"], expression: "moisture + temperature", arguments: ["25", "30"], result: "55" }], steps: [{ title: "Arguments", description: "Read call values." }, { title: "Parameter binding", description: "Match values to names." }, { title: "Expression", description: "Evaluate one expression." }, { title: "Returned value", description: "Send the result automatically." }] },
  agritechExamples: [
    { title: "Water requirement", explanation: "Scale a moisture reading for a quick calculator.", code: "water = lambda moisture: moisture * 5\nprint(water(20))", output: "100", parameters: ["moisture"], expression: "moisture * 5", arguments: ["20"], result: "100" },
    { title: "Temperature conversion", explanation: "Convert one Celsius reading to Fahrenheit.", code: "c_to_f = lambda c: (c * 9 / 5) + 32\nprint(c_to_f(30))", output: "86.0", parameters: ["c"], expression: "(c * 9 / 5) + 32", arguments: ["30"], result: "86.0" },
    { title: "Fertilizer calculation", explanation: "Scale field area by a fixed fertilizer rate.", code: "fertilizer = lambda area: area * 2\nprint(fertilizer(12))", output: "24", parameters: ["area"], expression: "area * 2", arguments: ["12"], result: "24" },
  ],
  builder: { title: "Lambda Builder", body: "Choose a focused preset, edit numeric arguments, and watch Python syntax, binding, evaluation, and the returned value stay synchronized.", presets: [{ label: "Square", parameters: ["x"], expression: "x * x", arguments: ["5"] }, { label: "Multiply", parameters: ["a", "b"], expression: "a * b", arguments: ["4", "5"] }, { label: "Water", parameters: ["moisture"], expression: "moisture * 5", arguments: ["20"] }, { label: "Profit", parameters: ["income", "expense"], expression: "income - expense", arguments: ["75000", "42000"] }] },
  converter: { title: "Def-to-Lambda Converter", body: "Compare equivalent single-expression functions. The converter is a learning aid—not a rule that every short def should become a lambda.", examples: [{ label: "Square", regularCode: "def square(x):\n    return x * x", lambdaCode: "lambda x: x * x", result: "25 for x = 5" }, { label: "Double", regularCode: "def double(n):\n    return n * 2", lambdaCode: "lambda n: n * 2", result: "16 for n = 8" }, { label: "Larger value", regularCode: "def larger(a, b):\n    return a if a > b else b", lambdaCode: "lambda a, b: a if a > b else b", result: "9 for 9 and 4" }] },
  comparison: { title: "Choose clarity, not merely fewer characters", body: "A lambda is not a replacement for every def. Use the smallest style that keeps intent obvious to the next reader.", rows: [{ feature: "Name", regular: "Named with def", lambda: "Anonymous expression" }, { feature: "Body", regular: "Multiple statements allowed", lambda: "One expression only" }, { feature: "Return", regular: "Uses return", lambda: "Automatic" }, { feature: "Best fit", regular: "Reusable or complex logic", lambda: "Small one-time operation" }, { feature: "Documentation", regular: "Easy to document", lambda: "Keep concise and local" }] },
  mistakesTitle: "Common lambda mistakes",
  mistakes: [{ title: "Missing expression", incorrect: "square = lambda x:", reason: "A lambda must contain one expression after the colon.", correct: "square = lambda x: x * x" }, { title: "Trying multiple statements", incorrect: "lambda x:\n    print(x)\n    return x", reason: "A lambda cannot contain a statement block or explicit return.", correct: "def show_and_return(x):\n    print(x)\n    return x" }, { title: "Hiding complex business logic", incorrect: "decision = lambda soil, temp, rain: ...", reason: "Multi-step domain logic deserves a descriptive named function.", correct: "def irrigation_decision(soil, temp, rain):\n    # clear multi-step logic\n    return decision" }],
  debugChallenges: [{ title: "Add the separator and expression", prompt: "Repair the incomplete square lambda.", code: "square = lambda x", mistakesToFind: 1, solution: "square = lambda x: x * x", hiddenGuidance: "The colon separates parameters from one required expression." }, { title: "Complete the cube", prompt: "Provide the expression that returns the cube automatically.", code: "cube = lambda x:", mistakesToFind: 1, solution: "cube = lambda x: x ** 3", hiddenGuidance: "Do not add the return keyword." }, { title: "Choose def for statements", prompt: "Explain why this is invalid and rewrite it clearly.", code: "lambda x:\nprint(x)", mistakesToFind: 1, solution: "def show(x):\n    print(x)", hiddenGuidance: "print is a statement call in an indented body; use def when the task needs statement structure." }],
  engineerScenario: { title: "Choose a function style intentionally", scenario: "A Smart Farm sorts one report by moisture once today, while its irrigation recommendation contains several rules and will be reused across the dashboard and alerts.", question: "Which design keeps both tasks clearest?", options: [{ label: "A small lambda for the one-time transformation and def for irrigation logic", explanation: "The compact task stays local while reusable domain logic remains named and maintainable.", recommended: true }, { label: "Convert every function to lambda", explanation: "Complex domain logic becomes difficult to read, test, and document.", recommended: false }, { label: "Never use lambda", explanation: "This ignores a useful concise tool for genuinely small temporary operations.", recommended: false }] },
  miniProject: { title: "Smart Farm Quick Calculator", brief: "Create three concise calculations and compare one with a named regular function.", deliverables: ["Create water = lambda moisture: moisture * 5", "Create fertilizer = lambda area: area * 2", "Create profit = lambda income, expense: income - expense", "Call every lambda with sample values", "Display each returned value", "Rewrite one calculation with def", "Explain which style is clearer"], starterCode: "water = lambda moisture: moisture * 5\nfertilizer = lambda area: area * 2\nprofit = lambda income, expense: income - expense\n\nprint(water(20))\nprint(fertilizer(12))\nprint(profit(75000, 42000))", challenge: "Replace one lambda with a regular named function, then justify the version you would keep in production." },
};
