import type { ForLoopLessonDevelopmentPack } from "@/types/content";

export const forLoopDevelopmentPack: ForLoopLessonDevelopmentPack = {
  kind: "for-loop",
  prerequisite: "Module 1 and Lessons 2.1–2.6",
  story: {
    title: "One reading at a time no longer scales",
    body: "The Smart Farm can decide and select actions, but a real deployment produces hundreds of sensor readings. Writing one instruction per device is repetitive, fragile, and impossible to maintain.",
    sensorCounts: [{ label: "Soil sensors", count: 500 }, { label: "Temperature sensors", count: 200 }, { label: "Humidity sensors", count: 100 }],
    repeatedCode: "print(sensor1)\nprint(sensor2)\nprint(sensor3)\nprint(sensor4)\n# ...\nprint(sensor1000)",
    workflow: { title: "Process a collection efficiently", description: "A loop applies the same operation to each item without duplicating the program.", steps: [{ title: "Sensor collection", description: "Provide many related readings." }, { title: "Take one item", description: "Python selects the next sensor automatically." }, { title: "Run the block", description: "Perform the monitoring action." }, { title: "Move forward", description: "Continue until the collection is exhausted." }, { title: "Complete", description: "Leave the loop after every item is processed." }] },
  },
  whyLoops: { title: "Replace copied instructions with one scalable rule", body: "A for loop expresses the repeated operation once and lets Python apply it to every item in a sequence.", items: ["Less duplicated code", "Consistent processing", "Easier maintenance", "Scales to large collections"], withoutLoop: "print(\"Checking Sensor\")\nprint(\"Checking Sensor\")\nprint(\"Checking Sensor\")\nprint(\"Checking Sensor\")\nprint(\"Checking Sensor\")", withLoop: "for i in range(5):\n    print(\"Checking Sensor\")", repeatedCount: 5 },
  definition: { title: "A for loop processes every item in a sequence", body: "Python assigns the next item to the loop variable, executes the indented block, and repeats until no items remain.", items: ["Sequence", "Current item", "Repeated block", "Next item", "Completion"], flow: [{ title: "Start", description: "Prepare the sequence." }, { title: "Item 1", description: "Assign and execute." }, { title: "Item 2", description: "Assign and execute." }, { title: "Item 3", description: "Assign and execute." }, { title: "End", description: "No items remain." }] },
  syntax: { title: "The loop header defines what changes and what repeats", body: "The loop variable receives one value at a time. The indented statements form the repeated block.", template: "for variable in sequence:\n    statements", parts: [{ token: "for", label: "Loop keyword", description: "Begins a for loop." }, { token: "variable", label: "Current item", description: "Stores one sequence item during each iteration." }, { token: "in", label: "Iteration keyword", description: "Reads items from the sequence one by one." }, { token: "sequence", label: "Data source", description: "A range, string, list, or another iterable value." }, { token: "    statements", label: "Repeated block", description: "Runs once for each item and must be indented." }] },
  rangeExamples: [
    { title: "Stop only", code: "for i in range(5):\n    print(i)", explanation: "range(5) starts at 0 and stops before 5.", output: "0\n1\n2\n3\n4", start: 0, stop: 5, step: 1 },
    { title: "Start and stop", code: "for i in range(2, 6):\n    print(i)", explanation: "The first value is 2 and the exclusive stop is 6.", output: "2\n3\n4\n5", start: 2, stop: 6, step: 1 },
    { title: "Start, stop, and step", code: "for i in range(2, 11, 2):\n    print(i)", explanation: "The step advances by two while the stop remains exclusive.", output: "2\n4\n6\n8\n10", start: 2, stop: 11, step: 2 },
  ],
  agritechExamples: [
    { title: "Checking Soil Sensors", code: "for sensor in range(5):\n    print(\"Checking Soil Sensor\", sensor)", explanation: "The same inspection message is generated for five sensor indexes.", output: "Checking Soil Sensor 0\nChecking Soil Sensor 1\nChecking Soil Sensor 2\nChecking Soil Sensor 3\nChecking Soil Sensor 4" },
    { title: "Water Pump Inspection", code: "for pump in range(1, 6):\n    print(\"Inspect Pump\", pump)", explanation: "Starting at one produces operator-friendly pump numbers.", output: "Inspect Pump 1\nInspect Pump 2\nInspect Pump 3\nInspect Pump 4\nInspect Pump 5" },
    { title: "Weather Monitoring", code: "for day in range(1, 8):\n    print(\"Collect Weather Data - Day\", day)", explanation: "One loop schedules a complete seven-day collection sequence.", output: "Collect Weather Data - Day 1\n...\nCollect Weather Data - Day 7" },
  ],
  stringExample: { title: "Looping through a string", code: "crop = \"RICE\"\n\nfor letter in crop:\n    print(letter)", explanation: "A string is a sequence of characters, so the loop receives R, I, C, and E one at a time.", output: "R\nI\nC\nE", sequence: ["R", "I", "C", "E"] },
  listExample: { title: "Looping through a list", code: "crops = [\"Rice\", \"Wheat\", \"Cotton\"]\n\nfor crop in crops:\n    print(crop)", explanation: "A list groups related values that a for loop can process naturally from first to last.", output: "Rice\nWheat\nCotton", sequence: ["Rice", "Wheat", "Cotton"] },
  nestedPreview: { title: "Nested loop preview · concept only", code: "for field in range(2):\n    for sensor in range(3):\n        print(field, sensor)", explanation: "This preview shows one loop inside another. Nested-loop design is intentionally deferred; focus here on one sequence and one loop.", output: "0 0\n0 1\n0 2\n1 0\n1 1\n1 2" },
  simulatorFields: [{ id: "count", label: "Number of Sensors", prompt: "Enter Number of Sensors: ", defaultValue: "3", type: "int" }],
  mistakesTitle: "Common for-loop mistakes",
  mistakes: [{ title: "Missing colon", incorrect: "for i in range(5)\n    print(i)", reason: "The loop header must end with a colon.", correct: "for i in range(5):\n    print(i)" }, { title: "Missing indentation", incorrect: "for i in range(5):\nprint(i)", reason: "Python cannot identify the repeated block.", correct: "for i in range(5):\n    print(i)" }, { title: "Missing in", incorrect: "for i range(5):\n    print(i)", reason: "The in keyword connects the loop variable to its sequence.", correct: "for i in range(5):\n    print(i)" }, { title: "Undefined sequence", incorrect: "for crop in crops:\n    print(crop)", reason: "crops must exist before Python can iterate over it.", correct: "crops = [\"Rice\", \"Wheat\"]\nfor crop in crops:\n    print(crop)" }],
  debugChallenges: [{ title: "Restore the range loop", prompt: "Find the missing punctuation.", code: "for i in range(5)\n    print(i)", mistakesToFind: 1, solution: "for i in range(5):\n    print(i)", hiddenGuidance: "Inspect the end of the loop header." }, { title: "Reconnect the loop variable", prompt: "Fix the malformed sensor loop.", code: "for sensor range(3):\n    print(sensor)", mistakesToFind: 1, solution: "for sensor in range(3):\n    print(sensor)", hiddenGuidance: "A keyword must connect sensor with range(3)." }],
  engineerScenario: { title: "Design for hundreds of farm devices", scenario: "A deployment has 500 soil sensors, 200 weather stations, and 50 irrigation pumps.", question: "How should the monitoring software scale?", options: [{ label: "Process each collection with loops", explanation: "A loop centralizes the repeated operation, improves consistency, and scales when device counts change.", recommended: true }, { label: "Write 750 print statements", explanation: "Copied code is slow to create, easy to break, and expensive to update.", recommended: false }, { label: "Ignore most devices", explanation: "Skipping data avoids the requirement instead of solving it.", recommended: false }] },
  miniProject: { title: "Mini Project · Smart Farm Sensor Monitor", brief: "Read the number of sensors and use one for loop to inspect every sensor in order.", deliverables: ["Read and convert the sensor count", "Use range(1, count + 1)", "Display one line per sensor", "Include the sensor number", "Append an OK status", "Handle at least 10 sensors without code duplication", "Test counts 1, 3, and 10"], outputTemplate: "Checking Sensor 1 - OK\nChecking Sensor 2 - OK\nChecking Sensor 3 - OK\n..." },
  comparison: { title: "Compare & Choose", body: "Decision structures choose a path. A for loop processes every item in a known sequence.", rows: [{ situation: "One decision", bestConstruct: "if", reason: "One guarded action" }, { situation: "Two outcomes", bestConstruct: "if-else", reason: "Two alternatives" }, { situation: "Multiple outcomes", bestConstruct: "if-elif-else", reason: "Ordered alternatives" }, { situation: "Dependent decisions", bestConstruct: "Nested if", reason: "Hierarchical checks" }, { situation: "Fixed menu selection", bestConstruct: "match-case", reason: "Fixed-value mapping" }, { situation: "Process every sensor", bestConstruct: "for loop", reason: "Repeat across a sequence" }] },
};
