import type { SetsDevelopmentPack } from "@/types/content";

export const setsDevelopmentPack: SetsDevelopmentPack = {
  kind: "sets",
  prerequisite: "Lessons 4.1, 4.2, 4.3, and 4.4",
  story: {
    title: "Eliminating Duplicate Sensor Data",
    body: "The Smart Farm dashboard receives thousands of sensor readings every second. Due to network retries, the same sensor IDs are often reported multiple times. Displaying duplicates would clutter the interface and skew statistics.",
    problem: {
      title: "Duplicate Sensor Readings",
      body: "Moisture and temperature sensors send their hardware IDs alongside telemetry data. When a gateway retries failed messages, duplicate readings flood the queue.",
      examples: ["Sensor 101 registered 3 times", "Sensor 205 registered 2 times", "Sensor 310 registered 2 times"],
    },
    whyListsNotEnough: {
      title: "Why lists are not always enough",
      body: "Lists preserve duplicates and maintain sequence order. If you only want to know the unique set of active sensor IDs, lists require manual loop checking to remove duplicates.",
      examples: [
        "Lists keep [101, 101, 205, 205] as-is",
        "Checking lists gets slower as they grow (O(N) search time)",
        "Removing duplicates manually requires custom filter loops",
      ],
    },
  },
  whatIsSet: {
    title: "What is a Set?",
    body: "A Set in Python is an unordered collection of unique elements. It is written using curly braces {} containing values separated by commas.",
    characteristics: [
      "Unique values: duplicate items are automatically discarded",
      "Mutable: you can add or remove elements",
      "Unordered: items have no fixed index position",
      "No indexing: you cannot access elements using []",
    ],
  },
  creation: {
    title: "Creating Sets",
    body: "Create sets directly using curly braces {}, or by passing an iterable like a list into the set() constructor.",
    examples: [
      { label: "Curly Braces", code: "sensor_ids = {101, 205, 310}", note: "Defines a set with three unique integers." },
      { label: "Constructor", code: "sensor_ids = set([101, 101, 205, 310])", note: "Removes duplicates from list, resulting in {101, 205, 310}." },
      { label: "Duplicate check", code: 'crops = {"Rice", "Rice", "Wheat"}', note: 'Results in {"Rice", "Wheat"}.' },
    ],
    emptyCreation: {
      title: "Creating an Empty Set",
      body: "An empty set cannot be created using empty curly braces {} because that creates a dictionary. You must use the set() function.",
      correct: "empty_set = set()",
      incorrect: "empty_dict = {}",
      reason: "Empty curly braces {} are reserved for initializing an empty dictionary. Calling set() is the only way to initialize an empty set.",
    },
  },
  characteristics: {
    title: "Set Characteristics",
    body: "Sets are optimized for uniqueness and relational mathematical operations. Here is a breakdown of their characteristics:",
    items: [
      { name: "Unique Values", description: "Any duplicate element is automatically ignored.", check: true },
      { name: "Unordered", description: "Elements do not have a defined position or sequence.", check: true },
      { name: "No Indexing", description: "Since there is no order, subscript indexing like A[0] is not allowed.", check: true },
    ],
  },
  adding: {
    title: "Adding Elements",
    body: "Use the add() method to insert new items into a set. Adding an element that is already present has no effect and raises no error.",
    code: "sensor_ids.add(410)",
    duplicateCode: "sensor_ids.add(205)",
  },
  removing: {
    title: "Removing Elements",
    body: "Python provides remove() and discard() to delete specific elements from a set, plus clear() to delete all elements.",
    removeCode: "sensor_ids.remove(205)",
    discardCode: "sensor_ids.discard(205)",
    clearCode: "sensor_ids.clear()",
    rows: [
      { method: "remove(x)", behavior: "Removes x from the set. Raises a KeyError if x is not present." },
      { method: "discard(x)", behavior: "Removes x from the set. Safe to use: does nothing if x is not present." },
      { method: "clear()", behavior: "Removes all elements, leaving the set empty." },
    ],
  },
  operations: {
    title: "Mathematical Set Operations",
    body: "Python sets support standard mathematical operations like Union, Intersection, Difference, and Symmetric Difference.",
    farmAValues: [101, 102, 103],
    farmBValues: [103, 104, 105],
    rows: [
      { operation: "Union (|)", code: "A | B", result: "{101, 102, 103, 104, 105}", description: "Combine all elements from both sets." },
      { operation: "Intersection (&)", code: "A & B", result: "{103}", description: "Get elements present in both sets." },
      { operation: "Difference (-)", code: "A - B", result: "{101, 102}", description: "Get elements in A that are not in B." },
      { operation: "Symmetric Difference (^)", code: "A ^ B", result: "{101, 102, 104, 105}", description: "Get elements in A or B, but not both." },
    ],
  },
  builtIns: {
    title: "Built-in Functions with Sets",
    body: "Standard Python built-ins help you summarize sets. Since sets are unordered, functions like sorted() will return a sorted list rather than a set.",
    examples: [
      { name: "len", purpose: "Count unique items", code: "len(sensor_ids)", output: "3" },
      { name: "min", purpose: "Find the smallest item", code: "min(sensor_ids)", output: "101" },
      { name: "max", purpose: "Find the largest item", code: "max(sensor_ids)", output: "310" },
      { name: "sum", purpose: "Sum numeric elements", code: "sum(sensor_ids)", output: "616" },
      { name: "sorted", purpose: "Return sorted list of items", code: "sorted(sensor_ids)", output: "[101, 205, 310]" },
      { name: "any", purpose: "True if any element is truthy", code: "any(sensor_ids)", output: "True" },
      { name: "all", purpose: "True if all elements are truthy", code: "all(sensor_ids)", output: "True" },
    ],
  },
  methods: {
    title: "Set Methods",
    body: "Python sets feature a rich collection of built-in methods for modification and checking relationships.",
    rows: [
      { method: "add", purpose: "Add an item to the set", example: "A.add(4)", output: "None" },
      { method: "remove", purpose: "Remove an item; error if missing", example: "A.remove(2)", output: "None" },
      { method: "discard", purpose: "Remove an item safely; no error if missing", example: "A.discard(5)", output: "None" },
      { method: "pop", purpose: "Remove and return a random item", example: "A.pop()", output: "1 (random)" },
      { method: "clear", purpose: "Remove all items from the set", example: "A.clear()", output: "None" },
      { method: "copy", purpose: "Return a shallow copy of the set", example: "B = A.copy()", output: "Copy of set" },
      { method: "update", purpose: "Merge another collection in-place", example: "A.update({3, 4})", output: "None" },
      { method: "union", purpose: "Return union as a new set", example: "A.union(B)", output: "New set" },
      { method: "intersection", purpose: "Return intersection as a new set", example: "A.intersection(B)", output: "New set" },
      { method: "difference", purpose: "Return difference as a new set", example: "A.difference(B)", output: "New set" },
      { method: "symmetric_difference", purpose: "Return symmetric difference as a new set", example: "A.symmetric_difference(B)", output: "New set" },
      { method: "issubset", purpose: "Check if A is subset of B", example: "A.issubset(B)", output: "True/False" },
      { method: "issuperset", purpose: "Check if A is superset of B", example: "A.issuperset(B)", output: "True/False" },
      { method: "isdisjoint", purpose: "Check if sets have no common items", example: "A.isdisjoint(B)", output: "True/False" },
    ],
  },
  comparison: {
    title: "List vs Tuple vs Set",
    body: "Choose the correct data collection based on mutability, ordering, and duplicate rules.",
    rows: [
      { feature: "Ordered", list: "✅ Yes", tuple: "✅ Yes", set: "❌ No" },
      { feature: "Mutable", list: "✅ Yes", tuple: "❌ No", set: "✅ Yes" },
      { feature: "Duplicates", list: "✅ Yes", tuple: "✅ Yes", set: "❌ No" },
      { feature: "Indexing", list: "✅ Yes", tuple: "✅ Yes", set: "❌ No" },
      { feature: "Best Use", list: "Dynamic ordered data", tuple: "Fixed records / metadata", set: "Unique data / math set ops" },
    ],
  },
  agritech: {
    title: "Merging Sensor Networks",
    body: "When merging data from two barn networks, duplicate sensor IDs can occur. A Union operation lets you identify all distinct active devices automatically.",
    sensorIds: [101, 102, 103],
    newSensorIds: [103, 104, 105],
    unionResult: [101, 102, 103, 104, 105],
    explanation: "Even though sensor 103 is present in both barns, the union combines them into a single unique set of five sensors.",
  },
  debugChallenges: [
    {
      title: "Set Subscript Error",
      prompt: "Why does indexing raise an error, and how do we fix it?\n\nA = {101, 205, 310}\nprint(A[0])",
      code: "A = {101, 205, 310}\nprint(A[0])",
      mistakesToFind: 1,
      solution: "# Sets are unordered and do not support indexing. Convert to a list if you need index-based access, or iterate using a loop.\nA = {101, 205, 310}\nfor item in A:\n    print(item)\n\n# Or:\nlist_A = list(A)\nprint(list_A[0])",
      hiddenGuidance: "Sets are unordered collections and do not support indexing.",
    },
    {
      title: "KeyError on Remove",
      prompt: "Why does this remove statement raise a KeyError, and how can we remove safely?\n\nsensor_ids = {101, 205}\nsensor_ids.remove(310)",
      code: "sensor_ids = {101, 205}\nsensor_ids.remove(310)",
      mistakesToFind: 1,
      solution: "# remove() raises KeyError if the item is missing. Use discard() for a safe removal.\nsensor_ids = {101, 205}\nsensor_ids.discard(310)\nprint(sensor_ids)",
      hiddenGuidance: "remove() raises an error for missing keys. discard() does not.",
    },
    {
      title: "Dictionary vs Set Mistake",
      prompt: "Why is this an empty dictionary instead of an empty set, and how do we fix it?\n\nempty = {}\nprint(type(empty))",
      code: "empty = {}\nprint(type(empty))",
      mistakesToFind: 1,
      solution: "# empty = {} creates an empty dictionary. Use set() for an empty set.\nempty = set()\nprint(type(empty))",
      hiddenGuidance: "Curly braces default to dictionary initialization in Python.",
    },
  ],
  engineerScenario: {
    title: "Large Scale Lookup Performance",
    body: "Suppose 100,000 sensor IDs arrive every hour. Checking membership in a list requires traversing elements one-by-one, which scales poorly. Checking membership in a set uses hash tables, making lookup speed instant.",
    question: "Why does a Set's O(1) average lookup time outperform a List's O(N) search time when checking if a sensor is registered? Explain in terms of membership testing.",
  },
};
