import type { OperatorLessonDevelopmentPack } from "@/types/content";

export const operatorsDevelopmentPack: OperatorLessonDevelopmentPack = {
  kind: "operators",
  prerequisite: "Lessons 1.1–1.5",
  story: {
    title: "A smart farm must transform readings into useful signals",
    body: "A dashboard receives temperature, humidity, rainfall, and pump status. It needs calculations and yes-or-no checks before an automated system can decide what should happen next.",
    readings: [
      { label: "Temperature", value: "32°C" },
      { label: "Humidity", value: "81%" },
      { label: "Rainfall", value: "110 mm" },
      { label: "Pump", value: "OFF" },
    ],
    questions: ["Is temperature greater than 30?", "Is rainfall enough?", "Do several irrigation conditions agree?", "Is the motor already on?"],
    workflow: {
      title: "Operators connect data to an actionable signal",
      description: "An operator performs a specific calculation, comparison, or logical combination.",
      steps: [
        { title: "Sensor data", description: "The farm supplies current measurements and status values." },
        { title: "Operators", description: "Python calculates, compares, or combines those values." },
        { title: "Decision signal", description: "The expression produces a number or Boolean result." },
        { title: "Action", description: "A later conditional lesson will map the signal to an automated action." },
      ],
    },
  },
  definition: {
    title: "What is an operator?",
    body: "An operator is a symbol or keyword that tells Python to perform an operation on one or more values. The values involved are called operands.",
    items: ["Operand", "Operator", "Operand", "Result"],
    example: { title: "Add two values", code: "a = 10\nb = 20\nprint(a + b)", explanation: "+ asks Python to add the values referred to by a and b.", output: "30" },
    operands: ["10", "20"],
    operator: "+",
    result: "30",
  },
  arithmetic: {
    title: "Arithmetic operators perform calculations",
    body: "Python supports familiar calculations and specialized operations such as floor division, remainder, and exponentiation.",
    rows: [
      { operator: "+", meaning: "Addition", example: "10 + 5", output: "15" },
      { operator: "-", meaning: "Subtraction", example: "10 - 5", output: "5" },
      { operator: "*", meaning: "Multiplication", example: "10 * 5", output: "50" },
      { operator: "/", meaning: "Division", example: "10 / 5", output: "2.0" },
      { operator: "//", meaning: "Floor division", example: "10 // 3", output: "3" },
      { operator: "%", meaning: "Remainder (modulus)", example: "10 % 3", output: "1" },
      { operator: "**", meaning: "Exponentiation", example: "2 ** 3", output: "8" },
    ],
    agritechExample: { title: "Distribute plants across complete rows", code: "plants = 240\nrows = 12\nplants_per_row = plants // rows\nprint(plants_per_row)", explanation: "Floor division produces the number of complete plants assigned to each row.", output: "20" },
  },
  comparison: {
    title: "Comparison operators produce Boolean results",
    body: "A comparison asks a precise yes-or-no question. Python returns True or False.",
    rows: [
      { operator: "==", meaning: "Equal to", example: "30 == 30", output: "True" },
      { operator: "!=", meaning: "Not equal to", example: "30 != 25", output: "True" },
      { operator: ">", meaning: "Greater than", example: "32 > 30", output: "True" },
      { operator: "<", meaning: "Less than", example: "28 < 30", output: "True" },
      { operator: ">=", meaning: "Greater than or equal to", example: "30 >= 30", output: "True" },
      { operator: "<=", meaning: "Less than or equal to", example: "28 <= 30", output: "True" },
    ],
    example: { title: "Check a temperature threshold", code: "temperature = 32\nprint(temperature > 30)", explanation: "The comparison is true because 32 is greater than 30.", output: "True" },
    agritechExample: { title: "Check whether soil moisture is below a threshold", code: "soil_moisture = 28\nprint(soil_moisture < 30)", explanation: "True is an irrigation signal; selecting an action with if is introduced later.", output: "True" },
    prediction: { title: "Predict comparison results", body: "Read each threshold carefully before revealing the Boolean output.", predictions: [
      { title: "Temperature threshold", code: "temperature = 32\nprint(temperature >= 35)", options: ["True", "False", "32"], answer: "False", explanation: "32 is not greater than or equal to 35." },
      { title: "Moisture threshold", code: "soil = 28\nprint(soil < 30)", options: ["True", "False", "28"], answer: "True", explanation: "28 is below 30." },
    ] },
  },
  logical: {
    title: "Logical operators combine or reverse Boolean conditions",
    body: "Use and when every condition must be true, or when at least one condition is enough, and not to reverse a Boolean result.",
    rows: [
      { operator: "and", meaning: "Both conditions must be True", example: "True and False", output: "False" },
      { operator: "or", meaning: "At least one condition must be True", example: "True or False", output: "True" },
      { operator: "not", meaning: "Reverse a Boolean result", example: "not True", output: "False" },
    ],
    example: { title: "Combine irrigation thresholds", code: "temperature = 32\nrainfall = 20\nprint(temperature > 30 and rainfall < 50)", explanation: "Both comparisons are True, so the combined and expression is True.", output: "True" },
    truthTables: [
      { operator: "and", rows: [{ a: true, b: true, result: true }, { a: true, b: false, result: false }, { a: false, b: true, result: false }, { a: false, b: false, result: false }] },
      { operator: "or", rows: [{ a: true, b: true, result: true }, { a: true, b: false, result: true }, { a: false, b: true, result: true }, { a: false, b: false, result: false }] },
      { operator: "not", rows: [{ a: true, result: false }, { a: false, result: true }] },
    ],
  },
  assignmentOperators: {
    title: "Assignment operators update a variable",
    body: "Augmented assignment combines an operation with reassignment. For example, plants += 25 is a concise form of plants = plants + 25.",
    rows: [
      { operator: "=", meaning: "Assign", example: "plants = 200", output: "200" },
      { operator: "+=", meaning: "Add and assign", example: "plants += 25", output: "225" },
      { operator: "-=", meaning: "Subtract and assign", example: "plants -= 25", output: "175" },
      { operator: "*=", meaning: "Multiply and assign", example: "plants *= 2", output: "400" },
      { operator: "/=", meaning: "Divide and assign", example: "plants /= 2", output: "100.0" },
      { operator: "%=", meaning: "Remainder and assign", example: "plants %= 30", output: "20" },
      { operator: "//=", meaning: "Floor-divide and assign", example: "plants //= 30", output: "6" },
      { operator: "**=", meaning: "Exponentiate and assign", example: "growth **= 2", output: "4" },
    ],
    example: { title: "Record newly planted seedlings", code: "plants = 200\nplants += 25\nprint(plants)", explanation: "+= updates plants using its previous value and the new amount.", output: "225" },
  },
  identity: {
    title: "Identity operators check whether references point to the same object",
    body: "is and is not answer an object-identity question. They do not replace ==, which compares values.",
    rows: [
      { operator: "is", meaning: "Same object", example: "field_b is field_a", output: "True" },
      { operator: "is not", meaning: "Different object", example: "field_c is not field_a", output: "True" },
    ],
    example: { title: "Compare shared and separate field records", code: "field_a = [\"Rice\", 28]\nfield_b = field_a\nfield_c = [\"Rice\", 28]\n\nprint(field_a is field_b)\nprint(field_a is field_c)\nprint(field_a == field_c)", explanation: "field_a and field_b refer to the same list object. field_c has equal contents but is a separate object.", output: "True\nFalse\nTrue" },
    note: "Use == for equal values. Reserve is for identity checks, especially checks such as value is None.",
  },
  membership: {
    title: "Membership operators search inside a container",
    body: "in checks whether a value occurs in a sequence or collection; not in checks that it does not occur.",
    rows: [
      { operator: "in", meaning: "Value is present", example: "\"R\" in \"Rice\"", output: "True" },
      { operator: "not in", meaning: "Value is absent", example: "\"Z\" not in \"Rice\"", output: "True" },
    ],
    example: { title: "Check a character in a crop name", code: "crop = \"Rice\"\nprint(\"R\" in crop)", explanation: "The character R occurs in Rice.", output: "True" },
    agritechExample: { title: "Check whether a crop is allowed", code: "allowed_crops = [\"Rice\", \"Wheat\", \"Maize\"]\nprint(\"Rice\" in allowed_crops)", explanation: "Membership returns True because Rice is an item in the allowed crop list.", output: "True" },
  },
  bitwise: {
    title: "Bitwise operators work with binary digits",
    body: "Bitwise operations compare the individual 0 and 1 digits of integers. This is an introduction; their lower-level applications are explored later when needed.",
    rows: [
      { operator: "&", meaning: "Bitwise AND", example: "5 & 3", output: "1" },
      { operator: "|", meaning: "Bitwise OR", example: "5 | 3", output: "7" },
      { operator: "^", meaning: "Bitwise XOR", example: "5 ^ 3", output: "6" },
      { operator: "~", meaning: "Bitwise NOT", example: "~5", output: "-6" },
      { operator: "<<", meaning: "Left shift", example: "5 << 1", output: "10" },
      { operator: ">>", meaning: "Right shift", example: "5 >> 1", output: "2" },
    ],
    example: { title: "Visualize bitwise AND", code: "print(5 & 3)", explanation: "5 is 0101 and 3 is 0011. AND keeps only positions where both bits are 1, producing 0001.", output: "1" },
    note: "Treat bitwise operators as a first exposure. They are different from the logical keywords and, or, and not.",
  },
  precedence: {
    title: "Operator precedence controls evaluation order",
    body: "Python evaluates higher-precedence operations first. Parentheses make intended grouping explicit and are often the clearest choice.",
    levels: ["Parentheses", "Exponentiation", "Unary operations", "Multiply, divide, floor divide, remainder", "Add and subtract", "Comparisons, identity, membership", "not", "and", "or"],
    examples: [
      { title: "Multiplication before addition", expression: "2 + 3 * 4", steps: [{ expression: "2 + 3 * 4", explanation: "Multiplication has higher precedence than addition.", operator: "*" }, { expression: "2 + 12", explanation: "Evaluate 3 * 4 first.", operator: "+" }, { expression: "14", explanation: "Complete the remaining addition." }], result: "14" },
      { title: "Parentheses first", expression: "(2 + 3) * 4", steps: [{ expression: "(2 + 3) * 4", explanation: "Parentheses override the normal order.", operator: "()" }, { expression: "5 * 4", explanation: "Evaluate the grouped addition first.", operator: "*" }, { expression: "20", explanation: "Complete the multiplication." }], result: "20" },
      { title: "Comparison before and", expression: "32 > 30 and 20 < 50", steps: [{ expression: "32 > 30 and 20 < 50", explanation: "Comparisons are evaluated before and.", operator: "> <" }, { expression: "True and True", explanation: "Both comparisons produce True.", operator: "and" }, { expression: "True", explanation: "and returns True because both operands are True." }], result: "True" },
    ],
  },
  agritechProgram: {
    title: "Create an irrigation decision signal",
    code: "temperature = 32\nsoil_moisture = 28\nrainfall = 15\n\nshould_start_irrigation = temperature > 30 and soil_moisture < 30 and rainfall < 50\n\nprint(should_start_irrigation)",
    explanation: "Comparison operators create three Boolean values and and combines them. This lesson prints the decision signal; Lesson 1.8 will use if to choose an action message.",
    output: "True",
  },
  expressions: [
    { title: "Farm supply calculation", expression: "20 + 10 * 3", steps: [{ expression: "20 + 10 * 3", explanation: "Multiplication is evaluated before addition.", operator: "*" }, { expression: "20 + 30", explanation: "10 * 3 becomes 30.", operator: "+" }, { expression: "50", explanation: "20 + 30 produces the final result." }], result: "50" },
    { title: "Plants per row", expression: "240 // 12 + 5", steps: [{ expression: "240 // 12 + 5", explanation: "Floor division is evaluated before addition.", operator: "//" }, { expression: "20 + 5", explanation: "240 // 12 produces 20 complete plants per row.", operator: "+" }, { expression: "25", explanation: "Add five reserve plants." }], result: "25" },
    { title: "Irrigation signal", expression: "32 > 30 and 20 < 50", steps: [{ expression: "32 > 30 and 20 < 50", explanation: "Evaluate both comparisons first.", operator: "> <" }, { expression: "True and True", explanation: "Both threshold checks are True.", operator: "and" }, { expression: "True", explanation: "The combined irrigation signal is True." }], result: "True" },
  ],
  playgroundActivities: ["Change temperature and rainfall", "Try each comparison operator", "Replace and with or", "Add an arithmetic expression", "Introduce a precedence-changing pair of parentheses"],
  mistakesTitle: "Repair common operator mistakes",
  mistakes: [
    { title: "Assignment used inside a comparison", incorrect: "temperature = 30\nprint(temperature = 30)", reason: "= performs assignment and cannot be used as the comparison expression here.", correct: "temperature = 30\nprint(temperature == 30)" },
    { title: "Reversed greater-than-or-equal symbol", incorrect: "age = 20\nprint(age => 18)", reason: "Python spells greater than or equal as >=.", correct: "age = 20\nprint(age >= 18)" },
    { title: "Non-Python logical operator", incorrect: "print(True && False)", reason: "Python uses the keyword and instead of &&.", correct: "print(True and False)" },
  ],
  debugChallenge: {
    title: "Fix three operator syntax mistakes",
    prompt: "Repair the equality comparison, comparison-symbol order, and logical operator without introducing an if statement.",
    code: "temperature = 32\nsoil = 25\nprint(temperature = 30)\nprint(soil >< 20)\nprint(True && False)",
    mistakesToFind: 3,
    solution: "temperature = 32\nsoil = 25\nprint(temperature == 30)\nprint(soil > 20)\nprint(True and False)",
    hiddenGuidance: "Python comparison operators have fixed symbol order, and logical operators are words.",
  },
  engineerScenario: {
    title: "Design an irrigation decision expression",
    scenario: "Temperature is 33, humidity is 82, rainfall is 15, and wind speed is 12. Irrigation should be recommended only when temperature > 30, rainfall < 50, and humidity < 85.",
    question: "Which expression produces the required Boolean signal?",
    options: [
      { label: "temperature > 30 and rainfall < 50 and humidity < 85", explanation: "Every required threshold must be true, so and correctly combines all three comparisons.", recommended: true },
      { label: "temperature > 30 or rainfall < 50 or humidity < 85", explanation: "or would return True when only one threshold is satisfied.", recommended: false },
      { label: "temperature = 30 and rainfall = 50", explanation: "= assigns values rather than comparing them, and the humidity requirement is missing.", recommended: false },
      { label: "not temperature > 30", explanation: "This reverses only one comparison and ignores rainfall and humidity.", recommended: false },
    ],
  },
  miniProject: {
    title: "Mini project · Smart Irrigation Decision System",
    brief: "Collect farm measurements, convert them to numbers, and combine comparison and logical operators into a reusable Boolean irrigation signal.",
    deliverables: ["Temperature input converted to float", "Rainfall input converted to float", "Humidity input converted to float", "Soil-moisture input converted to float", "A should_start_irrigation Boolean expression", "A report showing each measurement and the final signal"],
    outputTemplate: "SMART IRRIGATION REPORT\n------------------------\nTemperature :\nRainfall :\nHumidity :\nSoil Moisture :\nShould Start Irrigation : True/False\n------------------------",
  },
};
