import type { FunctionArgumentsLessonDevelopmentPack } from "@/types/content";

export const functionArgumentsDevelopmentPack: FunctionArgumentsLessonDevelopmentPack = {
  kind: "function-arguments",
  prerequisite: "Lessons 3.1–3.4 · Functions, Parameters, and Return Values",
  evolution: {
    title: "Function Evolution Timeline",
    body: "Each lesson strengthens the same function mental model. Lesson 3.5 makes call sites clearer and optional configuration easier to express.",
    stages: [{ lesson:"3.2",code:"Create Function",capability:"Define reusable work"},{lesson:"3.3",code:"Accept Inputs",capability:"Receive changing values"},{lesson:"3.4",code:"Return Outputs",capability:"Produce reusable results"},{lesson:"3.5",code:"Flexible Function Calls",capability:"Choose how values bind",active:true},{lesson:"3.6",code:"Variable Scope",capability:"Understand where names live"},{lesson:"3.7",code:"Anonymous Functions",capability:"Create compact functions"},{lesson:"3.8",code:"Recursion",capability:"Functions call themselves"},{lesson:"3.9",code:"Best Practices",capability:"Design maintainable functions"},{lesson:"3.10",code:"Capstone",capability:"Integrate the module"}],
  },
  lifecycle: { title:"Function Lifecycle",body:"This lesson focuses on how call values bind during Receive Arguments.",activeStep:"Receive Arguments",steps:[{title:"Define Function",description:"Declare parameters and defaults."},{title:"Call Function",description:"Choose a call style."},{title:"Receive Arguments",description:"Bind by position, name, or default."},{title:"Execute Code",description:"Use the bound values."},{title:"Return Value",description:"Send a result back."},{title:"Continue Program",description:"Reuse the result."}] },
  story: { title:"One function can receive values in several useful ways",body:"Thousands of farm reports need crop, moisture, and temperature. Developers may value brevity, clarity, or optional settings depending on the call, so Python provides complementary binding styles.",code:"def farm_report(crop, moisture, temperature):\n    print(crop)\n    print(moisture)\n    print(temperature)",needs:["Match short calls by position","Name values when clarity matters","Provide sensible optional settings"] },
  review: { title:"Parameters create slots; arguments fill them",body:"The definition declares the receiving names. Every call supplies values that Python binds into those slots before the body runs.",definition:"def farm_report(crop, moisture):",call:"farm_report(\"Rice\", 25)",parameters:["crop","moisture"],arguments:["\"Rice\"","25"] },
  positional: { title:"Positional arguments bind by order",explanation:"Rice is first, so it binds to crop. 25 is second, so it binds to moisture. Reversing them changes meaning even though Python can still run the call.",code:"def farm_report(crop, moisture):\n    print(crop)\n    print(moisture)\n\nfarm_report(\"Rice\", 25)",output:"Rice\n25",correct:{label:"Correct order",call:"farm_report(\"Rice\", 25)",bindings:[{parameter:"crop",value:"\"Rice\"",source:"positional"},{parameter:"moisture",value:"25",source:"positional"}],output:"Rice · 25"},wrong:{label:"Wrong order",call:"farm_report(25, \"Rice\")",bindings:[{parameter:"crop",value:"25",source:"positional"},{parameter:"moisture",value:"\"Rice\"",source:"positional"}],output:"25 · Rice"} },
  keyword: { title:"Keyword arguments bind by parameter name",explanation:"Explicit names remove dependence on call order and make meaning visible where the function is used.",code:"farm_report(moisture=25, crop=\"Rice\")",output:"Rice\n25",examples:[{label:"Definition order",call:"farm_report(crop=\"Rice\", moisture=25)",bindings:[{parameter:"crop",value:"\"Rice\"",source:"keyword"},{parameter:"moisture",value:"25",source:"keyword"}],output:"Rice · 25"},{label:"Reordered safely",call:"farm_report(moisture=25, crop=\"Rice\")",bindings:[{parameter:"crop",value:"\"Rice\"",source:"keyword"},{parameter:"moisture",value:"25",source:"keyword"}],output:"Rice · 25"}] },
  defaults: { title:"Default arguments fill optional parameter slots",explanation:"unit receives Percent only when the caller omits it. A supplied value overrides the default for that call.",code:"def irrigation(moisture, unit=\"Percent\"):\n    print(moisture)\n    print(unit)\n\nirrigation(25)\nirrigation(25, \"kPa\")",output:"25\nPercent\n25\nkPa",omitted:{label:"Default used",call:"irrigation(25)",bindings:[{parameter:"moisture",value:"25",source:"positional"},{parameter:"unit",value:"\"Percent\"",source:"default"}],output:"25 · Percent"},overridden:{label:"Default overridden",call:"irrigation(25, \"kPa\")",bindings:[{parameter:"moisture",value:"25",source:"positional"},{parameter:"unit",value:"\"kPa\"",source:"positional"}],output:"25 · kPa"},decisionSteps:[{title:"Parameter",description:"Inspect unit."},{title:"Default Exists",description:"Percent is available."},{title:"Value supplied?",description:"Check this call."},{title:"Use supplied or default",description:"Bind exactly one value."}] },
  combined: { title:"Combine styles using Python's ordering rules",explanation:"Required positional values come first, keyword values follow, and any omitted optional parameters keep their defaults.",code:"def farm(crop, moisture, unit=\"Percent\"):\n    print(crop, moisture, unit)\n\nfarm(\"Rice\", moisture=25)",output:"Rice 25 Percent",binding:{label:"Combined call",call:"farm(\"Rice\", moisture=25)",bindings:[{parameter:"crop",value:"\"Rice\"",source:"positional"},{parameter:"moisture",value:"25",source:"keyword"},{parameter:"unit",value:"\"Percent\"",source:"default"}],output:"Rice · 25 · Percent"},rules:["Place positional arguments before keyword arguments","Use an exact parameter name for every keyword","Required parameters must receive a value","Omitted optional parameters use their defaults"] },
  mapping: { title:"Argument Mapping Visualizer",body:"Compare the same parameter slots under positional, keyword, default, and combined binding rules.",examples:[] },
  builder: { title:"Function Call Builder",body:"Choose a call style, edit farm values, and decide whether to supply the optional unit. DI Notes generates valid Python and explains each binding.",functionName:"farm_report",parameters:[{name:"crop",initialValue:"Rice",type:"text"},{name:"moisture",initialValue:"25",type:"number"},{name:"unit",defaultValue:"Percent",initialValue:"kPa",type:"text"}] },
  comparison: { title:"Three complementary ways to provide values",body:"The best call style depends on simplicity, clarity, and whether a setting is optional.",rows:[{feature:"Matching rule",positional:"Order",keyword:"Parameter name",defaults:"Used when omitted"},{feature:"Order matters",positional:"Yes",keyword:"No",defaults:"Definition rules apply"},{feature:"Readability",positional:"Compact",keyword:"Explicit",defaults:"Communicates optionality"},{feature:"Optional values",positional:"No",keyword:"No",defaults:"Yes"},{feature:"Best fit",positional:"Few obvious values",keyword:"Many or ambiguous values",defaults:"Common configuration"}] },
  agritechExamples: [{title:"Sensor location can default safely",explanation:"Unknown is used until a location is supplied.",code:"def inspect_sensor(sensor_id, location=\"Unknown\"):\n    print(sensor_id, location)\n\ninspect_sensor(101)\ninspect_sensor(205, \"North Field\")",output:"101 Unknown\n205 North Field"},{title:"Season is optional fertilizer context",explanation:"Keyword calls make the selected crop and season clear.",code:"def fertilizer(crop, season=\"Summer\"):\n    print(crop, season)\n\nfertilizer(crop=\"Rice\")",output:"Rice Summer"},{title:"Humidity has a useful baseline",explanation:"A concise positional temperature combines with the default humidity.",code:"def weather(temperature, humidity=60):\n    print(temperature, humidity)\n\nweather(32)",output:"32 60"}],
  mistakesTitle:"Common argument-binding mistakes",
  mistakes:[{title:"Wrong positional order",incorrect:"farm_report(25, \"Rice\")",reason:"25 binds to crop and Rice binds to moisture.",correct:"farm_report(\"Rice\", 25)"},{title:"Unknown keyword",incorrect:"farm_report(crop_name=\"Rice\", moisture=25)",reason:"crop_name is not a declared parameter.",correct:"farm_report(crop=\"Rice\", moisture=25)"},{title:"Required argument missing",incorrect:"farm_report()",reason:"Required crop and moisture slots receive no values.",correct:"farm_report(\"Rice\", 25)"},{title:"Positional after keyword",incorrect:"farm_report(crop=\"Rice\", 25)",reason:"Python syntax requires positional arguments before keyword arguments.",correct:"farm_report(\"Rice\", moisture=25)"}],
  debugChallenges:[{title:"Supply required weather inputs",prompt:"Repair the call so both required parameters receive values.",code:"def weather(temp, humidity):\n    print(temp, humidity)\n\nweather()",mistakesToFind:1,solution:"def weather(temp, humidity):\n    print(temp, humidity)\n\nweather(32, 60)",hiddenGuidance:"Two required parameters need two arguments."},{title:"Use the declared keyword",prompt:"Repair the call without changing the function header.",code:"def crop(name, season=\"Summer\"):\n    print(name, season)\n\ncrop(crop_name=\"Rice\")",mistakesToFind:1,solution:"def crop(name, season=\"Summer\"):\n    print(name, season)\n\ncrop(name=\"Rice\")",hiddenGuidance:"The keyword must exactly match name."}],
  engineerScenario:{title:"Design calls for 50 farm settings",scenario:"A public Smart Farm API exposes dozens of configuration values used by several development teams.",question:"Which style makes important settings clearest while keeping common options convenient?",options:[{label:"Keyword + default arguments",explanation:"Named call values improve clarity and defaults remove repetitive common configuration.",recommended:true},{label:"Fifty positional arguments",explanation:"Remembering a long order is fragile and difficult to review.",recommended:false},{label:"Hardcode every setting",explanation:"Callers lose the ability to configure the operation.",recommended:false}]},
  miniProject:{title:"Smart Farm Report Generator",brief:"Build one report function that supports positional, keyword, default, and combined calls.",deliverables:["Define crop, moisture, and temperature as required parameters","Give unit a Percent default","Call once with positional arguments","Call once with reordered keyword arguments","Override unit with kPa","Verify every binding","Explain why each call style fits","Keep *args and **kwargs out of scope"],starterCode:"def farm_report(crop, moisture, temperature, unit=\"Percent\"):\n    print(crop)\n    print(moisture)\n    print(temperature)\n    print(unit)",calls:["farm_report(\"Rice\", 25, 32)","farm_report(crop=\"Cotton\", temperature=30, moisture=18, unit=\"kPa\")"],challenge:"Add season=\"Summer\" and generate reports for several farms using clear calls."},
};

functionArgumentsDevelopmentPack.mapping.examples = [functionArgumentsDevelopmentPack.positional.correct,functionArgumentsDevelopmentPack.keyword.examples[1],functionArgumentsDevelopmentPack.defaults.omitted,functionArgumentsDevelopmentPack.combined.binding];
