import type { FunctionDefinitionLessonDevelopmentPack } from "@/types/content";

export const functionDefinitionDevelopmentPack: FunctionDefinitionLessonDevelopmentPack = {
  kind: "function-definition",
  prerequisite: "Module 1, Module 2, and Lesson 3.1 · Why Functions?",
  story: {
    title: "Turn yesterday's repeated farm check into one reusable tool",
    body: "Lesson 3.1 identified the maintenance problem. Today, the Smart Farm writes the three status checks once and gives that focused responsibility a name that every feature can call.",
    repeatedCode: "print(\"Checking Soil Moisture\")\nprint(\"Checking Temperature\")\nprint(\"Checking Rainfall\")",
    conceptualCall: "check_farm_status()",
    consumers: ["Dashboard", "Daily Report", "Mobile App"],
    workflow: {
      title: "From repeated instructions to reusable execution",
      description: "The same responsibility now has one definition and several calls.",
      steps: [
        { title: "Repeated code", description: "Recognize the same status checks in several features." },
        { title: "Need a function", description: "Choose one focused responsibility to reuse." },
        { title: "Define", description: "Create the function once with a clear name and body." },
        { title: "Call", description: "Ask the function to perform its task." },
        { title: "Reuse", description: "Call the same function wherever the task is needed." },
      ],
    },
  },
  definitionKeyword: {
    title: "Meet the def keyword",
    body: "Python uses def to create a new function. Read it as: I am defining a reusable tool.",
    keyword: "def",
    meaning: "Create a named, reusable block of instructions",
    workflow: [
      { title: "def", description: "Begin a function definition." },
      { title: "Create function", description: "Give the reusable task a clear name." },
      { title: "Store task", description: "Keep the indented instructions together." },
      { title: "Ready to use", description: "Wait until the main program calls the function." },
    ],
  },
  anatomy: {
    title: "Explore the anatomy of a function",
    body: "Select each part to understand its role. Parentheses are intentionally empty because parameters begin in Lesson 3.3.",
    code: "def greet():\n    print(\"Hello\")",
    parts: [
      { id: "keyword", token: "def", label: "Function keyword", description: "Starts a new function definition." },
      { id: "name", token: "greet", label: "Function name", description: "Gives the reusable task a meaningful identity." },
      { id: "parentheses", token: "()", label: "Empty parentheses", description: "Marks this as a function. Inputs are introduced in the next lesson." },
      { id: "colon", token: ":", label: "Colon", description: "Begins the indented function body." },
      { id: "body", token: "print(\"Hello\")", label: "Function body", description: "Contains the instructions that run when the function is called." },
    ],
  },
  defining: {
    title: "Defining creates the function but does not run its body",
    explanation: "Python records the name and indented instructions. Because there is no function call, the console remains empty.",
    code: "def greet():\n    print(\"Welcome to Smart Farm\")",
    output: "No output",
    status: "Function created · Waiting for a call",
  },
  calling: {
    title: "Calling executes the stored instructions",
    explanation: "Adding parentheses after the function name asks Python to enter the function body, execute it, and then continue the main program.",
    code: "def greet():\n    print(\"Welcome to Smart Farm\")\n\ngreet()",
    output: "Welcome to Smart Farm",
    call: "greet()",
    flow: [
      { title: "Main Program", description: "Execution reaches greet()." },
      { title: "Function Call", description: "Python locates the earlier definition." },
      { title: "Jump to Function", description: "Control enters the function body." },
      { title: "Execute", description: "The welcome message is printed." },
      { title: "Return", description: "Control moves back after the call." },
      { title: "Continue", description: "The main program can run its next statement." },
    ],
  },
  multipleCalls: {
    title: "Write once, call many times",
    explanation: "The function body appears once. Three calls reuse the same trusted instructions in sequence.",
    code: "def greet():\n    print(\"Welcome to Smart Farm\")\n\ngreet()\ngreet()\ngreet()",
    output: "Welcome to Smart Farm\nWelcome to Smart Farm\nWelcome to Smart Farm",
    callCount: 3,
  },
  agritechExample: {
    title: "Create a reusable farm-status check",
    explanation: "The dashboard, daily report, and mobile experience can call the same definition instead of copying three print statements.",
    code: "def check_farm_status():\n    print(\"Checking Soil Moisture...\")\n    print(\"Checking Temperature...\")\n    print(\"Checking Rainfall...\")\n\ncheck_farm_status()",
    output: "Checking Soil Moisture...\nChecking Temperature...\nChecking Rainfall...",
    consumers: ["Dashboard", "Daily Report", "Mobile App"],
  },
  functionLibrary: {
    title: "Smart Farm Function Library",
    body: "Call each reusable module independently. The library remains visible as this module grows into parameters, return values, and larger programs.",
    functions: [
      { id: "irrigation", name: "irrigation()", output: "Irrigation Running", description: "Runs the irrigation module placeholder." },
      { id: "weather", name: "weather()", output: "Weather Monitoring", description: "Runs the weather module placeholder." },
      { id: "sensors", name: "sensors()", output: "Checking Sensors", description: "Runs the sensor inspection placeholder." },
      { id: "reports", name: "reports()", output: "Generating Report", description: "Runs the reporting module placeholder." },
    ],
  },
  execution: {
    title: "Trace definition, call, function body, and return",
    body: "Move through a simplified execution model. The highlighted source line, active frame, and call stack change together.",
    code: "def check_farm_status():\n    print(\"Checking Soil Moisture...\")\n    print(\"Checking Temperature...\")\n    print(\"Checking Rainfall...\")\n\nprint(\"Dashboard Ready\")\ncheck_farm_status()\nprint(\"Report Ready\")",
    steps: [
      { lineNumber: 1, frame: "Main Program", title: "Create function", description: "Python stores the definition. The body does not run yet." },
      { lineNumber: 6, frame: "Main Program", title: "Run regular statement", description: "The dashboard message executes immediately.", output: "Dashboard Ready" },
      { lineNumber: 7, frame: "Main Program", title: "Call function", description: "Python prepares to enter check_farm_status()." },
      { lineNumber: 2, frame: "check_farm_status()", title: "Enter function", description: "The first body statement executes.", output: "Checking Soil Moisture..." },
      { lineNumber: 3, frame: "check_farm_status()", title: "Continue function", description: "The second body statement executes.", output: "Checking Temperature..." },
      { lineNumber: 4, frame: "check_farm_status()", title: "Finish function", description: "The final body statement executes.", output: "Checking Rainfall..." },
      { lineNumber: 7, frame: "Main Program", title: "Return to caller", description: "The function has finished and its frame leaves the stack." },
      { lineNumber: 8, frame: "Main Program", title: "Continue program", description: "Execution resumes after the function call.", output: "Report Ready" },
    ],
  },
  comparison: {
    title: "Definition and call have different jobs",
    body: "Use this reference to decide whether Python is creating reusable behaviour or executing existing behaviour.",
    rows: [
      { action: "Define a function", code: "def greet():", effect: "Creates reusable code; the body does not run" },
      { action: "Call a function", code: "greet()", effect: "Executes the stored function body" },
      { action: "Execute immediately", code: "print(\"Ready\")", effect: "Runs as Python reaches the statement" },
      { action: "Reuse logic", code: "greet()\ngreet()", effect: "Calls the same definition more than once" },
    ],
  },
  mistakesTitle: "Common function-definition and call mistakes",
  mistakes: [
    { title: "Forgetting call parentheses", incorrect: "greet", reason: "The name refers to the function but does not call it.", correct: "greet()" },
    { title: "Missing definition colon", incorrect: "def greet()", reason: "A function header must end with a colon.", correct: "def greet():" },
    { title: "Missing body indentation", incorrect: "def greet():\nprint(\"Hello\")", reason: "Python uses indentation to identify the function body.", correct: "def greet():\n    print(\"Hello\")" },
    { title: "Calling before the definition", incorrect: "greet()\n\ndef greet():\n    print(\"Hello\")", reason: "Python executes this script from top to bottom, so greet is not defined when the first line runs.", correct: "def greet():\n    print(\"Hello\")\n\ngreet()" },
  ],
  debugChallenges: [
    { title: "Repair the function header", prompt: "Find the missing syntax that prevents Python from creating the function.", code: "def greet()\n    print(\"Welcome\")", mistakesToFind: 1, solution: "def greet():\n    print(\"Welcome\")", hiddenGuidance: "Inspect the end of the function header." },
    { title: "Repair the function body", prompt: "Fix the block structure so Python knows which statement belongs to farm().", code: "def farm():\nprint(\"Checking\")", mistakesToFind: 1, solution: "def farm():\n    print(\"Checking\")", hiddenGuidance: "The body must be indented." },
    { title: "Execute the stored function", prompt: "The definition is correct, but no message appears. Fix the call.", code: "def hello():\n    print(\"Hello\")\n\nhello", mistakesToFind: 1, solution: "def hello():\n    print(\"Hello\")\n\nhello()", hiddenGuidance: "A function call needs parentheses." },
  ],
  engineerScenario: {
    title: "Design the Smart Farm for teamwork",
    scenario: "The application contains irrigation, weather, sensor, report, and notification responsibilities maintained by several developers.",
    question: "Which structure best supports testing, ownership, and future maintenance?",
    options: [
      { label: "Create five focused functions", explanation: "Each responsibility gains a clear boundary, name, and independent call point.", recommended: true },
      { label: "Place every statement in one huge block", explanation: "Unrelated responsibilities become harder to locate, test, and change safely.", recommended: false },
      { label: "Copy each responsibility into every screen", explanation: "Duplication makes fixes inconsistent and increases maintenance cost.", recommended: false },
    ],
  },
  miniProject: {
    title: "Build the Smart Farm Module Library",
    brief: "Create four parameter-free functions, then call each one from the main program. Rearrange only the calls and observe how execution order changes.",
    deliverables: ["irrigation() definition", "weather() definition", "sensors() definition", "reports() definition", "One placeholder message per function", "Four function calls in the main program", "A second run with the call order changed"],
    starterCode: "def irrigation():\n    print(\"Irrigation Running\")\n\ndef weather():\n    print(\"Weather Monitoring\")\n\ndef sensors():\n    print(\"Checking Sensors\")\n\ndef reports():\n    print(\"Generating Report\")\n\nirrigation()\nweather()\nsensors()\nreports()",
    functions: ["irrigation()", "weather()", "sensors()", "reports()"],
  },
};
