import type { ReturnValuesLessonDevelopmentPack } from "@/types/content";

export const returnValuesDevelopmentPack: ReturnValuesLessonDevelopmentPack = {
  kind: "return-values",
  prerequisite: "Lessons 3.1–3.3 · Why Functions, Creating Functions, and Function Parameters",
  evolution: {
    title: "Function Evolution",
    body: "The soil function can already receive changing data. Lesson 3.4 adds the ability to produce a result that the rest of the program can reuse.",
    stages: [
      { lesson: "3.2", code: "check_soil()", capability: "Reusable action" },
      { lesson: "3.3", code: "check_soil(moisture)", capability: "Accept different inputs" },
      { lesson: "3.4", code: "status = check_soil(moisture)", capability: "Produce a reusable result", active: true },
      { lesson: "3.5", code: "check_soil(moisture=25)", capability: "Name arguments at the call" },
      { lesson: "3.6", code: "check_soil(moisture=25, unit=\"percent\")", capability: "Provide default values" },
    ],
  },
  lifecycle: {
    title: "Function Lifecycle",
    body: "Keep this complete mental model visible: data enters through arguments, work happens inside the function, and a returned result continues through the program.",
    activeStep: "Return Value",
    steps: [{ title: "Define Function", description: "Create the reusable operation." }, { title: "Call Function", description: "Request the operation." }, { title: "Receive Arguments", description: "Map call data into parameters." }, { title: "Execute Code", description: "Perform the calculation or decision." }, { title: "Return Value", description: "Send the result to the caller." }, { title: "Continue Program", description: "Store or reuse the result." }],
  },
  story: {
    title: "A displayed sensor value cannot power another module",
    body: "The soil function prints a reading, but the dashboard, AI engine, and report generator need the actual value. Displaying information ends at the screen; reusable program data must travel back to the caller.",
    code: "def check_soil(moisture):\n    print(\"Soil Moisture:\", moisture)",
    consumers: ["Dashboard", "AI Engine", "Report Generator"],
    flow: [{ title: "Sensor", description: "Supplies the reading." }, { title: "check_soil()", description: "Receives the value." }, { title: "Print Screen", description: "Displays text only." }, { title: "Done", description: "No reusable result is sent back." }],
  },
  printProblem: {
    title: "Why print() is not a produced result",
    explanation: "add() displays 8 but reaches the end without a return statement. Python therefore gives the caller None, so result contains None.",
    code: "def add(a, b):\n    print(a + b)\n\nresult = add(5, 3)\nprint(result)",
    output: "8\nNone",
    assignedVariable: "result",
    assignedValue: "None",
  },
  definition: {
    title: "return hands completed work back to the caller",
    body: "A return statement sends a value from a function to the exact place where that function was called. The caller can store, compare, calculate with, or pass that value onward.",
    analogy: { title: "A soil laboratory returns its report", steps: [{ title: "Farmer", description: "Requests a soil test." }, { title: "Laboratory", description: "Performs the analysis." }, { title: "Testing", description: "Produces the result." }, { title: "Report Returned", description: "Sends usable information back." }, { title: "Farmer Uses Report", description: "Makes the next decision." }] },
  },
  firstReturn: {
    title: "Write the first return function",
    explanation: "The function computes 8 and sends it to the call expression. Assignment then stores that value in result before the next line runs.",
    code: "def add(a, b):\n    return a + b\n\nresult = add(5, 3)\nprint(result)",
    output: "8",
    call: "add(5, 3)",
    receivingVariable: "result",
    returnedValue: "8",
  },
  returnFlow: {
    title: "Trace a value back to the main program",
    body: "Step through the complete hand-off and watch control return to the caller at the exact return statement.",
    functionName: "add",
    argument: "5, 3",
    receivingVariable: "result",
    returnedValue: "8",
    steps: [{ title: "Main Program", description: "Execution reaches result = add(5, 3)." }, { title: "Function Call", description: "Arguments enter add()." }, { title: "Calculate", description: "a + b evaluates to 8." }, { title: "return 8", description: "Control and the value move back to the caller." }, { title: "Store Result", description: "result receives 8." }, { title: "Continue", description: "print(result) executes next." }],
  },
  comparator: {
    title: "Printing and returning are different jobs",
    body: "Run the two designs side by side. Both can show 16, but only the return version gives value a reusable number.",
    printCode: "def square(n):\n    print(n * n)\n\nvalue = square(4)\nprint(value)",
    printConsole: "16\nNone",
    printVariable: "None",
    returnCode: "def square(n):\n    return n * n\n\nvalue = square(4)\nprint(value)",
    returnConsole: "16",
    returnVariable: "16",
  },
  propagation: {
    title: "One returned value can serve many modules",
    body: "calculate_water(18) returns a number once. The calling program stores it and can share the same dependable result across several responsibilities.",
    source: "calculate_water(18)",
    returnedValue: "100",
    receivingVariable: "water",
    consumers: [{ title: "Dashboard", use: "Display current requirement" }, { title: "Report", use: "Record the recommendation" }, { title: "Irrigation Controller", use: "Plan motor operation" }],
  },
  agritechExamples: [
    { title: "Return the required water amount", explanation: "The caller stores the number and decides where to use it.", code: "def calculate_water(moisture):\n    if moisture < 20:\n        return 100\n    return 50\n\nwater = calculate_water(18)\nprint(\"Water Needed:\", water)", output: "Water Needed: 100" },
    { title: "Return an irrigation status", explanation: "Different branches can return different text results.", code: "def irrigation_status(moisture):\n    if moisture < 20:\n        return \"START\"\n    else:\n        return \"STOP\"\n\nstatus = irrigation_status(35)\nprint(status)", output: "STOP" },
  ],
  returnTypes: [{ type: "Number", code: "return 45", example: "Water amount" }, { type: "String", code: "return \"Healthy\"", example: "Crop status" }, { type: "Boolean", code: "return True", example: "Sensor availability" }],
  returnEnds: {
    title: "return immediately ends the active function call",
    explanation: "After return executes, Python leaves the function. The later print line is unreachable and never runs.",
    code: "def demo():\n    print(\"Start\")\n    return\n    print(\"End\")\n\ndemo()",
    output: "Start",
    skippedLine: "print(\"End\")",
    steps: [{ title: "Function Starts", description: "Enter demo()." }, { title: "Print Start", description: "The first line runs." }, { title: "return", description: "Exit the function immediately." }, { title: "Caller Continues", description: "The End line is skipped." }],
  },
  comparison: {
    title: "Choose display or reusable program data",
    body: "Use print() when a person should see information. Use return when another part of the program needs the computed value.",
    rows: [{ feature: "Purpose", print: "Displays output", returns: "Sends a value back" }, { feature: "Audience", print: "User", returns: "Calling program" }, { feature: "Reuse", print: "Not directly reusable", returns: "Can be stored and reused" }, { feature: "Typical use", print: "Display or debugging", returns: "Modular application logic" }],
  },
  mistakesTitle: "Common return-value mistakes",
  mistakes: [{ title: "Ignoring a returned value", incorrect: "add(5, 3)", reason: "The result is produced but the caller neither stores nor uses it.", correct: "result = add(5, 3)" }, { title: "Printing instead of returning", incorrect: "def add(a, b):\n    print(a + b)", reason: "The caller receives None and cannot calculate with the displayed text.", correct: "def add(a, b):\n    return a + b" }, { title: "Unreachable code after return", incorrect: "def test():\n    return 10\n    print(\"Hello\")", reason: "return exits the function before print is reached.", correct: "def test():\n    print(\"Hello\")\n    return 10" }],
  debugChallenges: [{ title: "Repair the reusable calculation", prompt: "Make value usable in the + 5 calculation.", code: "def add(a, b):\n    print(a + b)\n\nvalue = add(2, 3) + 5", mistakesToFind: 1, solution: "def add(a, b):\n    return a + b\n\nvalue = add(2, 3) + 5", hiddenGuidance: "The function must send the number back instead of only displaying it." }, { title: "Find the unreachable statement", prompt: "Explain why Done never appears and place it before the exit if it should run.", code: "def square(n):\n    return n * n\n    print(\"Done\")", mistakesToFind: 1, solution: "def square(n):\n    print(\"Done\")\n    return n * n", hiddenGuidance: "Nothing after an executed return runs in that function call." }],
  engineerScenario: {
    title: "Design a reusable irrigation calculation",
    scenario: "A water calculation must support a dashboard, AI recommendation engine, report generator, and irrigation controller.",
    question: "What should the calculation function do with the water amount?",
    options: [{ label: "Return the amount", explanation: "Every caller can store and reuse one numeric result.", recommended: true }, { label: "Only print the amount", explanation: "A human sees it, but other modules receive None.", recommended: false }, { label: "Duplicate the calculation", explanation: "Copied logic creates inconsistent results and maintenance cost.", recommended: false }],
  },
  miniProject: {
    title: "Smart Farm Water Calculator",
    brief: "Return a water requirement from one moisture-based function and reuse the result in the main program.",
    deliverables: ["Define calculate_water(moisture)", "Return 100 below 20%", "Return 60 below 35%", "Return 20 otherwise", "Store the returned value in water", "Display the stored result", "Test all three branches", "Explain why the value is reusable"],
    starterCode: "def calculate_water(moisture):\n    if moisture < 20:\n        return 100\n    elif moisture < 35:\n        return 60\n    else:\n        return 20\n\nwater = calculate_water(18)\nprint(\"Water Required:\", water)",
    challenge: "Use the returned water value in a second calculation that estimates irrigation time without changing calculate_water().",
  },
};
