import type { CapstoneProjectLessonDevelopmentPack } from "@/types/content";

export const smartFarmProjectDevelopmentPack: CapstoneProjectLessonDevelopmentPack = {
  kind: "capstone-project",
  prerequisite: "Lessons 1.1–1.7 · Complete Module 1 fundamentals and problem solving",
  story: {
    title: "Your first assignment at an Agritech startup",
    body: "Your manager needs a simple application where a farmer enters farm details and immediately receives a useful report. No one chooses the variable names, conversions, formulas, or output structure for you. Your job is to design the solution.",
    request: "We need a simple software application where a farmer can enter farm details and immediately receive a report.",
    insight: "Software engineers combine familiar concepts deliberately. This project introduces no new Python syntax—it integrates everything already learned.",
    workflow: {
      title: "From assignment to working software",
      description: "A complete application begins with requirements and ends with tested, understandable output.",
      steps: [
        { title: "Problem", description: "A farmer needs an immediate farm-resource report." },
        { title: "Requirements", description: "Identify inputs, calculations, outputs, and units." },
        { title: "Python program", description: "Combine input, variables, conversion, expressions, and print statements." },
        { title: "Software", description: "Run realistic tests and deliver a readable result." },
      ],
    },
  },
  overview: {
    title: "Smart Farm Information System",
    purpose: "Store farm information, calculate water and fertilizer requirements, and generate one complete farm report.",
    features: [
      { title: "Farmer Registration", description: "Capture the farmer's identity and village." },
      { title: "Farm Details", description: "Record land area and crop information." },
      { title: "Crop Information", description: "Preserve the selected crop in the final report." },
      { title: "Weather Details", description: "Record temperature, rainfall, and soil moisture." },
      { title: "Water Requirement", description: "Calculate total irrigation water from an acre-based rate." },
      { title: "Fertilizer Requirement", description: "Calculate total fertilizer from an acre-based rate." },
      { title: "Final Farm Report", description: "Present every input and calculated value with clear labels and units." },
    ],
  },
  requirements: {
    title: "Translate the manager's request before coding",
    body: "The system needs nine inputs, two calculations, and one structured report. Each input has a meaningful variable name and an appropriate representation.",
    inputs: [
      { label: "Farmer Name", variable: "farmer", type: "str" },
      { label: "Village", variable: "village", type: "str" },
      { label: "Crop", variable: "crop", type: "str" },
      { label: "Land Area", variable: "area", type: "float", unit: "acres" },
      { label: "Temperature", variable: "temperature", type: "float", unit: "°C" },
      { label: "Rainfall", variable: "rainfall", type: "float", unit: "mm" },
      { label: "Soil Moisture", variable: "soil_moisture", type: "float", unit: "%" },
      { label: "Water per Acre", variable: "water_per_acre", type: "float", unit: "litres" },
      { label: "Fertilizer per Acre", variable: "fertilizer_per_acre", type: "float", unit: "kg" },
    ],
    processing: [
      { label: "Total Water", formula: "Area × Water per Acre", variable: "total_water" },
      { label: "Total Fertilizer", formula: "Area × Fertilizer per Acre", variable: "total_fertilizer" },
    ],
    outputs: ["Farmer details", "Crop and farm details", "Weather observations", "Total water required", "Total fertilizer required", "Complete labelled report"],
  },
  algorithm: {
    title: "Design the solution from start to finish",
    body: "The algorithm groups the program into input, processing, and output phases. Select a step to inspect its role before writing code.",
    steps: [
      { title: "Start", description: "Begin the Smart Farm Information System.", phase: "start" },
      { title: "Take Farmer Details", description: "Receive farmer name, village, and crop as text.", phase: "input" },
      { title: "Take Farm Details", description: "Receive and convert land area and environmental measurements.", phase: "input" },
      { title: "Take Resource Rates", description: "Receive water and fertilizer required per acre.", phase: "input" },
      { title: "Calculate Water", description: "Multiply area by the water-per-acre rate.", phase: "process" },
      { title: "Calculate Fertilizer", description: "Multiply area by the fertilizer-per-acre rate.", phase: "process" },
      { title: "Display Report", description: "Print input and calculated values with labels and units.", phase: "output" },
      { title: "End", description: "Finish after the complete report is displayed.", phase: "end" },
    ],
  },
  buildSteps: [
    { title: "Build Step 1 · Collect Farmer Details", purpose: "Store identity and crop values as text returned by input().", code: "farmer = input(\"Farmer Name: \")\nvillage = input(\"Village: \")\ncrop = input(\"Crop Name: \")", concepts: ["input()", "Variables", "str"] },
    { title: "Build Step 2 · Collect Farm Information", purpose: "Convert area and environmental measurements to decimal-capable numbers.", code: "area = float(input(\"Land Area (acres): \"))\ntemperature = float(input(\"Temperature (°C): \"))\nrainfall = float(input(\"Rainfall (mm): \"))\nsoil_moisture = float(input(\"Soil Moisture (%): \"))", concepts: ["input()", "float()", "Measurements"] },
    { title: "Build Step 3 · Collect Resource Rates", purpose: "Receive the two per-acre values required by the formulas.", code: "water_per_acre = float(input(\"Water Required per Acre (litres): \"))\nfertilizer_per_acre = float(input(\"Fertilizer Required per Acre (kg): \"))", concepts: ["Input", "Type conversion", "Rates"] },
    { title: "Build Step 4 · Calculate Requirements", purpose: "Use multiplication to convert each per-acre rate into a total farm requirement.", code: "total_water = area * water_per_acre\ntotal_fertilizer = area * fertilizer_per_acre", concepts: ["Expressions", "Multiplication", "Calculated variables"] },
    { title: "Build Step 5 · Generate the Report", purpose: "Communicate every value with a meaningful label and unit.", code: "print(\"SMART FARM REPORT\")\nprint(\"Farmer Name       :\", farmer)\nprint(\"Crop              :\", crop)\nprint(\"Water Required    :\", total_water, \"litres\")\nprint(\"Fertilizer Needed :\", total_fertilizer, \"kg\")", concepts: ["print()", "Formatted output", "Units"] },
  ],
  finalProgram: "print(\"===================================\")\nprint(\"      SMART FARM INFORMATION\")\nprint(\"===================================\")\n\n# Farmer Details\nfarmer = input(\"Farmer Name: \")\nvillage = input(\"Village: \")\ncrop = input(\"Crop Name: \")\n\n# Farm Details\narea = float(input(\"Land Area (acres): \"))\ntemperature = float(input(\"Temperature (°C): \"))\nrainfall = float(input(\"Rainfall (mm): \"))\nsoil_moisture = float(input(\"Soil Moisture (%): \"))\n\n# Resource Requirements\nwater_per_acre = float(input(\"Water Required per Acre (litres): \"))\nfertilizer_per_acre = float(input(\"Fertilizer Required per Acre (kg): \"))\n\n# Calculations\ntotal_water = area * water_per_acre\ntotal_fertilizer = area * fertilizer_per_acre\n\n# Report\nprint(\"\\n===================================\")\nprint(\"        SMART FARM REPORT\")\nprint(\"===================================\")\nprint(\"Farmer Name        :\", farmer)\nprint(\"Village            :\", village)\nprint(\"Crop               :\", crop)\nprint(\"Land Area          :\", area, \"acres\")\nprint(\"Temperature        :\", temperature, \"°C\")\nprint(\"Rainfall           :\", rainfall, \"mm\")\nprint(\"Soil Moisture      :\", soil_moisture, \"%\")\nprint(\"Water Required     :\", total_water, \"litres\")\nprint(\"Fertilizer Needed  :\", total_fertilizer, \"kg\")\nprint(\"===================================\")",
  walkthrough: [
    { startLine: 1, endLine: 3, title: "Application heading", purpose: "Display a clear title before collecting information.", variables: [], dataTypes: ["str"], expectedOutput: "SMART FARM INFORMATION heading" },
    { startLine: 5, endLine: 8, title: "Farmer details", purpose: "Receive three text values and store them under meaningful names.", variables: ["farmer", "village", "crop"], dataTypes: ["str"], expectedOutput: "Three prompts; values appear later in the report" },
    { startLine: 10, endLine: 14, title: "Farm and weather details", purpose: "Receive four measurements and convert each response from text to float.", variables: ["area", "temperature", "rainfall", "soil_moisture"], dataTypes: ["str → float"], expectedOutput: "Four prompts and four numeric variables" },
    { startLine: 16, endLine: 18, title: "Resource rates", purpose: "Receive the water and fertilizer rates required for calculation.", variables: ["water_per_acre", "fertilizer_per_acre"], dataTypes: ["str → float"], expectedOutput: "Two resource-rate prompts" },
    { startLine: 20, endLine: 22, title: "Calculations", purpose: "Multiply land area by each per-acre rate and store both totals.", variables: ["area", "water_per_acre", "fertilizer_per_acre", "total_water", "total_fertilizer"], dataTypes: ["float"], expectedOutput: "Two calculated numeric values" },
    { startLine: 24, endLine: 37, title: "Report generation", purpose: "Display inputs and calculated totals with clear labels and units.", variables: ["farmer", "village", "crop", "area", "temperature", "rainfall", "soil_moisture", "total_water", "total_fertilizer"], dataTypes: ["str", "float"], expectedOutput: "Complete SMART FARM REPORT" },
  ],
  simulatorFields: [
    { id: "farmer", label: "Farmer Name", prompt: "Farmer Name: ", type: "str", defaultValue: "Rahul" },
    { id: "village", label: "Village", prompt: "Village: ", type: "str", defaultValue: "Panvel" },
    { id: "crop", label: "Crop", prompt: "Crop Name: ", type: "str", defaultValue: "Rice" },
    { id: "area", label: "Land Area", prompt: "Land Area (acres): ", type: "float", defaultValue: "10" },
    { id: "temperature", label: "Temperature", prompt: "Temperature (°C): ", type: "float", defaultValue: "32" },
    { id: "rainfall", label: "Rainfall", prompt: "Rainfall (mm): ", type: "float", defaultValue: "110" },
    { id: "soil_moisture", label: "Soil Moisture", prompt: "Soil Moisture (%): ", type: "float", defaultValue: "40" },
    { id: "water_per_acre", label: "Water per Acre", prompt: "Water Required per Acre (litres): ", type: "float", defaultValue: "1500" },
    { id: "fertilizer_per_acre", label: "Fertilizer per Acre", prompt: "Fertilizer Required per Acre (kg): ", type: "float", defaultValue: "25" },
  ],
  testDatasets: [
    { id: "rice-panvel", title: "Reference test · Rice farm", description: "The lesson's acceptance dataset verifies both resource formulas.", inputValues: { farmer: "Rahul", village: "Panvel", crop: "Rice", area: "10", temperature: "32", rainfall: "110", soil_moisture: "40", water_per_acre: "1500", fertilizer_per_acre: "25" }, expectedValues: [{ label: "Water Required", value: "15000 litres" }, { label: "Fertilizer Needed", value: "250 kg" }], expectedOutputFragments: ["Water Required     : 15000.0 litres", "Fertilizer Needed  : 250.0 kg"] },
    { id: "wheat-nashik", title: "Boundary test · Small wheat farm", description: "Decimal area confirms that float conversion and multiplication remain accurate.", inputValues: { farmer: "Meera", village: "Nashik", crop: "Wheat", area: "2.5", temperature: "28.5", rainfall: "75", soil_moisture: "38", water_per_acre: "900", fertilizer_per_acre: "18" }, expectedValues: [{ label: "Water Required", value: "2250 litres" }, { label: "Fertilizer Needed", value: "45 kg" }], expectedOutputFragments: ["Water Required     : 2250.0 litres", "Fertilizer Needed  : 45.0 kg"] },
    { id: "maize-pune", title: "Alternative test · Maize farm", description: "Different values confirm that the program is not tied to the reference farm.", inputValues: { farmer: "Asha", village: "Pune", crop: "Maize", area: "6", temperature: "30", rainfall: "92", soil_moisture: "44", water_per_acre: "1100", fertilizer_per_acre: "22" }, expectedValues: [{ label: "Water Required", value: "6600 litres" }, { label: "Fertilizer Needed", value: "132 kg" }], expectedOutputFragments: ["Water Required     : 6600.0 litres", "Fertilizer Needed  : 132.0 kg"] },
  ],
  mistakesTitle: "Common project mistakes",
  mistakes: [
    { title: "Using unconverted input in a calculation", incorrect: "area = input(\"Area: \")\ntotal_water = area * water_per_acre", reason: "input() returns text. Resource calculations require compatible numeric values.", correct: "area = float(input(\"Area: \"))\ntotal_water = area * water_per_acre" },
    { title: "Combining unrelated measurements", incorrect: "print(area + temperature)", reason: "A calculation needs a meaningful real-world relationship. Adding acres and degrees does not produce a useful quantity.", correct: "total_water = area * water_per_acre\nprint(\"Water Required:\", total_water, \"litres\")" },
  ],
  challenges: [
    { title: "Add Farmer ID", brief: "Collect and display a farmer identifier.", guidance: "Treat the identifier as text so leading zeros are preserved.", concept: "Input and string variables" },
    { title: "Add Mobile Number", brief: "Collect and display a contact number.", guidance: "A phone number is an identifier, not a value for arithmetic.", concept: "Data-type choice" },
    { title: "Calculate Seed Requirement", brief: "Receive seed rate per acre and calculate total seed.", guidance: "Follow the same area × rate pattern used by water and fertilizer.", concept: "Expressions" },
    { title: "Calculate Labour Cost", brief: "Receive labour cost per acre and calculate the total.", guidance: "Use meaningful names and label the currency in the report.", concept: "Numeric input and multiplication" },
    { title: "Display Current Date", brief: "Add a report date supplied by the user.", guidance: "Modules are out of scope, so receive the date as text rather than importing a date library.", concept: "Text input" },
    { title: "Improve Report Formatting", brief: "Make the console report easier to scan.", guidance: "Use headings, separators, alignment, and explicit units with existing print statements.", concept: "Formatted output" },
  ],
  engineerScenario: {
    title: "Design for 100,000 farmers",
    scenario: "The prototype serves one farmer at a time. Imagine the startup now needs to support 100,000 farmers across multiple regions.",
    question: "Which product direction best prepares the system to scale?",
    options: [
      { label: "Database, login, cloud storage, reports, dashboard, mobile app, and analytics", explanation: "These capabilities address identity, durable records, access, reporting, delivery, and decision support. They are future architecture—not new syntax for this lesson.", recommended: true },
      { label: "Add more print statements only", explanation: "Better formatting can improve the prototype but does not provide identity, storage, or multi-user access.", recommended: false },
      { label: "Use shorter variable names", explanation: "Shorter names do not solve scale, persistence, security, or product-access requirements.", recommended: false },
    ],
  },
  completion: {
    title: "Module 1 complete · Python foundations",
    body: "You have combined every Module 1 concept to design, build, inspect, test, and improve a complete Python console application.",
    skills: ["Write Python programs", "Accept user input", "Store meaningful data", "Choose foundational data types", "Convert input", "Perform calculations", "Generate reports", "Solve beginner programming problems"],
    checkpoint: "You are ready to begin decision making and control flow when you can explain the inputs, formulas, variables, and expected output of this project without copying the completed program.",
  },
};
